### ISSUE TITLE
Menu draw

### ISSUE THREAD

**Issue by IncoCode** [crosire/scripthookvdotnet#100]
Is it possible to call menu draw method in each game frame irrespective of Script.Interval value? Because if set value of Interval, for example, in 1000 menu starts flickering.

**Comment by Frede1012** [comment]
Currently the scriphook only allows for features to tick in either a script or the scriptdomain, i suppose the Viewport could be moved to the scriptdomain instead. I might make a pull request doing some changes to the ui system, such as this soon :-)

**Comment by crosire** [comment]
Create two classes? One for menu drawing with Interval set to zero and one for the script logic with it being set to whatever you want.

**Comment by Frede1012** [comment]
@crosire But wouldn't it be better if there was only one Viewport, to prevent conflicts between mods showing menus on the same screen space?

**Comment by IncoCode** [comment]
@crosire , at the moment the logic of the menu is carried out in other class (but this class doesn't inherit the Script). I just set Interval in 0, when i want to show menu. 
Just interested, whether it is possible or whether it will be changed in the future.

**Comment by IncoCode** [comment]
@Frede1012 , then in case of such implementation some script can "accidental" close your menu.

**Comment by Frede1012** [comment]
@IncoCode Yes, in the current implementation, however if we go for such an implementation we would have to change how the viewport works a bit.
