### ISSUE TITLE
how do i install

### ISSUE THREAD

**Issue by ravenpro22** [crosire/scripthookvdotnet#1011]
i dont know how to code but a guide said i needed this

**Comment by WithLithum** [comment]
Download the package. Copy ScriptHookDotNet.asi, ScriptHookDotNet2.dll, ScriptHookDotNet3.dll into your game folder, where GTA5.exe is located.


Requires ScriptHookV. You can find it at dev-c.com


note that issue tracker is not normally for questions though.
