### ISSUE TITLE
ScriptHookV.net Crashes Game

### ISSUE THREAD

**Issue by SeptJack** [crosire/scripthookvdotnet#1014]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
3.1.0

**Description**
Game crashes after around 5-10 minutes, ive installed shvdn and it crashes the game with no errors then uninstalled it and my game runs fine

**Comment by kagikn** [comment]
Are you sure you've installed only SHV and SHVDN (and their dependencies)? If you have any other scripts installed, identify what mods cause the problem and tell the authors of the mods about it. If SHVDN scripts are not working well, then it might be responsible to SHVDN, though.

**Comment by SeptJack** [comment]
no mods just SHV & SHVDN it crashes then when i remove SHVDN it works fine

**Comment by kagikn** [comment]
I afraid to say more information will be needed to convince us that SHVDN really has serious bugs. I don’t think you’ll gather more info to convince us, so closing this issue.
