### ISSUE TITLE
Screen.ShowHelpMessage doesn't have to be called every tick

### ISSUE THREAD

**Issue by WithLithum** [crosire/scripthookvdotnet#1023]
New comment found on [the natives documentation](https://docs.fivem.net/natives/?_0x238FFE5C7B0498A6):
> p3 (duration in MS) was previously mentioned as "shape", but with some more testing it seems that it's more likely to be a duration in MS. (Tested this when not calling it every tick, but instead only once and let it display for the specified duration).
> -1 seems to be default delay (around 3 seconds), 5000 (ms) seems to be the max. Anything > 5000 will still result in 5 seconds of display time.  

After testing, it turns out the third parameter was DURATION instead of 'shape'. It works fine when called once, but also works correctly when called every tick (for displaying constant message like Press E to do something). Calling `Screen.ShowHelpMessageThisFrame` shows a help message for several seconds instead of only one frame.

You may add a new function called `GTA.UI.Screen.ShowHelpMessage(string text, int duration)`, etc.

**Comment by kagikn** [comment]
I appreciate your report. Will make `Screen.ShowHelpMessageThisFrame` show the help message only one frame and will add `Screen.ShowHelpMessage`.
As I tested `END_TEXT_COMMAND_DISPLAY_HELP`, the game shows the help message for the time specified with the 4th parameter if 2nd parameter is set to zero and the 4th parameter is positive (as a `int32_t`). If the 4th parameter is zero or negative, the help message will show for 7500 milliseconds in the real time (which means the game speed does not affect how long the help message will be showed). The game shows the help message forever is the 2nd parameter is set to any non-zero value, btw.
