### ISSUE TITLE
WeaponComponent errors

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#1025]
**Version**  Using latest code compile and V3.

**Description**
```
void TestWhatEver()
{
    if (Game.Player.Character.Weapons?.Current == null) return;

    Weapon weapon = Game.Player.Character.Weapons.Current;

    WeaponComponent suppressor = weapon.Components.GetSuppressorComponent();

    if (suppressor != null)
    {
        GTA.UI.Notification.Show(suppressor.LocalizedName);
    }
}
```

Results in
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.WeaponComponent.get_DisplayName()
   at TestWhatEver()
   ```

**Comment by kagikn** [comment]
#1013 didn’t _directly_ introduce the exceptions.
https://github.com/crosire/scripthookvdotnet/blob/3427538b1fc830b379428ce5c0044d911d4df8d0/source/scripting_v3/GTA/Weapons/WeaponComponent.cs#L31
https://github.com/crosire/scripthookvdotnet/blob/3427538b1fc830b379428ce5c0044d911d4df8d0/source/scripting_v3/GTA/Weapons/WeaponComponentCollection.cs#L19

But looks like #1013 indeed had problems with attachment point hashes. I think I picked the wrong offset of weapon attachment point.
Anyway, will fix both of the issues.

**Comment by Tanjitsu** [comment]
Hey,

I dont often use my attachments script but i was just testing some stuff an noticed it no longer worked :(
I checked the history and saw you did make some changes recently.

Sorry for blaming you :D
