### ISSUE TITLE
Typos in Vehicle.cs

### ISSUE THREAD

**Issue by bttf92** [crosire/scripthookvdotnet#1026]
Reporting two small typos in v3 Vehicle.cs class. For IsTrain property, the vehicle type is compared to the wrong enum.

public bool IsTrain => Type == VehicleType.Bycicle;

And also the correct spelling is "Bicycle"

**Comment by Tanjitsu** [comment]
If you hover over the code of the line in question ... you can copy a link[like this].(https://github.com/crosire/scripthookvdotnet/blob/5200a3ae5b2f6dcaaafc4a2e7a518f8edc7f9fcf/source/scripting_v3/GTA/Entities/Vehicles/Vehicle.cs#L242)
Makes it super easy to reference exactly which part you refer too ;)
