### ISSUE TITLE
Because of the file, the script of the hook asi crashes the game, what is the reason?

### ISSUE THREAD

**Issue by lavkennn** [crosire/scripthookvdotnet#1028]
Because of the file, the script of the hook asi crashes the game, what is the reason?

-----

**Version**
3.1.0

**Description**
plz help

**Comment by WithLithum** [comment]
Please describe what you did before the game crashes. Also, your grammar isn't good - are you using a translator?

**Comment by crosire** [comment]
This is not a support forum, see readme for links to better places for that purpose.
