### ISSUE TITLE
"Resolving API version 0.0.0" Warning is showing without script names

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#1032]
Same issue as #1031, but this is not a PR but a issue. I'm using a blockquote for easier reference.
> Hello, will someone be nice and I will write to me if WARNING after launching the Community Script Hook V window appears for every user who is playing? Is this a normal informational message and I shouldn't worry about it, or is there something that warns that some of my scripts are incompatible and cause / may be causing a running problem during the game?
> 
> [WARNING] Resolving API version 0.0.0.
> 
> https://media.discordapp.net/attachments/318626093013925889/895096032902385704/unknown.png

I'm sure the warning shows without script names because `HandleResolve` occurs with `RequestingAssembly` `null`, but not sure how to fix this problem. You can reproduce this problem with a script such as [DrunkIV 1.3](https://www.gta5-mods.com/scripts/drunkiv). 
https://github.com/crosire/scripthookvdotnet/blob/9fa2652224dc10a2dbeac6c2729d6b30bbd26b8d/source/core/ScriptDomain.cs#L803

**Comment by RemixPL1994** [comment]
Hello, can I ask you one more thing?
