### ISSUE TITLE
scripthookvdotnet error while in game.

### ISSUE THREAD

**Issue by Juice420** [crosire/scripthookvdotnet#1037]
![20211113093309_1](https://user-images.githubusercontent.com/65619263/141647754-b7057cdd-9b3c-4d54-af0c-9cd30ae3b08a.jpg)
[ScriptHookVDotNet.log](https://github.com/crosire/scripthookvdotnet/files/7532243/ScriptHookVDotNet.log)
[ScriptHookVDotNet2.log](https://github.com/crosire/scripthookvdotnet/files/7532244/ScriptHookVDotNet2.log)

**Comment by crosire** [comment]
This is a bug in the GangAndTurfMod script, not SHVDN.
