### ISSUE TITLE
I typed `Help()` in the console. And it gives the following error.

### ISSUE THREAD

**Issue by lsieben97** [crosire/scripthookvdotnet#1042]
I typed `Help()` in the console. And it gives the following error:
![gta](https://user-images.githubusercontent.com/10631441/145448364-49df32d2-781e-42a9-a939-c7a02baaee10.png)

_Originally posted by @lsieben97 in https://github.com/crosire/scripthookvdotnet/issues/1041#issuecomment-990077099_

**Comment by kagikn** [comment]
This is duplicated with #1041, I think.
