### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by Davidas59** [crosire/scripthookvdotnet#1043]
Hello, how to fix scripthookvdotnet one generation works the next generation doesn't work "scripthookvdotnet .log error"

![Screenshot_88](https://user-images.githubusercontent.com/26489219/146061626-96c401c4-71f8-4735-b6b4-a2ca01f56da7.png)

**Comment by Tanjitsu** [comment]
The log states that GTA\scripts directory is missing and that it does not have permission to access the log file.
