### ISSUE TITLE
NuGet API key is expired

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#1055]
I don't have the permissions to do regenerate a key. See [the AppVeyor history](https://ci.appveyor.com/project/crosire/scripthookvdotnet/builds/42229351) to confirm.

**Comment by crosire** [comment]
Fixed in d9275eea825daad05168b56a5264a0dec9cf150f. Had updated it already, but forgot that appveyor.xaml overwrites whatever I configure on the AppVeyor website.
