### ISSUE TITLE
Make Resolving API version 0.0.0 show all script names of the generation. Instead of just one.

### ISSUE THREAD

**Issue by RemixPL1994** [crosire/scripthookvdotnet#1056]
Make Resolving API version 0.0.0 show all script names of the generation. Instead of just one.

**I reported here that it shows "Resolving API version 0.0.0" on the older SHVDN version:

https://github.com/crosire/scripthookvdotnet/issues/1032?fbclid=IwAR0Gx0tXPwjkGBnwOnlVxQukMQap8ivfQdBLDDisladIRS_TdaIHC3f8nGg**

I have now used the latest version of SHVDN and I can see it now displays it like this:

Resolving API version 0.0.0 + script name.

But if we have more than one script saying Resolving API version 0.0.0 it will only display the first name instead of all of them.

e.g. RealParamedics.dll + SittingMod.dll + WorkingHotdogVendors.dll + Gym.dll

Instead of showing in the console that it is:

Resolving API version 0.0.0 for e.g. RealParamedics.dll + SittingMod.dll + WorkingHotdogVendors.dll + Gym.dll

I will only show one of them, eg RealParamedics.dll.

After removing RealParamedics.dll and restarting the game, it will display another script with this text again.

Is it possible to make the text with the names of all scripts with the text Resolving API version 0.0.0 displayed at once and for the first time automatically in the console and provide all the names of the scripts it refers to instead of just one at a time?

Screen in game:

![obraz](https://user-images.githubusercontent.com/52541621/149812975-abcc11e3-00d5-47b7-9ed4-85d117d64a1e.png)

Screen scripts catalog:

![obraz](https://user-images.githubusercontent.com/52541621/149812935-b77b7293-8999-4141-a360-4518d4c97caf.png)

**Comment by kagikn** [comment]
I hope you'll be happy when the next version is released.

**Comment by kagikn** [comment]
Now you can have the first version (v3.5.1) that doesn't have this issue. But don't get me wrong. I released v3.5.1 because I forgot to update assembly versions of APIs. The change I made for this issue is nice to have, but not urgent unlike script compatibility problems.
