### ISSUE TITLE
Disable ScriptHookVDotNet2

### ISSUE THREAD

**Issue by Daniel41920** [crosire/scripthookvdotnet#1060]
Hello. Is there a way to disable ScriptHookVDotNet2.dll from loading into the game? I would not like to get into it, but I am having a problem that I believe I could solve by removing this component.

**Comment by seaque** [comment]
Just relocate the dll?

**Comment by WithLithum** [comment]
It is not "hard-linked" to SHVDN. If you remove, it will only result in scripts requiring SHVDN API version 2 no longer working.

**Comment by Kaiops213** [comment]
on OpenIV it says that ScriptHookVDotNet.asi has failed to load, same with native trainer
