### ISSUE TITLE
[11:59:29] [WARNING] Unable to resolve API version 2.10.9.

### ISSUE THREAD

**Issue by makarhuyaker** [crosire/scripthookvdotnet#1061]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
3.4.0

**Description**
Add a clear and concise description of what the bug is and how to reproduce it.

**Comment by makarhuyaker** [comment]
wait i need ScriptHookVDotNet2.dll?

**Comment by kagikn** [comment]
Yes, you need to install `ScriptHookVDotNet2.dll`, too. Also, you might want to install `ScriptHookVDotNet3.dll` for other scripts.
