### ISSUE TITLE
after the update of gta 5.script does not run the lattest version of game.please fix it

### ISSUE THREAD

**Issue by dev-unnie** [crosire/scripthookvdotnet#1064]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
Which version of SHVDN was the problem encountered with?

**Description**
Add a clear and concise description of what the bug is and how to reproduce it.

**Comment by kagikn** [comment]
You need to explain more before we can handle the problem, or we can't even figure what cause it at all. Besides, you should explain the version where you have it, not just _the latest version_.
I assume SHVDN properly works in v1.0.2612.1 as usual, so closing the issue.
