### ISSUE TITLE
Owner of a projectile might not be a ped

### ISSUE THREAD

**Issue by Sardelka9515** [crosire/scripthookvdotnet#1067]
**Version**
3.4.0 

**Description**
`Projectile.Owner` always returns a `Ped`, but it may be a vehicle if it's a vehicle weapon.

**Comment by kagikn** [comment]
You are correct. You can easily reproduce the problem by entering some vehicle with weapons and firing projectiles from it.
I thought `Projectile.Owner` was always the ped. Actually, despite of my guess, projectiles fired from vehicles will get deleted when the game deletes vehicles.
