### ISSUE TITLE
Doesn't work with the new game version (2612)

### ISSUE THREAD

**Issue by BerkieBb** [crosire/scripthookvdotnet#1068]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

I acknowledged the above but got the example error when adding SHVDN to my GTAV folder, I saw that the latest release and the source code aren't up to date with the newest game build 2612 (I saw that the source code wasn't up to date after I tried to build it), I tried to build the solution as well but got some errors trying to do that.

-----

**Version**
Which version of SHVDN was the problem encountered with? 3.4.0

**Description**
If you add SHVDN to your game with the newest version of SHV, then it will give you the error `FATAL: Unknown game version`, trying to build the source code also doesn't work as I'm getting the error shown in the screenshot
![image](https://user-images.githubusercontent.com/82737367/170681057-72743583-cbcf-40d0-ab7e-755fa2c37dc1.png)

**Comment by WithLithum** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Be aware of that the latest build is 2628, and SHV has not been updated for 2628 yet.Message ID: ***@***.***>

**Comment by BerkieBb** [comment]
Ohh, okay, didn't see the 2612 or 2628 in the GameVersion.cs in scripting_v3/GTA, so I assumed it wasn't updated yet, I'll wait for SHV to update then

**Comment by kagikn** [comment]
I’m not convinced if this issue is really related to SHVDN. Are you sure you have installed [Visual C++ Redistributable for Visual Studio 2019 x64](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)?
By the way, you can detect newer versions with `Game.Version` in scripts even if the `GameVersion` enum does not have corresponding values (SHVDN uses the value returned from SHV).

**Comment by BerkieBb** [comment]
Ah okay, but I do have all requirements installed, also unpacked SHV SDK into sdk/

**Comment by kagikn** [comment]
Ah, do you mean this typical error? In that case, this issue is not related to SHVDN because SHV currently supports `1.0.2618.1`, but doesn't support `1.0.2618.2`.
![GTA5_I4S1oMD1XO](https://user-images.githubusercontent.com/9353978/170685392-b86b2538-75dd-47c0-9376-20e0544b134e.png)

**Comment by BerkieBb** [comment]
Yeah I got that, but not the build error I got, do you get that or does it build fine for you?

**Comment by kagikn** [comment]
It builds fine for me. The way I see it from your screenshot, I guess you need to install Windows SDK. Make sure `10.0.18362.0` of Windows SDK is available.
Note that building SHVDN from the source doesn’t make difference if you can launch the exe with SHV.
https://github.com/crosire/scripthookvdotnet/blob/ccdf0c1b13688b52c36cf3322da1d15eaea7bc4c/ScriptHookVDotNet.vcxproj#L20

**Comment by BerkieBb** [comment]
That could be the problem, well thanks for the support!
