### ISSUE TITLE
ScriptHookVDotNet Causing Crash with RagePluginHook

### ISSUE THREAD

**Issue by LoganIsLogan14** [crosire/scripthookvdotnet#1084]
Hi, anytime I try to launch GTA5 with RagePluginHook and ScriptHookVDotNet installed it crashes when loading into the game, at the same spot every time. Right when it says loading and populating game world. I can start the game just fine without Rage, and this happens no matter which version of ScriptHookVDotNet I have installed. I've tried reinstalling GTA5 and I have the same problem. I have no scripts installed and my scripts folder is empty. I've checked all the logs and they don't show anything. The only thing I have to go off of, is Windows Event Viewer, which points to MpOav.dll as the faulting module. I've looked it up, and it's a dll file for windows defender. I've tried disabling and reseting Windows Defender to no prevail. I'll attach some screenshots and some logs. Any help would be great, thanks in advance.
[AdvancedHookV.log](https://github.com/crosire/scripthookvdotnet/files/9304552/AdvancedHookV.log)
[asiloader.log](https://github.com/crosire/scripthookvdotnet/files/9304553/asiloader.log)
[RagePluginHook.log](https://github.com/crosire/scripthookvdotnet/files/9304554/RagePluginHook.log)
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/9304555/ScriptHookV.log)
[ScriptHookVDotNet.log](https://github.com/crosire/scripthookvdotnet/files/9304556/ScriptHookVDotNet.log)
![EmptyScriptsFolder](https://user-images.githubusercontent.com/32691406/184035984-715045af-c4d6-499a-9037-f3496b0072b4.png)
![EventViewer](https://user-images.githubusercontent.com/32691406/184035989-69ff41e9-7806-4603-8572-6e70132d3489.png)

**Comment by kagikn** [comment]
`MpOav.all` is irrelevant to GTA5.exe, this plugin, or RagePluginHook. I guess it comes with Windows Defender, but not relevant to this plug-in’s bug anyway.
