### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by ThatOnlyWeb** [crosire/scripthookvdotnet#1087]
Version: 1.0.2699.0

Script hook doesnt work with the latest version of gta (stated above)
when is the script update out?
Thank you

**Comment by kagikn** [comment]
v3.5.1 should work. Without providing any info that makes us sure something isn't right about SHVDN (e.g. #1079), this issue won't be worth opening. If some of the scripts you have installed don't work, report to the authors.
