### ISSUE TITLE
How to get actual screen width?

### ISSUE THREAD

**Issue by lsieben97** [crosire/scripthookvdotnet#1094]
Hi!
My game runs on a 1920 X 1080 resolution but the hardcoded `Width` (in the `Screen` class) appears to be 1280. The `ScaledWidth` property also returns 1280 so how do I find the actual screen width of 1920?

I'm trying to draw some text horizontally centered on screen but without the actual screen width it's not centered properly.

Any help is appreciated!

**Comment by Sardelka9515** [comment]
`GTA.UI.Screen.Resolution` returns the actual resolution of the game, but I use this to draw text with LemonUI:
```
        public static SizeF ResolutionMaintainRatio
        {
            get
            {
                // Get the game width and height
                int screenw = Screen.Resolution.Width;
                int screenh = Screen.Resolution.Height;
                // Calculate the ratio
                float ratio = (float)screenw / screenh;
                // And the width with that ratio
                float width = 1080f * ratio;
                // Finally, return a SizeF
                return new SizeF(width, 1080f);
            }
        }
```
It'll give you the **absolute** screen bound for drawing LemonUI's elements, while SHVDN  takes `Screen.Width` and `Screen.Height` as screen bound for drawing sprites

**Comment by lsieben97** [comment]
@Sardelka9515, Thanks for the information.
Is there a reason for you code to always return a height of 1080?

**Comment by Sardelka9515** [comment]
LemonUI takes that scaled resolution as parameter, I'm not sure about the reason behind
