### ISSUE TITLE
Add Tick event for ScriptDomain

### ISSUE THREAD

**Issue by Sardelka9515** [crosire/scripthookvdotnet#1098]
Add a clear and concise description of the feature you have in mind.

Add a `ScriptDomain.Tick` event that'll be invoked from main thread, so modders could choose to subscribe to this event for more performant native calling.
Waiting and yielding will be unavailable in the handler

**Comment by Sardelka9515** [comment]
I could make a PR

**Comment by Sardelka9515** [comment]
#1099

**Comment by crosire** [comment]
You can simply add set the `NoScriptThread` attribute on your script class now to make SHVDN execute that script on the main thread. Do note that `Script.Wait()` and `Script.Yield()` are not available and will throw an exception if used in that case.
```c#
[ScriptAttributes(NoScriptThread = true)]
public class MyCoolScript : Script
{
    ...
}
```
