### ISSUE TITLE
Entity.MaxHealthFloat returns zero

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#1106]
**Version**
Which version of SHVDN was the problem encountered with?

af95f80dbef4144c9f8b10a1838a38e74946b31a

**Description**
Add a clear and concise description of what the bug is and how to reproduce it.

Looks like MaxHealthFloat is returning 0 for some reason.

I used this line to show the subtitle on the image:

```cs
GTA.UI.Screen.ShowSubtitle($"{Game.Player.Character.HealthFloat} {Game.Player.Character.MaxHealthFloat}");
```

![image](https://user-images.githubusercontent.com/11861253/200136934-46287c17-e360-426c-b03e-2bdc26875dc2.png)

I'm using game version 2699.

**Comment by kagikn** [comment]
Confirmed in 2699.**16**. I thought this bug also reproduced in 2699.**0**, but that's not the case. Will fix this issue by using some memory pattern.
