### ISSUE TITLE
Rockstar Games Social Club has been logged out / Se ha cerrado la sesion en el Social Club de Rockstar Games

### ISSUE THREAD

**Issue by ElReglas** [crosire/scripthookvdotnet#1108]
when i start the game this happens

![image](https://user-images.githubusercontent.com/117763419/200632478-64d50a24-4d91-4cfb-9326-8318368d179a.png)

When i get off Scripthook dot net of the main folder, the game starts correctly but the mods doesnt load
please help.

**Comment by Dominikjano** [comment]
GTA 5 online doesn't work

**Comment by Dominikjano** [comment]
GTA 5 online doesn't work

**Comment by Dominikjano** [comment]
GTA 5 online

**Comment by nomakewan** [comment]
> GTA 5 online doesn't work
Remove dinput8.dll from your GTAV folder. Either move it to a different folder, or delete it. This is not SHVDN's fault.
