### ISSUE TITLE
Implementing SET_VEHICLE_MOD_KIT

### ISSUE THREAD

**Issue by tlt54321** [crosire/scripthookvdotnet#111]
I was trying to create a quick menu for changing the window tint of your current car. Here is my code:

Player player = Game.Player;
 
        active_menu = new GTA.Menu("Customization Menu", new GTA.MenuItem[] {
            new GTA.MenuButton("Tint Windows", () => {
                player.Character.CurrentVehicle.WindowTint = VehicleWindowTint.Limo;
                UI.Notify("Windows Tinted");
            })
       });

The UI displays a message so the button works, but the windows do not change tint. I don't know if the code is wrong or if it's an issue with Scripthookdotnet. Any help is appreciated!

**Comment by IncoCode** [comment]
Try to call
```c#
Function.Call( Hash.SET_VEHICLE_MOD_KIT, veh.Handle, 0 );
```
before apply new tint.

**Comment by tlt54321** [comment]
Works perfectly now. Thank you for the help!

**Comment by JohnnyCrazy** [comment]
Mh...Would be good if we have this in a method, what about `veh.EnableModKit`?

**Comment by IncoCode** [comment]
Or we can just call this SET_VEHICLE_MOD_KIT function in SetMod method, WindowTint setter etc.

**Comment by JohnnyCrazy** [comment]
Mh, this would create a lot of unnecessary calls, wouldn't it? Or do you have to call it before every mod you change?

**Comment by IncoCode** [comment]
Not before every, but as far as I remember after certain time you should call this function again.

**Comment by JohnnyCrazy** [comment]
Mh, then I think we should go with the extra-method.

**Comment by crosire** [comment]
Or set a boolean in the vehicle class and only call it if it's not yet set to true?

**Comment by IncoCode** [comment]
@crosire , no. Like i said, after some time you should call this function again. Just go in LSC, then leave and try to call SetMod method - it's works, wander around some time, try again - it's don't work.

**Comment by crosire** [comment]
Then save a DateTime and check if the last call is over a certain limit.

**Comment by IncoCode** [comment]
@crosire , yeah, but i don't know after which time **exactly** it ceases to work.

**Comment by crosire** [comment]
I'd just do it like @IncoCode originally proposed. Call it on every SetMod etc. It's the safest way.

**Comment by JohnnyCrazy** [comment]
Closed by 4941bc1e5e2e97d515c4839e7f10b9f3fcba56d4
