### ISSUE TITLE
Help setting my dev environment to contribute to this

### ISSUE THREAD

**Issue by SpeedySDK** [crosire/scripthookvdotnet#1117]
Hi! I want to contribute to help with migration of scripthookv to .net core but I need some help to fix these errors I get when I build the solution. I already copied the sdk to the respective solution folder.

![image](https://user-images.githubusercontent.com/59510273/203425998-36a6649f-6eea-4808-b29a-07dbb4264665.png)

**Comment by nomakewan** [comment]
The issue is that the targeted Windows Platform Version in the csproj file for ScriptHookVDotNet_APIv2 does not match any in your C:\Program Files (x86)\Windows Kits\10\bin folder.

Go to that folder and see what you actually have. You will likely have a newer version. Copy the name of that version’s folder, then open the csproj file in your text editor of choice and replace the WindowsPlatformVersion value with that.

**Comment by Sardelka9515** [comment]
Install windows SDK 1.0.18362.0 with visual studio installer

**Comment by nomakewan** [comment]
Clean your solution. Then build Core, then build solution.

The APIv2 and APIv3 parts rely on ScriptHookVDotNet.asi existing, and while the solution build order should make sure that happens, a previous failed build can make it fail.

**Comment by Sardelka9515** [comment]
Simply Re-targeting the scripting API to .NET Core won't work, it is the C++/CLI core that needs to be upgraded.

**Comment by SpeedySDK** [comment]
> Simply Re-targeting the scripting API to .NET Core won't work, it is the C++/CLI core that needs to be upgraded.


![image](https://user-images.githubusercontent.com/59510273/203620059-ddde16b0-f6cc-4898-b6c5-12236e950940.png)

Both projects need to be upgraded right? User .net core projects cannot reference .net framework dlls. Yeah I see now that the core project file is targeting .net framework 4.8. I don't have much experience with c++ projects and the language in general but i'll try. I think the features and performance increase of .net 6 and upcoming .net 7 are worth it. Do you agree?

**Comment by SpeedySDK** [comment]
It also seems that C++/CLI projects don't support .net 6 for now, so only .net 5 (not supported by MS anymore) and .net core 3.1.
https://github.com/dotnet/core/issues/6066
