### ISSUE TITLE
World.CreateProp not working?

### ISSUE THREAD

**Issue by Yothri** [crosire/scripthookvdotnet#112]
Hey,

i cant get to work World.CreateProp. I tried it like this for example:

```cs
World.CreateProp(new Model(WeaponHash.AdvancedRifle), Game.Player.Character.Position, true, true);
```

But it just doesnt happen anything... Tried it also with a VehicleHash but same result. Andalso, can i spawn game objects with that, such as trees for example?

**Comment by JohnnyCrazy** [comment]
Hey,

World.CreateProp is not working that way. You can only spawn "props", which are objects in GTA V. (like a jetski ramp e.g). You can get a full list [here](http://ecb2.biz/releases/GTAV/lists/props.txt)

Example:
````
World.CreateProp(new Model("prop_jetski_ramp_01"), Game.Player.Character.Position, true, true);
````

**Comment by Yothri** [comment]
Thank you so much for the example, i already tried this:
```cs
World.CreateProp(new Model(0xB717705B), Game.Player.Character.Position, true, true);
```

But this throws a syntax error.
Model 0xB717705B is a object in GTA V: DB_PierlightA_MH11

I will try using its name now. Thank you :)

**Comment by crosire** [comment]
Btw. you don't need to write "World.CreateProp(new Model(XYZ), ...);". The Model class has an implicit conversion operator, so simply write "World.CreateProp(XYZ, ...);" directly =).

**Comment by Yothri** [comment]
Thankx, works perfectly.
