### ISSUE TITLE
V3.5.1 Incompatible with ENB

### ISSUE THREAD

**Issue by GhostRider0700** [crosire/scripthookvdotnet#1122]
Unfortunately it appears that SHVDN is incompatible with any graphical mods that rely on ENB. 

When all files are in the root directory (no ENB installed) GTA V loads fine. 

When all files are in the root directory (with ENB installed for graphical mods such as NVE, QuantV or RealismBeyond), the game will begin loading, or load to the character, before the game crashes to desktop (however no crash report is generated, and the ScriptHookVDotNet text document in the root directory does not show a crash either). 

When non of the files are installed into the root directory (only ENB from graphical mods) the game boots fine. 

Has anyone else experienced this or have a fix? 

Thanks in advance! 

EDIT - I have now determined it is not ENB that is causing the issue, but Rage Plugin Hook. Both work fine seperate, however together the game crashes.

**Comment by nomakewan** [comment]
I just installed a fresh copy of ENBseries on a copy of the game that is vanilla save for BTTFV and its dependencies (FusionLibrary, SHVDN 3.5.1, LemonUI 1.9.1), Menyoo, Stop Reversing While Braking, and Default Radio OFF.

The game boots and plays just fine, so I'm afraid I cannot replicate your bug on my end. Usually CTDs are a result of an improper/insufficient gameconfig.xml, or a badly-written mod making a call it shouldn't.

**Comment by GhostRider0700** [comment]
> my

After a little more testing, I've found that it's actually Rage Plugin Hook that's causing an issue when trying to work with SHVDN. Whether the game is launched via RPH, or whether its launched after, the crash remains the same. 

From reading on the LSPDFR support forum, it's down to an issue with handling when RPH is used with it.
