### ISSUE TITLE
`Weapon.Components` getter crashes the game after latest update

### ISSUE THREAD

**Issue by Sardelka9515** [crosire/scripthookvdotnet#1123]
**Version**
Which version of SHVDN was the problem encountered with?
3.5.1

**Description**
`GTA.Weapon.Components` getter crashes the game with an `AccessViolationException` after the recent update (1.0.2802)

Stack trace from event viewer after the crash:
```Aplicativo: GTA5.exe
Versão do Framework: v4.0.30319
Descrição: O processo foi terminado devido a uma exceção sem tratamento.
Informações da Exceção: System.AccessViolationException
   em SHVDN.NativeMemory.FindWeaponInfo(UInt32 nameHash)
   em SHVDN.NativeMemory.GetAllCompatibleWeaponComponentHashes(UInt32 weaponHash)
   em GTA.WeaponComponentCollection.GetComponentsFromHash(WeaponHash hash)
   em GTA.WeaponComponentCollection..ctor(Ped owner, Weapon weapon)
   em GTA.Weapon.get_Components()
   em RageCoop.Client.WeaponUtil.GetWeaponComponents(Weapon weapon)
   em RageCoop.Client.Networking.SendPed(SyncedPed sp, Boolean full)
   em RageCoop.Client.EntityPool.DoSync()
   em RageCoop.Client.Main.OnTick(Object sender, EventArgs e)
   em SHVDN.Script.DoTick()
   em SHVDN.ScriptDomain.DoTick()
   em RageCoop.Client.Loader.LoaderContext.DoTick()
   em RageCoop.Client.Loader.LoaderContext.TickAll()
   em SHVDN.Script.DoTick()
   em SHVDN.ScriptDomain.DoTick()
   em SHVDN.ScriptDomain.DoTick()
   em <Module>.?A0xc5785e66.ScriptHookVDotnet_ManagedTick()```

**Comment by Makinolo** [comment]
Just in case it helps, the same stack trace in English
Aplicación: GTA5.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: System.AccessViolationException
   en SHVDN.NativeMemory.FindWeaponInfo(UInt32)
   en SHVDN.NativeMemory.GetAllCompatibleWeaponComponentHashes(UInt32)
   en GTA.WeaponComponentCollection.GetComponentsFromHash(GTA.WeaponHash)
   en GTA.WeaponComponentCollection..ctor(GTA.Ped, GTA.Weapon)
   en GTA.Weapon.get_Components()
   en CoopClient.Util.GetWeaponComponents(GTA.Weapon)
   en CoopClient.Networking.SendPlayerData()
   en CoopClient.Main.OnTick(System.Object, System.EventArgs)
   en SHVDN.Script.MainLoop()
   en System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   en System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   en System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   en System.Threading.ThreadHelper.ThreadStart()

**Comment by Makinolo** [comment]
Same thing happens to me
Aplicación: GTA5.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: System.AccessViolationException
   en SHVDN.NativeMemory.FindWeaponInfo(UInt32)
   en SHVDN.NativeMemory.GetAllCompatibleWeaponComponentHashes(UInt32)
   en GTA.WeaponComponentCollection.GetComponentsFromHash(GTA.WeaponHash)
   en GTA.WeaponComponentCollection..ctor(GTA.Ped, GTA.Weapon)
   en GTA.Weapon.get_Components()

**Comment by dtnguyen22** [comment]
I don't know if this is related, my game crashes every time I hit connect

**Comment by Makinolo** [comment]
@dtnguyen22 Take a look into the Windows Event Viewer -> Windows registry -> application and find the error related to .NET runtime. Post it here to see if it's the same problem, but it's likely it is

**Comment by kagikn** [comment]
Was valid issue. Rockstar changed what the virtual function returns. It returned a pointer value before but now returns a non-pointer value.
