### ISSUE TITLE
Wrong console cursor position with long input text

### ISSUE THREAD

**Issue by Sardelka9515** [crosire/scripthookvdotnet#1133]
**Version**
3.6.0

**Description**
When the input text in console exceeds a certain length, the cursor seems to be placed at half to one character before the position it was supposed to be.
![image](https://user-images.githubusercontent.com/106232474/213162932-510fbaab-14e6-44ce-b272-a2df907aead5.png)
![image](https://user-images.githubusercontent.com/106232474/213163059-c657c402-d606-4abc-8f47-24b24e2e48df.png)

The cursor is at the end of line in both pictures

**Comment by kagikn** [comment]
It looks like `END_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT` will return a smaller value when the input string takes 100 bytes or more (in UTF-8) even the string is pushed as a separate chunk that takes 99 bytes or less.
Therefore, the text byte length should be less than 100 bytes when you call `BEGIN_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT` and `END_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT`. We would have to calcurate text length per 99 bytes or less.
https://github.com/crosire/scripthookvdotnet/blob/4cad4c4b6135d6560e1383442a705a6d125a83df/source/core/Console.cs#L724

**Comment by Sardelka9515** [comment]
Tried with a simple recusive function, but it somehow returns a bigger value now, looks like the text component has some "margin" at the start, and the native has taken that into account.

**Comment by Sardelka9515** [comment]
```
static unsafe float GetTextLength(char* str, int count)
        {
            if (count <= 0) return 0;
            var calculated = count;
            if (calculated > 50) { calculated = 50; }
            while (Encoding.UTF8.GetByteCount(str, calculated) > 50) { calculated--; };
            Call((Hash)0x66E0276CC5F6B9DA /*SET_TEXT_FONT*/, 0);
            Call((Hash)0x07C837F9A01C34C9 /*SET_TEXT_SCALE*/, 0.35f, 0.35f);
            Call((Hash)0x54CE8AC98E120CAB /*_BEGIN_TEXT_COMMAND_GET_WIDTH*/, NativeMemory.CellEmailBcon);
            PushString(new ReadOnlySpan<char>(str, calculated));
            return Call<float>((Hash)0x85F061DA64ED2F67 /*_END_TEXT_COMMAND_GET_WIDTH*/, true) + GetTextLength(str + calculated, count - calculated);
        }
```

**Comment by Sardelka9515** [comment]
It should still be possible to get the raw length by substracting the width of two strings

**Comment by kagikn** [comment]
Closing as 3298662 addresses the issue.
