### ISSUE TITLE
Setting values of MenuToggle,MenuNumericScroller,MenuEnumScroller

### ISSUE THREAD

**Issue by nmdanny** [crosire/scripthookvdotnet#114]
Right now, the menu toggle defaults to false, the numeric scroller defaults to the minimum and the enum-scroller defaults to the first entry. So you can't maintain state whenever you re-open the menu.

It would be useful to have a parameter in the constructor that lets you set their current value(true/false, current number, or current entry index, respectively) , as well as having a property that lets you dynamically change those values.

**Comment by JohnnyCrazy** [comment]
Good catch. :+1:

**Comment by Frede1012** [comment]
Fixed in #121 :)

**Comment by frodzet** [comment]
Can i ask a dumb question here?

I have the latest version of ScriptHookVDotNet (0.9) but i don't see a MenuToggle, i only have the following: Menu, MenuBase, MenuItem and MenuButton.

**Comment by IncoCode** [comment]
@frodzet , download latest version from https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/artifacts

**Comment by frodzet** [comment]
Thanks! :+1:  :dancers:

**Comment by frodzet** [comment]
There are two overloaded methods in the MenuToggle, one has a bool as the last parameter, what is this bool?

Also there is no overloaded method which accepts NO description? :-)

**Comment by Frede1012** [comment]
@frodzet The bool defines whether the toggle starts toggled true or false :)

**Comment by frodzet** [comment]
@Frede1012 ah that makes sense, thank you :-)

**Comment by Frede1012** [comment]
@frodzet No problem!

This issue should be closed though, since its fixed. @JohnnyCrazy @crosire

**Comment by JohnnyCrazy** [comment]
Fixed in #121
