### ISSUE TITLE
SHVDN.NativeMemory.GetGXTEntryByHash(Int32 entryLabelHash)   Maybe there's a mistake?

### ISSUE THREAD

**Issue by BaiFeng666** [crosire/scripthookvdotnet#1150]
**Version**
last night version

**Description**

when I Get Weapon Name , Such as:
`WeaponHash[] weapons = (WeaponHash[])Enum.GetValues(typeof(WeaponHash));
            for (int i =0; i < weapons.Length; i++)
            {
                UIMenuItem weaponItem = new UIMenuItem(Weapon.GetLocalizedName(weapons[i]));
                weaponselectmenu.Add(weaponItem);
            }
`

Weapon.GetLocalizedName() 
I added it myself because I need to get the Chinese name of the weapon....
Here's what the function does
`public static string GetLocalizedName(WeaponHash hash)
        {
            return Game.GetLocalizedString((int)NativeMemory.GetHumanNameHashOfWeaponInfo((uint)hash));
        }
`

The script will crash (Sometimes it crashes, but most of the time it works)

This is Log :
Misinstantiated script  BFMenu.MainMenu Because the constructor throws an exception: System.TypeInitializationException: “BFMenu.SubMenu.WeaponMenu”Throws an exception for a type initializer。 ---> System.AccessViolationException: Attempt to read or write to protected memory. This usually indicates that other memory is corrupted.
   在 SHVDN.NativeMemory.GetGXTEntryByHash(Int32 entryLabelHash)
   在 BFMenu.SubMenu.WeaponMenu.WeaponSelectMenu()
   在 BFMenu.SubMenu.WeaponMenu..cctor()
   --- 内部异常堆栈跟踪的结尾 ---

**Comment by kagikn** [comment]
Confirmed. As I searched dumped exes of b2699 and b2802, two matches will be found with `48 89 5C 24 08 48 89 6C 24 18 89 54 24 10 56 57 41 56 48 83 EC 20`, which is used to find the function `GetLocalizedString()`.

**Comment by BaiFeng666** [comment]
I found out something ...
Game.GetLocalizedString()  is in conflict with Rampage Trainer
when I install Rampage Trainer, Anything about GetLocalizedString() Script will crash

I hope that will be helpful.

**Comment by kagikn** [comment]
> I found out something ... Game.GetLocalizedString() is in conflict with Rampage Trainer when I install Rampage Trainer, Anything about GetLocalizedString() Script will crash
> 
> I hope that will be helpful.

I also confirmed Rampage Trainer hooks the original function. I guess we will have to indirectly find the function address and call it.

**Comment by BaiFeng666** [comment]
Sorry,My skills are limited and I haven't learned how to manipulate function addresses,I hope you can succeed,hhhhhh

**Comment by kagikn** [comment]
Don't mention it. It may be our fault that we didn't spot one memory search could find more than 1 occurrence (in later game versions), but conflict with other mods can happen.
