### ISSUE TITLE
AppVeyor builds fail for unavailable download link for SHV SDK

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#1151]
Starting from 5c9525c2, build fails for the unavailable download link for SHV SDK. https://github.com/crosire/scripthookvdotnet/blob/5c9525c211f150e1c16d1c9a0c71aa0e38f951bb/tools/install_sdk.ps1#L4
I haven't manage to download the SDK from AB's site with PowerShell yet, but we could solve this issue by providing another download link or hosting the SDK on this repo. @crosire

**Comment by justalemon** [comment]
Downloading the SHV SDK from AB's site is easy. You just need to set the headers for the Referer to point to AB's own site.

```ps1
$headers = @{
    "Referer" = "http://www.dev-c.com"
}
$source = "http://www.dev-c.com/files/ScriptHookV_SDK_1.0.617.1a.zip"
Invoke-WebRequest $source -OutFile "sdk.zip -Headers $headers
```

If you want a better example, I have this file called [download.ps1](https://github.com/justalemon/RagePresence/blob/master/sdk/download.ps1) which does this automatically plus some extra cleanup.

**Comment by crosire** [comment]
I had actually tried that first, but had attempted to download from and use the HTTPS site as referer and that failed ... Didn't think to simply try the HTTP variant.

**Comment by kagikn** [comment]
I knew you have to download via HTTP because otherwise just get a 302 response even with a browser, but didn’t think you have to set the referer value `http://www.dev-c.com/` to the header as well.

**Comment by justalemon** [comment]
The HTTPS implementation on AB's site is straight up borked. Only works with the main page and none of the assets.
