### ISSUE TITLE
Hash for Native _DRAW_3D_BOX missing. [Update NativeHashes.hpp]

### ISSUE THREAD

**Issue by Guad** [crosire/scripthookvdotnet#116]
No hash for GRAPHICS::_DRAW_3D_BOX
_START_SCREEN_EFFECT & _STOP_SCREEN_EFFECT are missing too.
Maybe add a way to call functions without the Hash enum?

**Comment by JohnnyCrazy** [comment]
Since NativeDB is updated continuously, we can't ensure our file is always up-to-date.
In your case, the functions are not named in the file, you need use their hash:
![img](http://i.imgur.com/sBRlJHJ.png)

**Comment by crosire** [comment]
@JohnnyCrazy true!

**Comment by mlgthatsme** [comment]
Have you got an automated script to convert them to an enum?

**Comment by JohnnyCrazy** [comment]
Would be cool if we have one in the repo, will see what I can do

**Comment by crosire** [comment]
Did it with a simple regex, so yeah, shouldn't be much of an issue to make a quick script out of it.

**Comment by nevadascout** [comment]
When you add new hashes to the enum, will you remove the raw hashes for them?

Because this will break any compiled DLL's that use the raw hashes, won't it?

**Comment by Nacorpio** [comment]
No, because functions can be called using the raw hash.

**Comment by JohnnyCrazy** [comment]
@Nacorpio I think he means functions, which are named now. Since they have names now, you can't use their old direct hash anymore

**Comment by nevadascout** [comment]
For example, in 0.9 the build, `Hash._SET_BLACKOUT` doesn't exist, so you have to call `Hash._0x1268615ACE24D504` instead.

But if you add `_SET_BLACKOUT` to the hashes enum, and remove `_0x1268615ACE24D504` then my compiled dll will break.

I only ask because no named hashes have their raw hashes in the enum as well.

**Comment by mlgthatsme** [comment]
... You can use 'Function.Call((Hash)0x1268615ACE24D504)' to call the raw hash.

**Comment by nevadascout** [comment]
Ohh, that's cool, I didn't know that :D

But it would still break my compiled DLL if you removed the raw hash for `_SET_BLACKOUT`

**Comment by mlgthatsme** [comment]
Yeah it would, so best idea is that in your code you only use the enum for functions that have their original function name, and use Raw for any user named or unknown ones. It's tedious, but if you just want it to work with most future versions, thats the way to go.

**Comment by nevadascout** [comment]
That makes sense.

It would be stupid to have both the raw and named hashes in the enum, considering none of the existing named ones have their raw ones.

**Comment by JohnnyCrazy** [comment]
Can someone have a look at [helper/NativeGenerator](https://github.com/JohnnyCrazy/scripthookvdotnet/tree/native-generator/helpers/NativeGenerator)?

It's downloading the `natives.json`, parsing the JSON into the object `NativeFile`. Then it will just go through all namespaces and write their functions into `NativeHashes.hpp`

Pro:
* We could add the function's params/result to the inline docs
* `nativeTemplate.txt` can be updated if there is any new license
* Totally dynamic, no need to change anything for a while (forever? :D )

Con:
* JSON .NET Nuget package dependency

**Comment by Frede1012** [comment]
@JohnnyCrazy But i guess it means someone has to run it manually sometimes and commit?

**Comment by IncoCode** [comment]
@JohnnyCrazy ,
```c#
if (File.Exists("NativeHashes.hpp"))
	File.Delete("NativeHashes.hpp");
File.AppendAllText("NativeHashes.hpp", string.Format(nativeTemplate, resultBuilder));
```
it can be done using one method: File.WriteAllText

**Comment by IncoCode** [comment]
@Frede1012 , app veyor can do this, before build.

**Comment by Frede1012** [comment]
@IncoCode Oh, cool!

**Comment by JohnnyCrazy** [comment]
But do we really want this? This means we could have different hashes on every build. This would maybe also break a lot of builts, since the file gets updated AFTER you submit it

**Comment by Frede1012** [comment]
Thats true, that might be problematic.

**Comment by IncoCode** [comment]
@JohnnyCrazy , nobody says that this file must be updated on every build. This tool could be useful for periodic hashes updates.

**Comment by Frede1012** [comment]
I agree the tool is useful, however are we going to just have someone update the hashes manually sometimes?

**Comment by JohnnyCrazy** [comment]
I don't know the exact plans and what @crosire has in mind. Let's just wait what he's suggesting

**Comment by mlgthatsme** [comment]
I think once in a while manually is probably a good idea.

**Comment by crosire** [comment]
While I like the idea to update it automatically each build (The NativeHashes.hpp would be removed from Git tracking and recreated during the build process), I understand it could be a problem. So periodic updates are probably the easiest solution.

**Comment by JohnnyCrazy** [comment]
Yea, but then every realease, in which NativeHashes are updated, is considered as a major release. (We implement new stuff which is not backwards compatible and breaks compiled scripts). So we should consider updating it not that often.

**Comment by crosire** [comment]
Updated to latest version in 5bdb1349e701d3a88cbe47443571a5b8252b88cf using the generator by @JohnnyCrazy.
