### ISSUE TITLE
LSPDFR Crashing

### ISSUE THREAD

**Issue by 5T-23** [crosire/scripthookvdotnet#1160]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
Which version of SHVDN was the problem encountered with?

**Description**
Every time I load lspdfr with scripthook.net 3.6.0 the game closes out no errors at all. As soon as I take out scripthook.net lspdfr loads fine. Is there any solution for this?

**Comment by nomakewan** [comment]
Duplicate of #1127 

It's not LSPDFR but RPH.
