### ISSUE TITLE
NativeVector3 and Vector3

### ISSUE THREAD

**Issue by Sardelka9515** [crosire/scripthookvdotnet#1166]
Just curious about why NativeVector3 was introduced instead of using 8 bytes per field alignment in Vector3 struct. This way we don't have to process the edge case in Function.ObjectFromNative and the pointer and be directly passed to some natives that uses Vector3*.

I assume it's for performance reason, but wouldn't the conversion increase overhead as well?

**Comment by kagikn** [comment]
Note that `Vector3` has the attribute `[StructLayout(LayoutKind.Explicit, Pack = 4)]` and can be used as a pointer type (like `var pos = (Vector3*)(entity.MemoryAddress + offset)`). We might as well consider changing field alignment of `Vector3` struct to 8 bytes in the v4 API, but not in the v3 one in favor of existing script compatibility.
