### ISSUE TITLE
V3 Conflicts with V2 and my compiler decides i referenced V2. 

### ISSUE THREAD

**Issue by HalilErenOymez** [crosire/scripthookvdotnet#1173]
Hi, as i mentioned in the heading, i reference scripthookdotnetv3.6.0 in visual studio. And i copied the scripthookdotnetV2 file in my game folder with v3 as well. I think i hold all of the requirements(visual c+++, .net 4.8 ,ScrptpHookV, etc.). But when i compile my script in the game. But game decides i referenced V2 and gives me namespace errors. Such as "GTA.Vehicle does not contain a definition for mods". But when i delete the scripthookdotnetV2 from my game folder script works without an issue but in this scenario i can't use "NativeUI" to my script as a reference. So can you help me please? I'm trying to solve this for a 1 week now.

**Comment by nomakewan** [comment]
NativeUI is for SHVDN2.

Please update whatever script you're making to use LemonUI instead.

**Comment by HalilErenOymez** [comment]
Ok thanks! I will update it but my priority now is solving the conflict issue. After that i will start the solve NativeUI issues.

**Comment by nomakewan** [comment]
Did you actually reference ScriptHookVDotNet3 explicitly? As an example, for BTTFV, we have this line in our csproj:

```
    <PackageReference Include="ScriptHookVDotNet3">
      <Version>3.5.1</Version>
    </PackageReference>
```
This tells Visual Studio that we intend to use the SHVDN3 library rather than SHVDN2. And since we use LemonUI, which uses SHVDN3, it causes no problems. You should avoid SHVDN2 if you can help it.

**Comment by HalilErenOymez** [comment]
![1](https://user-images.githubusercontent.com/88717962/221348014-264c15b9-4536-4dc4-8df9-1eab5826b5c2.JPG)
i added this codes to my NuGet package from "Manage NuGet Packages" from project menu. But this didn't solve my issue and gave me a warning.(I'm modding/codding learner so i can make silly mistakes sorry)

**Comment by kagikn** [comment]
We don't expect scripts to use multiple API version via some libraries. It might be better if we can log warning messages when multiple api versions are using in one parent script assembly (like parent script is built against the v3 API and it's referencing some library built against the v2 API), though.

**Comment by HalilErenOymez** [comment]
Can you explain me how to do it?

**Comment by nomakewan** [comment]
That warning is normal for packages.config. Visual Studio is just being silly, and it shouldn't stop you from being able to compile since it is a warning not an error.

**Comment by HalilErenOymez** [comment]
ok then i correctly referenced then right?

**Comment by nomakewan** [comment]
Yes, that looks correct.

**Comment by HalilErenOymez** [comment]
![2](https://user-images.githubusercontent.com/88717962/221349595-6242b576-377f-46b1-ba49-397a6ea35c70.JPG)
it's like this. I guess i haven't doubled anything :/

**Comment by nomakewan** [comment]
Yep, looks good. I don't see any problems, nor does Visual Studio.

I'm guessing the only problem you have now is converting the old NativeUI code you were using to the LemonUI equivalents. That isn't an SHVDN-related issue, though. But here: shorturl.at/abkBS

Sadly the LemonUI wiki appears to have disappeared, so above is the link to the Google Cache version of the upgrade guide.

**Comment by HalilErenOymez** [comment]
Well, i deleted scripthookdotnetV2 file from my folder, and referenced lemonui on the top of my codes as"Using LemonUI" and it's already referenced on "references" tab. Now i got this error;
![20230225123953_1](https://user-images.githubusercontent.com/88717962/221350248-b5d01e34-7174-4ca6-a8ad-1ab681e10e11.jpg)
Translation: Type or namespace name not found.(Do you missing using instruction or assembly reference?)

**Comment by nomakewan** [comment]
Again, this is the issues page for ScriptHookVDotNet, and you are not having an issue with ScriptHookVDotNet. Just going to point that out once more. Your issue is now with LemonUI, specifically that you do not know how to use it. I would suggest you start by trying `using LemonUI.Menus;` as your using parameter. LemonUI on its own is not a valid parameter. The valid parameters are:

LemonUI.Elements
LemonUI.Extensions
LemonUI.Menus
LemonUI.Scaleform
LemonUI.TimerBars

I would highly suggest you inquire over on the LemonUI github for further issues with LemonUI. ScriptHookVDotNet is not the appropriate forum for such issues.

**Comment by HalilErenOymez** [comment]
(i haven't used any paramaters or functions etc. I just only referencing lemonui on the top of my code) but my prior problem still is an issue when i add both scripthookdotnetv3.6.0 and scripthookdotnetv2 it gives me errors like this i don't have referencing issues as we discussed before;


![20230225130413_1](https://user-images.githubusercontent.com/88717962/221351163-c4ef2555-3112-4d12-8862-3f387798aefc.jpg)

translation(more or less): at line 34 name not in valid content

at line 35 GTA.Vehicle Hash does not contain a definition for mods and...

**Comment by nomakewan** [comment]
Do not attempt to use SHVDN2 and SHVDN3 simultaneously. Get rid of NativeUI if you are still trying to use it. Only use SHVDN3 and LemonUI.

**Comment by HalilErenOymez** [comment]
Where should i get rid off SHVDVN2 i haven't referenced it before? I don't use NativeUI.

**Comment by nomakewan** [comment]
At this point, I'm afraid my ability to help you ends. I don't know how your code works.

However, now that I look at your screenshots more closely, it appears you're trying to use raw cs files without compiling. I don't do that; I compile scripts into DLLs. This is why I cannot help you any further. I do, however, wish you the best of luck.

**Comment by HalilErenOymez** [comment]
i'm not trying to use them simultaneously. I don't use NativeUI. As i previously said that my code is works when i delete SHVDN2. I'm not referencing it in anywhere. 

> ![2](https://user-images.githubusercontent.com/88717962/221349595-6242b576-377f-46b1-ba49-397a6ea35c70.JPG) my references are exactly like this.

**Comment by HalilErenOymez** [comment]
> At this point, I'm afraid my ability to help you ends. I don't know how your code works.
> 
> However, now that I look at your screenshots more closely, it appears you're trying to use raw cs files without compiling. I don't do that; I compile scripts into DLLs. This is why I cannot help you any further. I do, however, wish you the best of luck.

Ok thanks :/

**Comment by HalilErenOymez** [comment]
> At this point, I'm afraid my ability to help you ends. I don't know how your code works.
> 
> However, now that I look at your screenshots more closely, it appears you're trying to use raw cs files without compiling. I don't do that; I compile scripts into DLLs. This is why I cannot help you any further. I do, however, wish you the best of luck.

OMG! I can cry right now i just compile my script into dll and all of my problems solved!  
![20230225141243_1](https://user-images.githubusercontent.com/88717962/221353798-600a0ced-300d-47bb-9443-92432d511f24.jpg)

Thanks indeed!

**Comment by kagikn** [comment]
Ah, so the issue was the issue author was trying to run their script against the v3 API without compiling. Expected behavior as of v3.6.0 because you need to specify the API version by putting an additional period and an API version number right before the extension string, just like `script.3.cs`. The API version of uncompiled (raw) source code is the v2.

**Comment by HalilErenOymez** [comment]
@kagikn hi, i said my problem solved but still when i try to reach UI class from NativeUI for example i getting same error. But interestingly now i can reach nativeui as you can see in the previous image that i upload. 

![232](https://user-images.githubusercontent.com/88717962/222917817-fb5dc985-2fb5-4c6d-9c85-e55e978cbda1.JPG)
