### ISSUE TITLE
Unknow version error

### ISSUE THREAD

**Issue by peteleco2007** [crosire/scripthookvdotnet#1176]
Scripthookv is updated to the latest version, but the 3.6.0 still gives unknow error, when I remove it, scripthookv works normally, but when I add scripthookvdotnet, it pop ups the error.

**Comment by kagikn** [comment]
I think you must be thinking wrong and this issue should not be relevant to our ScriptHookVDotNet. ScriptHookV has not been updated to v1.0.2845.0 as of the date this issue created and it will give the error when you just have dinput8.dll and ScriptHookV.dll installed. Unless you have backups of older GTA5.exe and update.rpf files, you have to wait until ScriptHookV updates.
