### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by IncoCode** [crosire/scripthookvdotnet#118]
Is it possible to use threads? Or this is not a good idea? :smile: 
```c#
new Thread( () =>
{
	player.Armor = 100;
} ).Start();
```
Then error and crash:
```
Caught fatal unhandled exception:
System.NullReferenceException: 
   в GTA.ScriptDomain.ExecuteTask(IScriptTask task)
   в GTA.Native.Function.Call[T](UInt64 hash, InputArgument[] arguments)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()
```

**Comment by JohnnyCrazy** [comment]
Some methods seem to crash the game when called outside the main-thread (e.g `UI.Notify`) while some actually work.
About the good idea thing. Yea, why not, I'm using it in some mods too and some implementations just require threading :stuck_out_tongue_winking_eye: 
For example you can use a `ConcurrentQueue`:

````c#
private ConcurrentQueue<Action> queue = new ConcurrentQueue<Action>();

//OnTick
if (queue.Count > 0)
{
    Action action;
    if (queue.TryDequeue(out action))
        action();
}

//in some other Thread
queue.Enqueue(() => player.Armor = 100);
````

**Comment by crosire** [comment]
No, do not do this! There's a reason for all the complicated task scheduling in the ScriptDomain implementation. The game only accepts sequential script calls, multi-tasking (and thus the possibility for multiple calls to be made at the same time) breaks both the C++ Script Hook (which works with thread-unsafe globals) and the game. So if you need multiple separate "threads", just use multiple classes inheriting from "Script", that's what they are for.

**Comment by IncoCode** [comment]
Thanks for answers.
