### ISSUE TITLE
World.GetClosestVehicle broken as of f91b701

### ISSUE THREAD

**Issue by nomakewan** [crosire/scripthookvdotnet#1186]
**Version**
Latest source build, dc331ad

**Description**
While working on my mod I noticed that some of our train-related code was no longer working correctly. When I dug into why I discovered that the code we were using to detect conflicts with other rail vehicles was detecting the player's vehicle as a conflict rather than only seeking out GTAV's freight trains. The code we use is this:

`Vehicle _train = World.GetClosestVehicle(Vehicle.Position, 25, ModelHandler.FreightModel, ModelHandler.FreightCarModel, ModelHandler.TankerCarModel);`

Under normal circumstances this would remain null until a freight train or its cars were nearly touching the player's vehicle. However, as of f91b701 this instead returns the player's own vehicle, which is not FreightModel (freight), FreightCarModel (freightcar), or TankerCarModel (tankercar). It is its own unique model, referred to in our code as as ModelHandler.DMCDebugModel (dmc_debug). As such, there should be no way for `World.GetClosestVehicle(Vehicle.Position, 25, ModelHandler.FreightModel, ModelHandler.FreightCarModel, ModelHandler.TankerCarModel);` to return the player's own vehicle.

To be absolutely sure, I then did a follow-up test where I used this code while my character was sitting in any vehicle:

```
Vehicle _test = World.GetClosestVehicle(Vehicle.Position, 25, ModelHandler.Deluxo);
if (_test != null)
    GTA.UI.Screen.ShowSubtitle("_test: " + _test + " Distance: " + _test.DistanceToSquared2D(Vehicle) + " IsTouching: " + Vehicle.IsTouching(_test));
```
Then I got into a completely unrelated vehicle to the Deluxo, while there was in fact no Deluxo spawned anywhere in the world. Sure enough, I got this subtitle:

![271590_20230324033726_1](https://user-images.githubusercontent.com/11485516/227499205-b08df0f3-dbc9-4594-96d6-1e280bc1d3c0.png)

As the actual World.GetClosestVehicle didn't change at all, I'm afraid I'm at a loss as to why it is no longer working properly.

**Comment by kagikn** [comment]
I just forgot to use the model array argument when I refactored internal code for entity handle fetch, and nothing else 🙂 Glad the issue was found before the new official version was shipped.
