### ISSUE TITLE
DISABLE_CONTROL_ACTION is not working SHVDN3

### ISSUE THREAD

**Issue by yusufYAZICI155** [crosire/scripthookvdotnet#1189]
I try this code from F4 console of SHVDN3 but this not working.

`GTA.Native.Function.Call(GTA.Native.Hash.DISABLE_CONTROL_ACTION, 0, (int)GTA.Control.Phone, true)`

I can open phone after this code write.
I want to the phone not to be opened

**Comment by Dominikjano** [comment]
Nejde to

**Comment by Dominikjano** [comment]
@XBLToothPik

**Comment by kagikn** [comment]
For those wondering if this issue is really responsible to SHVDN, this is not the case. `DISABLE_CONTROL_ACTION` disables the given action only for 1 frame.
