### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by crosire** [crosire/scripthookvdotnet#12]
We need some visualization for errors and some way to send commands to ScriptHook (like to reload scripts), without having to use keys for everything.
It's probably easiest to start with an external console window and then later write one rendered ingame.

**Comment by IncoCode** [comment]
lol. I thought that "closed #12, #13" only applies to my repo. :worried: sorry

**Comment by crosire** [comment]
Oh. Didn't even notice this =D

**Comment by JohnnyCrazy** [comment]
Some notes:

* **We need a LowLevel-Keyboard Hook IMO**  
If we want to support a full ingame console, we need to be able to catch keyhooks with the ability to block them (so the game won't receive the keydown). These Keyhooks are easy to implement and should give us a lot more freedom. 

* **What should be printed to the console? All log entries?**
I would actually go with the last one and print all log entries. Any other thoughts?

* **Best Console Toggle Key?**
F10 is critical key, since a lot of capture programs use the last F-key row for recording stuff. If we get the LowLevel-Keyboard hook working, maybe SHIFT + ^?

* **What functions should it supply to scripts?**
I would simply go with one function, `AddCommand(String cmdName, Action<String[] args> callback)`. And what about storring them, should every Script get their own dictionary? (this would allow registering the same command on two different scripts)

**Comment by Frede1012** [comment]
- The LowLevel-Keyboard hook is a great idea, if someone knows how to implement it.
- I dont think every log entry should be printed, the console log will be too cluttered, i think the scripts themselves should be allowed to choose if the log entry is shown or not.
- If we get a LowLevel-Keyboard hook, i think "tilde" is the best key (also used by many others as a console key).
- Seems like a good idea, however how would you call a specific scripts command? Something like `scriptname commandname args`?

**Comment by crosire** [comment]
- I had a keyboard hook implemented in an earlier version, but removed it again since the C++ Script Hook implemented one itself, so just reused that one.
- I'd print everything too actually (maybe reduce the log messages Script Hook writes itself a little).
- ^ is the tilde key on german keyboards, so that's what @JohnnyCrazy meant =)

**Comment by Frede1012** [comment]
@crosire @JohnnyCrazy I worked a bit on handling commands, however there seems to be some weird syntax error in my code, any ideas (im not that experienced in C++)? https://github.com/Frede1012/scripthookvdotnet/commit/29b3f843de6e24439f7b3024a67de8897b1a63f5

**Comment by crosire** [comment]
@Frede1012 In [Console.hpp](https://github.com/Frede1012/scripthookvdotnet/commit/29b3f843de6e24439f7b3024a67de8897b1a63f5#diff-a4303326ab1baba9b29709ea86d54d45R29) you are using the ConsoleCommand class before actually having declared it (it's declared after Console).

**Comment by Frede1012** [comment]
@crosire Oh, fixed and submitted as pull request #120

**Comment by Frede1012** [comment]
What's next? @JohnnyCrazy @crosire

**Comment by JohnnyCrazy** [comment]
Just had a quick look, but the next thing would propably a keyhook so we can actually use it.

**Comment by mlgthatsme** [comment]
You can uses DISABLE_ALL_CONTROL_ACTIONS to stop all player input, if that helps at all.

Also I noticed, that there is a string size limit when rendering text? So if you were to make a console, it might not even render all text properly. This something to do with CLI?

**Comment by crosire** [comment]
@mlgthatsme Good idea. I'd prefer to use that over adding yet another keyboard hook (over the one the C++ script hook already installs). It only makes things more complicated and slower.

**Comment by Frede1012** [comment]
@mlgthatsme The string size limit is a native function limit, i don't think we have any method of defining  the width of the label.

**Comment by mlgthatsme** [comment]
Ahhh damn. Might have to do some memory patching on start up to increase that or something along those lines. Another idea would be to hook into the GXT function in the executable itself, and reroute.

**Comment by Sergeeeek** [comment]
Would it be possible to use scaleform for that?

**Comment by crosire** [comment]
There is https://www.gta5-mods.com/scripts/net-developer-console now, so I don't think we need to add this to the core anymore =).

**Comment by nevadascout** [comment]
That mod has been created with functions that are designed to cheat in multiplayer. Just look the source code, there is a anti ban function and a kick function. This will be used to cheat.

https://github.com/Dakota628/GTAVDeveloperConsole/blob/master/gtav_console/Commands/DefaultCommands.cs

**Comment by JohnnyCrazy** [comment]
I second this.
We should not depend on a third party for such simple and important features. 

(And this library is definetly not legit, [look at this](https://github.com/Dakota628/GTAVDeveloperConsole/blob/be58b2ed2264bb6a34b9821eb516e7d72e5e51ca/gtav_console/Utils/GTAFuncs.cs#L241) )

**Comment by Dakota628** [comment]
@crosire If you want, I may be willing to modify the script to any requests/standards.

**Comment by JohnnyCrazy** [comment]
@Dakota628 
Well, then you should realize that modding online is a violation against their TOS and is not tolerated. If we link to your library as console-extension, then their should be no online support at all (IMO). But @crosire has to decide, wether we support it or not.

**Comment by Dakota628** [comment]
@JohnnyCrazy That is certainly understandable. As I stated I am willing to make any changes to comply with ethical expectations of this project. Just create an issue or pull request.

**Comment by nevadascout** [comment]
> preventing online manipulation completely with my script is impossible

ScriptHookV does not allow you to play online with it loaded.

**Comment by Dakota628** [comment]
@nevadascout Yes I wrote something to bypass it and add other debug features.

**Comment by crosire** [comment]
I'm strictly against anything directly violating the games terms of use or GTA Online modding. But still, a console project does exist and it can be used for singleplayer modding, so I see no benefit in adding another one. I would of course highly appreciate it if you remove the non-legit features, at least from the public source base, but it's your project afterall =).

**Comment by Dakota628** [comment]
@crosire Sounds good. I'll remove all the non essential commands. I urge anybody who sees any additional issues violating the TOS to submit an issue or pull request.

**Comment by crosire** [comment]
@Dakota628 Thank you, a lot!
