### ISSUE TITLE
Mission Blips

### ISSUE THREAD

**Issue by GoatedAk** [crosire/scripthookvdotnet#1209]
Add a clear and concise description of the feature you have in mind.
Are the mission blips bugged, Mines aren't working for some missions, when I take SCVDN out it works fine.

**Comment by kagikn** [comment]
We're sorry to say this for your first issue, but this issue only has a too vague info for us to reproduce. If you have the idea how to reproduce the issue, you'll have to write in detail (including the SHVDN version you are using).
