### ISSUE TITLE
Set ped.Bones[bone].Rotation?

### ISSUE THREAD

**Issue by ILaCHu** [crosire/scripthookvdotnet#1210]
Any chance to add Set ped.Bones[bone].Rotation ?

**Comment by kagikn** [comment]
I doubt if we can create a proper implementation for the setter of `EntityBone.Rotation` as `GET_ENTITY_BONE_ROTATION` also reads the translation matrix that is not separated by bone IDs (see 2464065 for a little more detail). I think we can add the setter of `EntityBone.RelativeRotation`, however.
