### ISSUE TITLE
Compatibility Issues with RAGE Hook Plugins

### ISSUE THREAD

**Issue by VenomGames120** [crosire/scripthookvdotnet#1224]
**Version**
Which version of SHVDN was the problem encountered with?
Latest Version

**Description**
I know this has been an ongoing issue for a lot of people because I've seen it posted on other githubs and discords as well. I'm not really sure if this is the right place to report this but recently i've encountered a crash while trying to load any plugin from RAGE Hook. I narrowed it down to the cause being the scripthookvdontnet files causing the crash. I read on another post [(976)](https://github.com/crosire/scripthookvdotnet/issues/976) that people were already aware of this issue and what causes it, I just thought I'd bring it to attention on this page so hopefully it gets fixed. It would definitely help a lot of people that have been having the issue.
Thanks

**Comment by kagikn** [comment]
I would say the same thing as in #1217. If you encounter the issue in v3.6.0, that is expected. Try with builds later than 29ba91e (such as a3dd322) first if you would like to run both ScriptHookVDotNet and RAGE Plugin hook at the same time before the next SHVDN version is released. If you still encountering the issue, please describe the issue verbosely as possible such as the exact ScriptHookVDotNet version ("latest version" is too ambiguous for other people to recognize the version on sight).

**Comment by VenomGames120** [comment]
Alright, so what releaseof ScriptHookVDotNet should i use? (meaning like v3.version number) When I click on a3dd322 it brings me to the changes

**Comment by kagikn** [comment]
Good question actually, CI checks don't directly show in the commit page, so I excepted.
You can download the artifact for the builds on AppVeyor from the badge in README (here's [the link for a3dd322](https://ci.appveyor.com/project/crosire/scripthookvdotnet/builds/47048371/artifacts)). That build is not official one, but I'm planning to officially release the next version soon after the publisher transferring is completed.

**Comment by VenomGames120** [comment]
Installing that version did the trick! Everything works now thank you so much!

**Comment by WaavyGravy** [comment]
> 

Sorry to post about this again, is there a new link for an artifact download on AppVeyor? I'm not seeing anything to download, although I could be doing it wrong.

**Comment by kagikn** [comment]
You can download new artifacts from the Actions page. Choose an item with a green check mark and download an artifact from the Artifacts section.
