### ISSUE TITLE
neew LineCount

### ISSUE THREAD

**Issue by BaiFeng666** [crosire/scripthookvdotnet#1226]
GTA.UI.TextElement.cs maybe can add a property
`/// <summary>
		/// Get Line Count
		/// </summary>
		public int LineCount
		{
			get
			{
				return (int)(this.Width / this.WrapWidth) + 1;
			}
		}`

Many things will be convenient

**Comment by kagikn** [comment]
I think we could get more accurate results with `BEGIN_TEXT_COMMAND_GET_NUMBER_OF_LINES_FOR_STRING` and `END_TEXT_COMMAND_GET_NUMBER_OF_LINES_FOR_STRING`, but seems worth the addition.
