### ISSUE TITLE
Message bus between scripts?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#123]
I have read we must not use threading in our scripts. Crosire says we should let classes simply inherit from Script in order to let them run in their own thread. However there needs to be a way to communicate between those classes without coupling them. So is there a message bus we can use to toss around data?

**Comment by IncoCode** [comment]
At the moment, we can use only static fields and etc.

**Comment by RainerHilmer** [comment]
Hmm... okay. So I guess I make an event based approach whenever one class needs to wait for something to happen in the other.

**Comment by JohnnyCrazy** [comment]
Just leaving a tip here: [Singletons](https://msdn.microsoft.com/en-us/library/ff650316.aspx) should be a good alternative, only one object-instance will be created and you can access it from every script.

**Comment by RainerHilmer** [comment]
I know Singletons but that's completely different from a message bus and serves a whole different purpose..
