### ISSUE TITLE
Key combination with Shift not recognized.

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#128]
See for yourself by simply attaching this to a KeyDown event.

      private void OnKeyDown(object sender, KeyEventArgs e)
      {
         var output = "Alt=" + e.Alt
                      + "/Ctrl=" + e.Control
                      + "/Shift=" + e.Shift
                      + "/Key=" + e.KeyCode;
         UI.Notify(output);
      }

**Comment by nevadascout** [comment]
Confirming that this also happens for me. `e.KeyCode` returns as "ShiftKey"

**Comment by crosire** [comment]
Should work now, was a simple typo.

**Comment by nevadascout** [comment]
Awesome, thanks
