### ISSUE TITLE
Get list of entities

### ISSUE THREAD

**Issue by crosire** [crosire/scripthookvdotnet#13]
Something like "GTA::World::GetPeds"/"GTA::World::GetVehicles". There doesn't seem to be a native function for this though (correct me if I'm wrong), so need to do this differently somehow (GTAIV ScriptHook read it directly from game memory for example).

**Comment by WozStudios** [comment]
`World::GetNearbyPeds()` and `World::GetNearbyVehicles()` both work properly now, but we should still leave this issue open for now.  Both methods seem to only return entities within a maximum radius of 55 units

**Comment by crosire** [comment]
And it only works by passing another ped, it would be nice to have methods were you just have to pass a position.

**Comment by Sergeeeek** [comment]
I'm working on this. The address of the entity pool is at *(GTA5.EXE+29A1920). The way pools are laid out in the memory is pretty much the same as GTA 4 so you can see how it can be implemented in original ScriptHook .Net.

**Comment by IncoCode** [comment]
:+1:

**Comment by crosire** [comment]
@Sergeeeek That's great to know!

**Comment by JohnnyCrazy** [comment]
Discussion continues in #191 , should be merged soon :+1:
