### ISSUE TITLE
Scaleforms

### ISSUE THREAD

**Issue by mlgthatsme** [crosire/scripthookvdotnet#130]
Hi all,

I've been playing around with the Scaleform natives and I've gotten things like loading Scaleforms, then rendering them to either the entire screen, a location on the screen or in 3D space.

I've managed to implement it all in C#, but I just need some help with porting it over to CLI/C++.

Everythings working, but I can't for the life of me figure out the CLI equivalent of the following code:

            foreach (object o in arguments)
            {
                if (o is Int32)
                {
                    Function.Call(Hash._0xC3D0841A0CC546A6, (Int32)o); // _PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_INT
                }
                else if (o is String)
                {
                    Function.Call(Hash._0x80338406F3475E55, "STRING"); // _BEGIN_TEXT_COMPONENT
                    Function.Call(Hash._ADD_TEXT_COMPONENT_STRING, (string)o);
                    Function.Call(Hash._0x362E2D3FE93A9959); // _END_TEXT_COMPONENT
                }
                else if (o is Char)
                {
                    Function.Call(Hash._0x80338406F3475E55, "STRING"); // _BEGIN_TEXT_COMPONENT
                    Function.Call(Hash._ADD_TEXT_COMPONENT_STRING, ((char)o).ToString());
                    Function.Call(Hash._0x362E2D3FE93A9959); // _END_TEXT_COMPONENT
                }
                else if (o is Single)
                {
                    Function.Call(Hash._0xD69736AAE04DB51A, (Single)o); // _PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT
                }
                else if (o is Double)
                {
                    Function.Call(Hash._0xD69736AAE04DB51A, (Single)((Double)o)); // _PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_FLOAT
                }
                else if (o is Boolean)
                {
                    Function.Call(Hash._0xC58424BA936EB458, (Boolean)o); // _PUSH_SCALEFORM_MOVIE_FUNCTION_PARAMETER_BOOL
                }
                else if (o is SFArgSprite)
                {
                    Function.Call(Hash._0xBA7148484BD90365, ((SFArgSprite)o).name); // Pass a TXD
                }
                else
                {
                    throw new Exception(string.Format("Unknown argument type {0} passed", o.GetType().Name));
                }
            }

More specifically, the `if (o is {insert_type_here})` and casting the objects to said type.

So hopefully when it's done we can start seeing more mods use stuff like this :)

![grand_theft_auto_v_2015-05-25_01-57-23](https://cloud.githubusercontent.com/assets/1716268/7818700/979014f4-0420-11e5-9d90-29e3bdc20ce3.jpg)
![grand_theft_auto_v_2015-05-25_23-03-41](https://cloud.githubusercontent.com/assets/1716268/7818723/b7ac4690-0420-11e5-8497-fbe5d212985d.jpg)

**Comment by IncoCode** [comment]
Here's nice MSDN article: https://msdn.microsoft.com/en-us/library/85af44e9(vs.80).aspx

**Comment by RainerHilmer** [comment]
Sorry for being off topic but how do you get the online garage in single player mode?

**Comment by Nacorpio** [comment]
@RainerHilmer Don't ask a question like that in this issue - start your own if you need help.

**Comment by mlgthatsme** [comment]
It's a mod I'm working on. I also might submit the code I use to save vehicles to a class cause that might be handy for some people. And thanks @IncoCode I'll check that out :)

**Comment by JohnnyCrazy** [comment]
You could also check [this link](http://stackoverflow.com/questions/2410721/how-to-check-an-objects-type-in-c-cli)

**Comment by JohnnyCrazy** [comment]
Since it's merged, we could use this issue as a discussion if you're okay with it @mlgthatsme 

* Should we implement some scaleforms into our UI-part? e.g  `MIDSIZED_MESSAGE` seems useful
* We don't have any way to remove scaleforms yet (`SET_SCALEFORM_MOVIE_AS_NO_LONGER_NEEDED`)

**Comment by mlgthatsme** [comment]
Yeah thats fine. And sure thing. Implementing it into the code would make it easier for developers, so why not :) Only problem with setting a scaleform as no longer needed is sometimes it can interfere with the games native scripts that are currently using them. Although I could be wrong.
