### ISSUE TITLE
How to add the new abstract class?

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#131]
Greetings,

So there's this new Updater abstract class added to the repository, however i'm not quite sure how i can access it in my code? I've tried adding the abstract class below my own class and tried to add it separately to it's own .cs file but it just won't work or well it might, but i'm not quite sure exactly what it does and how to access it's Methods etc?

**Comment by Nacorpio** [comment]
Just override all the abstract methods from the Updater class, and you'll be good to go.

**Comment by frodzet** [comment]
Thanks, could you explain to me what it does? :-) Sorry, but i'm new at programming, just saw an "update" that i wanted to apply to my ScriptHookDotNet, but some understanding on what it does would be nice :-)

**Comment by Nacorpio** [comment]
I explained everything here:
https://github.com/crosire/scripthookvdotnet/wiki/Tick-System-by-Nacorpio

**Comment by frodzet** [comment]
Thank you :-)
