### ISSUE TITLE
Menu Font uses integer values? [Implement Font-Enum]

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#135]
I'm trying to change the font in my menu, however in order to change the font it requires an integer value? So is there either a way to use Enumerations instead or is there maybe a way that i can find these Fonts according to their assigned integer value?

**Comment by nevadascout** [comment]
Have you tried just experimenting with int values? eg. using `1` or `3` ?

**Comment by Frede1012** [comment]
I think having an Enum is a good idea, however i dont know which font is associated with which int. Also i dont know the names of any of the fonts :P

**Comment by nevadascout** [comment]
> I think having an Enum is a good idea

Agreed, there's really no reason not to have one for things like this.

**Comment by JohnnyCrazy** [comment]
The only problem I see: How we want to name the fonts?
4 is a thicker font than 3 and 2 is some kind of curved font, no idea for names tho

**Comment by nevadascout** [comment]
I'll have a look at all the fonts and work out what their names are.

**Comment by nevadascout** [comment]
So it appears that there are 8 fonts:

```
0 -> Arial
1 -> House Script
2 -> Monospace (name unknown)

3 -> Icon Font
4 -> Helvetica Bold
5 -> Broken - only numbers appear when using this font

6 -> Helvetica
7 -> Pricedown
```

Font 3 is interesting. It appears to be some kind of icon font... This is all english chars + numbers in font 3: http://i.imgur.com/CgsuHbm.jpg

Also, choosing in an int larger than 7 defaults to font 0.

**Comment by Frede1012** [comment]
Good work! Not sure if we should include the icon font, and definitely not the broken font :P

**Comment by nevadascout** [comment]
The icon font would be useful if we could set specific parts of menu buttons to be different fonts. Then you could have an arrow denoting that a button has a sub menu.

Actually, now that I think about it, I'm pretty sure that the icon font is used in the in-game menus to show the left-right arrows on numbers indicating that they can increase/decrease

**Comment by Frede1012** [comment]
I agree, however our current implementation does not allow for font changes mid string.

**Comment by nevadascout** [comment]
So for a `GTA.Font` enum I'll suggest these values:

```
Arial           -> 0
HouseScript     -> 1
Monospace       -> 2
Helvetica       -> 6
Helvetica Bold  -> 4
Pricedown       -> 7
```

**Comment by Frede1012** [comment]
@nevadascout You want me to do it?

**Comment by nevadascout** [comment]
Well you don't have to, but you can if you want to :D

**Comment by Frede1012** [comment]
Sure, give me a sec :-)

**Comment by Frede1012** [comment]
@nevadascout Which file do you think it makes the most sense to have it in?

**Comment by nevadascout** [comment]
Not sure to be honest. I have zero experience with C++, but in C# an enum would go into it's own file.

Maybe the menu file (as that's what it's related to?)

**Comment by Frede1012** [comment]
I was thinking its own file as well, however i am not sure. @JohnnyCrazy ?

**Comment by Nacorpio** [comment]
All the other enums seem to be placed in their files.

**Comment by nevadascout** [comment]
I'd go with a new file then, @Frede1012 :)

**Comment by Frede1012** [comment]
Added in #152 :)

**Comment by crosire** [comment]
@nevadascout The source is organized in the VS project using filters instead of being organized on filesystem level.

**Comment by nevadascout** [comment]
@crosire Ah, fair enough

**Comment by frodzet** [comment]
Oh wow, thanks man! :+1:

**Comment by JohnnyCrazy** [comment]
Done in #152
