### ISSUE TITLE
MenuToggle and MenuEnumScroller bugs, plus enhancement idea

### ISSUE THREAD

**Issue by nmdanny** [crosire/scripthookvdotnet#139]
I found some bugs:
1. In MenuToggle, the initial value given in the constructor does not seem to work. The toggle will show an off value regardless.
2. In MenuEnumScroller, you can go out of bounds and it generates exceptions.

enhancements:
1.for the scrollers, have them jump between the first/last values whenever going out of bounds.
2.the numeric scroller's interface(aka get/set property and constructor) shouldn't use 'timesIncremented', instead it should use the value itself.
3. The EnumScroller currently uses a string array and an index to access the values, which isn't very convenient. I think it would be better if it had used a generic list for the elements, and perhaps a Func<T,string> that would display those elements. (And use ToString if no Func has been specified). In addition, instead/in addition to exposing the current index, it should have a CurrentItem property, plus setting the selected item in the constructor, instead of the selected index.

**Comment by frodzet** [comment]
Ah i thought it was just me doing something wrong with that initial value. Tried all sorts of things but returned (OFF) regardless of the boolean.

**Comment by Frede1012** [comment]
It returns the correct value, but is not showing it. Correct?

**Comment by Frede1012** [comment]
Fixed in #141 :)

**Comment by nevadascout** [comment]
If this is resolved, can this issue be closed?

**Comment by JohnnyCrazy** [comment]
Sure @nevadascout
