### ISSUE TITLE
Script logging

### ISSUE THREAD

**Issue by crosire** [crosire/scripthookvdotnet#14]
I think it would be useful to adjust the logging class (#11) to create separate log files when called from inside a script, so that the log isn't cluttered.

**Comment by JohnnyCrazy** [comment]
Yes, and we should add different logging types e.g debug, Info, Warning, error

**Comment by Frede1012** [comment]
Solved in #90 or?

**Comment by Nacorpio** [comment]
I think I'm going to create a tool that reads the logs and gives you a notification in the notification-center once an error occurs in the script. I don't know, though.

**Comment by Frede1012** [comment]
That is a good idea, however I think it should be featured in the script console instead.

**Comment by Nacorpio** [comment]
Or in-game.

**Comment by Frede1012** [comment]
Yes, the ingame script console :P

**Comment by Nacorpio** [comment]
Ah, I see what you mean now.

**Comment by crosire** [comment]
No longer needed due to 5cff7ca7c6e03e28a18b888baf0a1899ffe494fe.
