### ISSUE TITLE
My updater explanation and example

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#140]
For those of you who didn't understand the point of my Updater class, I will show some examples:
https://github.com/Nacorpio/GTA-Z/blob/master/GTAZ/Vehicles/AbandonedVehicle.cs
https://github.com/Nacorpio/GTA-Z/blob/master/GTAZ/Peds/TeamPed.cs

As I mentioned previously, it is pretty useful if you know how to use it. :+1:

**Comment by frodzet** [comment]
:+1: Thanks :-)

**Comment by Frede1012** [comment]
Maybe post this in the wiki instead?

**Comment by Nacorpio** [comment]
I thought that too, but I can't do that.

**Comment by Frede1012** [comment]
Why not?

**Comment by Nacorpio** [comment]
I didn't have time yesterday. I updated it now, though.
https://github.com/crosire/scripthookvdotnet/wiki/Tick-System-by-Nacorpio

**Comment by Frede1012** [comment]
Ah :-)
