### ISSUE TITLE
I get an error suddenly when I added a menu base

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#143]
[18:32:43] [ERROR] Failed to list assembly types:
System.Reflection.ReflectionTypeLoadException: Det går inte att läsa in en eller flera av de begärda typerna. Hämta egenskapen LoaderExceptions om du vill ha mer information.
   vid System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   vid System.Reflection.Assembly.GetTypes()
   vid GTA.ScriptDomain.LoadAssembly(String filename, Assembly assembly)

**Comment by Frede1012** [comment]
Sourcecode?

**Comment by Nacorpio** [comment]
I just added a reference.

**Comment by Nacorpio** [comment]
I just found out that when I inherit the menu base, I just get that error.

**Comment by Frede1012** [comment]
What about when you just inherit Menu? That seems to be working for me.

**Comment by Nacorpio** [comment]
It's not the same base as you're using.

**Comment by JohnnyCrazy** [comment]
We need some actuall source to work with :)

**Comment by Nacorpio** [comment]
You can close this issue. It's fixed. :+1:
