### ISSUE TITLE
Adding menu related events

### ISSUE THREAD

**Issue by nmdanny** [crosire/scripthookvdotnet#148]
I think it would be of benefit if there were some events for menu related elements, in addition to the current way(using actions).
Events follow the conventions of most C# GUI libraries, plus they allow multiple methods to be subscribed to an event. 
Also, events would provide access to the sender(the menu/button), which would be useful for dynamically changing elements.(A button whose caption is changed upon click, for example), seeing as actions currently provide very little information. (And events are a better practice for such uses, though I think actions should be left for convenience with simple methods.)

**Comment by JohnnyCrazy** [comment]
Yep! Definitely a good idea. 
Actions was only the first approach, we should change it to events before 1.0

**Comment by Frede1012** [comment]
So they support both actions and events or only events?

**Comment by nmdanny** [comment]
I think we should get rid of the action properties, but keep them in the constructors. The constructors would subscribe the parameter actions to the events.

**Comment by Frede1012** [comment]
So no constructors that take events? I am unsure of how you want this implemented..

**Comment by nmdanny** [comment]
Constructors can't take events, what I mean is something like this.
```C#
    public class MenuButtonEventArgs
    {
        public MenuItem MenuItem { get; set; }

        public MenuButtonEventArgs(MenuItem item)
        {
            this.MenuItem = item;
        }
        // more relevant properties here..
    }

    public class MenuButton:MenuItem
    {
        public event EventHandler<MenuButtonEventArgs> OnActivate;
        public MenuButton(string caption, string description, Action activateAction)
        {
            this.Caption = caption;
            this.Description = description;
            this.OnActivate += (sender, args) => activateAction();
        }

        protected virtual void RaiseOnActivate() // called whenever the player activates a menu button
        {
            if (OnActivate != null) 
                OnActivate(this, new MenuButtonEventArgs(this)); // more advanced controls will usually pass more args to the object..
        }

        // more properties/methods and such here...
    }
```
then, in order to use this, somebody could create a quick button this way:
```C#
 var myButton=new MenuButton("Some button","",()=>UI.Notify("Hi"));
```
Which is identical to how it's currently done, only that internally it registers that UI notify action to the event instead of saving it as an Action property.
If we wanted more control we would do the following:

```C#
myButton.OnActivate+= (s,e) => 
{
   (s as MenuButton).Caption= "I've been activated!";
   UI.Notify("Button activated.");
};
```

**Comment by Frede1012** [comment]
Ah, i dont know much about events. So why is this implementation better?

**Comment by nmdanny** [comment]
It's not a very big change as events are pretty much an encapsulation of delegates.
The major improvement is that you can register multiple methods to a single event.
Secondly, it's a convention used in most C# GUI libraries. So I think it would be a good idea to follow it.

Also, either way we need to change the actions so they'd pass the sender too(so your lambdas/methods could change the button that invoked them), so we might as well change to events.

**Comment by Frede1012** [comment]
Seems like a great idea!

**Comment by frodzet** [comment]
I like it! 
But getting rid of actions would that then mean that our projects would have to be re-constructed?

**Comment by nmdanny** [comment]
If you use the action property then yes, but we can keep the action signature in the constructors(like in the above example) then no.

**Comment by frodzet** [comment]
Sweet, sounds really good :-) Would love to see this feature :+1:

**Comment by IncoCode** [comment]
I have a question. In managed c++ we can't register action to the event in a way that was described by @nmdanny (https://github.com/crosire/scripthookvdotnet/issues/148#issuecomment-107228674). How to implement it? Or leave it as it is and just add an event? Something like:
```c++
void MenuButton::Activate()
{
	mActivationAction->Invoke();
	this->SomeEvent(this, params);
}
```

**Comment by JohnnyCrazy** [comment]
Just do it right after you created the object, no need to pass it to the constructor.

**Comment by IncoCode** [comment]
@JohnnyCrazy it's current implementation: [we can pass action to the constructor](https://github.com/crosire/scripthookvdotnet/blob/master/source/MenuItem.hpp#L48) that will called if item was selected.

**Comment by nmdanny** [comment]
We could for now keep the action property+the action constructor, and events would be completely separate from them. Not the neatest solution but it would maintain compatibility with the current way of creating menu/items.

**Comment by frodzet** [comment]
@nmdanny But would maintaining compatibility be worth it? I mean version 1.0 haven't hit yet, so people would properly have guessed that such changes might occur?

**Comment by JohnnyCrazy** [comment]
I think we should completely remove actions. Bad practice

**Comment by Frede1012** [comment]
If we are changing to events, no need to keep the actions.

**Comment by crosire** [comment]
I'm closing this due to #260.
