### ISSUE TITLE
World.CreateVehicle not Working

### ISSUE THREAD

**Issue by ajberasategui** [crosire/scripthookvdotnet#154]
Hi, 
I'm using lastest version from github and the following code is not working:

`Vehicle v = World.CreateVehicle(VehicleHash.Buffalo2, Game.Player.Character.Position * 2, Game.Player.Character.Heading);`

And this is always returning null and not creating the Vehicle. I've also tried:
`Vehicle v = World.CreateVehicle(new Model(VehicleHash.Buffalo2), Game.Player.Character.Position * 2, Game.Player.Character.Heading);`
with no success.

**Comment by ajberasategui** [comment]
I think my error was not requesting the vehicle model and waiting for it to load before creating it. Doing so makes it work fine.

**Comment by JohnnyCrazy** [comment]
[World.CreateVehicle does request the model on its own](https://github.com/crosire/scripthookvdotnet/blob/master/source/World.cpp#L191)

The only possible reason in my eyes could be the timeout. But I doubt the model won't load within 1 second

**Comment by ajberasategui** [comment]
Yes, you're right. The problem is other bit I don't know which. Sometimes it works and sometimes not. 

I'll reopen the issue if I find more feedback to post, meanwhile if I'm the only one experiencing it, it's probably me using it wrong somehow.
