### ISSUE TITLE
How to add Buttons Horizontal instead of Vertical? :-)

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#156]
Greetings,

Pretty much the title is self-explanatory, but here it goes. 

I'd like to know how to add buttons next to each other instead of on top of each other. Is this possible and if so, how should i go about doing this? :-)

I know that you probably rather see issues regarding the ScriptHookDotNet itself, but i have tried various forums where i asked the same question with no success, so i'm here now :-)

Thank you in advance!

**Comment by Nacorpio** [comment]
I don't think that this is possible at the moment.
Correct me if I'm right.

**Comment by Frede1012** [comment]
You could create your own Menu class to do this, the UIText component can be positioned.

**Comment by frodzet** [comment]
@Frede1012 Alright, i'll give it a try :-) so i guess the UIText components should be placed in a Tick? :-) Else it would just flash, right? :-)

**Comment by Frede1012** [comment]
UIText.Draw() should be called in Tick :')

**Comment by frodzet** [comment]
@Frede1012 Thanks, got it working :-)

**Comment by Frede1012** [comment]
No problem :-)
