### ISSUE TITLE
Blip::Sprite:set Not Working

### ISSUE THREAD

**Issue by ajberasategui** [crosire/scripthookvdotnet#157]
I've been looking at the Blip::Sprite:set method and can't found anything wrong about it, but when I try to use it raises the exception:
`Method not found: 'Void GTA.Blip.set_Sprite(GTA.BlipSprite)'`

**Comment by Frede1012** [comment]
Are you using the latest version?

**Comment by IncoCode** [comment]
In last version you should assign [BlipSprite](https://github.com/crosire/scripthookvdotnet/blob/master/source/Blip.hpp#L16) enum, not int.

**Comment by JohnnyCrazy** [comment]
Seems like you are using an old version. The last official release is pretty old already, but we are preparing for 1.0 :+1:

**Comment by ajberasategui** [comment]
I've cloned and compiled the github master branch version and I'm using the BlipSprite enum.

**Comment by IncoCode** [comment]
Did you update .asi file in your game folder?

**Comment by ajberasategui** [comment]
Oh! That's probably my error! I think I didn't, my bad, I'm really sorry
about this.
I'll check that soon and update.



2015-06-01 16:46 GMT-03:00 Dmitry <notifications@github.com>:

**Comment by ajberasategui** [comment]
Yes, I'm sorry to say that was the problem. Well, not sorry to say that, I'm sorry for creating the issue. 

Thank you.
