### ISSUE TITLE
Menu Back Key Change

### ISSUE THREAD

**Issue by Frede1012** [crosire/scripthookvdotnet#165]
The current menu back key is NUM0, shouldn't the key be backspace like the ingame menus are?

**Comment by IncoCode** [comment]
```this.BackKey = Keys.Back;```
:blush:

**Comment by Frede1012** [comment]
I know, but the default key :)

**Comment by frodzet** [comment]
@Frede1012 I don't think it matters, it's pretty easy to set it to your own liking. However when that's said, NumPad0 doesn't really make sense for a Back key :-) Backspace or the Home key or something would make more sense.

**Comment by Frede1012** [comment]
@frodzet Thats what i am saying! :P

**Comment by frodzet** [comment]
I agree with you :-)

**Comment by JohnnyCrazy** [comment]
@crosire Should we change it?

**Comment by crosire** [comment]
Yeah, sure.

**Comment by Frede1012** [comment]
Fixed in #173
