### ISSUE TITLE
I'm trying to make a mod that allows you to remotely control a car.

### ISSUE THREAD

**Issue by AAYapps** [crosire/scripthookvdotnet#172]
I making a mod that will allow me to remotely control my current car i am in. I made a vehicle variable to hold the current car I spawn. I'm have problems with steering while moving the car forward at the same time. I would like to know if there is a better way going about doing this mod a little bit better. 

This is on key up

if (e.KeyCode == Keys.T)
            {
                RCmode = !RCmode;

                if (RCmode)
                {
                    player.CanControlCharacter = true;
                    Game.Player.CanControlCharacter = false;
                    RCcontrolstart.Play();
                    Deloreon.EngineRunning = true;
                    charatorhandle = Deloreon.Handle;
                    
                }
                else
                {
                    player.CanControlCharacter = false;
                    Game.Player.CanControlCharacter = true;
                    RCcontrolstop.Play();
                    Deloreon.EngineRunning = false;
                    charatorhandle = switchbackcharator;
                }
            }

this is on key down

if(RCmode)
            {

                if (e.KeyCode == Keys.W)
                {
                    if (Deloreon.Speed < 100)
                    {
                        Deloreon.Speed += 1;
                    }

                    if (e.KeyCode == Keys.A)
                    {
                        Deloreon.Rotation += new Vector3(0, 0, 2);
                    }

                    if (e.KeyCode == Keys.D)
                    {
                        Deloreon.Rotation -= new Vector3(0, 0, 2);
                    }
                }

                if (e.KeyCode == Keys.S)
                {
                    if (Deloreon.Speed > -100)
                    {
                        Deloreon.Speed -= 5;
                    }

                    if (e.KeyCode == Keys.A)
                    {
                        Deloreon.Rotation += new Vector3(0, 0, 2);
                    }

                    if (e.KeyCode == Keys.D)
                    {
                        Deloreon.Rotation -= new Vector3(0, 0, 2);
                    }
                }

                if (e.KeyCode == Keys.A)
                {
                    Deloreon.Rotation += new Vector3(0, 0, 2);
                }

                if (e.KeyCode == Keys.D)
                {
                    Deloreon.Rotation -= new Vector3(0, 0, 2);
                }
            }

And yes this is like a bttf like bod. If anyone knows how to pass control from player's character to the car I spawn. 

Your help will be in the credits of the mod.

**Comment by IncoCode** [comment]
```C#
If (KeyCode == S)
{
  if (KeyCode == A) // if you got here - then your KeyCode is S, so it's cannot be A :)
}
```
I think you should check pressed keys in Tick. Try something like:
```c#
if ( _veh == null )
{
	return;
}
if ( _veh.Speed > 0 )
{
	_veh.Speed -= 1;
}
if ( Game.IsKeyPressed( Keys.A ) )
{
	_veh.Rotation += new Vector3( 0, 0, 3 );
}
if ( Game.IsKeyPressed( Keys.D ) )
{
	_veh.Rotation -= new Vector3( 0, 0, 3 );
}
if ( Game.IsKeyPressed( Keys.W ) )
{
	_veh.Speed += 3;
}
if ( Game.IsKeyPressed( Keys.S ) )
{
	_veh.Speed -= 3;
}
```
P.S.
```c#
player.CanControlCharacter = true;
Game.Player.CanControlCharacter = false;
```
What is this? :confused:

**Comment by RainerHilmer** [comment]
Such a mod exists already.
http://gtaforums.com/topic/796271-vrel-autodrive-for-gta-v/

**Comment by AAYapps** [comment]
Thanks, for the help, I will look at the source code for that mod (giving that person credit too if it works).  My mod was meant to actually help recreate the Deloreon being remotely by doc brown scene controlled (if there was a model for the Deloreon). I even worked on my own time circuits. If someone is making a bttf script mod let me know. I saw the one time travel mod with the alien car (forgot the model name), but mine has actual display in the future, present, and past (where you going, when you are, and when you bin. Don't remember doc's actual quot).


The to lines there
player.CanControlCharacter = true;
Game.Player.CanControlCharacter = false;

was for stopping the character from moving while you control the car. I can get rid of the fist one.

**Comment by JohnnyCrazy** [comment]
````c#
player.CanControlCharacter = true;
Game.Player.CanControlCharacter = false;
````
These lines are just redundant, since you just set it to true and directly to false afterwards. You can delete one of the lines.

**Comment by frodzet** [comment]
@AAYapps Take a look at VehicleHash.Dune2, it looks pretty much like a Time Traveling car :-P

**Comment by AAYapps** [comment]
Ok, thanks. I'll took at that.

**Comment by AAYapps** [comment]
Yeah, I knew it was what car you where suggesting. I used the ruiner because it is close to a deloreon (to just test the different parts).

**Comment by AAYapps** [comment]
I'm having trouble with the physics. I have used place on ground to keep the car from flying but I have other problems like at a slope can't turn. I'm trying to see if there is a better way to do this, I need the character outside the car, and be able to accelerate and steer the car without having physics problems.

**Comment by mlgthatsme** [comment]
FYI There's a native to control a Vehicles steering direction.

**Comment by AAYapps** [comment]
I'm trying to look for that native, but I don't see it. Is the native not named yet, It would be helpful to know what the name or hash number it is.
