### ISSUE TITLE
Is there a way to use a created camera. 

### ISSUE THREAD

**Issue by AAYapps** [crosire/scripthookvdotnet#177]
I made a new camera in my code but not sure how to make the game use that camera

outside keyup method

Camera cam;

inside command
cam = World.CreateCamera(Deloreon.GetOffsetInWorldCoords(new Vector3(0, 5, 0)), new Vector3(0, 0, 0), 1);

I tried using this.but nothing happens
cam.IsActive = true;

**Comment by JohnnyCrazy** [comment]
Try this:
````c#
World.RenderingCamera = cam;
````

**Comment by AAYapps** [comment]
thanks, I'll try it

later

It worked, but how do I get out of it
I used this to try and get out of it

World.RenderingCamera.AttachTo(Game.Player.Character, new Vector3(0, 0, 0));

**Comment by WozStudios** [comment]
`World.RenderingCamera = null` will set rendering back to the default Gameplay Camera

I've been meaning to add documentation for cameras to the wiki, I've just been busy with work lately

**Comment by AAYapps** [comment]
Thanks. Your a great help. Can I use your name in the credits

**Comment by AAYapps** [comment]
World.RenderingCamera = null;

is not working

**Comment by AAYapps** [comment]
nevermind, sorry. Put the line in the wronge please. Sometimes i'm braindead

**Comment by AAYapps** [comment]
I'm trying to make the rendercamera follow a my car. however it stays in one position, I tried putting it in the tick event but the camera stays in place instead of following car. Please help if you can. in the time being I will try and see if there are different modes
