### ISSUE TITLE
How to work with Hashes inside Native Functions? e.g. Hash statHash

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#179]
Greetings,

So i've been looking over the Native Trainer code and seen that the 'Add Cash' feature of the mod uses STAT_GET_INT and STAT_SET_INT to increase money by a certain amount:

					for (int i = 0; i < 3; i++)
					{
						char statNameFull[32];
						sprintf_s(statNameFull, "SP%d_TOTAL_CASH", i);
						Hash hash = GAMEPLAY::GET_HASH_KEY(statNameFull);
						int val;
						STATS::STAT_GET_INT(hash, &val, -1);
						val += 1000000;
						STATS::STAT_SET_INT(hash, val, 1);
					}

So i tried to do something similar in my code, the problem is that if i do something like:

Hash hash = Function.Call<Hash>(GET_HASH_KEY, "someString");
int val;
Function.Call<bool>(Hash.STAT_GET_INT, hash, &val, -1);

I get an exception saying that no such overloaded method exist. The issue here is the hash part in the parameters i think, but how can i work with Hash keys then?

**Comment by IncoCode** [comment]
```c#
int hash = Function.Call(GET_HASH_KEY, "someString");
int val;
Function.Call(Hash.STAT_GET_INT, hash, &val, -1);
```

**Comment by IncoCode** [comment]
I.e. if you are using function that returns something - you should specify return type in ```<some_return_type>```.
And ```Hash``` (in type.h from ScriptHookV SDK) it's usual ```UInt32``` :wink: So, you should use ```UInt32``` or ```int```.

**Comment by frodzet** [comment]
Thank you :-)

@IncoCode Could you try to convert the example i gave from native trainer into C# code? :-)

**Comment by IncoCode** [comment]
```c#
for ( int i = 0; i < 3; i++ )
unsafe
{
	int hash = Function.Call<int>( Hash.GET_HASH_KEY, "SP" + i + "_TOTAL_CASH" );
	int val;
	Function.Call( Hash.STAT_GET_INT, hash, &val, -1 );
	val += 1000000;
	Function.Call( Hash.STAT_SET_INT, hash, val, 1 );
}
```

**Comment by frodzet** [comment]
@IncoCode Ah now i get it! Thanks man, the SP represents single player and the i represents the single player character. So i could do something like:

for ( int i = 0; i < 3; i++ )
unsafe
{
    int hash = Function.Call<int>( Hash.GET_HASH_KEY, "SP1_TOTAL_CASH" );
    int val;
    Function.Call( Hash.STAT_GET_INT, hash, &val, -1 );
    val += 1000000;
    Function.Call( Hash.STAT_SET_INT, hash, val, 1 );
}

For Franklin :-)

But where can i find these Hashes?

**Comment by Frede1012** [comment]
Is there any reason for doing this natively? We have a money property :-)

**Comment by frodzet** [comment]
@Frede1012 Well it's not for the money, i'm just trying to get my head around hashes. I need it for other purposes :-) The money was just to put out an example which was easy to work with and test :-)

**Comment by IncoCode** [comment]
@frodzet yeah. Stats in spstatssetup.xml in one of the rpf-file.
@Frede1012 but if you want add money only to Franklin and your current character Trevor?

**Comment by IncoCode** [comment]
@frodzet but you forgot to add ```<int>``` after ```Call```.
```c#
int hash = Function.Call<int>( Hash.GET_HASH_KEY, "SP1_TOTAL_CASH" );
```

**Comment by frodzet** [comment]
@IncoCode I didn't forget to add it, somehow github removes it when i copy paste it from my code :-P I know that things with return types requires the opening and closing angle brackets :-) But thanks for the heads up! :-)

**Comment by IncoCode** [comment]
@frodzet use code blocks https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by frodzet** [comment]
@IncoCode Thanks :-)

**Comment by frodzet** [comment]
@IncoCode Do you know why this isn't working properly:

        for ( int i = 0; i < 3; i++ )
        unsafe
        {
            int hash = Function.Call<int>(Hash.GET_HASH_KEY, "SP" + i + "_STAMINA");
            int test;
            Function.Call(Hash.STAT_GET_INT, hash, &test, -1);
            test = 100;
            Function.Call(Hash.STAT_SET_BOOL, hash, test, 1);
        }

I'm trying to set a stat value like Stamina, but only if i go to the Pause Menu and into Stats is it changed, as soon as i hit ALT my Stamina value have not changed, and if i go back into Stats it is back to it's original value. 

Is there a way to bypass this? Do i have the right values in my parameters? The HASH.STAT_GET_INT is probably redundant for this particular case, since i don't care about what the current value is.

**Comment by IncoCode** [comment]
Stamina is int value. But you trying to set 100 as bool :grimacing:
Try to use STAT_SET_INT.

**Comment by frodzet** [comment]
@IncoCode Oops, i know - just forgot to change to INT, already tried that with int instead, was trying to set STAMINA_MAXED with bool :-P

**Comment by JohnnyCrazy** [comment]
@frodzet resolved?

**Comment by frodzet** [comment]
@JohnnyCrazy Unfortunately no. I can't seem to work out how to change a stat value of a player.

**Comment by IncoCode** [comment]
By the way, did you tried other stats? The stamina stat didn't work even in c++ :confused:

**Comment by frodzet** [comment]
@IncoCode I did not! :-) Maybe i should try that out later :-)

**Comment by frodzet** [comment]
Tested it, the results remains the same for any other stat as for the STAMINA. So i guess in order to change stats of "abilities" we need some other way to approach it! :-)
