### ISSUE TITLE
GetGroundZ is error prone

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#180]
I got grey hairs because I couldn't make the player character follow the nav mesh to a waypoint until I found this essential important note in the natives DB:
"Note that if the specified position is below ground level, the function will output zero!"
I solved this issue myself with a simple extension method
      public static Vector3 ToGround(this Vector3 position)
      {
         position.Z = 1000.0f;
         return new Vector3(position.X, position.Y, World.GetGroundZ(position));
      }
Maybe you can do the same little trick to prevent headaches by the users.
Full story here:
http://gtaforums.com/topic/797312-strange-behavior-of-taskgoto/?p=1067559820

**Comment by Frede1012** [comment]
So you are saying that GetGroundZ should use a Z value of 1000.0f or?

**Comment by RainerHilmer** [comment]
Yes anything above the maximum elevation of about 797 units (which is on mount Chiliad). That way the GET_GROUND_Z_FOR_3D_COORD native always calculates from above and we get around the issue which is described in the natives DB. I tested it and it works.

**Comment by Yothri** [comment]
I still have the problem to spawn under the map using this. Any ideas?

**Comment by RainerHilmer** [comment]
@Yothri, you want to spawn something BELOW the map? So you call GetGroundHeight and subtract a certain value from the resulting z-value? If not then can you please be more precise about what you do?

**Comment by Yothri** [comment]
Sorry, i was not precise enough. I just figoured out how to teleport to a specific waypoint. But the waypoint blip only provides the x and y coordinate... And now i just thought i can use this GetGroundHeight function to get the correct Z coordinate so i dont spawn under the map.

**Comment by RainerHilmer** [comment]
Yeah there's a little trick behind that. GetGroundHeight is the right choice BUT your character (or whatever) spawns at that location with it's center. On a ped this center is not at the bottom of his feet but in the middle of the body. Logical consequence: he falls through the ground because his feet are already below. Just add some value after you received the ground height (maybe 1.5? idk) and you should be fine.

**Comment by Yothri** [comment]
Thats what i also thought... and therefore i created a small log directly after adding pos.Z = World.GetGroundHeight(pos);

Console.WriteLine(pos.ToString()) outputs pos.Z as 0... So this isnt the problem.

**Comment by crosire** [comment]
Ehm, sure. It's supposed to be:
```c#
pos.Z = World.GetGroundHeight(pos);
```

**Comment by RainerHilmer** [comment]
That's strange. You have set the waypoint somewhere on the ground and not in the water i guess?
Just out of curiosity try this:
1. Write this method:
public static Blip GetWaypoint()
  {
     try
     {
        return World.GetActiveBlips().FirstOrDefault(b => b.Type == 4);
     }
     catch(ArgumentNullException)
     {
        return null;
     }
  }

2. Try this code:
var waypoint = GetWaypoint();
var groundHeight = World.GetGroundHeight(waypoint.Position).
// Now log groundHeight.

3. In case you still get zero as result, extend the code above and try again:
var waypoint = GetWaypoint();
waypoint.Position.Z = 1000f; // This should not be necessary as exactly this happens inside the new GetGroundHeight method.
var groundHeight = World.GetGroundHeight(waypoint.Position).
// Now log groundHeight.

**Comment by Yothri** [comment]
Both doesnt work. Weird.

**Comment by RainerHilmer** [comment]
And you have set the waypoint on a valid ground position? I can't reproduce this issue.

**Comment by Yothri** [comment]
Yup, tried on different positions...

**Comment by RainerHilmer** [comment]
Can you please upload your code somewhere (i.e. a public dropbox link or a public git repo)?

**Comment by Yothri** [comment]
http://puu.sh/ixAL8/d9e303db7b.txt

**Comment by RainerHilmer** [comment]
Thanks. Your console output is wrong. You wrote
Console.WriteLine(pos.ToString());
but it should be
Console.WriteLine(pos.Z.ToString());

BTW I recommend you use the LINQ version with FirstOrDefault (see my code above) to retrieve the waypoint.

**Comment by IncoCode** [comment]
@RainerHilmer why wrong? ```pos.ToString()``` returns string ```X: some_x_value Y: some_y_value Z: some_z_value```, ```pos.Z.ToString()``` returns ```some_z_value```.

**Comment by RainerHilmer** [comment]
Ah okay I didn't know you implemented ToString in the Vector3 struct. So I take my reply back.

**Comment by Yothri** [comment]
You got that ToString Override too... xD just btw.

**Comment by RainerHilmer** [comment]
@Yothri, ToString() is inherited from the Object class but in order to get such a string it must be filled with code or the one from Object gets called and in case of Vector3 it would just produce useless information.
https://msdn.microsoft.com/en-us/library/system.object.tostring%28v=vs.110%29.aspx

**Comment by Yothri** [comment]
Yes, what I meant... ToString method gets overriden so its possible to output a custom string.

**Comment by RainerHilmer** [comment]
Yes and I said I didn't know it is overridden. I never used Vector3.ToString(). Mea Culpa, mea maxima Culpa! Are we done yet or is it too much fun to further poke me? Have fun with your ground height issue.

**Comment by IncoCode** [comment]
@RainerHilmer :worried:

**Comment by Yothri** [comment]
Erm, my intention wasnt to insult you... i thought we are just discussing things here. I am still having the issue. Just to remember... you changed the topic to the ToString () issue which has nothing to do with the actual problem

**Comment by nevadascout** [comment]
I'll take a look a little later today and let you know what I find...

**Comment by IncoCode** [comment]
This code is ported from NativeTrainer by AB:
```c#
var groundHeight = new float[]
{
	100.0f, 150.0f, 50.0f, 0.0f, 200.0f, 250.0f, 300.0f, 350.0f, 400.0f,
	450.0f, 500.0f, 550.0f, 600.0f, 650.0f, 700.0f, 750.0f, 800.0f
};
var blips = World.GetActiveBlips();
Blip blip = blips.FirstOrDefault( b => b.Type == 4 );
if ( blip != null )
{
	var pos = new Vector3( blip.Position.X, blip.Position.Y, blip.Position.Z );
	foreach ( float g in groundHeight )
	{
		unsafe
		{
			float z = 0;
			player.Position = new Vector3( pos.X, pos.Y, g );
			Wait( 100 );
			if ( Function.Call<bool>( Hash.GET_GROUND_Z_FOR_3D_COORD, pos.X, pos.Y, g, &z ) )
			{
				player.Position = new Vector3( pos.X, pos.Y, z + 3 );
				break;
			}
			UI.Notify( z.ToString() );
		}
	}
	UI.ShowSubtitle( "Done", 2000 );
}
else
{
	UI.ShowSubtitle( "Not found", 2000 );
}
```
Works perfectly, but if you comment this string ```player.Position = new Vector3( pos.X, pos.Y, g );``` - ```GET_GROUND_Z_FOR_3D_COORD``` always will return a zero :confused:

**Comment by IncoCode** [comment]
Perhaps this function checks for a collision on this coords or something.

**Comment by sollaholla** [comment]
Has nobody solved this?

**Comment by RainerHilmer** [comment]
I have just found something interesting: If I am closer than (rough guess) 100 meters to the waypoint I retrieve the correct ground height. I suspect the physical ground is only generated nearby. I mean there seems to be a physical ground and a visual ground (which is always rendered inside the fov, independent of the distance). Does this make sense?

**Comment by Yothri** [comment]
Yes, i figured this also out already a long time ago. Sometimes it worked sometimes not. This is because if you are much more far away from ground which is currently not loaded into gpu / ram then u also cant get the ground height if there is no mesh to calculate. And obviously they dont load the mesh if its not loaded when this function is called.

**Comment by Dilapidated** [comment]
For those who's been waiting on this for a few years..... it took me a few days but I have the answers as well as a few extras to go with it. 

`public static Vector3 ForceGroundZ(this Vector3 v)
    {
        float zcoord = 0.0f;
        var outArgb = new OutputArgument();
 
 
        float[] firstCheck = new float[] { 0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000 };
 
        float[] secondCheck = new float[] { 1000, 900, 800, 700, 600, 500,
            400, 300, 200, 100, 0, -100, -200, -300, -400, -500 };
 
        float[] thirdCheck = new float[] { -500, -400, -300, -200, -100, 0,
            100, 200, 300, 400, 500, 600, 700, 800, 900, 1000};
 
        if (Function.Call<bool>(Hash.GET_GROUND_Z_FOR_3D_COORD, v.X, v.Y, 1000f, outArgb))
            zcoord = outArgb.GetResult<float>();
 
        if (zcoord == 0)
        {
            for (int i = 0; i < firstCheck.Length; i++)
            {
                Function.Call(Hash.REQUEST_COLLISION_AT_COORD, v.X, v.Y, firstCheck[i]);
                GTA.Script.Wait(0);
            }
 
            if (Function.Call<bool>(Hash.GET_GROUND_Z_FOR_3D_COORD, v.X, v.Y, 1000f, outArgb))
                zcoord = outArgb.GetResult<float>();
        }
 
        if (zcoord == 0)
        {
            Log.Write(true, "ZCoord secondCheck");
 
            for (int i = 0; i < secondCheck.Length; i++)
            {
                Function.Call(Hash.REQUEST_COLLISION_AT_COORD, v.X, v.Y, secondCheck[i]);
                GTA.Script.Wait(0);
            }
 
            if (Function.Call<bool>(Hash.GET_GROUND_Z_FOR_3D_COORD, v.X, v.Y, 1000f, outArgb))
                zcoord = outArgb.GetResult<float>();
        }
 
        if (zcoord == 0)
        {
            Log.Write(true, "ZCoord thirdCheck");
 
            for (int i = 0; i < thirdCheck.Length; i++)
            {
                Function.Call(Hash.REQUEST_COLLISION_AT_COORD, v.X, v.Y, thirdCheck[i]);
                GTA.Script.Wait(0);
            }
 
            if (Function.Call<bool>(Hash.GET_GROUND_Z_FOR_3D_COORD, v.X, v.Y, 1000f, outArgb))
                zcoord = outArgb.GetResult<float>();
        }
 
        return new Vector3(v.X, v.Y, zcoord);
    }
 
 
    public static Vector3 ForceWaterZ(this Vector3 v)
    {
        float zcoord = 0.0f;
        var outArgb = new OutputArgument();
 
 
        float[] firstCheck = new float[] { 0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000 };
 
        float[] secondCheck = new float[] { 1000, 900, 800, 700, 600, 500,
            400, 300, 200, 100, 0, -100, -200, -300, -400, -500 };
 
        float[] thirdCheck = new float[] { -500, -400, -300, -200, -100, 0,
            100, 200, 300, 400, 500, 600, 700, 800, 900, 1000};
 
        if (Function.Call<bool>(Hash.TEST_PROBE_AGAINST_ALL_WATER, v.X, v.Y, 1000f, v.X, v.Y, -500f, 1, outArgb))
            zcoord = outArgb.GetResult<Vector3>().Z;
 
        if (zcoord == 0)
        {
            for (int i = 0; i < firstCheck.Length; i++)
            {
                Function.Call(Hash.REQUEST_COLLISION_AT_COORD, v.X, v.Y, firstCheck[i]);
                GTA.Script.Wait(0);
            }
 
            if (Function.Call<bool>(Hash.TEST_PROBE_AGAINST_ALL_WATER, v.X, v.Y, 1000f, v.X, v.Y, -500f, 1, outArgb))
                zcoord = outArgb.GetResult<Vector3>().Z;
        }
 
        if (zcoord == 0)
        {
            Log.Write(true, "ZCoord secondCheck");
 
            for (int i = 0; i < secondCheck.Length; i++)
            {
                Function.Call(Hash.REQUEST_COLLISION_AT_COORD, v.X, v.Y, secondCheck[i]);
                GTA.Script.Wait(0);
            }
 
            if (Function.Call<bool>(Hash.TEST_PROBE_AGAINST_ALL_WATER, v.X, v.Y, 1000f, v.X, v.Y, -500f, 1, outArgb))
                zcoord = outArgb.GetResult<Vector3>().Z;
           
        }
 
        if (zcoord == 0)
        {
            Log.Write(true, "ZCoord thirdCheck");
 
            for (int i = 0; i < thirdCheck.Length; i++)
            {
                Function.Call(Hash.REQUEST_COLLISION_AT_COORD, v.X, v.Y, thirdCheck[i]);
                GTA.Script.Wait(0);
            }
 
            if (Function.Call<bool>(Hash.TEST_PROBE_AGAINST_ALL_WATER, v.X, v.Y, 1000f, v.X, v.Y, -500f, 1, outArgb))
                zcoord = outArgb.GetResult<Vector3>().Z;
        }
 
        return new Vector3(v.X, v.Y, zcoord);
    }
 
 
    public static float ForceWaterHeight(this Vector3 v)
    {
        float result = -1;
        var ground = v.ForceGroundZ().Z;
        var water = v.ForceWaterZ().Z;
 
        if (water > ground)
            result = water - ground;
 
        return result;
    }`

Hopefully this helps someone else out there. Enjoy!

**Comment by RainerHilmer** [comment]
@Dilapidated Dude, if you were a girl i'd kiss you right now! :D

**Comment by RainerHilmer** [comment]
@Dilapidated You seem to have forgotten one tiny thing. When I call ForceWaterDepth it returns a positive z-value, which is of course wrong. So I added
result = 0 - result;
right before the return and now it works perfect. :)

**Comment by crosire** [comment]
@Dilapidated This would make a useful snippet for the Wiki (https://github.com/crosire/scripthookvdotnet/wiki/Code-Snippets).

**Comment by Dilapidated** [comment]
@crosire Thanks! Just updated it, will post it there as you requested.
