### ISSUE TITLE
Is there a way to control peds by passing player control to them

### ISSUE THREAD

**Issue by AAYapps** [crosire/scripthookvdotnet#181]
I have been trying to pass my keyboard control to other peds. I have used.

out methods
Player controlped;

inside keyup method
controlped = new Player(World.CreatePed(PedHash.Michael, Deloreon.GetOffsetInWorldCoords(new Vector3(0, 5, 0))).Handle);
Game.Player.CanControlCharacter = false;
controlped.CanControlCharacter = true;

i'm not sure what is wrong. is it because I create a new player, is there a way to transfer my control from my character to a ped. I'm spawning a ped first before I go for grabing random peds in the street.

**Comment by crosire** [comment]
You cannot create a new player?! There is only one. You could try to use Ped Tasks and change the target position according to the keys you press.

**Comment by XBLToothPik** [comment]
You can do CHANGE_PLAYER_PED

**Comment by JohnnyCrazy** [comment]
ping @AAYapps , resolved?

**Comment by AAYapps** [comment]
I Got that to work. Thanks for the help.
