### ISSUE TITLE
KeyDown event fires repeatedly when key is held

### ISSUE THREAD

**Issue by SeijiSuenaga** [crosire/scripthookvdotnet#183]
Is this by design? I expected:
1) KeyDown fires once when key is pressed.
2) KeyUp fires once when key is released.

If I did want to execute some code repeatedly while a key is held down, the current behavior still wouldn't be sufficient because the event stops firing after several seconds. Instead, I would probably use the Tick event to check IsKeyPressed().

**Comment by JohnnyCrazy** [comment]
Good point.

But the thing is we are using the internal scripthook's keyhook. So I don't know if we should/can fix it at all.

@crosire

**Comment by crosire** [comment]
This is by design and how Windows handles keyboard input. Windows sends the KeyDown event once and after a second or so it starts to repeatingly sending it until you release the key again.
