### ISSUE TITLE
Function.Call is a 'method' but used like a 'type'

### ISSUE THREAD

**Issue by Strikewolf11** [crosire/scripthookvdotnet#185]
hello,

ive been trying to use the function.call feature to call native function but everytime i go and use the function.call feature VS 2013 says that its a method but used like a type?

is there a way to fix this with code or?

**Comment by ajberasategui** [comment]
Plase share your code where trying to make this call and we may be able to
guide you.

**Comment by zorg93** [comment]
function.call(hash.set_entity_invincible, Game.Player.Character, true);
You need to use it kind of like that

**Comment by JohnnyCrazy** [comment]
Any updates @Strikewolf11 ?

**Comment by crosire** [comment]
Since there was no feedback and the issue very likely to be level 8 I'll close this for now. Can be reopened later in case of further help needed.
