### ISSUE TITLE
OutputArgument should also support input

### ISSUE THREAD

**Issue by JohnnyCrazy** [crosire/scripthookvdotnet#19]
Like crosire wrote, `Native::OutputArgument` does not support inputs yet.

Old:
> Some API-Calls require `ref` parameters, like `void GET_SCREEN_RESOLUTION(int *p0, int *p1)`
> I don't think we have that implemented yet, do we? @crosire (Direct calls from C#, not C++ CLI)

**Comment by crosire** [comment]
That's what Native::OutputArgument is for, though it still needs an addition to not only allow output, but also input + output (some natives use pointers for input).
I tried to get it working with the natural "ref" syntax, but wasn't able to: C++/CLI compiler then cannot decide between call by reference and call by value overloads and errors.

**Comment by crosire** [comment]
This was fixed in #136.
