### ISSUE TITLE
NonExistingEntityException?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#194]
The .net script hook for GTA IV provides a NonExistingObjectException. Are there plans to implement that in the .ScriptHookvDotNet as well?

**Comment by crosire** [comment]
Where would we need that?

**Comment by RainerHilmer** [comment]
This is a method from my common functions framework.
      public static Ped[] GetPedsSafe(Ped playerCharacter, float radius)
      {
         lock(SyncLock)
         {
            Ped[] pedsAround;
            try
            {
               pedsAround = World.GetNearbyPeds(playerCharacter, radius);
            }
            catch(Exception) //note: was NonExistingObjectException
            {
               UI.ShowSubtitle(SCRIPT_ENGINE_FAILURE_MESSAGE, 4000);
               return new Ped[] {};
            }
            return pedsAround;
         }
      }
However I don't know if World.GetNearbyPeds throws if no peds can be retrieved. Aside from that I use this Exception in some try/catch blocks of other mods. I can resolve this by refactorizing but before I begin this work I'd like to know what's on your plan.

**Comment by JohnnyCrazy** [comment]
I don't think there is a need of a exception at `World.GetNearbyPeds` currently.
We get the entities out of the pool and if they exist, we add them to the list. If there is no entity around, it will be an empty list. (I don't understand the concept of the exception in the old scripthook anyway, why it didn't just return an empty array if there is none?)

**Comment by RainerHilmer** [comment]
Me neither Johnny. Those mod crashes due to non existing entities gave me grey hairs back then and I needed to implement checks all over the place. Okay, good to know. Now I can remove some todo marks in my code. :)
