### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by logicspawn** [crosire/scripthookvdotnet#201]
Can we have a new release for the ScriptHookVDotNet? A lot of changes has been made since 0.9 which was 27 days ago.

**Comment by Frede1012** [comment]
Some 1.0 features are still missing as far as i know. Which is why no 1.0 release has been made.

**Comment by logicspawn** [comment]
Would it be possible to have a 0.91 or something similar? Would be nice to be able to link a mod user to the release page for downloading a recent version.

Also, which features is a 1.0 release missing?

**Comment by IncoCode** [comment]
@logicspawn https://github.com/crosire/scripthookvdotnet/milestones

**Comment by RainerHilmer** [comment]
I second this request. There is no reason why there couldn't be a version 0.10. I just read through semver.org again and I couldn't find anything against it.

**Comment by JohnnyCrazy** [comment]
Plans for 1.0 AFAIK:
* Clean-up code and maybe rewrite some stuff
* Implementing a lot of common and needed features (listed in the 1.0 milestone issues)

But another release before we go 1.0 would be good IMO, we implemented already a lot till the last one. @crosire

**Comment by crosire** [comment]
True. I'll wrap things up in a moment.

**Comment by crosire** [comment]
The problem is that semver requires minor releases to not make breaking changes. But the current codebase is not compatible to the previous version at all!

**Comment by Guad** [comment]
The thing is that people are downloading nightly builds from AppVeyor and they get confused when .NET mods don't work. Releasing a 0.91 version would be more than great, even though it doesn't meet the semver criteria.

**Comment by RainerHilmer** [comment]
The next logical minor version increment would be 0.10, not 0.91. Just saying to prevent confusion.

**Comment by Sergeeeek** [comment]
Maybe release current version as 1.0 and make milestone 1.1?

**Comment by RainerHilmer** [comment]
Suggestion: Rename the current milestone to 2.0 and release V1.0 already.

**Comment by crosire** [comment]
Released v1.0, new build is automatically pushed to the release page in a few minutes.

**Comment by IncoCode** [comment]
@crosire you should not give up so easily :laughing:

**Comment by crosire** [comment]
It really was time for a new release, last one was way too old. And I had planned to push it this weekend anyway =).

**Comment by Sergeeeek** [comment]
Hey, what about #191 ? Is it in the new release?
