### ISSUE TITLE
Proposal/Request: World.NextPositionOnStreet

### ISSUE THREAD

**Issue by Straysify** [crosire/scripthookvdotnet#204]
GTA IV's .NET ScriptHook had this. It was extremely useful for spawning things such as vehicles on random locations on streets. Basically, you specified a Vector3, and it got the closest road position to it. It was extremely useful.

**Comment by IncoCode** [comment]
Already here.

13 июня 2015 г. 22:16 пользователь Stray <notifications@github.com> написал:

**Comment by IncoCode** [comment]
For vehicle PlaceOnNextStreet

**Comment by IncoCode** [comment]
Something like [Vehicle::PlaceOnNextStreet](https://github.com/crosire/scripthookvdotnet/blob/master/source/Vehicle.cpp#L432)?

**Comment by Nacorpio** [comment]
As @IncoCode stated, there is a method within the Vehicle namespace which does this, but I agree that it would be very useful to add that to the Vector3 class as well. I would personally like to use this on Peds and other objects,

**Comment by IncoCode** [comment]
How about to move ```PlaceOnNextStreet``` method to ```Entity``` class? Then it can be used in ```Vehicle```, ```Ped``` and ```Prop```.

**Comment by Nacorpio** [comment]
That is also something I have considered suggesting.

**Comment by Straysify** [comment]
Or, in Vector3. Vector3.GetNextPositionOnStreet(Vector3 pos), returns the closest street position. Then you can use the vector3 it returns for anything.

**Comment by Sergeeeek** [comment]
This function would make more sense to be in the World class.

**Comment by RainerHilmer** [comment]
I agree with Sergeeeek.
