### ISSUE TITLE
"Vehicle Door Fully Open Check" doesn't work

### ISSUE THREAD

**Issue by T4Ever** [crosire/scripthookvdotnet#205]
Hi
I need follow function for my vehicle door handling script, but the function doesn't work. The returned value is always "false":

Function.Call<bool>(Hash.IS_VEHICLE_DOOR_FULLY_OPEN, ClosestVehicle, 0);

I hope you can fix this in your next release. Thank you for your support.

**Comment by Sergeeeek** [comment]
I assume you call it like that.
```csharp 
Function.Call<bool>(Hash.IS_VEHICLE_DOOR_FULLY_OPEN, ClosestVehicle, 0); // if you don't then you should
```

Are you sure you are passing the right door index? Btw there is a convinient enum for this called VehicleDoor.

Function.Call is basically just a wrapper around ScriptHookV, so it should work the same way. Are you sure function does what you think it does and have you tested it with ScripHookV or Lua script hook?

**Comment by T4Ever** [comment]
Thanks for your answer. Yes I call the function with the bool command. 0 is the front left door. I'm checking the value all the time. The true value never exist. Even if the door is fully open.
I don't have experience in LUA & ScriptHookV. I'm coding only in C++.
Can someone try this function if it works in .NET?
