### ISSUE TITLE
Disable label as a possible selection index? 

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#206]
Greetings,

I'm trying to implement a Label to make my menu look more neat, however i'm not sure how i can prevent the label from being selected when navigating up/down in my menu.

How can i make it so that when i get to the label it will skip it and go to the next/prev Button in my menu instead.

**Comment by IncoCode** [comment]
You can try something like that:
```c#
private int _prevIndex = 0;
...
var gtaMenu = new Menu( "TestMenu", new MenuItem[]
{
	new MenuLabel( "lbl2" ),
	new MenuButton( "Btn" ),
	new MenuButton( "Btn2" ),
	new MenuLabel( "lbl2" ),
	new MenuButton( "Btn3" ),
	new MenuEnumScroller( "enum", "", new[] { "one", "two", "three" } ),
	new MenuLabel( "lbl3" )
} );
gtaMenu.SelectedIndexChanged += ( o, args ) =>
{
	int oldPrev = this._prevIndex;
	this._prevIndex = args.SelectedIndex;
	if ( gtaMenu.Items[ args.SelectedIndex ] is MenuLabel )
	{
		bool down = args.SelectedIndex - oldPrev > 0;
		int count = gtaMenu.Items.Count - 1;
		if ( oldPrev == 0 && args.SelectedIndex == count )
		{
			down = false;
		}
		else if ( args.SelectedIndex == 0 && oldPrev == count )
		{
			down = true;
		}
		gtaMenu.OnChangeSelection( down );
	}
};
this.View.AddMenu( gtaMenu );
gtaMenu.SelectedIndex = 1; // because first (0) element is label
```

**Comment by frodzet** [comment]
@IncoCode Thank you, i think it's quite a lot of trouble to go through to just prevent a label from being selected.

@crosire IMO labels shouldn't be select-able or at least there should be an overloaded method that would take like a boolean value: canSelect or something. Label's should in my opinion only be used to display stuff and since they already have no events associated with them i see no reason as to why they act like a button.

**Comment by crosire** [comment]
True, that how labels are generally handled in other GUI systems too. We should change that.

**Comment by crosire** [comment]
No longer needed, because the menu was removed.
