### ISSUE TITLE
A Few Suggestions/Enhancements/Bug Fixes.

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#207]
Greetings,

@crosire 
@IncoCode 
@JohnnyCrazy 
and all the rest on board!

First of all, i'd like to thank you for putting so much effort into making ScriptHookVDotNet as good as it already is. The new features you have added and the switch from actions to events is awesome! 

I have just a few suggestions/bug fixes i'd like to share with you:

1) [Suggestion/Enhancement] MenuButtons should have the possibility to be placed side on side rather than on top of each other if one so desires. This would allow large lists of items to be placed on one 'page', such as a car spawner menu, making navigation for such purposes better and quicker.

2) [Suggestion/Enhancement] MenuButtons are the only MenuItem which does not require a string description argument. All MenuItems should have one such method as well, leaving an empty string makes the code, excuse my language - 'fugly'. (e.g. Godmode, there would be no reason to have a description for this, so i'd like to leave that part of the parameter out.)

3) [Bug Fix] This i'm a bit unsure about, maybe i should do something myself to prevent this, but having it like the following as standard would be nice. Game.GetUserInput can be used to do many things, i use it to allow the player to set a desired amount of cash among other things. The thing is that since the default back key for the menu is NumPad0 and the default activate key is NumPad5 if you hit either of those two NumPad keys while editing a currently open Game.GetUserInput the menu will either be handled back or open a bunch of new Game.GetUserInput overlays. Due to this when you hit the enter key you either need to hit Enter countless times (to get rid of all those additional windows popped up for hitting NumPad5) to get back to your menu or your menu get's closed (For hitting NumPad0) and you'll have to navigate back to where you were. This should not be the case, Menu navigation should be ignored while working with such.

Let me know what you guys think.

Also i'd like to contribute to the project, but since my programming skills are very limited i thought i could maybe contribute in another way? Maybe on the user experience, such as the IntelliSense part, adding description's to each Method and their associated parameters for example. This is just a thought, but let me know.

**Comment by crosire** [comment]
Agreed, those are some good points that should be taken care of.

As for contribution, the documentation is rather sparsely currently, so yes, any work on that end is greatly appreciated (either in form of extending the Github Wiki or adding some XML comments, like you mentioned) =).

**Comment by nevadascout** [comment]
I added a load of usage examples to the wiki a while back. I've been meaning to add more, but been pretty busy lately.

**Comment by frodzet** [comment]
@nevadascout Exactly what i wanted to add :-) Would really help newcomers as well :-)

**Comment by nevadascout** [comment]
@frodzet Definitely :) Feel free to add me on Skype, btw. I'm `ShotgunPsycho` on there

**Comment by frodzet** [comment]
@nevadascout Thanks, well there are two - ShotgunPsycho from US and from Britain :-) Who are you? :-)

**Comment by nevadascout** [comment]
I'm British. The US one is an imitation ;)

**Comment by crosire** [comment]
1 and 2 are no longer relevant, since the menu was removed and 3 was fixed, so I'll close this now.
