### ISSUE TITLE
New 2.0 branch

### ISSUE THREAD

**Issue by JohnnyCrazy** [crosire/scripthookvdotnet#209]
Since we're now on 1.0 and already have some PRs which are not compatible with the current version, we should make a 2.0.0 branch which only contains features which will be merged once 2.0.0 is ready. The current master branch would be for all 2.X.X features which are little changes + backwards compatible

**Comment by RainerHilmer** [comment]
You guys would rather need a separate release branch. You know Sourcetree and gitflow? Those two make versioning a piece of cake. :)

**Comment by crosire** [comment]
True, using the gitflow workflow in other projects with success (you don't need SourceTree for that, works just fine manually =) ). Did the necessary steps.

**Comment by RainerHilmer** [comment]
Freak ;-)

**Comment by crosire** [comment]
TortoiseGit ;)

**Comment by RainerHilmer** [comment]
Yep great tool. Even better than Sourcetree for certain more in-depth tasks. However I like how you can manage all repos/projects on a single page and how it collaborates with BitBucket. Give it a shot. Both are free of charge. :)
