### ISSUE TITLE
Something interesting for the documentation regarding speeds

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#211]
I am currently working on a speed balancing system in my Autodrive mod (fast vehicles tend to drive a bit faster than set) and I was about to get grey hairs until I found something remarkable:
The speed value we get from GET_ENTITY_SPEED is in meters per second while the speed unit for the DriveTo method is mph/2!
I think whoever does the documentation should mention this.

**Comment by crosire** [comment]
Or we should change one of those so values match.

**Comment by RainerHilmer** [comment]
That would be even better, of course. Maybe mph on both and also internally divide by 2 in the DriveTo method already. But still there should be a note in the XML comments about this for people who know about this flaws and wonder.

**Comment by frodzet** [comment]
That's kinda weird, why would Rockstar measure speed using two different systems? But i'm guessing converting meters per second to miles per hour would fix the issue? @RainerHilmer You're sure DriveTo is not measured in Kilometers Per Hour?

**Comment by RainerHilmer** [comment]
@frodzet yes it's true. I was surprised myself but when I set 25/2 for instance the vehicle drives with 25mph (up to +4 depending on the vehicle parameters). That's what the speedometer in the cars show and also the mph display of sjaak's simple trainer.

**Comment by frodzet** [comment]
@RainerHilmer I see, that is really odd. Them stubborn developers, lol :-)

**Comment by JohnnyCrazy** [comment]
Since this is issue is already open for some time, how we will proceed? Should we change one of the methods? Or should we keep current behavior for the sake of compatibility? If we change it, we also need to decide for one speed-unit.

@crosire

**Comment by crosire** [comment]
Changing it now would probably be fatal for some existing scripts. But it could still be done in a 3.0 release, which is allowed to break backwards compatibility.

**Comment by JohnnyCrazy** [comment]
Sounds like a good plan, should we go for the freedom-units or the europe ones? :wink:

**Comment by kagikn** [comment]
I don't think it's worth deciding for one speed-unit, finding speed unit with every function would be hassle...

**Comment by crosire** [comment]
If we do, I'd go for mph. That's what the speedometer in vehicles displays.

**Comment by kagikn** [comment]
RAGE Plugin Hook has speed-unit converters, how about introducing general math function class? http://docs.ragepluginhook.net/html/F44D02ED.htm

**Comment by crosire** [comment]
Mmh. Maybe. I don't want the code to get too bloated.

**Comment by kagikn** [comment]
I see, it can cause the code to do it, we shouldn't insert the code more than necessary.

**Comment by JohnnyCrazy** [comment]
Yea, I don't think we should implement too many Utility-helpers. These methods are easy to implement yourself and are too generic.

So, if we go for mp/h
* Adapt `DriveTo` from `mph/2` to `mph`
* Adapt `Speed` from `mps` to `mph`

**Comment by JohnnyCrazy** [comment]
Uhm, so I just tested this. Follwing code:
````c#
ped.Task.DriveTo(ped.CurrentVehicle, World.GetActiveBlips().FirstOrDefault(b => b.Type == 4).Position, 20, 20);

//OnTick
Ped ped = Game.Player.Character;
if (ped.IsInVehicle())
{
    _speedText.Caption = $"Speed: {ped.CurrentVehicle.Speed}";
}
````

And I'm always getting 20 as a Speed while driving without any obstacles or red lights. Seems like this issue isn't correct anymore? :smile:

**Comment by JohnnyCrazy** [comment]
Could someone confirm this quick test? Then we can close this.

@RainerHilmer @crosire @kagikn

**Comment by kagikn** [comment]
The speed unit of `TASK_VEHICLE_DRIVE_TO_COORD_LONGRANGE` is definitely `mps`. If the car instance's speed is above the limit (e.g. when it's set to a too high value by scripts), the driver will use the brake strongly. But usually, drivers drive a car a bit slower than the limit.

**Comment by JohnnyCrazy** [comment]
So we should proapbly just leave it like it is shouldn't we? @crosire

**Comment by crosire** [comment]
Agreed.

**Comment by RainerHilmer** [comment]
Well my idea was to just mention this in the documentation anyway (see title). :)
