### ISSUE TITLE
Need help on Script.Tick! :-)

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#213]
Greetings,

@IncoCode Sorry for directing yet another issue to you, but you have just been of such great help this far.

So i'm trying to refactor my code some, just to make it more readable. But i cannot seem to get 
Tick += (sender, args) => { };

My old file looked like this:

    private void PlayerMenu()
    {
        List<IMenuItem> menuItems = new List<IMenuItem>();

        var toggleInvincible = new GTA.MenuToggle("Invincible", "", IsPlayerInvincible);
        toggleInvincible.Changed += (sender, args) =>
        {
            if (!IsPlayerInvincible)
                ActivatePlayerInvincible();
            else
                DeactivatePlayerInvincible();
        };
        menuItems.Add(toggleInvincible);

        var playerMenu = new GTA.Menu("Player Options", menuItems.ToArray());
        DrawMenu(playerMenu);
    }

With these two methods:

    internal void ActivatePlayerInvincible()
    {
        IsPlayerInvincible = true;

        Tick += (sender, args) =>
        {
            Function.Call(Hash.SET_PLAYER_INVINCIBLE, Game.Player, true);
        };

    }
    internal void DeactivatePlayerInvincible()
    {
        IsPlayerInvincible = false;

        Tick += (sender, args) =>
        {
            Function.Call(Hash.SET_PLAYER_INVINCIBLE, Game.Player, false);
        };

    }

This all worked fine, so i decided i wanted to refactor my code and i did the following:

Added a new class containing all player functionalities. That is in the example i gave here on the site the DeactivatePlayerInvincible() and ActivatePlayerInvincible() (I have many more, but the issue is when Ticking only)

Nothing worked after refactoring, so i thought i would start adding a few UI.Notify functions to see which parts worked and didn't work. I figured that the issue was within the Tick += (sender, args) => { }; so i removed them and the Activate/Deactivate Invincible now worked. (However this will only work while i stay at the same character, therefore i need the Tick so i freely can switch between characters and leave Godmode ON/OFF.) 

I want to use the tick in the style i showed above (or a better approach), but inside my new class. How can i do this? The Class containing the PlayerMenu() and the class containing Player Functionalities should stay as two different class's. 

DrawMenu is just a method i created, don't mind it - it's pretty much the same as View.AddMenu()

**Comment by SeijiSuenaga** [comment]
Looks like you're adding multiple event handlers without ever removing them, so the Activate/Deactivate methods conflict with each other. That's an issue with anonymous handlers — you can add them but can't remove them.

**Comment by SeijiSuenaga** [comment]
I'm a bit confused how the old code worked, since it looks like you're adding conflicting event handlers without ever removing them... Maybe I'm mistaken.

**Comment by IncoCode** [comment]
You showed us your old code, but have not shown the new one :smirk:
I agree with @AnotherSymbiote .
Or my example:
```c#
static class PlayerOptions
{
	public static bool Invincible { get; set; }
	public static bool InvincibleUpdated { get; set; }

	public static void MakeInvincible( bool enable )
	{
		Function.Call( Hash.SET_PLAYER_INVINCIBLE, Game.Player.Handle, enable );
		InvincibleUpdated = true;
	}
}

public class YourScript : Script
{
	public YourScript()
	{		
		this.Tick += this.Upd;		
	}
	
	private void Upd( object sender, EventArgs e )
	{
		if ( PlayerOptions.InvincibleUpdated ) // because no need to call "DisableInvincible" each tick
		{
			if ( !PlayerOptions.Invincible && Game.Player.Character.Exists() )
			{
				PlayerOptions.MakeInvincible( false );
			}
			PlayerOptions.InvincibleUpdated = false;
		}
		if ( PlayerOptions.Invincible )
		{
			PlayerOptions.MakeInvincible( true );
		}
	}
	
	private void PlayerMenu()
	{
		var menuItems = new List<IMenuItem>();

		var toggleInvincible = new GTA.MenuToggle( "Invincible", "" );
		toggleInvincible.Changed += ( sender, args ) =>
		{
			PlayerOptions.Invincible = !PlayerOptions.Invincible;
		};
		menuItems.Add( toggleInvincible );

		var playerMenu = new Menu( "Player Options", menuItems.ToArray() );
		DrawMenu( playerMenu );
	}
}
```

**Comment by frodzet** [comment]
@AnotherSymbiote Nice example! :-) Thanks.
@IncoCode I thought showing more code would just make the post too confusing :-) But i can see why one would get confused :-) Thanks for sharing your code as well! :-)

**Comment by frodzet** [comment]
Oh dear god, looking through my code it all makes sense now! Thank you very much @IncoCode and @AnotherSymbiote for pointing out the obvious! :-D

**Comment by JohnnyCrazy** [comment]
Then I guess we can close this :)
