### ISSUE TITLE
How can I call a native function which is not in the Hash enumeration?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#216]
I just found AI::TASK_PLANE_LAND and I'd like to do some tests with it but this function is not in the Hash enum and also not the hashes 0xBF19721FA34D32C0 or 0x5F7E23EA. Btw why do those native functions have two hashes anyway?
EDIT: Ugh stupid me. I guess I just need to inject the integer representation of the hash, right? But which one of those two?

**Comment by JohnnyCrazy** [comment]
This one: `0xBF19721FA34D32C0`
The short one is used to find the long one AFAIK.

**Comment by RainerHilmer** [comment]
Thanks :)

**Comment by crosire** [comment]
AFAIK the short one was the console hash (which are 32bit) and the long one is the PC hash (where the game is 64bit). Could be wrong though, but that's what I remember to have seen somewhere.

**Comment by RainerHilmer** [comment]
I was too happy too soon. Function.Call needs a parameter of type GTA.Native.Hash and there is no overload which accepts a hex value instead. So I cannot inject a hex value and casting to hash is useless because this value is no part of the hash enum.
I guess I have to wait until the TASK_PLANE_LAND native is implemented.

**Comment by IncoCode** [comment]
@RainerHilmer wiki is your friend: https://github.com/crosire/scripthookvdotnet/wiki/How-Tos#if-the-hash-does-not-exist-under-the-hash-enum :smiley:

**Comment by nevadascout** [comment]
@IncoCode As a side note, the example in that section referring to `SET_BLACKOUT` is now outdated as that hash has now been added to the hashes enum :P

**Comment by RainerHilmer** [comment]
Thanks guys. :)
I thought I get an exception when I try to cast to an enum member that doesn't exist but I learned something new today.
