### ISSUE TITLE
Finalizing a script before restart

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#218]
I have a mod which can save locations and display them through a blip map (can be toggled on/off). However when the blip map is on and I hit the insert key to reload all script mods, there is no way (other than to reload the savegame) to remove those blips from the map. So is there a way to prevent this?
Maybe if the .net script hook provides a "Finalize" event, we could attach this to a finalization method which does some housekeeping before the script gets terminated. Make this a two way communication with the script firing a Finalized event so the script hook knows when it's safe to restart the script. You could also add a timeout like "when you don't answer within x milliseconds I will terminate you!". Such an architecture would also help with removing outdated props (which occupy memory). I have another fun mod which spawns those big orange balls wherever the user wants but they keep being in the world when I don't dispose them.

**Comment by JohnnyCrazy** [comment]
I agree we need some kind of callback which is fired when the script is unloaded.
Either the finalize way, or a simple callback (like the tick one)

**Comment by nevadascout** [comment]
I believe that if you set the `IsPersistent` property to be false **(it's true by default)** then the game engine will automatically cleanup items when you go a certain distance away from them.

**Comment by RainerHilmer** [comment]
@nevadascout, you talk about the big oranges? Yeah I know but the thing is when I toss one down Mount Chiliad it would be disposed way too soon (distance) or as soon as it's off screen. So I have implemented a method (which is attached to the tick event) that disposes them when farther away than 1000 units. Also there's a method attached to the KeyDown event which disposes all spawned oranges at once. However that doesn't help if I forget to dispose them before I hit the insert key because the connection (a List<Prop>) is broken.

**Comment by Frede1012** [comment]
I agree, this sounds like a good idea!

**Comment by nevadascout** [comment]
Oh, that's a good point. I have a similar system that removes them from my object list and sets them to be not persisted when they get more than 250m away.

Also, the standard "units" for measuring X Y and Z in a game engine is meters :)

**Comment by IncoCode** [comment]
Did you try override ```Dispose``` method?
```c#
protected override void Dispose( bool A_0 )
{
	if ( A_0 )
	{
		// remove your blips here
	}
}
```

**Comment by RainerHilmer** [comment]
@IncoCode I fail to see how this could help here. We need some system that notifies any registered script mod to trigger disposing of objects and probably other housekeeping tasks before terminating.

**Comment by IncoCode** [comment]
@RainerHilmer this method [is called](https://github.com/crosire/scripthookvdotnet/blob/master/source/ScriptDomain.cpp#L333) before terminating the script.

**Comment by RainerHilmer** [comment]
Ooooh gotta try that right now! :)
