### ISSUE TITLE
Help adding new buttons and multiple pages. E.g. max 15 items per page.

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#221]
Greetings,

So i'm trying to add all the cars for the car spawner part of my menu. However adding more than roughly 15 cars to my spawner will make the list extend beyond my screen. 

What i want to do is for every 15 items, add a button saying: "Next Page" and once Next Page is activated a new set of 15 items should be loaded and that should continue until i reached the end of my list of cars. I have no idea how to grasp this subject, therefore no code.

I'm kinda lost,
thank you in advance! :-)

EDIT: Below is some code i'm trying out. I hope you can get the idea of what i'm trying to accomplish.

    private void VehicleSpawnerMenu()
    {
        List<MenuButton> vehicleSpawnerMenuItems = new List<MenuButton>()
        {
            new GTA.MenuButton("Bikes"), 
            new GTA.MenuButton("Cars"), 
            new GTA.MenuButton("Boats"),
            new GTA.MenuButton("Choppers"),
            new GTA.MenuButton("Planes"),
            new GTA.MenuButton("Trailers"),
            new GTA.MenuButton("Busses"),
        };
        foreach (GTA.MenuButton buttonVehicleMenu in vehicleSpawnerMenuItems)
        {
            buttonVehicleMenu.Activated += (sender, args) => VehicleSpawnerCategories(buttonVehicleMenu);
        }

        var vehicleSpawnerMenu = new GTA.Menu("Vehicle Spawner Options", vehicleSpawnerMenuItems.ToArray());
        DrawMenu(vehicleSpawnerMenu);
    }

    private void VehicleSpawnerCategories(MenuButton sender)
    {
        List<MenuButton> vehicleSpawnerCategoryItems = new List<MenuButton>();

        foreach (VehicleHash vehicle in Enum.GetValues(typeof(VehicleHash)))
        {
            GTA.Model vehicleType = new Model(vehicle);
            GTA.MenuButton buttonVehicle = new GTA.MenuButton(vehicle.ToString());

            // Bikes menu
            if (sender.Caption == "Bikes" && vehicleType.IsBike)
            {
                vehicleSpawnerCategoryItems.Add(buttonVehicle);
            }

            // Cars menu
            if (sender.Caption == "Cars" && vehicleType.IsCar)
            {
                vehicleSpawnerCategoryItems.Add(buttonVehicle);
            }
        }
        var buttonNextPage = new GTA.MenuButton("Next Page");
        vehicleSpawnerCategoryItems.Add(buttonNextPage);

        var vehicleSpawnerSubMenus = new GTA.Menu(sender.Caption, vehicleSpawnerCategoryItems.ToArray());
        DrawMenu(vehicleSpawnerSubMenus);
    }

**Comment by IncoCode** [comment]
Try this. Not tested but should work :smile: 
```c#
public class ListMenu : Menu
{
	private readonly List<IMenuItem> _allItems;
	private readonly int _itemsPerPage;
	private int _currentShift = 0;

	public ListMenu( string headerCaption, IMenuItem[] items, int itemsPerPage )
		: base( headerCaption, items.Take( itemsPerPage ).ToArray() )
	{
		this._allItems = new List<IMenuItem>();
		this._allItems.AddRange( items );
		foreach ( IMenuItem item in this._allItems )
		{
			item.Parent = this;
		}
		this._itemsPerPage = itemsPerPage;
		this.ShowMenu();
	}

	private void NextPage()
	{
		if ( this._currentShift + this._itemsPerPage < this._allItems.Count )
		{
			this._currentShift += this._itemsPerPage;
		}
		else
		{
			this._currentShift += this._allItems.Count - this._currentShift;
		}
		this.ShowMenu();
	}

	private void PrevPage()
	{
		if ( this._currentShift - this._itemsPerPage > 0 )
		{
			this._currentShift -= this._itemsPerPage;
		}
		else
		{
			this._currentShift = 0;
		}
		this.ShowMenu();
	}

	private void ShowMenu()
	{
		this.ShowMenu( this._currentShift > 0, this._currentShift + this._itemsPerPage < this._allItems.Count );
		this.Initialize();
	}

	private void ShowMenu( bool showPrevBtn, bool showNextBtn )
	{
		this.Items = this._allItems.Skip( this._currentShift ).Take( this._itemsPerPage ).ToList();
		if ( showPrevBtn )
		{
			var prevBtn = new MenuButton( "PrevPage" ) { Parent = this };
			prevBtn.Activated += ( sender, args ) => this.PrevPage();
			this.Items.Add( prevBtn );
		}
		if ( showNextBtn )
		{
			var nextBtn = new MenuButton( "NextPage" ) { Parent = this };
			nextBtn.Activated += ( sender, args ) => this.NextPage();
			this.Items.Add( nextBtn );
		}
	}
}
```
Usage:
```c#
VehicleHash[] vehicles = Enum.GetValues( typeof( VehicleHash ) ).Cast<VehicleHash>().OrderBy( v => v.ToString() ).ToArray();
View.AddMenu( new ListMenu( "VehMenu", vehicles.Select( vehicle => new MenuButton( vehicle.ToString() ) ).ToArray(), 10 ) );
```

**Comment by frodzet** [comment]
@IncoCode Oh my dear god, i want to hug the f*** out of you! :-) Works like a charm, once my mod gets released i will definitely give credit where credit is due! Best part is, i can use it again for pedestrians and what not! Lovely! :+1:

**Comment by frodzet** [comment]
@IncoCode Can you help me change it a bit so it also works on NumPad 4 and NumPad 6 to go to previous and next page. Thank you! :-D

**Comment by IncoCode** [comment]
1. I think you should create several arrays for different models: like bikes array, cars array etc (you can create it when your script gets initialized).
2. You should override ```OnChangeItem``` method in ```ListMenu``` to get ability to change pages using ```NumPad 4``` and ```NumPad 6```.
```c#
public class ListMenu : Menu
{
	private readonly List<IMenuItem> _allItems;
	private readonly int _itemsPerPage;
	private int _currentShift = 0;

	public ListMenu( string headerCaption, IMenuItem[] items, int itemsPerPage )
		: base( headerCaption, items.Take( itemsPerPage ).ToArray() )
	{
		this._allItems = new List<IMenuItem>();
		this._allItems.AddRange( items );
		foreach ( IMenuItem item in this._allItems )
		{
			item.Parent = this;
		}
		this._itemsPerPage = itemsPerPage;
		this.ShowMenu();
	}

	public override void OnChangeItem( bool right )
	{
		if ( right && this._currentShift + this._itemsPerPage < this._allItems.Count )
		{
			this.NextPage();
		}
		else if ( !right && this._currentShift > 0 )
		{
			this.PrevPage();
		}
	}

	private void NextPage()
	{
		if ( this._currentShift + this._itemsPerPage < this._allItems.Count )
		{
			this._currentShift += this._itemsPerPage;
		}
		else
		{
			this._currentShift += this._allItems.Count - this._currentShift;
		}
		this.ShowMenu();
	}

	private void PrevPage()
	{
		if ( this._currentShift - this._itemsPerPage > 0 )
		{
			this._currentShift -= this._itemsPerPage;
		}
		else
		{
			this._currentShift = 0;
		}
		this.ShowMenu();
	}

	private void ShowMenu()
	{
		this.ShowMenu( this._currentShift > 0, this._currentShift + this._itemsPerPage < this._allItems.Count );
		this.Initialize();
	}

	private void ShowMenu( bool showPrevBtn, bool showNextBtn )
	{
		this.Items = this._allItems.Skip( this._currentShift ).Take( this._itemsPerPage ).ToList();
		if ( showPrevBtn )
		{
			var prevBtn = new MenuButton( "PrevPage" ) { Parent = this };
			prevBtn.Activated += ( sender, args ) => this.PrevPage();
			this.Items.Add( prevBtn );
		}
		if ( showNextBtn )
		{
			var nextBtn = new MenuButton( "NextPage" ) { Parent = this };
			nextBtn.Activated += ( sender, args ) => this.NextPage();
			this.Items.Add( nextBtn );
		}
	}
}
```
```c#
public class VehMenu : Script
{
	private List<VehicleHash> _cars = new List<VehicleHash>();
	private List<VehicleHash> _bikes = new List<VehicleHash>();

	public VehMenu()
	{
		this.KeyDown += this.VehMenu_KeyDown;
		this.FillArr();
	}

	private void FillArr()
	{
		foreach ( VehicleHash vehicle in Enum.GetValues( typeof( VehicleHash ) ) )
		{
			var model = new Model( vehicle );
			if ( model.IsCar )
			{
				this._cars.Add( vehicle );
			}
			else if ( model.IsBike )
			{
				this._bikes.Add( vehicle );
			}
		}
		this._cars = this._cars.OrderBy( c => c.ToString() ).ToList();
		this._bikes = this._bikes.OrderBy( b => b.ToString() ).ToList();
	}

	private void SpawnVehicle( VehicleHash vehicle )
	{
		World.CreateVehicle( vehicle, Game.Player.Character.Position );
		this.View.CloseAllMenus();
	}

	private void ShowModelsMenu( VehicleHash[] models )
	{
		var buttons = new List<MenuButton>();
		foreach ( VehicleHash vehicle in models )
		{
			var button = new MenuButton( vehicle.ToString() );
			var veh = vehicle;
			button.Activated += ( sender, args ) => this.SpawnVehicle( veh );
			buttons.Add( button );
		}
		this.View.AddMenu( new ListMenu( "VehMenu", buttons.ToArray(), 10 ) );
	}

	private void ShowCategoriesMenu()
	{
		var carsBtn = new MenuButton( "Cars" );
		carsBtn.Activated += ( sender, args ) => this.ShowModelsMenu( this._cars.ToArray() );
		var bikesBtn = new MenuButton( "Bikes" );
		bikesBtn.Activated += ( sender, args ) => this.ShowModelsMenu( this._bikes.ToArray() );
		this.View.AddMenu( new Menu( "Categories", new IMenuItem[] { carsBtn, bikesBtn } ) );
	}

	private void VehMenu_KeyDown( object sender, KeyEventArgs e )
	{
		if ( e.KeyCode == Keys.I )
		{
			this.ShowCategoriesMenu();
		}
	}
}
```

**Comment by IncoCode** [comment]
@frodzet ```ListMenu.Items``` contains items of current page. ```ListMenu._allItems``` (private, but you can make it public if you want so) contains all items, that you passed in constructor :smile: But i recomend you to look at my example above.

**Comment by frodzet** [comment]
@IncoCode Thank you! :-) By the way do you have a skype account i can add? Or maybe you could add me: sifferjb :-) I don't want to post questions on smaller issues here, but would be nice if i could get in touch with you with small issues i come across :-)

**Comment by IncoCode** [comment]
Yeah: akulich.dmitri .

**Comment by frodzet** [comment]
@crosire, @JohnnyCrazy This thread can be closed now :-)

**Comment by IncoCode** [comment]
Click on close issue button :-)

**Comment by Don2233** [comment]
LOL. I used stack for showing menu. )) It so stupid.
It turns out there is a simple solution.Do i can change action keys?It is processed at a native level.
