### ISSUE TITLE
Implementation of the new DirectX Hook and Global Pointers

### ISSUE THREAD

**Issue by JohnnyCrazy** [crosire/scripthookvdotnet#223]
The new scripthook has some neat new features.

````c++
IMPORT void drawTexture(int id, int index, int level, int time,
	float sizeX, float sizeY, float centerX, float centerY,
	float posX, float posY, float rotation, float screenHeightScaleFactor,
	float r, float g, float b, float a);

typedef void(*PresentCallback)(void *);
IMPORT void presentCallbackRegister(PresentCallback cb);
IMPORT void presentCallbackUnregister(PresentCallback cb);
````

Before we implement them, we need to find out how far we want to go. Do we want to include a c# wrapper around the directX stuff (SlimDX etc.)? drawTexture will propably get wrapped in a class.

**Comment by crosire** [comment]
SlimDX etc. can be added by the script developers if needed. I don't want to bloat this project more than needed. But the texture drawing is something of interest.

**Comment by JohnnyCrazy** [comment]
Yea, sounds good :+1:

**Comment by frodzet** [comment]
I think i know what it does, but just to be sure, could someone explain it to me? :-) Also what makes you @JohnnyCrazy so exited about it? :-)

**Comment by JohnnyCrazy** [comment]
Well, the draw_texture is pretty awsome, allows us to draw custom PNGs on the screen :+1: 
And the DirectX hook itself deliver endless possibilties for developers. (Custom fonts and even custom animations and stuff)

**Comment by frodzet** [comment]
@JohnnyCrazy Sounds very nice, but let's just take custom fonts for instance, would that also mean we would be able to use System.Drawing.Fonts and other fonts we either create or find online? :-)

**Comment by JohnnyCrazy** [comment]
If the font is installed on the target PC, you can use them. But we most likely won't implement DirectX Text-Drawing directly in this library, since it would bloat the library. However, we **may** provide a little wrapper around the DirectX interface, so developers can easily use SlimDX with it.

**Comment by crosire** [comment]
Support for custom textures was added in 150fdd7953a97a7a9ecc2c8d662c754ec10f971a.

**Comment by crosire** [comment]
Globals were added in #295, so this is now fully resolved.
