### ISSUE TITLE
Auto start the engine after shutdown

### ISSUE THREAD

**Issue by ChillyWillyGilly** [crosire/scripthookvdotnet#225]
case Keys.NumPad0:
                        vehicle.EngineRunning = this.mEngineRunning = !this.mEngineRunning;
                        break;

The game sitting in the car press 0 and the engine switched off. But immediately turned back on. How to block it? Sorry for my English. please, help

**Comment by letsplayordy** [comment]
In GTA IV you would have to set the PetrolTankHealth to 0 so that the vehicle couldn't start up.

**Comment by ChillyWillyGilly** [comment]
It is working! Thank you very much! you are the best!
