### ISSUE TITLE
Game.Pause() seems to do nothing.

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#230]
I called that method before I rendered a menu but the game still runs and I can even move the character while the menu is on.
      private void OpenMenu()
      {
         Game.Pause();
         var menuItems = CreateMenuItems();
         var modMenu = FormatMenu(menuItems);
         View.AddMenu(modMenu);
      }

**Comment by LibertyLocked** [comment]
SET_PAUSE_MENU_ACTIVE doesn't really work, but,
Pause menu pauses all the scripts - you won't be able to see your menu.

**Comment by RainerHilmer** [comment]
Thank you but anyway, how can I pause the game when I display a menu?

**Comment by LibertyLocked** [comment]
Use Game.TimeScale. Set to 0 the game will pause

**Comment by RainerHilmer** [comment]
Thanks I will try that. :)

**Comment by RainerHilmer** [comment]
@JohnnyCrazy I'd say this is more of a bug than a question. A method that does nothing either needs to get fixed or removed.

**Comment by RainerHilmer** [comment]
Game.TimeScale=0 does not do the trick.
1. The game is still running, at an extremely slow pace but still.
2. I changed the menu item up key to arrow up to match the in-game menu handling but this makes also brings up the character's phone. So the key events are not blocked for the "live mode".

**Comment by RainerHilmer** [comment]
LOL
Function.Call(Hash.SET_GAME_PAUSED, true);
just works flawless.

**Comment by RainerHilmer** [comment]
Sorry I hit the wrong button. I didn't close this issue because I think this should be fixed in the ScripthooVDotNet.
