### ISSUE TITLE
Where can I set the label of the input line?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#231]
I call Game.GetUserInput(string startText, int maxLength). The input frame appears in game but
1. there is a label "This label is here!" at the top of the frame. So i guess we can set this label somehow, but how and where?
2. I thought startText appears as default string in the input line but I don't see that string anywhere.

**Comment by crosire** [comment]
Just checked against NativeDB and GetUserInput uses the "DISPLAY_ONSCREEN_KEYBOARD" native incorrectly, which is what it doesn't work properly. That needs fixing.

**Comment by JohnnyCrazy** [comment]
Yes, noticed the same issue too when using it the last week (but forgot to create an issue tho :( )
Implemented DISPLAY_ONSCREEN_KEYBOARD while the doc was in an early stage, but I think it was working back there.

**Comment by crosire** [comment]
Was fixed in 9c6e6b6a7d7f21d48e47fa84fa4ffba0dec3bd80.
