### ISSUE TITLE
Line numbers in crash log

### ISSUE THREAD

**Issue by BenjaminFaal** [crosire/scripthookvdotnet#234]
When the code crashes it prints a stack trace to the log file but without line numbers.

Please is this possible to add?

**Comment by crosire** [comment]
Line numbers are part of the stack trace if debug information was found. This is the case if you loaded directly from a source file or, in case you compiled your scripts to a DLL, you put the debug database (.pdb) into the game directory.

**Comment by BenjaminFaal** [comment]
Hey, thanks for the quick reply!

I modified the post build commands so it copies the .cs file to the scripts folder.

Now it shows me the line number, thanks again and sorry for asking becasue i really couldnt figure it out else.
