### ISSUE TITLE
Changing Weapon Animation Speed? (Rapid Fire)

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#235]
Greetings,

So i'm trying to change the animation speed of weapons. Or well the actual animation i'm trying to speed up is the time between shots. If i have for instance infinite ammunition in clip and i shoot with e.g. RailGun there is some delay between each RailGun shot. How can i override this? :-) I guess it has something to do with animations?

**Comment by crosire** [comment]
The new "Ped.ShootRate" property should do exactly this.
