### ISSUE TITLE
Method to get all Entities, or colliding Entity of Entity?

### ISSUE THREAD

**Issue by BenjaminFaal** [crosire/scripthookvdotnet#237]
Please take a look at the thread below:

http://gtaforums.com/topic/806827-native-methode-to-get-all-entities-in-area/

What it comes down to is i need a way to retreive the colliding Entity of a give Entity.

Of course i could loop through all Entities which i can get from World.GetAllEntities() but it does not return all Entities, like no Props in there. I hope it is clear what i mean if you have time please tell me the best way.

I also tried to RayCast but its not what i need.

**Comment by Nacorpio** [comment]
I have made a helper class which wraps around entity and catches events such as when an entity is touching another one.

**Comment by BenjaminFaal** [comment]
Wow that seems helpful, is it open source and is it also possible to get the actual touching Entity object or?

**Comment by Nacorpio** [comment]
I will try to test some things out, and I'll report back to you whether it works or not.

**Comment by BenjaminFaal** [comment]
Nice, in ideal i would need this for all type of Entities so Prop Ped and Vehicle.

I hope it will work!

**Comment by BenjaminFaal** [comment]
@Nacorpio I found this function http://www.dev-c.com/nativedb/func/info/5c3d0a935f535c4c, it returns an int i thought it would return the Entity's handle but its some other number. Any ideas on this?

**Comment by Dakota628** [comment]
Why could you not achieve your goal with Raycast?

**Comment by BenjaminFaal** [comment]
@Dakota628 I have tried but i cant seem to get the colliding entity, do you know how to do this?

**Comment by zorg93** [comment]
@BenjaminFaal Entity entity = World.Raycast(source, target, IntersectOptions.Everything).HitEntity;

**Comment by BenjaminFaal** [comment]
@zorg93 I understand how you need to use the RayCast method but lets say im driving in a Vehicle.

What would be the source and destination to get the colliding Entity of the Vehicle?

Also RAGE Plugin Hook actually has these GetAllEntities which really returns all Entities.

**Comment by zorg93** [comment]
@BenjaminFaal Maybe there isnt such a high limit on the script pool after all
good point that wont work, but if you are driving the vehicle, just use get_ped_nearby_vehicles, and the it would probably be the first or second one in the array

**Comment by BenjaminFaal** [comment]
Hmm thats a good point too, thanks for that native, to be honest i didnt think of that one yet!

Thanks very much!
