### ISSUE TITLE
Ability to Scroll in Menu ?

### ISSUE THREAD

**Issue by GrandTheftMods** [crosire/scripthookvdotnet#239]
@ scripthookvdotnet-Team
Suggestion: It may be a useful addition to make own menus scollable, e.g: you have 50 entries for your menu but you only want to appear 10 at the same time, cause your otherwise your screen is too small to see all the items.  Also im kinda to stupid to set a value for the MenuNumericScroller.
It says that the value is read only...

thanks in advance

**Comment by IncoCode** [comment]
#211 
Not scroll, but i think you can rewrite it to add scroll :wink:

**Comment by GrandTheftMods** [comment]
Thank you i'll give it a try later :+1: .....  u may know a solution for the problem with the MenuNumericScroller?

**Comment by IncoCode** [comment]
Look how the ```Value``` is formed: https://github.com/crosire/scripthookvdotnet/blob/dev/source/MenuItem.hpp#L202

**Comment by GrandTheftMods** [comment]
well , i guess that was kinda too easy.... Thank you :smile:

**Comment by GrandTheftMods** [comment]
the scrolling is working now as well, again thanks for your help man :+1:

**Comment by zorg93** [comment]
I have just modified the menu class to autoscroll, will put in a commit when I figure out how to draw up and down arrows to indicate there are more things in the menu than shown on screen

**Comment by zorg93** [comment]
https://github.com/crosire/scripthookvdotnet/pull/247

**Comment by GrandTheftMods** [comment]
pretty nice :+1:    i personally changed the footer to show Itemselected/Numberoficons automatically   so you a better overview over your items, may this would be an useful addition (maybe not by changing the footer but show it somewhere else) ?

**Comment by zorg93** [comment]
@GrandTheftMods I thought about having a system like that, but decided against it because there wasnt an obvious place to put it without it being too obtrusive, which is why i use the up and down arrows. Using the footer for item count/max display would cause an issue with people who prefer not to use the footer in their menu

**Comment by GrandTheftMods** [comment]
yep thats the problem i was facing too, i decided to use the numbers but i also kinda like the idea of using the arrows now i have to decide...

**Comment by zorg93** [comment]
@GrandTheftMods If your scrolling menu inherits the GTA.Menu then once the next release is made all GTA.Menus will have this scrolling ability

**Comment by GrandTheftMods** [comment]
@zorg93  so i can have both. nice :smile:

**Comment by GrandTheftMods** [comment]
i looked up the arrowthing  wouldn't it be more smooth to scroll item by item and not that kind of side thing ?  and it would also be nice to have the option too choose how many items are shown at one time ?

**Comment by zorg93** [comment]
I'm just testing altering how many items can be displayed now, as for your first point, I have no idea what you are asking

**Comment by GrandTheftMods** [comment]
if i scoll down it jumps too the end of the men, it would be smoother that way : the selected item is the last one which can be seen -> you press down and on the the top the upmost item disappears and on the bottem the niext item is added

**Comment by GrandTheftMods** [comment]
* if i scroll down it jumts to the end of the menu ....

**Comment by GrandTheftMods** [comment]
Wtf my keyboard

**Comment by GrandTheftMods** [comment]
if i scroll down it jumps to the end of the menu, it would be smoother that way : the selected item is the last one which can be seen -> you press down and on  the upmost item disappears and on the bottem the next item is added

**Comment by zorg93** [comment]
Still dont know what you're asking

**Comment by GrandTheftMods** [comment]
okay another try ^^     
    public class ScrollMenu : Menu
    {
        private List<IMenuItem> _allItems;
        private int _itemsPerPage;
        private int Itemstoskip = 0;

        public ScrollMenu(string headerCaption, IMenuItem[] items, int itemsPerPage)
            : base(headerCaption, items.Take(itemsPerPage).ToArray())
        {
            this._allItems = new List<IMenuItem>();
            this._allItems.AddRange(items);
            foreach (IMenuItem item in this._allItems)
            {
                item.Parent = this;
            }
            this._itemsPerPage = itemsPerPage;
            this.ShowMenu();
            
        }

        public override void OnChangeSelection(bool down)
        {
            if (down)
            {
                if (this.SelectedIndex >= _itemsPerPage - 1)
                {
                    bool skip = false;

                    if (this.Itemstoskip + this._itemsPerPage < this._allItems.Count)
                    {
                        this.Itemstoskip += 1;
                    }
                    else
                    {
                        this.Itemstoskip = 0;
                        skip = true;
                    }
                    this.ShowMenu();

                    if (skip) { this.SelectedIndex = 0; skip = false; }
                    else { this.SelectedIndex = _itemsPerPage - 1; }
                }
                else
                {
                    this.SelectedIndex++;
                }
            }
            else if (down == false)
            {

                if (this.SelectedIndex <= 0)
                {
                    bool skip = false;

                    if (this.Itemstoskip - this._itemsPerPage > -this._itemsPerPage)
                    {
                        this.Itemstoskip -= 1;
                    }
                    else
                    {
                        this.Itemstoskip = this._allItems.Count - _itemsPerPage;
                        skip = true;
                    }

                    this.ShowMenu();

                    if (skip) { this.SelectedIndex = _itemsPerPage - 1; skip = false; }
                    else { this.SelectedIndex = 0; }
                }
                else
                {
                    this.SelectedIndex--;
                }
            }
        }

        private void ShowMenu()
        {
            int index = 1;
            foreach (IMenuItem i in this._allItems)
            {
                i.Description = index + "/" + this._allItems.Count.ToString();
                index += 1;
            }


            if (_allItems.Count < _itemsPerPage)
            {
                _itemsPerPage = _allItems.Count;
            }
            this.Items = this._allItems.Skip(this.Itemstoskip).Take(this._itemsPerPage).ToList();
            this.Initialize();
        }
    }

 

may its a bit sloppy and not c++  but anyways i hope its understandable......

based on code of IncoCode

**Comment by zorg93** [comment]
So you wait til you're selecting the item at the bottom of the list to start scrolling where as i start scrolling a items above that. or was that not the point you were getting at

**Comment by GrandTheftMods** [comment]
i think my code and the new menu doesnt fit together so some strange things are happening ....   anyways i'll just wait for your final version and we'll see i guess!  thanks for taking the time
