### ISSUE TITLE
Dependency System

### ISSUE THREAD

**Issue by Dakota628** [crosire/scripthookvdotnet#241]
Currently it is fairly difficult and hacky to allow scripts to depend on other scripts. I propose a dependency system to allow scripts access to their dependent scripts app domains as well as loading scripts based on a hierarchical dependency structure.

**Comment by Dakota628** [comment]
@JohnnyCrazy @crosire is there anyway I can contact you guys outside of here?

**Comment by zorg93** [comment]
We have a channel on slack, https://scripthookvdotnet.slack.com/

**Comment by Dakota628** [comment]
Thank you sir!

**Comment by Dakota628** [comment]
@zorg93 Can somebody invite me? dakota@jqa.me

**Comment by zorg93** [comment]
@Dakota628 think you'll have to wait for @JohnnyCrazy to invite you

**Comment by JohnnyCrazy** [comment]
Done
