### ISSUE TITLE
Native "GET_PED_LAST_WEAPON_IMPACT_COORD" is completely broken

### ISSUE THREAD

**Issue by andrewcamphouse** [crosire/scripthookvdotnet#242]
Given that this native is the only way to obtain the coordinates of a projectile impact (that isn't terribly complicated), this is rather important. The native is as follows: 
"BOOL GET_PED_LAST_WEAPON_IMPACT_COORD(Ped ped, Vector3 *coord)"
However, ScriptHookVDotNet does not allow the GTA.Math.Vector3 variable to be passed in. Many others have also stated that this native is implemented incorrectly.

Here is an image of the issue occuring. I am implementing it correctly.
![brokennative](https://cloud.githubusercontent.com/assets/9450131/8640579/1871540e-28c3-11e5-91c1-cc9004071ad8.png)

**Comment by letsplayordy** [comment]
I believe you have to use Native.OutputArgument as the parameter and then use GetResult<...>() to get the Vector3.

**Comment by andrewcamphouse** [comment]
That is interesting. I have spent hours searching and nobody has said that.
