### ISSUE TITLE
CreateRandomPedOnSeat creates animals sometimes

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#243]
Myself and users of my VAutodrive experienced this.

**Comment by crosire** [comment]
That's expected. Animals are peds too and CreateRandomPedOnSeat just chooses a random value out of the PedHash enumeration.

**Comment by IncoCode** [comment]
![dog-driving-dwi 1](https://cloud.githubusercontent.com/assets/6574672/8657900/fee93f60-29a8-11e5-84f3-e646465803ac.jpg)

**Comment by RainerHilmer** [comment]
Who expects an animal to be spawned on a vehicle seat? smh

**Comment by zorg93** [comment]
why not use create_random_ped_as_driver or create_random_ped for this method instead of randomly choosing a hash from the enum

**Comment by JohnnyCrazy** [comment]
Didn't know these 2 hashes exist, good catch. I think it would be good using them here.
@crosire

**Comment by crosire** [comment]
Agreed.
