### ISSUE TITLE
VehicleMod suspension, brakes, engine, etc returns null?

### ISSUE THREAD

**Issue by frodzet** [crosire/scripthookvdotnet#244]
Greetings,

So i've been trying to make a VehicleMod menu. The thing is that anything that does not have a visual appearance returns null, below is my code:

    private void SublimeVehicleModMenu()
    {
        List<IMenuItem> vehicleModCategoriesList = new List<IMenuItem>();

        foreach (VehicleMod modType in Enum.GetValues(typeof(VehicleMod)))
        {
            Vehicle currentVehicle = Game.Player.Character.CurrentVehicle;
            Function.Call(Hash.SET_VEHICLE_MOD_KIT, currentVehicle, 0);

            int numMods = Function.Call<int>(Hash.GET_NUM_VEHICLE_MODS, currentVehicle, (int) modType);

            if (numMods != 0)
            {
                var buttonModCategory = new MenuButton(modType.ToString());
                buttonModCategory.Activated += (sender, args) =>
                {
                    List<IMenuItem> modItemsList = new List<IMenuItem>();

                    for (int modIndex = 0; modIndex < numMods; modIndex++)
                    {
                        string getModLabel = Function.Call<string>(Hash.GET_MOD_TEXT_LABEL, currentVehicle, (int) modType, modIndex);
                        string getDisplayLabel = Function.Call<string>(Hash._GET_LABEL_TEXT, getModLabel);

                        var buttonSetMod = new MenuButton(getDisplayLabel);
                        modItemsList.Add(buttonSetMod);
                    }

                    ListMenu vehicleModsListMenu = new ListMenu(modType.ToString(), modItemsList.ToArray(), 20);
                    DrawMenu(vehicleModsListMenu);
                };
                vehicleModCategoriesList.Add(buttonModCategory);
            }
        }

        VehicleModMenu = new GTA.Menu("Vehicle Mod Options", vehicleModCategoriesList.ToArray());
        DrawMenu(VehicleModMenu);
    }

The thing that returns null is the buttons generated by the for modIndex loop. Tyres, exhausts, bumpers, skirts etc all return the correct value, but all the other stuff such as horn, transmission, engine, suspension etc returns a null value. Why is that?

Could it be that those does not have the correct value associated with them? Could the native be wrong or is it something with my code?

**Comment by crosire** [comment]
Since quite some time passed since this issue was created, I assume it's no longer relevant, so I'll close it for now.
