### ISSUE TITLE
Only Detect Compiled Assemblies that have .net.dll, or .net

### ISSUE THREAD

**Issue by ricci07** [crosire/scripthookvdotnet#245]
I think we should adopt the way IV.net scripthook way and only allow the the .net.dll and .net file extensions to avoid scripthook loading any .dll, which will causing crashing.

**Comment by JohnnyCrazy** [comment]
The scripthook only checks wether there are script-classes in the DLL, if not, nothing will happen.
Or is there a problem when native (c++ etc.) DLLs are in the folder?

**Comment by crosire** [comment]
I always found that a strange naming. Scripthook should just ignore DLLs that do not contain any .NET assembly code and script classes, as @JohnnyCrazy mentioned. So that shouldn't be an issue.

**Comment by ricci07** [comment]
Well, as JulioNIB says,  "put scripthookVDotNet.dll in scripts folder and you will see ^^"
I think maybe because this dll 'has' script classes inside, that is why it crashes.

**Comment by crosire** [comment]
ScriptHookVDotNet.dll contains .NET assembly code, it's not a native DLL. ScriptHook will try to load it, only to [replace the reference with its own one](https://github.com/crosire/scripthookvdotnet/blob/dev/source/ScriptDomain.cpp#L60), which probably causes an infinite loop and finally crashes. Just a guess though.
