### ISSUE TITLE
ScriptSettings cannot be accessed in constructor

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#248]
The Script filename property isnt set until after the constructor has been called, therefore you cannot use ScriptSettings in the constructor

**Comment by crosire** [comment]
I would prefer to find a way to fix this without having to introduce a virtual function to override.

**Comment by zorg93** [comment]
Event handler would be another way, though it would only get called once.

**Comment by crosire** [comment]
I meant to find a way to set up the settings early, so they can be used in the constructor.

**Comment by zorg93** [comment]
@crosire I looked at that and its not looking likely, the script class doesnt exist until you call the constructor so you cant set it up before, you also cant supply any params to the base constructor when you instantiate it either

**Comment by zorg93** [comment]
How about instead of 
String ^path = IO::Path::ChangeExtension(this->mFilename, ".ini"); for the ini file
You could use 
path = System::IO::Path::Combine(System::IO::Path::GetDirectoryName(System::Reflection::Assembly::GetExecutingAssembly()->Location), "scripts", this->GetType()->Name + ".ini");

however that would have the issue that the ini files are called the scripts name instead of the file they exist in

**Comment by zorg93** [comment]
@crosire I found a way that works and lets you use ScriptSettings in the constructor

**Comment by Dakota628** [comment]
Simply have an internal constructor for Script that sets all that stuff up then calls the default constructor. Should fix your problem.

**Comment by zorg93** [comment]
Already fixed it

**Comment by crosire** [comment]
Fixed in 751b9e1a35f49ffcf7f4f1880150794172d9942e.
