### ISSUE TITLE
ScriptSettings dont get saved by the script

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#249]
There is no save method which prevents you from editing ini files with your script

**Comment by crosire** [comment]
The reason there was no save function is because the fastest way to do it it would overwrite all comments in the INI file and I'm not sure if that is such a good idea.

**Comment by zorg93** [comment]
Comments in an ini could easily be replaced by a read me file

**Comment by JohnnyCrazy** [comment]
+1 for READMEs.

**Comment by crosire** [comment]
As if people read readmes these days =P

**Comment by letsplayordy** [comment]
*raises hand* I do :P

**Comment by crosire** [comment]
Added in 7750c6a4baada81c13443039c7e2bcc9f6d2ec6d.
