### ISSUE TITLE
Crash when alt-tabbing back in to the game

### ISSUE THREAD

**Issue by FabioGNR** [crosire/scripthookvdotnet#25]
Steps to reproduce ( always works for me ): Launch game in fullscreen mode, latest scripthook and .net scripthook as only ASI. One script loaded via .NET. Switch to another window so GTA V loses focus, switch back in and scripthook produces an error:
`[17:04:40] CORE: Started thread 'ScriptHookVDotNet.asi', id 27 active 1
[17:04:40] CORE: Launching main() for 'ScriptHookVDotNet.asi'
[17:16:52] CORE: An exception occurred while executing 'ScriptHookVDotNet.asi'`
Nothing in ScriptHookVDotNet.log, except loading of my scripts.

**Comment by JohnnyCrazy** [comment]
Did you use the latest Version?
A crash, which occurs some time after tabbing out too long was fixed in #20

**Comment by FabioGNR** [comment]
That's probably it yeah, I just realized i'm in fact not on the latest version since I overwrote it with my own build, i'll switch to the new one and make a new issue if it reappears, sorry for wasting your time ;)

**Comment by JohnnyCrazy** [comment]
No problem, glad I could help :+1:
