### ISSUE TITLE
Question: Accessing the active page on phone

### ISSUE THREAD

**Issue by ardaozkal** [crosire/scripthookvdotnet#251]
Is it even possible? The natives doesn't show such thing. But I know that we ALL want to get a cargobob, so we need to figure it out.

**Comment by zorg93** [comment]
Webpages are gfx(swf) files, not scripts. So this wont happen

**Comment by JohnnyCrazy** [comment]
As @zorg93 said, this can't be achieved through natives and propably won't get in the scripthook.
