### ISSUE TITLE
GetUserInput Doesnt block key up/down events

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#252]
When using getuserinput it logs what keys have been pressed and released and as soon as you finish Inputting it will fire those key up/down events in all scripts, GetUserInput should stop the scripthook recording keyevents while active

**Comment by JohnnyCrazy** [comment]
Woops, didn't see this one. Let's continue here.

**Comment by frodzet** [comment]
I already added an issue about this here:

https://github.com/crosire/scripthookvdotnet/issues/207
