### ISSUE TITLE
Can't get a complete list of blips in map

### ISSUE THREAD

**Issue by ardaozkal** [crosire/scripthookvdotnet#253]
I found and tried two ways and one returns 0 items and one returns my location. How to get all blips? I can use native too, no problem, but how can I do it?

**Comment by ardaozkal** [comment]
More specifically, I'm trying to make something to skip races (in sp ;) ) so I can get %100. Next blip of race checkpoint would be nice too.

**Comment by RainerHilmer** [comment]
I rather you are searching for checkpoints. Blips are the dots and icons on map view while checkpoints are those cylinders you see appearing on a race track, together with those chevron formed markers.

**Comment by JohnnyCrazy** [comment]
Like @RainerHilmer said, Blips are the little Dots on the Map. What you are searching are checkpoints which are not implemented yet (see #155 )
