### ISSUE TITLE
How can I change the menu key bindings [Move keybindings to UI]

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#255]
Currently I scroll with Numpad8 up, Numpad2 down and select with Numpad5. Is it possible to change those keys so they match the keys of in-game menus (Cursor up/down and Return/Enter to select)? I think that would be better so users can handle them as they are used to.

**Comment by IncoCode** [comment]
```Script``` instance have properties: ```ActivateKey```, ```BackKey``` etc.

**Comment by crosire** [comment]
We should probably move that out of Script into UI.

**Comment by RainerHilmer** [comment]
Thanks :)

**Comment by crosire** [comment]
No longer needed, because the menu was removed.
