### ISSUE TITLE
Script Hook V .NET is interfering with exception catching in C++ ASI plugins

### ISSUE THREAD

**Issue by MakG10** [crosire/scripthookvdotnet#258]
Hi.
It seems that Script Hook V .NET is causing caught exceptions to throw anyway in ASI plugins written in C++. To reproduce, you can compile this example using latest Script Hook V SDK:

```
#include <string>
#include "main.h"

void CrashTestMain()
{
	srand(GetTickCount());

	std::string test = "F3"; // invalid integer, exception will be thrown
	int conversionResult;

	try
	{
		conversionResult = std::stoi(test);
	} catch (const std::invalid_argument& e) {
		// supressing exception...
	} catch (...)
	{
		// supressing any other exceptions...
	}

	while (true)
	{
		WAIT(0);
	}
}

BOOL APIENTRY DllMain(HMODULE hInstance, DWORD reason, LPVOID lpReserved)
{
	switch (reason)
	{
	case DLL_PROCESS_ATTACH:
		scriptRegister(hInstance, CrashTestMain);
		break;
	case DLL_PROCESS_DETACH:
		scriptUnregister(hInstance);
		break;
	}
	return TRUE;
}
```

It causes error on script load or reload if Script Hook V .NET is installed. Without it, it's all good. Is there anything you can do? It's a pretty serious flaw.

Regards.

**Comment by crosire** [comment]
The only explanation I have for this is that the CLR runtime changes exception handling when loaded into the process. But there is not much I can do about that then.
