### ISSUE TITLE
Native UI

### ISSUE THREAD

**Issue by crosire** [crosire/scripthookvdotnet#260]
I think for 2.0 we should consider overhauling the UI system to look like the game one by default. There are some libraries for this available already, so why not move them into the core.

**Comment by zorg93** [comment]
I had thought about this, the current menu Base just looks plain and boring. Also cursor support would be very nice

**Comment by zorg93** [comment]
Just looked in commonmenu, all the textures seem to be in there

**Comment by frodzet** [comment]
Sounds like a good idea, you should also reconsider the way the menu class is written.. You should add a seperate class with scrollable menu in it, because the way it works now it's kinda stupid when inheriting from menu class. Don't get me wrong, i like the scrollable menu, but we need as a seperate menu rather than a feature on the current menu class :-)

**Comment by zorg93** [comment]
Why would you want to remove the scrollable feature, It doesnt come into play when you dont have enough items on the screen

**Comment by frodzet** [comment]
I don't want it removed, i want it to be a seperate menu class.. I'm so hungover at the moment, can't really explain what i mean properly :-) sorry.

**Comment by zorg93** [comment]
Why are you inheriting from the menu class?

**Comment by crosire** [comment]
I'm toying with the idea to simply remove the current menu implementation altogether. Almost all new mods use https://github.com/Guad/NativeUI now, which is better in many ways. So there is not much of a reason to keep the old base, other than to support old mods.

**Comment by crosire** [comment]
Removed menu in 9faffe5cd9a926398b6852fbde63aceb80cd4ca6. This is a drastic step, but it cleans up the code and there are better alternatives as mentioned. It will break a number of mods though, so we should probably provide a "compatibility build" for the release, which still contains the menu.

**Comment by zorg93** [comment]
suppose I better update my script testing mod :'(

**Comment by zorg93** [comment]
UIContainer needs to be added back, NativeUI uses it

**Comment by zorg93** [comment]
So do UIText and UIRectangle

**Comment by crosire** [comment]
Good call, I didn't notice they are independent from the menu implementation.
