### ISSUE TITLE
Error message when loading GTA V

### ISSUE THREAD

**Issue by slolo1** [crosire/scripthookvdotnet#261]
When I load up GTA V a this message pops up:

// GTA V ASI LOADER (build May 2 2015) 
// (C) Alexander Blade 2015 
LIB: "C:\WINDOWS\system32\dinput8.dll" => 00007FFAB3AF0000 
API: "DirectInput8Create" => 00007FFAB3AFA570 
API: "DllCanUnloadNow" => 00007FFAB3B0BBA0 
API: "DllGetClassObject" => 00007FFAB3B0BC70 
API: "DllRegisterServer" => 00007FFAB3B160A0 
API: "DllUnregisterServer" => 00007FFAB3B16430 
LOADER: Loading *.asi plugins 
ASI: Loading "D:\Program Files\Rockstar Games\Grand Theft Auto V\NativeTrainer.asi" 
"NativeTrainer.asi" => 00007FFABFC60000 
ASI: Loading "D:\Program Files\Rockstar Games\Grand Theft Auto V\ScriptHookVDotNet.asi" 
"ScriptHookVDotNet.asi" failed to load 
LOADER: Finished loading *.asi plugins

Any ideas of what the problem is??

**Comment by zorg93** [comment]
Are you using the latest 1.1 release

**Comment by slolo1** [comment]
Yes i am using the latest release, but do you put it in the gta V directory or the "scripts" folder?

**Comment by zorg93** [comment]
It goes in the gta directory, Then I dont know what your issue. you have updated your game and scripthookv to latest releases aswell?

**Comment by slolo1** [comment]
i have updated my game but not my scripthookv, i'll give it a go

**Comment by slolo1** [comment]
IT WORKS!!!!!!!!!!!!! Thank you very much zorg93!!!!!!

**Comment by zorg93** [comment]
Close this issue then, the button next to comment :)
