### ISSUE TITLE
Quaternions to Vector3

### ISSUE THREAD

**Issue by ardaozkal** [crosire/scripthookvdotnet#263]
So how can I convert one to Vector3 exactly? It was easy back in Unity.

Title must be quaternions. It burned my brain, sorry.

**Comment by crosire** [comment]
What do you mean? Do you want to convert the rotation represented by a quaternion into euler angles? Because quaternions and vectors are just mathematical structures, nothing you can "convert" without knowing what the data represents.

**Comment by zorg93** [comment]
You can convert quaternions to euler angles with some math

**Comment by crosire** [comment]
```c#
// http://www.euclideanspace.com/maths/geometry/rotations/conversions/quaternionToEuler/index.htm
public Vector3 QuaternionToEulerAngles(Quaternion q) {
	var t = q.X * q.Y + q.Z * q.W;
	if (test > 0.499) {
		return new Vector3(2 * Math.Atan2(q.X, q.W), Math.PI / 2, 0);
	}
	else if (test < -0.499) {
		return new Vector3(-2 * Math.Atan2(q.X, q.W), -Math.PI / 2, 0);
	}
	else {
		return new Vector3(Math.Atan2(2 * q.Y * q.W - 2 * q.X * q.Z, 1 - 2 * q.Y * q.Y - 2 * q.Z * q.Z), Math.Asin(2 * t), Math.Atan2(2 * q.X * q.W - 2 * q.Y * q.Z, 1 - 2 * q.X * q.X - 2 * q.Z * q.Z));
	}
}
```

**Comment by ardaozkal** [comment]
Works perfect! You are awesome!
