### ISSUE TITLE
A quick preview of what I'm currently working on

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#265]
What I am working on is pretty complicated, but I'll try to explain it to you. Basically, I'm trying to create a "manager", which allows you to add "controllers" which could be any type of Entity. Using the Controller, you'll be able to catch events in all types of entities.

I will show you an example:
![037e79a6b385aaa84bfe053cb915af4d](https://cloud.githubusercontent.com/assets/2174104/8906683/caaeb766-3470-11e5-9d62-4c9457b2eeb4.png)

Do you think this will be useful for any of you? 
I will find this useful in many situations where I have to "follow" any type of entity.

**Comment by BenjaminFaal** [comment]
Holy sheet looks good, i need this, however isnt this similar to https://github.com/crosire/scripthookvdotnet/wiki/Code-Snippets#tick-system-by-nacorpio?

**Comment by Nacorpio** [comment]
@BenjaminFaal I will be adding some more utilities, then I'll make sure to release it.
And yes, I made that one too - but that isn't the same thing.

**Comment by JohnnyCrazy** [comment]
While I think it's pretty cool and useful, you may want to consider moving it either to our [Slack-Platform](http://scripthookvdotnet.slack.com) (You can get your invite [here](http://scripthookvdotnet.johnnycrazy.de/)) or the GTAV-Forums.  
IMO the issue page should be used for tracking down bugs and log enhancements (etc.) and I don't have the feeling third-party discussions should be here. ( @crosire ? )

**Comment by Nacorpio** [comment]
No problem. I'll get rid of it.
