### ISSUE TITLE
Player Health problems?

### ISSUE THREAD

**Issue by George0828Zhang** [crosire/scripthookvdotnet#266]
this is what happened:

after I set the player's max health to 500, I then set player's health to 500, but somehow it doesn't work, though the player's max health was increased, the player's health just remained 100(1/5 of the healthbar), has someone help me?

playerPed.MaxHealth = 500;//this works
playerPed.Health = 500;//not working
Function.Call(Hash.SET_ENTITY_HEALTH, playerPed, 500);//not working either

by the way the healthpacks still works fine however.

**Comment by Birdboat** [comment]
Try
```
Function.Call(Hash.SET_ENTITY_HEALTH, playerPed.Handle, 500);
```

**Comment by Nacorpio** [comment]
@Birdboat It's the same thing.

**Comment by Birdboat** [comment]
@Nacorpio Sorry, don't know what I was thinking :P
@George0828Zhang Can you set the Player health before you set the max?

**Comment by George0828Zhang** [comment]
@Birdboat I tried to set it to 500 without setting max value, it won't work.

**Comment by tcpie** [comment]
I ran into a similar issue myself, but was able to resolve it. It seems you need to call SET_PED_MAX_HEALTH instead of the ENTITY version.

When I get git working correctly I'll submit a pull request :).

**Comment by zorg93** [comment]
Is that just for max health, as i cant see a native for set entity health

**Comment by tcpie** [comment]
Yeah, sorry I'll be more specific: use:
SET_PED_MAX_HEALTH
to set the max health.

Then use:
SET_ENTITY_HEALTH
to set the health
