### ISSUE TITLE
.ini file help needed!

### ISSUE THREAD

**Issue by kakaoen404** [crosire/scripthookvdotnet#269]
I need help with creating a .ini file for my script because i don´t know how to do it and i need it for my scripts so if anybody wanna help then please write to me.

**Comment by IncoCode** [comment]
I'm using this method: https://github.com/IncoCode/IniFile/blob/master/IniFile/IniFile.cs

**Comment by Birdboat** [comment]
Here is what some code would look like:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using GTA;
using GTA.Math;
using GTA.Native;

namespace GTAScript
{
    class IniTest : Script
    {
        private ScriptSettings _config;
        private Keys _wkey;
        IniTest()
        {
            // Load the Config on startup
            _config = ScriptSettings.Load(@"scripts\yourscriptinifile.ini");
            // Get the Value from the config as well as its default
            _wkey = _config.GetValue<Keys>("KEYS", "WeatherKey", Keys.NumPad0);
            // Key Function
            KeyUp += (sender, args) =>
            {
                // If its equal to the key they set
                if (args.KeyCode == _wkey)
                {
                    // Make it rain
                    World.Weather = Weather.Raining;
                }
            };
        }
    }
}

```
The 1st argument in the ```GetValue()``` function is the section the key will be in
The 2nd is the name of the key in the ini file
The 3rd will be the default value if it is not set in the ini file

Here is what the ini file looks like:
```
[KEYS]
WeatherKey=NumPad0 // Default: NumPad0
```

You can create multiple sections like this:
```
[KEYS]
YourKey=NumPad1 

[MENU]
DrawKey=NumPad0
```
Hope this helps!

**Comment by kakaoen404** [comment]
Thank you for your help guys i will try your method first @Birdboat  because that looks more clean and easy to understand what is going on.

**Comment by kakaoen404** [comment]
@Birdboat i can´t get it to work in my script for some reason i am pasting screenshots of my code so you can see what´s wrong. 
![image](https://cloud.githubusercontent.com/assets/13606200/9028576/9f43ce1e-397e-11e5-9508-6744f6e2f40b.png)
![image](https://cloud.githubusercontent.com/assets/13606200/9028577/ad7c774c-397e-11e5-8c0c-9350f2c2117a.png)
![image](https://cloud.githubusercontent.com/assets/13606200/9028579/b4b94ce2-397e-11e5-8676-4b3282dcfd6c.png)

**Comment by Birdboat** [comment]
Could you possibly upload the solution?

**Comment by kakaoen404** [comment]
Sure thing here it is: https://gist.github.com/kakaoen404/46b4130c3963fef1febe i really appreciate your help by the way i just wanted to let you know that ;)

**Comment by Birdboat** [comment]
So what was exactly the problem? (Glad to help)

**Comment by kakaoen404** [comment]
I can´t change the key in the .ini file which is located in the same folder as the script it self. When i try to change they from the default key which is PageUp to something like F9 it doesn´t change it to F9 it stays at Pageup

**Comment by Birdboat** [comment]
That's probably because you never 'used' the key, you said "if I press PageUp I'm going to increase my wanted level", when you should say, "if I press (The key I'm getting from the config) I'm going to increase my wanted level"

**Comment by Birdboat** [comment]
I'm working on a copy to explain that.

**Comment by kakaoen404** [comment]
Okay thank you!

**Comment by Birdboat** [comment]
https://gist.github.com/Birdboat/0f638ca9094b716dabed
I added comments for better understanding

**Comment by kakaoen404** [comment]
Okay so basically whenever i add a new feature i have to add that to this:         /// <summary>
        /// The Keys needed for your ini
        /// </summary>
        private Keys _wantedup, _wantedlower, _addmoney, _clearlvl;

and then add a new one of theese:   /// Set the <c>_clearlvl</c> key to what it in the ini
            _clearlvl = _config.GetValue<Keys>("KEYS", "ClearLevel", Keys.NumPad7);
            
Is that how i should understand it? because if it is then that looks to be super easy for me

**Comment by Birdboat** [comment]
Yes for every key you add (lets say ```MenuToggle```)
You must define it with
``` MenuToggle = _config.GetValue<Keys>("YOURMENUGROUP", "MenuToggle", Keys.YOURDEFAULTKEY) ```
Obviously you fill in the group and default key
In other words, Yes, that's how you should understand it.

**Comment by kakaoen404** [comment]
Okay well that seems to be very easy to do if i have any more answers i will ask again. But thank you so much for your help and for your time for almost rewriting the entire script.

**Comment by Birdboat** [comment]
np :+1:

**Comment by kakaoen404** [comment]
i just ran in to a problem and that is that now the script doesn´t work at all i copied your script to get it work properly but now none of my keys works.

**Comment by zorg93** [comment]
@birdboat the issue with your code is the fix for using script settings in the constructor isn't in the latest release, once that gets updated this should work fine

**Comment by Birdboat** [comment]
Sorry, wasn't aware of that

**Comment by kakaoen404** [comment]
So what do i have to do to make this work again? i am kinda confused. @zorg93  do you know how to fix it so it works again or @Birdboat  do you know how to fix it?

**Comment by Birdboat** [comment]
Unfortunately, I don't know of any more ini reading methods, so you could either use @IncoCode 's method, or use a custom library like [this](https://github.com/rickyah/ini-parser) (Which isn't as small as Inco's method, so I'd recommend his).

**Comment by kakaoen404** [comment]
Damn that sucks!! well i guess i might have to use that although i understand nothing of that code and if i can get mulitple keys in there or how it will work with my script as it is right now. @IncoCode Is it possible to explain a bit more in depth if i will be able to use it for my script and how to have more keys when i develop my script more and need more keys?

**Comment by zorg93** [comment]
@Birdboat The issue with ScriptSettings is only if you use this.Settings in the constructor, you can still use scriptsettings.load along with the filepath of the script

**Comment by Birdboat** [comment]
@kakaoen404 Alright, I believe this is the solution, You cannot use ScriptSettings in the constructor yet. So I created a separate function to load it ```Config()```, but that will have to be initialized by a key ```Keys.NumPad0``` (I updated the [gist](https://gist.github.com/Birdboat/0f638ca9094b716dabed))
@zorg93 Thanks for your help! :+1:

**Comment by kakaoen404** [comment]
@zorg93 and @Birdboat you guys are awesome i am gonna try this when i wake up and then report back. One question though the ini file is still the same setup as you showed initially right?

**Comment by kakaoen404** [comment]
@Birdboat So a keyevent to load the config when i want to use it? i still can´t get it to work with the .ini yet though so something is either missing or my ini is not set up correctly.

**Comment by Birdboat** [comment]
Here's the problem, you cannot use ```ScriptSettings.Load()``` in the constructor, So if you bind a key to load all the other keys, that should work.
```
private void OnKeyUp(object sender, KeyEventArgs e)
            {
            /// If our code is equal to NumPad0
            if (e.KeyCode == Keys.NumPad0)
            {
                /// Load our config
                Config();
            }
            
            /// If our code is equal to the key to raise our wanted level
            if (e.KeyCode == _wantedup)
            {
                /// Raise our level
                _pl.WantedLevel++;
                UI.ShowSubtitle("Raised Wanted level");
            }

            /// If our code is equal to the key to lower our wanted level
            if (e.KeyCode == _wantedlower)
            {
                /// Lower our level
                _pl.WantedLevel--;
                UI.ShowSubtitle("Lowed Wanted Level");
            }

            /// If our code is equal to the key to add money
            if (e.KeyCode == _addmoney)
            {
                /// Add money
                _pl.Money += 100000;
                UI.ShowSubtitle("Money added");
            }

            /// If our code is equal to the key to clear our wanted level
            if (e.KeyCode == _clearlvl)
            {
                /// Clear wanted level
                Function.Call(Hash.CLEAR_PLAYER_WANTED_LEVEL, Game.Player.Handle);
                UI.ShowSubtitle("Wanted Level Cleared");
            }
        }
```
Config:
```
private void Config()
        {
            /// Load the ini file
            _config = ScriptSettings.Load(@"scrips\yourinifile.ini");

            /// Set the <c>_wantedup</c> key to what it in the ini
            _wantedup = _config.GetValue<Keys>("KEYS", "WantedLevelUp", Keys.PageUp);

            /// Set the <c>_wantedlower</c> key to what it in the ini
            _wantedlower = _config.GetValue<Keys>("KEYS", "WantedLevelLower", Keys.PageDown);

            /// Set the <c>_addmoney</c> key to what it in the ini
            _addmoney = _config.GetValue<Keys>("KEYS", "AddMoney", Keys.NumPad4);

            /// Set the <c>_clearlvl</c> key to what it in the ini
            _clearlvl = _config.GetValue<Keys>("KEYS", "ClearLevel", Keys.NumPad7);

        }
```
Ini:
The same you had before,
```
[KEYS]
WantedLevelUp=PageUp
WantedLevelLower=PageDown
AddMoney=NumPad4
ClearLevel=NumPad7
```

Sorry for such a tedious process.

**Comment by IncoCode** [comment]
@kakaoen404 
1. Download the [latest release](https://github.com/IncoCode/IniFile/releases/tag/1.0.1-Build-8);
2. Add reference to `Ini.dll` (or you can just take [`Ini.cs`](https://github.com/IncoCode/IniFile/blob/master/IniFile/IniFile.cs) from source and add it directly in your project, then you don't need an dll);
2. Usage:
```c#
using Ini;
...
private readonly IniFile _settings;
...
public YouConstructor()
{
  // load settings
  this._settings = new IniFile( "scripts\\YourAwesomeMod.ini" );
}
...
// somewhere in your script

// read (default value can be of the following type: string, int, bool, double)
int myDefaultInt = 4;
int myVar = this._settings.Read( "Key", "Section", myDefaultInt );
string myStr = this._settings.Read( "MyKey", "Section2", "defaultSrting" );

// write
this._settings.Write( "Key", 5, "Section" );
this._settings.Write( "Key", "str", "Section2" );
```

**Comment by JohnnyCrazy** [comment]
Is this resolved @kakaoen404  ?

**Comment by kakaoen404** [comment]
@JohnnyCrazy  no not yet i just haven´t been very active recently that´s why but i will start on working on asking new stuff in this post shortly i just have to do something first.

**Comment by RainerHilmer** [comment]
I may say I see an error that most modders do. Don't just query the keycode! You should also query whether Alt, Ctrl and/or Shift is pressed, even though you want the user to just press a single key. The reason why this is important and a solution is described here.
http://gtaforums.com/topic/823869-how-to-filter-a-key-press-the-right-way-c/
