### ISSUE TITLE
Ped.Task.GoTo spawns ped at 0,0,0 coords.

### ISSUE THREAD

**Issue by aleksandarzivanovic** [crosire/scripthookvdotnet#271]
Using Ped.Task.GoTo causes ped to spawn in middle of ls even though spawn location is in desert.

**Comment by zydevs** [comment]
Ped.Task.GoTo is for having the ped walk / drive to a location.

Use Ped.Position = Vector3Coords;

**Comment by RainerHilmer** [comment]
Ped.Task.GoTo works great in my VAutodrive mod and btw 0,0,0 is in Vinewood west near Michael's garage and even below ground. The elevation is at 71 units there.

**Comment by JohnnyCrazy** [comment]
Seems like this is not a bug, else just report back @aleksandarzivanovic :)
