### ISSUE TITLE
How to get the script running in the online mode?

### ISSUE THREAD

**Issue by JannyMon** [crosire/scripthookvdotnet#272]
As we know, the script example "NativeTrainer.asi" provided by Alexander Blade (the author of Script Hook V) can not run in the online mode. I'd like to if I use the GTALua engine; then can the script run in the online mode? Or how can I get the script to work in the online mode? I don't know the method. Can you share some?Need some specific methods.

**Comment by IncoCode** [comment]
Nope :rage:

**Comment by zydevs** [comment]
Solution:

Don't mod online.

**Comment by zorg93** [comment]
To get it online use this http://fivem.net

**Comment by JohnnyCrazy** [comment]
We don't support multiplayer molding, so no answer here
