### ISSUE TITLE
World.AddRope not working

### ISSUE THREAD

**Issue by zydevs** [crosire/scripthookvdotnet#273]
Rope TestRope = World.AddRope(RopeType.Normal, Game.Player.Character.GetOffsetInWorldCoords(new Vector3(0, 5, 5)), Vector3.Zero, 20.0f, 1.0f, false); Crashes the game.
It should work, but doesnt and has worked in previous versions of SHV.NET
Anyone have a solution?

**Comment by crosire** [comment]
This was fixed in d15cc09a77dce20e643f28ff653bde187f509991.
