### ISSUE TITLE
Blip.Remove not working

### ISSUE THREAD

**Issue by marhex** [crosire/scripthookvdotnet#274]
whay my code is not working

for (int i = 0; i < players.Length; i++)
            {
                if (players[i].IsDead)
                {
                    if(players[i].CurrentBlip.Exists())
                         players[i].CurrentBlip.Remove();
                }
            }

**Comment by tjhorner** [comment]
Can you give all of the code so we have some context?

**Comment by marhex** [comment]
public class team_group
{

    public Ped[] players;


    public team_group()
    {
        players = new Ped[20];
    }


    public team_group(int num)
    {
        players = new Ped[num];
    }


    public void initial(Model mod, Vector3[] pos, int groupe)
    {
        for(int i = 0;i<this.players.Length;i++)
        {
            players[i] = World.CreatePed(mod, pos[i]);
            Function.Call(Hash.SET_ENTITY_AS_MISSION_ENTITY, players[i], true, true);
            players[i].RelationshipGroup = groupe;
        }
    }

    public void initial(Model mod, Vector3 pos,int groupe)
    {
        for (int i = 0; i < this.players.Length; i++)
        {
            players[i] = World.CreatePed(mod, pos.Around(7f));
            Function.Call(Hash.SET_ENTITY_AS_MISSION_ENTITY, players[i], true, true);
            players[i].RelationshipGroup = groupe;
        }


    }
    public void update()
    {
        for (int i = 0; i < players.Length; i++)
        {
            if (players[i].IsDead)
            {
                if (players[i].CurrentBlip.Exists())
                    players[i].CurrentBlip.Remove();
            }
        }
    }
}

**Comment by zydevs** [comment]
Blip.Remove(); doesnt work as of now, there's a few solutions on gtaforums if you want to look there :)

**Comment by tjhorner** [comment]
I can possibly submit a PR that fixes this, seems simple enough.

**Comment by Guad** [comment]
If CurrentBlip is null, calling Exists on it will cause a System.NullReferenceException. This works perfectly for me.
```
foreach (Pedmate in _mates.Where(mate => mate.IsDead))
{
     mate.CurrentBlip?.Remove();
}
```
