### ISSUE TITLE
World.GetAllProps() doesn't work

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#277]
As the title suggests, the World.GetAllProps() method doesn't work. For example, when I'm around a lot of props, it only returns about two out of them. There's obviously something wrong.

**Comment by zorg93** [comment]
This has been known for a long time(ever since the feature got added) The method actually only returns Props in the script pool, not the game object pool. A fix will arrive once alexander updates scripthookv. You may aswell close this issue

**Comment by Nacorpio** [comment]
What is the point of having the method if it doesn't do what it says?

**Comment by zorg93** [comment]
Wasnt fully tested when it was first made, and considering its going to get fixed, there is no point removing it now. the issue also exists with World.GetAllPeds, GetAllVehicles and GetAllEntities

**Comment by Nacorpio** [comment]
It's kind of bad, because I had planned to use the feature in a mod, and now it doesn't work properly. It's just a little bit frustrating.

**Comment by zorg93** [comment]
This has been fixed, just waiting for the sdk to be updated on here before pushing it

**Comment by JohnnyCrazy** [comment]
pinging @crosire :)

**Comment by crosire** [comment]
Updated in 7641591955012e3b5f10023e2521f2ad513d8761.

**Comment by crosire** [comment]
Should be fixed in abcc5c3ca10c4eee9bc17a97d32aa408788cec95.

**Comment by Nacorpio** [comment]
How come I only get the player, and not rest of all the entities in the world?

**Comment by zorg93** [comment]
This has been fixed
