### ISSUE TITLE
0 scripts

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#282]
I was testing a menu I'm working on, and suddenly when I had built a new .dll, the scripts folder was moved into a new folder inside the root folder in GTA called "update". I tried moving the scripts folder back to the root folder, but then it said "a file with this name already exists inside the target folder", and I saw that there was a new file called "scripts". When I opened it, there was just random text, so I decided to delete it. I could now move the "scripts" folder back to its original spot. But now when I'm reloading the scripts, it says that it can't find any scripts within my .dll files. What the fuck is happening?

**Comment by zorg93** [comment]
check your project settings in the post build events, it may be trying to copy your script to gta directory, but messing it up

**Comment by JohnnyCrazy** [comment]
Updates @Nacorpio ?

**Comment by Nacorpio** [comment]
I fixed it. I don't know how, but I did.
