### ISSUE TITLE
World.GetNearbyPeds() not working

### ISSUE THREAD

**Issue by marhex** [crosire/scripthookvdotnet#284]
when i use this

for (int j = 0; j < place.Length; j++)
{

   Ped[] peds = World.GetNearbyPeds(place[j], 150f);
   for (int i = 0; i < peds.Length;i++ )
     {
        Allpeds.Add(peds[i]);
     }

}

where place is an array of vector3
and Allpeds is a list<Ped>

and when i test it dosn't return all ped in the area

**Comment by zorg93** [comment]
https://github.com/crosire/scripthookvdotnet/issues/277

**Comment by marhex** [comment]
i know that World.GetAllPeds() don't return all peds
but when i use
Ped[] peds = World.GetNearbyPeds(game.player.character, 150f); it return all peds in the area
but Ped[] peds = World.GetNearbyPeds(new vector3(X,Y,Z), 150f); it don't return all peds in the area

**Comment by zorg93** [comment]
Yeah, but GetNearbyPeds(Position, distance) uses the same thing GetAllPeds uses. anyway once AB updates scripthookv This will get fixed, nothing can happen about it before then

**Comment by JohnnyCrazy** [comment]
Handled in #277 , closing
