### ISSUE TITLE
Has this project died?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#290]
I look at the commit statistics every day and it looks like not much is happening anymore. Is everybody on vacation or what else is the reason? I'm just asking because I start to worry.

**Comment by zorg93** [comment]
It's quietened down

**Comment by crosire** [comment]
The current version is pretty solid and I have some other projects to attend to, I still check here daily though. I'll probably do some code cleanup and refractoring in the near future though.

**Comment by JohnnyCrazy** [comment]
Same goes for me, other projects I need to take care of currently, although I would like to get some stuff done within next month
