### ISSUE TITLE
Windows 10 incompatibility

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#296]
A lot of users are complaining about not being able to run ths especially people who have upgraded to windows 10. Im presuming the issue is with .net framework or some other windows core feature

**Comment by JohnnyCrazy** [comment]
We got any errors?

**Comment by crosire** [comment]
I hope a5f37540ff04e897c6daf182fba5ec0af0acb2f2 fixes this by changing to the more recent .NET v4.5.2.
But even before that, I upgraded my testing computer to Windows 10 and was able to run GTAV + ScriptHook .NET just fine, without doing anything special.

**Comment by zorg93** [comment]
Heres hoping it fixes it, but if the issue isnt that it will be pretty hard to dig it out

**Comment by crosire** [comment]
Could somebody on Windows 10 who cannot run version 1.1 check if it works with [this](https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/Build%20No.%20428/artifacts)?

**Comment by RainerHilmer** [comment]
I have no such issues whatsoever but maybe that's also (like crosire) because I run a development machine with all .net and C++ versions.

**Comment by alex8b** [comment]
I will ask to try this version on a win10 pc which had this problem tomorrow

**Comment by alex8b** [comment]
They tested and this build works fine.

**Comment by crosire** [comment]
Great!

**Comment by sinand99** [comment]
Crashing the game with NativeUI in Windows 10:  https://github.com/Guad/NativeUI/issues/13
I don't know if this is caused by NativeUI or scripthookvdotnet. Only happens when I try to show the menu.  There was no problem when i was using old menu system.

**Comment by zorg93** [comment]
NativeUI is working fine for me in Windows 10

**Comment by RainerHilmer** [comment]
Okay new situation. Complaints of Windows 10 users keep rolling in on my mod page. It affects user who only have .net 4.6 installed. An installation of a previous version is denied by the system ("there is already a newer version installed").
My suggestion: Update scriphookvdotnet to refer .net 4.6

**Comment by crosire** [comment]
4.6 includes 4.5, so nothing to worry there. They just need to install the Visual C++ 2015 redistributable for everything to work fine.

**Comment by crosire** [comment]
I'm starting to think we should statically link against the C++ runtime libraries, so the redistributable package is not required. This is not recommended and it could cause issues, because then multiple runtime versions are used at the same time in the GTA process (which doesn't use 2015, but an older version), but it would solve people having trouble using this mod, because they don't install the listed requirements.

**Comment by RainerHilmer** [comment]
Thanks I will tell them to use the Visual C++ 2015 redistributable.
