### ISSUE TITLE
Add set operator to "Vehicle" for CurrentRPM

### ISSUE THREAD

**Issue by Kryo4lex** [crosire/scripthookvdotnet#298]
Would be great if a set operator for the RPM of a vehicle could be implemented, because then we could easily control vehicle speeds.

**Comment by RainerHilmer** [comment]
Just use Task.DriveTo with the speed you want. You can take a look into the code of my VAutodrive mod here:
https://bitbucket.org/CyronsTeam/vautodrive/src
Mod download here:
https://www.gta5-mods.com/scripts/vautodrive

**Comment by zorg93** [comment]
Its alot deeper than that I'm afraid I tried adding a setter based of the current rpm getter, but it didnt force the car to accelerate etc

**Comment by JohnnyCrazy** [comment]
Since this seems to be impossible to add (if @zorg93 says it's hard to accomplish, then propably it's impossible :stuck_out_tongue_winking_eye: ), I will close this.

**Comment by zorg93** [comment]
If I put my mind to it I could find out what needs to be set, however I have a feeling its not RPM that needs to be set, instead its accelerator pressure(what happens when you hold W)
