### ISSUE TITLE
Script::Wait()

### ISSUE THREAD

**Issue by crosire** [crosire/scripthookvdotnet#30]
It would be useful if the Script.Wait function didn't pause the entire Script Hook, but instead would allow other scripts to continue running.

GTAIV Script Hook started each script in a separate thread. It still went through them sequentially, but if one script was currently waiting it would simply skip it. The problem is that natives have to be called in the main script thread where Script Hook is running, which is why that attempt isn't a very good solution in my opinion (it had to gather all native calls first and then invoke them back in the main thread again).

**Comment by screeny05** [comment]
Have a look at [this Post of AB](http://gtaforums.com/topic/717612-v-scriptnative-documentation-and-research/page-2#entry1065742778). Also changing the Scripthook .NET to work like this makes it easier to introduce breaking changes to the API without breaking older Scripts.

**Comment by crosire** [comment]
While this certainly has advantages I'm not sure if it's really the best way to go. It could be confusing to users that are used to the way the GTAIV .NET scripthook installation worked.

**Comment by Nacorpio** [comment]
How about adding two different wait() methods?

**Comment by crosire** [comment]
How does that help?

**Comment by TORISOUP** [comment]
I made coroutine system like Unity3d.It is green threads.
https://github.com/TORISOUP/GTAV_InfernoScripts/blob/master/Inferno/InfernoScripts/InfernoCore/CoroutineSystem.cs
CoroutineLoop() is called every 100ms.

How do you like this approach?

```csharp
//
IEnumerable<Object>  DelayPedKill(Ped ped)
{
    // wait for 5 seconds.
    yield return WaitForSeconds(5.0f);
    ped.Kill();
}
```

```csharp
StartCoroutine(DelayPedKill(Game.Player.Character));
```

**Comment by crosire** [comment]
I really like that approach, but I think it's too confusing to people new to the language. It would be interesting to have this as an additional feature though.
