### ISSUE TITLE
Roslyn

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#301]
I know not much can be done about adding support for Roslyn (Its not part of .NET Framework) however It should be stated to avoid confusion of making cs/vb files that use features added in Roslyn but not CSharpCompiler and VisualBasicCompiler found currently in .NET

**Comment by Megasware128** [comment]
Adding support for Roslyn is pretty easy. My fork of this scripthook (still 1.0) uses the Roslyn compiler for the cs/vb files. But it requires you to distribute the extra libraries with the package

**Comment by Megasware128** [comment]
I think  you can also use ILMerge if you really want one binary file

**Comment by JohnnyCrazy** [comment]
The better question is how many people would actually use it and if it's worth the change.
IMHO roslyn features useful stuff, but it's not worth the extra trouble with the libraries.

**Comment by Megasware128** [comment]
It is also possible to dynamically load the library in runtime and check if the library exist and if not use the old system and make it optional for the user to download the Roslyn library. And also I believe the people who really want the features can do it themselves (or just compile a dll).

**Comment by zorg93** [comment]
Given how big the libraries are for Roslyn compilers I dont think its a good idea to include them inside the dll

**Comment by Megasware128** [comment]
The whole package would be 12,6 MB so that is like 10 MB more. Not really that huge. But the package contains one extra dll for interop between CodeDOM and the Roslyn compiler and a folder with the Roslyn compiler stack. It is pretty lightweight if you would compare it with the old C# compiler or the VC compiler

**Comment by RainerHilmer** [comment]
I changed to VS2015 recently and I changed part of the code of my mods to C#6 already. I haven't read into Roslyn yet. So my question is: Does this code also run without Roslyn?

**Comment by zorg93** [comment]
If you compile in visual studio with Roslyn it will be fine, the issue is using raw cs or vb files in the scripts directory

**Comment by RainerHilmer** [comment]
Ah okay thanks. :)

**Comment by JohnnyCrazy** [comment]
Any last thoughts on this @crosire ? It does not seem to be worth the effort IMHO.

**Comment by crosire** [comment]
Yeah. Roslyn can be used when compiling to a .NET assembly instead of using open script files, so there it isn't worth the effort in my opinion too.
