### ISSUE TITLE
Latest Push does not load

### ISSUE THREAD

**Issue by bilago** [crosire/scripthookvdotnet#302]
I grabbed the latest push from Appveyor (https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/artifacts) and I get this on Win 7 and Win 10, both having 4.5.2 installed:

// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\WINDOWS\system32\dinput8.dll" => 00007FFE5ACA0000
API: "DirectInput8Create" => 00007FFE5ACAA570
API: "DllCanUnloadNow" => 00007FFE5ACB9ED0
API: "DllGetClassObject" => 00007FFE5ACB9FA0
API: "DllRegisterServer" => 00007FFE5ACC3C50
API: "DllUnregisterServer" => 00007FFE5ACC3EF0
LOADER: Loading *.asi plugins
ASI: Loading "A:\GTAV\ScriptHookVDotNet.asi"
     "ScriptHookVDotNet.asi" failed to load
LOADER: Finished loading *.asi plugins

**Comment by zorg93** [comment]
Is that directory a copy of where GTA was installed or the actual directory it was installed in

**Comment by bilago** [comment]
A:\GTAV\ is my Actual GTA Installation. Verified same issue with another user in their Actual installation directory.

**Comment by crosire** [comment]
Make sure you have the Visual C++ redistributable installed (2013 or 2015, I don't know which compiler version AppVeyor uses).

**Comment by zorg93** [comment]
should probably add that to the requirements part of the readme if thats the issue

**Comment by crosire** [comment]
Done in 5e93770d8aa6ccca4a60b1623137910440496007.
