### ISSUE TITLE
So what external alternatives to the obsolete menu class are there?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#305]
I have just downloaded V2.0 and to my surprise I found the Menu class is obsolete now. You can imagine my frustration as I have to rewrite the whole menu handling now. Why did you do this? The menu class worked well for me.
So what alternatives are there?

**Comment by IncoCode** [comment]
[NativeUI](https://github.com/Guad/NativeUI)

**Comment by JohnnyCrazy** [comment]
This decision was made in #260 .
While our UI was working, by this time there are better libraries out there which have more features and also look better(https://github.com/Guad/NativeUI e.g completely mocks Rockstars NativeUI)

Quote from crosire:
>This is a drastic step, but it cleans up the code and there are better alternatives as mentioned.

**Comment by RainerHilmer** [comment]
Thanks anyway. :-/
