### ISSUE TITLE
whay my code is not working

### ISSUE THREAD

**Issue by marhex** [crosire/scripthookvdotnet#306]
if (e.KeyCode == Keys.F6)
            {
                Ped[] tr = World.GetNearbyPeds(Game.Player.Character, 150f);
                 UI.ShowSubtitle(" " + tr.Length);
            }

it always show 0 
and if thear is a workground please give it to me
i use version 2.0.0

**Comment by crosire** [comment]
Make sure you have the latest C++ Script Hook.

**Comment by marhex** [comment]
yes i have it

**Comment by zorg93** [comment]
Do you have the latest c++ ScriptHook and the latest ScriptHookVDotNet, I just tried that exact code and it worked perfectly. in a busy area of town it printed 74

**Comment by marhex** [comment]
thenks it work now
