### ISSUE TITLE
Holding a key down causes the KeyDown method to be called constantly

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#307]

**Comment by crosire** [comment]
That's normal behaviour on Windows. It's called once on the first press and after a short period of time repeatingly again, until the key is released (also known as [autorepeat](https://msdn.microsoft.com/library/windows/desktop/ms646280(v=vs.85).aspx)).

**Comment by zorg93** [comment]
Ahh didn't know that
