### ISSUE TITLE
CurrentRPM not working

### ISSUE THREAD

**Issue by timower** [crosire/scripthookvdotnet#308]
The current RPM of a vehicle just changes between 0 and 1 depending if the acceleration key is pressed.

**Comment by zorg93** [comment]
What came version are you using

**Comment by timower** [comment]
VER_1_0_350_1_STEAM

**Comment by zorg93** [comment]
Update your game if you want to use it. The address for rpm changed after the release of 350

**Comment by timower** [comment]
ok, thanks. Maybe I can help to built in a version check in the function?

**Comment by IncoCode** [comment]
It's relative value, it should be between 0 and 1.

**Comment by zorg93** [comment]
What it's returning is the control value for vehicle accelerate for the car.  The reason it's 0-1 is its a digital switch (w can be pressed or not pressed) results using a game pad will be from 0-1. Actual rpm for a car with its engine on range from 0.2-1.0.
I don't know the address for the 350 version of the game and i can't test it either as i don't have that version of the game

**Comment by timower** [comment]
the offset for version 305 is 1988. In case you need it.

**Comment by zorg93** [comment]
There are many offsets that store rpm. Think i counted 9 for one vehicle
