### ISSUE TITLE
ArgumentOutOfRangeException at World.GetCurrentDate

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#310]
I don't know if this was introduced with V2.0 or 2.1 but ever since one of my mods constantly crashes because of this (worked flawlessly before).

```
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ArgumentOutOfRangeException: Die Parameter "Year", "Month", und "Day" beschreiben eine nicht darstellbare DateTime.
   bei System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   bei System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond)
   bei System.Globalization.GregorianCalendar.ToDateTime(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond, Int32 era)
   bei System.Globalization.Calendar.ToDateTime(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond)
   bei System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Calendar calendar)
   bei GTA.World.get_CurrentDate()
   bei VPTS.JobElements.GetActualLocations()
   bei VPTS.JobElements.CreateJobIfDue()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei VPTS.StateBroker.RunJob(ServiceState state)
   bei VPTS.Core.OnTick(Object sender, EventArgs e)
   bei GTA.Script.raise_Tick(Object value0, EventArgs value1)
   bei GTA.Script.MainLoop()
```

**Comment by crosire** [comment]
Could you post for which numbers this is the case. This should have been fixed.

**Comment by crosire** [comment]
Looks like my fix by adding a custom calender implementation [doesn't solve the problem](http://stackoverflow.com/a/17963762/2055880). That means we need to handle values that are not representable in the gregorian calender separately somehow.

**Comment by RainerHilmer** [comment]
I'm going to make a spike right away and report back.

**Comment by RainerHilmer** [comment]
What I realized at first is that World.CurrentDate.DayOfWeek is always one day behind the actual weekday (i.e claims its saturday when it's sunday) when I change the weekdays with the snt.
Oddly enough those crasshes only occure right after the game has loaded. Switching daytimes and weekdays with snt do not lead to further crashes.
Because of that, the following tests have been set up this way: Set a specific weekday and a specific daytime, save the game, load the game.
1. Test (Tuesday, 8am): World.CurrentDate.DayOfWeek and World.CurrentDate.TimeOfDay crashed but not World.CurrentDayTime and the crash also occurs only right after the game has loaded.
Changing the time back and forth with snt does not lead to anther crash. DayOfWeek claims it's saturday.
2. Test (Monday, 8am): No crash but DayOfWeek claims it's saturday.
3. Test (Tuesday, 3pm): No crash but DayOfWeek claims it's saturday.
4. Test (Tuesday, 1am): No crash but DayOfWeek claims it's saturday.
5. Test (same as 2. Test!): No crash
So it seems the crash does only occur on first game start.
Here is the code I used:
´´´
using System;
using System.Windows.Forms;
using Cyron43.GtaV.Common;
using GTA;

namespace VDynamicSpikes
{
   public class DynamicSpike : Script
   {
      public DynamicSpike()
      {
         UI.Notify("Spike is running.");
         Interval = 1000;
         Tick += (sender, args) => DisplayCurrentDayAndTime();
      }   

      private void DisplayCurrentDayAndTime()
      {
         //UI.Notify("DoTest called.");
         var weekDay = DayOfWeek.Sunday;
         var time = new TimeSpan();
         var x = new TimeSpan();
         bool noException = true;
         try
         {
            weekDay = World.CurrentDate.DayOfWeek;
         }
         catch(ArgumentOutOfRangeException)
         {
            noException = false;
            UI.Notify("~r~World.CurrentDate.DayOfWeek crashed.~w~");
         }
         try
         {
            time = World.CurrentDate.TimeOfDay;
         }
         catch(ArgumentOutOfRangeException)
         {
            noException = false;
            UI.Notify("~r~World.CurrentDate.TimeOfDay crashed.~w~");
         }
         try
         {
            x = World.CurrentDayTime;
         }
         catch(ArgumentOutOfRangeException)
         {
            noException = false;
            UI.Notify("~r~World.CurrentDayTime crashed.~w~");
         }
         if(noException)
            UI.ShowSubtitle("Today is " + weekDay + ", " + x + " || " +
                            time);
      }
   }
}
´´´

**Comment by crosire** [comment]
Interesting. Could you check if GTA reports the correct values with these?
```c#
int year = Native::Function::Call<int>(Native::Hash::GET_CLOCK_YEAR);
int month = Native::Function::Call<int>(Native::Hash::GET_CLOCK_MONTH);
int day = Native::Function::Call<int>(Native::Hash::GET_CLOCK_DAY_OF_MONTH);
int hour = Native::Function::Call<int>(Native::Hash::GET_CLOCK_HOURS);
int minute = Native::Function::Call<int>(Native::Hash::GET_CLOCK_MINUTES);
int second = Native::Function::Call<int>(Native::Hash::GET_CLOCK_SECONDS);
```

**Comment by RainerHilmer** [comment]
Will do.

**Comment by RainerHilmer** [comment]
I added
```
int weekDay = Function.Call<int>(Hash.GET_CLOCK_DAY_OF_WEEK);
```
to this. The week starts at Sunday with 0 and increments as expected.
All other values also return as expected. Everything seems to be fine with these.
However, I don't know if the 16th of January 1970 is correct but I wouldn't mind the date.

**Comment by JohnnyCrazy** [comment]
So how we want to handle this one? Should we try to get `DateTime`-parsing working or should we go back and just make a small wrapper around the values? @crosire

**Comment by crosire** [comment]
Doesn't look like ```DateTime```-parsing can be made working. So it looks like we have to provide our own struct around those values. Or allow retrieving them separatly, like ```World.CurrentDayOfWeek``` etc., but I doubt that's a better solution.

**Comment by RainerHilmer** [comment]
Maybe I can help you out on this. The following code is part of my VCommonFunctions framework and I use it for a long time already w/o ever having any crashes. However, it's in C#.
`using System;
using GTA.Native;

namespace Cyron43.GtaV.Common
{
   /// <summary>
   /// Provides actual elements of the GTA V in-game clock.
   /// </summary>
   // ReSharper disable once InconsistentNaming
   public struct DateTime
   {
      /// <summary>
      /// Gets the current time of day.
      /// </summary>
      /// <value>
      /// The current time of day.
      /// </value>
      public static TimeSpan CurrentDayTime
      {
         get
         {
            var instance = Now;
            return new TimeSpan(instance.Hour, instance.Minute, instance.Second);
         }
      }

      /// <summary>
      /// Gets the actual hour of the in-game clock.
      /// </summary>
      /// <value>
      /// The hour.
      /// </value>
      public int Hour => Function.Call<int>(Hash.GET_CLOCK_HOURS);

      /// <summary>
      /// Gets the actual minute of the in-game clock.
      /// </summary>
      /// <value>
      /// The minute.
      /// </value>
      public int Minute => Function.Call<int>(Hash.GET_CLOCK_MINUTES);

      /// <summary>
      /// Gets the actual DateTime object.
      /// </summary>
      public static DateTime Now => new DateTime();
      
      /// <summary>
      /// Gets the actual hour of the in-game clock.
      /// </summary>
      /// <value>
      /// The second.
      /// </value>
      public int Second => Function.Call<int>(Hash.GET_CLOCK_SECONDS);
      
      /// <summary>
      /// Gets the actual weekday of the in-game clock. The week starts sundays with 0.
      /// </summary>
      /// <value>
      /// The weekday.
      /// </value>
      public DayOfWeek Weekday => (DayOfWeek)Function.Call<int>(Hash.GET_CLOCK_DAY_OF_WEEK);
   }
}`

**Comment by kagikn** [comment]
`World.CurrentDate` still throws exceptions certain cases, so we could make `World.CurrentDate` clamp the day to a valid value as a workaround for the game using 31 days in all months. It's a temporary workaround though.
