### ISSUE TITLE
It does not work only in GetNearbyPeds and GetNearbyVehicles in Mission?

### ISSUE THREAD

**Issue by meronmks** [crosire/scripthookvdotnet#311]
```
var player = Game.Player;
var ped = player?.Character;
var char = World.GetNearbyPeds(ped, 500.0f);
```
This code is not work.
Anyone have a solution?

**Comment by zorg93** [comment]
char is a reserved key word, use this instead
 var nearbypeds = World.GetNearbyPeds(ped, 500.0f);

**Comment by meronmks** [comment]
I tried to change, but it does not work.

**Comment by zorg93** [comment]
are you compiling this in visual studio or leaving it as a cs file?

**Comment by meronmks** [comment]
There are still.

**Comment by zorg93** [comment]
what?

**Comment by meronmks** [comment]
Yes, I have compiled with visual studio.

**Comment by zorg93** [comment]
then it should work fine. whats the issue you're getting

**Comment by crosire** [comment]
Please be more specific. "It does not work" is not very helpful =).

**Comment by meronmks** [comment]
Updating "ScriptHook" as v1.0.393.4a made that working.
