### ISSUE TITLE
Can't go to prison

### ISSUE THREAD

**Issue by JonezK** [crosire/scripthookvdotnet#320]
When i try to get arrested they just shoot at me, and when i have 2 or more stars after me i press F12, and it doesn't work... What could i have done wrong?

I have installed:
Scripthook V
Scripthook V NET
MS Visual C++ x64
Prison Mod (latest)

**Comment by letsplayordy** [comment]
You should contact the author. This is not an issue with ScriptHookV .NET, but with the prison mod.

**Comment by JonezK** [comment]
Okay, thanks.

**Comment by JohnnyCrazy** [comment]
Like @letsplayordy said, best way to get support would be contacting the mod author :+1:
