### ISSUE TITLE
How to abort a native task?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#321]
Hi there, I am using this native in my mod, it works but I can't abort it. Is there any way to abort a native task?
From the natives DB:
void TASK_PLANE_LAND(Ped pilot, Vehicle plane, float runwayStartX,
  float runwayStartY, float runwayStartZ, float runwayEndX,
  float runwayEndY, float runwayEndZ)
// 0xBF19721FA34D32C0

```C#
      private void LandAirplane()
      {
         var runway =
            DrivingData.GetClosestRunway(DrivingData.Vehicle.Position);
         if(runway.Airport == "")
         {
            UI.ShowSubtitle("No runway found.");
            return;
         }
         UI.ShowSubtitle($"Landing at {runway.Airport}, Rwy{runway.Rwy}");
         Function.Call(Hash.TASK_PLANE_LAND,
            DrivingData.Driver,
            DrivingData.Vehicle,
            runway.RwyStart.X, runway.RwyStart.Y, runway.RwyStart.Z,
            runway.RwyEnd.X, runway.RwyEnd.Y, runway.RwyEnd.Z);
         while(!DrivingData.Vehicle.IsOnAllWheels && AutodriveRequested)
            Wait(100);
      }
```
Usually the AutodriveRequested flag gets set to false if the user presses the ToggleAutodrive key again but it doesn't help here. It's as if everything is blocked as long as the task is running (KeyUp event is not recognized during the task).

**Comment by LibertyLocked** [comment]
AI::CLEAR_PED_TASKS maybe?
http://www.dev-c.com/nativedb/func/info/e1ef3c1216aff2cd

**Comment by RainerHilmer** [comment]
Thank you @LibertyLocked. However my problem is that the KeyUp event isn't recognized anymore while this loop runs and because of that AutodriveRequested keeps being true. I have to research why this happens.

**Comment by RainerHilmer** [comment]
Nevermind, I resolved it now with event based mediators.
