### ISSUE TITLE
Checkpoints Issue :@

### ISSUE THREAD

**Issue by testiclelo0ver** [crosire/scripthookvdotnet#322]
int finishCheckpoint;
finishCheckpoint = Function.Call<int>(Hash.CREATE_CHECKPOINT, 24, finishCoords[0], finishCoords[1], finishCoords[2], finishCoords[0], finishCoords[1], finishCoords[2], 10, 254, 207, 12, 100, 0);

Function.Call(Hash._SET_CHECKPOINT_ICON_RGBA, finishCheckpoint, 0, 255, 255, 255);

^this, why does this not work?

**Comment by rushlink** [comment]
I believe it is because you are setting your alpha channel (RGB*A*) to 255, which is 100% transparent.
