### ISSUE TITLE
Game crashes when I make car disappear and have the speed set at the same time

### ISSUE THREAD

**Issue by AAYapps** [crosire/scripthookvdotnet#326]
I have been trying to get the game to stop crashing but when I put 

car.speed = 48;
car.IsVisible = false;

and when

car.speed = 48;
car.IsVisible = false;

the game crashes

Does anyone know how to fix this?

**Comment by AAYapps** [comment]
The second one was supposed to be 

car.speed = 48;
car.IsVisible = true;

**Comment by letsplayordy** [comment]
.speed should be capitalized.

**Comment by AAYapps** [comment]
speed is capitalized. th at is not the problem

**Comment by JohnnyCrazy** [comment]
Coud you pls attach/post your error logs? (ScriptHookVDotNet and ScriptHook)

**Comment by AAYapps** [comment]
I don't see the log

It did not make the log file

**Comment by zorg93** [comment]
Does the game crash when that code is removed?

**Comment by AAYapps** [comment]
no, it does not crash

**Comment by crosire** [comment]
Closing for now because does not seem to be reproducible. Please report back If the problem persists.
