### ISSUE TITLE
Please extend the VehicleSeat enum

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#327]
There are several vehicles with more than 3 passenger seats, like the stretch limo (5), bus(15!), insurgent with turret (8), Buckingham Luxor Deluxe (7) and the Vinewood tours bus (9).

**Comment by JohnnyCrazy** [comment]
You can always cast the specific number to `VehicleSeat`:
````csharp
Game.Player.Character.SetIntoVehicle(veh, (VehicleSeat)3);
````

But I guess there is nothing wrong with extending it.
