### ISSUE TITLE
Add Euphoria Class

### ISSUE THREAD

**Issue by jedijosh920** [crosire/scripthookvdotnet#329]
RAGE Plugin Hook has added a Euphoria class where you can set arguments for the messages. I was wondering if ScriptHookVDotNet could have a Euphoria class as well?

Here is an example for setting a pedestrian to use the body balance message where they will try to keep their balance.

    void BodyBalance(Ped ped, int duration)
    {
        Function.Call(Hash.SET_PED_CAN_RAGDOLL, ped, true);
        Function.Call(Hash.SET_PED_TO_RAGDOLL, ped, duration, duration, 1, 1, 1, 0);
        Function.Call(Hash.CREATE_NM_MESSAGE, 1, 466);
        Function.Call(Hash.GIVE_PED_NM_MESSAGE, ped);
    }

I also have a list of messages, with help from Zorg:

http://gtaforums.com/topic/817563-v-euphorianaturalmotion-messages/

Now if you can find out how RAGE added arguments that you can set, that would be amazing and I would appreciate it! 

I hope a Euphoria class can make it soon in ScriptHookVDotNet!

**Comment by zorg93** [comment]
I'll give you a clue,  rage plugin hook doesn't use natives to accomplish that task

**Comment by zorg93** [comment]
Hmm I think I have found it. Was staring me in the face the whole time, I just never noticed

**Comment by zorg93** [comment]
Update, I have it kind of working, but the code is currently really messy and full of debug statements, Will clean it up and test more before adding anything

**Comment by BDKing00** [comment]
Looking forward to this :)

**Comment by zorg93** [comment]
Added in #331

**Comment by crosire** [comment]
Merged in #331.
