### ISSUE TITLE
Need help converting code to .net

### ISSUE THREAD

**Issue by AAYapps** [crosire/scripthookvdotnet#332]
I just need some help converting this code I worked on in the scripthook V and want to transfer it to the scripthook V .net. 

I am having trouble getting this code to work on the .net

	// common variables
	Player player = PLAYER::PLAYER_ID();
	Ped playerPed = PLAYER::PLAYER_PED_ID();

	if (!ENTITY::DOES_ENTITY_EXIST(playerPed)) return;

	STREAMING::REQUEST_NAMED_PTFX_ASSET("scr_family4");
	GRAPHICS::_SET_PTFX_ASSET_NEXT_CALL("scr_family4");
	GRAPHICS::START_PARTICLE_FX_LOOPED_ON_ENTITY("scr_fam4_trailer_sparks", playerPed, 0, 1, 0, 3, 0, 0, 2, false, false, false);

I would appreciate the help, if it is possible.

**Comment by crosire** [comment]
```c#
using GTA;
using GTA.Native;

...

Ped playerPed = Game.Player.Character;

if (!playerPed.Exists()) return; // The player ped always exists, so you can leave that out

Function.Call(Hash.REQUEST_NAMED_PTFX_ASSET, "scr_family4");
Function.Call(Hash._SET_PTFX_ASSET_NEXT_CALL, "scr_family4");
Function.Call(Hash.START_PARTICLE_FX_LOOPED_ON_ENTITY, "scr_fam4_trailer_sparks", playerPed, 0, 1, 0, 3, 0, 0, 2, false, false, false);
```

**Comment by AAYapps** [comment]
the effect does not appear. for some reason. It works on just scripthook V but not the .net.
I think it has to do with the last function START_PARTICLE_FX_LOOPED_ON_ENTITY as it would return an Any in scripthook V

**Comment by crosire** [comment]
Closing because not an issue with Script Hook V .NET itself.
