### ISSUE TITLE
Add Gwen-dotnet support

### ISSUE THREAD

**Issue by mat27** [crosire/scripthookvdotnet#334]
I was just wondering if Gwen-dotnet support was possible to be added to scripthookvdotnet.
RageHook allows users to create forms/dialogues  via the gwen plugin, adding this to scripthookvdotnet would allow users to do more. 

https://code.google.com/p/gwen-dotnet/

Cheers

**Comment by crosire** [comment]
I personally think that GUI looks horrible in GTA. We have NativeUI, which matches the style Rockstar follows very closely and thus is the preferred way to go.

**Comment by Guad** [comment]
I tried it and personally I hated it. You only could have one window open which blocked all of your controls and was generally unstable. Implementing your own Forms would be better.
