### ISSUE TITLE
World.GetClosestVehicle returns vehicle player is in

### ISSUE THREAD

**Issue by mat27** [crosire/scripthookvdotnet#335]
Before the latest update World.GetClosestVehicle never returned the vehicle the ped is currently in. Any way around this? The old native GTA.Native.Hash.GET_CLOSEST_VEHICLE doesn't seem to do anything anymore either.

Could be just me.

**Comment by zorg93** [comment]
It will return all vehicles. Could use get nearby vehicles and find out the closest
