### ISSUE TITLE
Game Crash when i press F4 or F7... .NET RUNTIME APPLICATION ERROR

### ISSUE THREAD

**Issue by Meatrush** [crosire/scripthookvdotnet#338]
Hi, sorry for my english i have a problem when i try to use any script with scripthookv... when the game starts in story mode, i press f4 to activate the menu, but the game crash. I don't know why, i have all updated. Here is the windows report (is in spanish but the important things are in english).

Aplicación: GTA5.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: System.IndexOutOfRangeException
Pila:
   en GTA.ScriptDomain.DoKeyboardMessage(Keys key, Boolean status, Boolean statusCtrl, Boolean statusShift, Boolean statusAlt)
   en GTA.ScriptDomain.DoKeyboardMessage(System.Windows.Forms.Keys, Boolean, Boolean, Boolean, Boolean)
   en <Module>.ManagedKeyboardMessage(Int32, Boolean, Boolean, Boolean, Boolean)

Nombre de la aplicación con errores: GTA5.exe, versión: 1.0.350.1, marca de tiempo: 0x5540c256
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.10240.16384, marca de tiempo: 0x559f38c3
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000002a1c8
Identificador del proceso con errores: 0x266c
Hora de inicio de la aplicación con errores: 0x01d107d1f5057c08
Ruta de acceso de la aplicación con errores: C:\Program Files\Rockstar Games\Grand Theft Auto V\GTA5.exe
Ruta de acceso del módulo con errores: C:\WINDOWS\system32\KERNELBASE.dll
Identificador del informe: 787a75a7-3ad6-41bc-b6cc-40cc146b5226

**Comment by crosire** [comment]
While I don't see how the F4 key is out of range, at least the crash should be fixed now as of 82a7e21652b8bfc5e3b9033931f15e76771081a8.
