### ISSUE TITLE
Creating a GUI with mouse input

### ISSUE THREAD

**Issue by rushlink** [crosire/scripthookvdotnet#343]
Is there any way to create a GUI that implements a mouse input?
I can use system.drawing and the UI in order to draw out the GUI, but I don't know how to capture mouse input, and display the mouse on screen.

Any help appreciated. 
Thanks :)

**Comment by leonardosnt** [comment]
Like that http://i.imgur.com/t9EkUJ1.png (Working...)

u can can disabled control action using

Function.Call(Hash.DISABLE_CONTROL_ACTION, 0, control...);

and to get mouse position use

Function.Call<float>(Hash.GET_CONTROL_NORMAL, 0, Controls.CursorX or Controls.CursorY);

with this you can do several things
