### ISSUE TITLE
loading .cs files missing dll References?

### ISSUE THREAD

**Issue by bilago** [crosire/scripthookvdotnet#344]
if I create a .cs script and reference System.Xml for example I get this when trying to load the game:

Failed to compile 'FiveStarResponse.cs' with 1 error(s):
   at line 12: The type or namespace name 'Xml' does not exist in the namespace 'System' (are you missing an assembly reference?)

If I compile the .cs it works without problem. Any way to fix this? Same issue with System.Linq

**Comment by crosire** [comment]
Source code scripts are limited to use features in the [System, System.Drawing and System.Windows.Forms namespaces](https://github.com/crosire/scripthookvdotnet/blob/dev/source/ScriptDomain.cpp#L181). If you need any other reference, it is required to compile the script beforehand.

**Comment by bilago** [comment]
Any reason you're hard coding just those specific namespaces instead of supporting all System.* references made in the script?

**Comment by bilago** [comment]
something simple like the following (hacky approach):

if (extension->Equals(".cs", StringComparison::InvariantCultureIgnoreCase))
		{
			for each(String ^UsingLines in IO::File::ReadAllLines(filename))
			{
				if (UsingLines->StartsWith("using System."))
				{
					compilerOptions->ReferencedAssemblies->Add(UsingLines->Split(' ')[1]);
				}
				else if (UsingLines->ToLower->StartsWith("public"))
					break;
			}

			compiler = gcnew Microsoft::CSharp::CSharpCodeProvider();
			compilerOptions->CompilerOptions += " /unsafe";
		}

**Comment by crosire** [comment]
Using an IDE for developing scripts and compiling them to binaries is the preferred (and more common) way to go. Plain source code scripts are mainly available for quick prototyping, which usually does not need all the framework references. I guess it won't do any damage to add a few more of the most used ones (like System.Xml and System.Linq) though.

**Comment by bilago** [comment]
When I give out code to my team members for testing, it's a lot easier to locate crashes with the .cs file as the exceptions will include the line numbers while the already compiled dll can't provide such granular information about the crash/error. Thanks!

**Comment by crosire** [comment]
It can actually. Simply put the .pdb the compiler generated in the same directory and line numbers will show up.

**Comment by RainerHilmer** [comment]
@bilago If you go with SRP/SOC you shouldn't have to rely on line numbers as you don't have god classes and big methods full of spaghetti code.

**Comment by JohnnyCrazy** [comment]
>I guess it won't do any damage to add a few more of the most used ones (like System.Xml and System.Linq) though.

What would you guys suggest as a compact, but sufficient, list of references?

**Comment by Fireboyd78** [comment]
@crosire @JohnnyCrazy How about the following references?

`System.Collections.Generic`
`System.IO`
`System.Linq`
`System.Text`

**Comment by crosire** [comment]
@Fireboyd78 Sounds reasonable, yes.
