### ISSUE TITLE
Gitter instead of Slack

### ISSUE THREAD

**Issue by crosire** [crosire/scripthookvdotnet#346]
I suggest we move from using Slack to Gitter for communication, since all we really need is a public chat, instead of a full blown team management system and logging into Gitter is a lot easier too. Any opinions before I make the switch?

**Comment by JohnnyCrazy** [comment]
While I have no objections, I wonder if a chatroom is currently necessary.
Back in the past when we opened our slack-page, there was a lot more questions and general discussion. Now, I have the feeling everyone got into it and the project itself is in a finished(?) state.

But I think having a Gitter-Room is better than nothing :)
