### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Yothri** [crosire/scripthookvdotnet#358]
Hi,

i havent been active in GTA V Scene in last weeks, but now i wanted to try it again.
Well i got my old projects and just replaced the .dll from last release, but when i want to compile, it says that all of the namespaces arent recognized. Well i tried it by creating a new project which results into the same errors. The hook works, and when just putting the .cs file into scripts folder everything works as expected, just the library compiling doesnt work. I have no idea why.

Funny is, the namespaces are recognized by intellisense but not by the compiler. O.O

**Comment by zorg93** [comment]
Did you add the reference for the dll file

**Comment by Yothri** [comment]
Sure i did :) 
Like i meant, intellisense also gives me suggestions.
Its only failing when i compile.

**Comment by digovc** [comment]
Try remove the old reference in project and re-enter the referente to new
version dll. Check target from all your project in your solution. If you
want send me it I can try fix this problem for you. Good luck.

Em seg, 16 de nov de 2015 às 13:36, Johannes Jacobs <
notifications@github.com> escreveu:

**Comment by Yothri** [comment]
I cant even create a new project without getting that error. In my opinion there is nothing to send you.
What i do is just creating a new c# project framework 4.5. Add reference to dll. add using statements to GTA namespace and gta.native, gta.math and such, and for example when just being in constructor of class and want to instantiate vector3 on compile it will throw error that there are missing using statements circling the using statement of GTA itself and the vector3 statement.

**Comment by digovc** [comment]
Change target to .Net Framework 4.5.2. This fix your problem.

Em seg, 16 de nov de 2015 às 14:44, Johannes Jacobs <
notifications@github.com> escreveu:

**Comment by Yothri** [comment]
Indeed that was the problem, thank you so much :)
