### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by digovc** [crosire/scripthookvdotnet#359]
Hello friends,
I know that recently FiveM had to stop your multiplayer project alternative, but, someone in here have interest in make a thing like this?

**Comment by crosire** [comment]
This really isn't the discussion forum for requests like this.

**Comment by digovc** [comment]
This isn't a request or issue. Is a question. Someone are working in some project like this?

Sorry if here isn't the best place to make this question.

**Comment by letsplayordy** [comment]
I'd suggest making a post on GTAForums, perhaps [here](http://gtaforums.com/forum/304-pc/).

**Comment by digovc** [comment]
Tks.
