### ISSUE TITLE
System.IO.FileNotFound Exception on a reference

### ISSUE THREAD

**Issue by TeamTiffany** [crosire/scripthookvdotnet#364]
I'm having the following problem:

I use a .cs script where I want to use parts of the "Accord.Net" framework to use RanSac in my code.
The as soon as I execute parts of the Accord.Net framework I'm getting the above mentioned error.
From what I can see so far the scripts aren't able to reference the .dlls properly, but I have no clue how to workaround this.

Any help appreciated.

**Comment by JohnnyCrazy** [comment]
Hi,

AFAIK, depending on non-script libraries (like `Accord.Net`) is not possible with pure `.cs` files. You have to compile it to a `.dll` and then copy both, the `Accord.Net`-Library and your `.dll` file into the `/scripts`-folder. If you don't want to ship 2 DLLs, you can use [ILMerge](https://www.microsoft.com/en-us/download/details.aspx?id=17630) to merge both into one.

**Comment by digovc** [comment]
Hello,

In fact you just have to compile your solution, copy all compiled resources
(dlls, exes, etc) in scripts folder in your GTA directory. A script in *.cs
file don't works with yours references compiled (like a dll).

Em qui, 3 de dez de 2015 às 11:20, Jonas Dellinger <notifications@github.com>
escreveu:

**Comment by TeamTiffany** [comment]
I build all the .cs files to a .dll in fact (forgot to mention that, sorry).

But Johnny already gave the proper hint... I just needed to add the .dll files into the /scripts folder.
Quite embarrassing that I didn't get that myself.

Thanks a lot!
