### ISSUE TITLE
How to get coords player looking at?

### ISSUE THREAD

**Issue by SamperMan44** [crosire/scripthookvdotnet#365]
I wanna make a fire cannon, but I can't find a function that gets coords player looking at while aiming. My English is bad and I can't find this in db. SOS!!

**Comment by letsplayordy** [comment]
Are you wanting the direction the player is looking at or the position a
bullet would land if you fired one?

**Comment by JohnnyCrazy** [comment]
Well, you propably want `static RaycastResult GetCrosshairCoordinates();` inside `World`.

Also, please ask further questions inside the [Gitter-Room](https://gitter.im/crosire/scripthookvdotnet?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge), the issues should be primarily for bug-tracking/feature-requests.

**Comment by SamperMan44** [comment]
letsplayordy, I wanna the position a bullet will land if I fire one

**Comment by SamperMan44** [comment]
JohnnyCrazy, thx, it works!
