### ISSUE TITLE
Mod does not respond to mouse click

### ISSUE THREAD

**Issue by SamperMan44** [crosire/scripthookvdotnet#366]
Look at this:
<code>
void OnKeyDown(object sender, KeyEventArgs e)
    {   
 if (e.KeyCode == Keys.LButton)      
  {      
  // This code does not works    
  }}
</code>
When I press the Left Mouse Button, nothing happens. Sorry for this question, but I am a newbie. Help

**Comment by zorg93** [comment]
Mouse buttons don't work with the keydown and up events, use game.IsControlJustPressed to achieve that

**Comment by SamperMan44** [comment]
zorg93 ok thx, i will try it later
