### ISSUE TITLE
How to get the current weather type?

### ISSUE THREAD

**Issue by uPrizZ** [crosire/scripthookvdotnet#369]
GTA.World.Weather seems to be a setter only. Why are we not able to get the weather, or is there any function I simply did not find?

**Comment by JohnnyCrazy** [comment]
As you can see on [line 176](https://github.com/crosire/scripthookvdotnet/blob/157ac57f9530a1cf55afa61d81a066849b52f8ba/source/scripting/World.cpp#L176), there is a `getter`. 

If you have any more questions, feel free to reopen the issue

**Comment by uPrizZ** [comment]
Well, that's strange. Tried to use the following if statement:

if(World.Weather == Weather.Raining) { ... }

But it throws me an error on "World.Weather" -> Cannot use it in this context due to a "missing get accessor"

**Comment by JohnnyCrazy** [comment]
I just tested it myself and indeed the `getter` can't be found, I have no idea why tho.

**Comment by uPrizZ** [comment]
I also cannot seem to find the native hash (_GET_CURRENT_WEATHER_TYPE), which is used in the getter either. (tried to find it in GTA.Native.Hash)

**Comment by kagikn** [comment]
GTA.World.Weather getter is currently only in develop version, not in release version.

**Comment by uPrizZ** [comment]
Well that explains it, thank you.

**Comment by JohnnyCrazy** [comment]
@kagikn Ah yea, just noticed I had the release version pulled. Thanks :+1:
