### ISSUE TITLE
Create a Blip wrapper

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#37]
I think adding a Blip wrapper is a very good idea, because there are so many methods to be taken advantage of when it comes to blips. I have created a wrapper in C# already, which easily could be ported to C++.

https://github.com/Nacorpio/GTAExperimenting/blob/master/GTAModExperimenting/Blip.cs

**Comment by Nacorpio** [comment]
![](http://i.gyazo.com/9e84797e8b4f93082c41bf58d0b50e16.png)
That's what I get when creating a blip with a radius.

**Comment by JohnnyCrazy** [comment]
Will look at this tomorrow :+1:

**Comment by CrossCRS** [comment]
I'm working on it, but since it's my first commit I'm sure I made some mistakes :F 
Seems like everything is working though, except REMOVE_BLIP, and I don't know why, but I'll try again tomorrow.

**Comment by JohnnyCrazy** [comment]
Implemented in 780fdcd
