### ISSUE TITLE
Usage of the euphoria classes crashes newer game patches

### ISSUE THREAD

**Issue by crosire** [crosire/scripthookvdotnet#370]
Apparently the memory structure was changed in a recent game patch, so it does not work anymore.

**Comment by JohnnyCrazy** [comment]
Would it be possible to replace the hard-coded addresses by some pattern-matching? This would prevent it from breaking on patches, but I have no idea if this is easy to do (?)

@crosire @zorg93

**Comment by crosire** [comment]
This is already done: https://github.com/crosire/scripthookvdotnet/blob/dev/source/core/NativeMemory.cpp#L183.
I'm guessing some memory offsets have changed, but don't have the time to dig into the disassembly right now.

**Comment by zorg93** [comment]
Im kind of busy with life atm to go looking into this stuff

**Comment by kagikn** [comment]
I'm not busy, but I have no skill to find the addresses for the euphoria stuff.

**Comment by Nacorpio** [comment]
I really wish I had the knowledge to fix this, because I have all time in the world.

**Comment by zorg93** [comment]
Download ida and decompile the gta v exe as well as the last exe euphoria worked on. Look how this code works and it's probably a case of just updating signatures

**Comment by Nacorpio** [comment]
Yes, but I still don't have the knowledge to update signatures.
Are you still lacking time to look into this stuff?

**Comment by Nacorpio** [comment]
I will take that as a yes.

**Comment by CamxxCore** [comment]
I submitted a pull request that updates this for the latest patch: [#456](https://github.com/crosire/scripthookvdotnet/pull/456)

**Comment by crosire** [comment]
Fixed in b66e0f30da3b15fd2ac6f70b551f91a699ba7802 thanks to @CamxxCore.
