### ISSUE TITLE
Set opacity of drawn textures

### ISSUE THREAD

**Issue by uPrizZ** [crosire/scripthookvdotnet#371]
Hello there.
Is there any way to modify the opacity of texture that I want to draw via UI.DrawTexture? If this isn't possible yet, well then this can be seen as a feature request :D

**Comment by JohnnyCrazy** [comment]
Hi @uPrizZ ,
you can use one of the method-overloads of `UI.DrawTexture` which uses a Color-Object (found [here](https://github.com/crosire/scripthookvdotnet/blob/157ac57f9530a1cf55afa61d81a066849b52f8ba/source/scripting/UI.cpp#L73)). Just use a custom alpha-value (`A`-Property) inside the color-object and it should work as expected.
