### ISSUE TITLE
GTA V update 1.0.505.2 crash on pressing enter or space

### ISSUE THREAD

**Issue by xagent007** [crosire/scripthookvdotnet#374]

**Comment by xagent007** [comment]
when i delete the scripthookdotnet.asi file game runs normal no crashes plz any fix  ?

**Comment by crosire** [comment]
Does this happen without any script mods installed too (delete the /scripts folder in your game directory)?

**Comment by xagent007** [comment]
even without script folder still crashing when i press enter or soace bottom ?!

**Comment by crosire** [comment]
Is this still the case with 1.5.1?

**Comment by crosire** [comment]
Since there was no feedback, I'll close this for now. Can be reopened later if the issue still occurs.
