### ISSUE TITLE
ScriptHookVdotnet Logs

### ISSUE THREAD

**Issue by xxnamxx** [crosire/scripthookvdotnet#375]
Hi, My brother has issue trying to get the Mod MP COOP working which is a script for .net, but it seems to not load the scripthookvdotnet and no .log file is created, scripthookv trainer menu works fine and everything works fine on my pc and log files are ok. Any suggestions for him? he has .net 4.6.1 and C++ 2013 x86/x64 Installed, also tried removing all things related to .net and just installing version 4.5.3. any suggestions? he's on Windows 7 and im on Windows 10.

**Comment by Studly97** [comment]
Also having the same problem but I'm on Windows 8.1

**Comment by xxnamxx** [comment]
Although not the best fix but we ended up using: https://www.gta5-mods.com/tools/gtav-mod-manager

And for some reason it worked.
