### ISSUE TITLE
ScriptDomain::ExecuteTask throws errors in some cases

### ISSUE THREAD

**Issue by tjhorner** [crosire/scripthookvdotnet#379]
When in a different thread (websocket server), it will throw "Object reference not set to an instance of an object." when run. (but the task still runs)

**Comment by crosire** [comment]
```ScriptDomain::ExecuteTask``` only works with managed threads, not with native Win32 threads (a managed threads are handled by the CLR). But either way, you should not create your own threads and execute scripting code inside them, managed or not. It is not supported.

**Comment by tjhorner** [comment]
>you should not create your own threads and execute scripting code inside them, managed or not.

I wasn't, a library I was using was...

But a workaround I guess is to store stuff you want to call inside of a variable and on tick if those are set then call it from there since it would be on the main (managed) thread. It's really hacky, but it works...
