### ISSUE TITLE
Entity Health is off in v2.5

### ISSUE THREAD

**Issue by LibertyLocked** [crosire/scripthookvdotnet#383]
My player seems to die at player.Health == 50

Apparently this
```cs
	int Entity::Health::get()
	{
		return Native::Function::Call<int>(Native::Hash::GET_ENTITY_HEALTH, Handle) - 100;
	}
```
is changed to 
```cs
	int Entity::Health::get()
	{
		return Native::Function::Call<int>(Native::Hash::GET_ENTITY_HEALTH, Handle) / 2;
	}
```

I'm wondering why it is changed in v2.5?

**Comment by crosire** [comment]
Was done here #352. According to http://dev-c.com/nativedb > GET_ENTITY_HEALTH the range for players is 0 to 200, which would make that code correct. But it could be that only 100 - 200 is used while alive. Needs confirmation.
