### ISSUE TITLE
Memory offsets?

### ISSUE THREAD

**Issue by E66666666** [crosire/scripthookvdotnet#385]
There's a few methods in there which don't use native functions, but access memory to change stuff. One of those is setting a headlight damage status:
```c#
void Vehicle::LeftHeadLightBroken::set(bool value) {
	unsigned char *const address = reinterpret_cast<unsigned char *>(Native::MemoryAccess::GetAddressOfEntity(Handle));
	if (address == nullptr) {
		return;
	}

	const unsigned char mask = 1 << 0;

	if (value) {
		*(address + 1916) |= mask;
	}
	else {
		*(address + 1916) &= ~mask;
	}
}
```

Now, I get the basic gist of it, but how did you discover this specific offset of 1916 bytes(?) to damage the headlights? Is there any other documentation available for what I think is a Vehicle struct? Specifically, I want to find out what damages the wheels such that the suspension lowers.

**Comment by Mellnik** [comment]
Cheat Engine has a feature called "Dissect data/structures". Then you have to try out every offset see what it does. But since GTAV has those script threads I am not sure if this works.

**Comment by E66666666** [comment]
Well, the main thing is GTA V tends to crash after I try and do the "Find out what writes to this address" thing.

**Comment by E66666666** [comment]
I found a few values around the 0x0710 to 0x0A28 Vehicle offset range, so this can be considered answered. I haven't found the suspension/tires values, but that'll come later. Thanks for the CE pointers!

**Comment by zorg93** [comment]
I know it's old but the head light setter was made from reversing the head light getter native

**Comment by E66666666** [comment]
What steps could one take to reverse a native?

**Comment by zorg93** [comment]
Breakpoint the register native function. launch the game, when that breakpoint hits dump the exe. load the exe up in ida, search for the hash of the native you want to reverse(will need to be translated to current game version) then you can view the function, but r* liked to obscure some of the code at the start of the natives making it even harder

**Comment by E66666666** [comment]
Ah, I think I'll stick to the CheatEngine + experimental poking around then.
