### ISSUE TITLE
Scaleform -- Render3DAdditive is actually Render3D (and vice versa!)

### ISSUE THREAD

**Issue by Fireboyd78** [crosire/scripthookvdotnet#394]
So the native that was originally called "_DRAW_SCALEFORM_MOVIE_3D_ADDITIVE" is actually just "[DRAW_SCALEFORM_MOVIE_3D](http://www.dev-c.com/nativedb/func/info/87d51d72255d4e78)", so I've updated the NativeDB to reflect this. Unfortunately now we have the "[_DRAW_SCALEFORM_MOVIE_3D_NON_ADDITIVE](http://www.dev-c.com/nativedb/func/info/1ce592fdc749d6f5)" native that I have no idea how it works. This was originally called "_DRAW_SCALEFORM_MOVIE_3D". I've tried every possible name for this unknown version:

DRAW_SCALEFORM_MOVIE_3D_FULLSCREEN
DRAW_SCALEFORM_MOVIE_3D_FULLSCREEN_MASKED
DRAW_SCALEFORM_MOVIE_3D_MASKED
DRAW_SCALEFORM_MOVIE_3D_BLEND
DRAW_SCALEFORM_MOVIE_3D_BLENDED
DRAW_SCALEFORM_MOVIE_3D_OVERLAY
DRAW_SCALEFORM_MOVIE_3D_TRANSPARENT

(and many, many more...)

I've pretty much run out of ideas for what it could be called. I'm not sure who did the original research but it would probably be a good idea to figure out what the unknown native is!

I apologize if I've created any extra work for you guys. I may do code contributions in the future, but this is just a start for me. Good luck!

**Comment by JohnnyCrazy** [comment]
As far as I understand, this is more of a NativeDB-naming problem. Since we just copy those names and don't modify them, I would suggest this topic would fit better into the gta-forums.
