### ISSUE TITLE
use SemVer

### ISSUE THREAD

**Issue by screeny05** [crosire/scripthookvdotnet#41]
Please plan on using [Semantic Versioning](http://semver.org/) to keep versioning sane

**Comment by crosire** [comment]
Agreed

**Comment by crosire** [comment]
Agreed. The question is if we should treat all the current API additions as a jump of the major version or the minor version. Because I'd merge the minor and patch part into one, to keep the version short.

**Comment by screeny05** [comment]
I'd treat them as minor bumps, until the API could be considered stable
