### ISSUE TITLE
ScriptHookVDotNet will not start.

### ISSUE THREAD

**Issue by maaaallen** [crosire/scripthookvdotnet#411]
I installed 2.5.1 and other versions but they just wont start. I tried using mods that require .net none will work. If I scroll through the gta 5 directory there's no log file for it either that is why I believe it's not even starting. It would be really great if somebody could help me on this issue thank you.

**Comment by RainerHilmer** [comment]
There is a dll and an asi file. You need to copy the scripthookvdotnet.asi into the root installation folder of GTA V. Also you need Alexander Blade's scripthookV.dll (that's without "dotnet", you see?). The scripthookvdotnet.dll, however, is for developers only. Do not put this into the GTA V installation folder.

**Comment by kagikn** [comment]
Actually, there is a few scripts which have reference to the scripthookvdotnet.dll in root GTA V directory. So you have to put it in the directory in some case, but DO NOT put it in the scripts folder.

**Comment by crosire** [comment]
No? The ASI resolves that reference to itself, the DLL is not required and for development only. The ASI is actually the same as the DLL, just with a different file extension.
