### ISSUE TITLE
Question: How to save all weapons a player has, in order to give him his equip back later

### ISSUE THREAD

**Issue by uPrizZ** [crosire/scripthookvdotnet#413]
Hello community,
this might be a pretty stupid question, but I am trying to figure this out for some time now.
So GTA.Game.Player.Character.Weapons has a getter, which returns a "WeaponCollection" instance. Apparently this is what I need for saving all the weapons, but I cannot give the PED his weapons back as there is no .Weapons setter, nor does the Give method accept a WeaponCollection parameter.

Now I thought about creating an array and store the weapon hashes/ammo etc. inside. Problem is though, that I simply did not find any solution for getting all the player weapons seperatly yet (i.e. by iterating through WeaponCollection or something like that)
Oh yeah, and I also tried to go through NativeDB, but did not find anything helpful either...

Is there any proper solution for that?

**Comment by crosire** [comment]
You can iterate through all enum values in ```GTA.Native.WeaponHash``` and store the associated weapon data:
```
foreach (var hash in System.Enum.GetValues(typeof(WeaponHash)).Cast<WeaponHash>())
{
    ... = Game.Player.Character.Weapons[hash];
}
```
Later use the ```WeaponCollection.Give``` method to give each of them back.
```
foreach (var hash in System.Enum.GetValues(typeof(WeaponHash)).Cast<WeaponHash>())
{
    Game.Player.Character.Weapons.Give(hash, ...);
}
```
