### ISSUE TITLE
Missing Methods Since Code Clean Up

### ISSUE THREAD

**Issue by jbienz** [crosire/scripthookvdotnet#419]
Some methods went missing from 2.0 onwards but their removal was not documented in the release notes. World.GetGroundZ is at least one example. Its removal broke mods like Just Cause 2 and Shark-O-Matic. I am not the author of those mods, but I could reach out to them if there was a replacement API to use. Just browsing the code, though, I'm not clear what the replacement is for that API.

**Comment by JohnnyCrazy** [comment]
`World.GetGroundZ` never got removed, it was just renamed to `World.GetGroundHeigth` in 1371e63bd7a4b7678a3586050961e5d658f76f09 ([line](https://github.com/crosire/scripthookvdotnet/commit/1371e63bd7a4b7678a3586050961e5d658f76f09#diff-a47801223162d17946d0212ff17bb7e0L173))
