### ISSUE TITLE
Bug with Arrest Warrant Script/NativeUI (Maybe)

### ISSUE THREAD

**Issue by zanesix** [crosire/scripthookvdotnet#433]
I would like to report a bug with the script Better Chases and Arrest Warrant found here: https://www.gta5-mods.com/scripts/better-chases-arrest-warrant where every time you go in the menu and uncheck the arrest warrant module in the latest beta script it crashes the script and gives the following error in the log:

[21:32:55] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.String.ToCharArray()
   at GTA.Game.GenerateHash(String input)
   at BetterChases.CleanWarrant(Boolean notify, Boolean CleanPlayer, Boolean CleanVeh)
   at BetterChases.OnCheckboxChange(UIMenu sender, UIMenuCheckboxItem checkbox, Boolean Checked)
   at NativeUI.UIMenu.SelectItem()
   at NativeUI.UIMenu.ProcessControl(Keys key)
   at NativeUI.MenuPool.ProcessControl()
   at NativeUI.MenuPool.ProcessMenus()
   at BetterChases.OnTick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()

Nobody knows why this is happening, but we do know that the last working build that **DOES NOT** have this happen is build no. 663: https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/Build%20No.%20663/artifacts , and of course this does not happen with the relase version

What could have made this happen? Will the script(s) have to be updated or is it a bug with this?  Posting here by the request of Dilapidated.

**Comment by crosire** [comment]
Sounds like ```GenerateHash``` is called with ```null``` as argument, which is not valid.

**Comment by kagikn** [comment]
I'll test ```GET_HASH_KEY``` with 0 value and fix ```GenerateHash```.

**Comment by Dilapidated** [comment]
I'll have the team test this fix in the next build once implemented. Thank you :)

**Comment by kagikn** [comment]
I confirmed, we call ```GET_HASH_KEY``` with literal ```null```, the game will crash, but we call it with a null string variable, it will return 0.

**Comment by Eddlm** [comment]
The script was setting two Model variables to null to clear the Warrant on the player. That was what was causing crashes.
Setting the model variables to "" instead of null seems to fix the issue.

**Comment by zanesix** [comment]
Script has been updated to cope with the changes, so everything works now.
