### ISSUE TITLE
Proposal: Have all objects inherit from base class/interface(s)

### ISSUE THREAD

**Issue by Fireboyd78** [crosire/scripthookvdotnet#438]
I've been glancing over the code and noticed that most objects don't share a common ancestor. For example, in `NativeTask::ObjectToNative`, there's code that checks for _every_ type and returns the appropriate value. However, this makes it a PITA to add new types because then you have to make sure you add it to stuff such as `ObjectToNative`.

I would like to run this idea by you guys first before actually implementing it, but I was thinking about making an abstract `GTAObject` class that inherits at least the following properties:

- **Handle** property
- **GetHashCode** method (returns **Handle** property)
- **Equals** method (base implementation checks if handles are the same)
- **ToNativeObject** method (returns the native representation of this object; protected internal)

Yes, there are the `IHandleable` and `ISpatial` interfaces for the `Entity` class, but the `Model` class doesn't inherit from anything. The proposed `GTAObject` class could inherit from all of the necessary interfaces, then the classes such as `Entity` and `Model` can inherit from `GTAObject` and override stuff as needed.

I don't see any downsides to this, it would definitely cut down on the amount of code needed to get things running, and would also allow users to implement their own custom classes that play well with `ObjectToNative`.

What do you guys think? I'd be willing to write all of the code, I just need to know if it's even worth it. Existing user mods should remain 100% compatible even with an updated DLL, assuming they do not use strange hacks in their code that would interfere with the proposed changes.

**Comment by Fireboyd78** [comment]
Also, the properties I've mentioned above aren't necessarily final, but it's pretty much the same idea. I won't edit the OP, but I would actually consider taking things a step further and implement an `INativeObject` interface that implements the **ToNativeObject** method or whichever name makes sense. Then, in `ObjectToNative`, the code would check to see if the object implements the `INativeObject` interface and calls the method that returns the object as a native.

**Comment by crosire** [comment]
I prefer the interface approach that was started not long ago but never fully finished. Most of the selection cases in ```ObjectToNative``` could be solved with a check for ```IHandleable``` for instance, with the only exception being the ```Model``` class. Now that one case could be solved with a ```INativeObject```, but I'm not sure it's necessary, because I can't think of any additional non-handle types that may be added in the future.

**Comment by crosire** [comment]
Since this is now implemented in v3 via `INativeValue`, I'll close this.
