### ISSUE TITLE
DistanceTo2D does not exclude Z-distance

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#442]
I have read you have optimized the Tick process with this version. However, the Tick event handlers in my VAutodrive mod don't get called anymore. Do we need to make any changes in the code or what's wrong here?

**Comment by crosire** [comment]
Refers to commit 8784dd27d96cd542bae3d9d5cb1fe097a6f9fad1, which is the only change to the Tick process. Nothing else was modified since 2.5.1. I checked with a few scripts and in all of them the tick event handlers were called as expected.

**Comment by JohnnyCrazy** [comment]
Can confirm it's working as expected, just ran 2 example scripts, both `OnTicks` were called

**Comment by RainerHilmer** [comment]
I found the culprit.
Before
´´´C#
if((DrivingData.Vehicle.Position.DistanceTo2D(
            DrivingData.StaticTarget) > 10.0f))
´´´
Now
´´´C#
if((DrivingData.Vehicle.Position.ToGround().DistanceTo2D(
            DrivingData.StaticTarget.ToGround()) > 10.0f))
´´´
Without the ToGround method it added the Z-distance. The gound-level was at about 73 where I was testing, so this piece of code always returned true even though I was right at the waypoint. Looks like there is something wrong with the DistanceTo2D method.

**Comment by crosire** [comment]
```Vector3.DistanceTo2D``` is indeed invalid, it just returns the normal 3D distance, when it actually should ignore the Z components.

**Comment by RainerHilmer** [comment]
Now I get the full picture and why I run into this error. Before that I used my own implementation of DistanceTo2D as an extension method. This is my code and that works:
`      public static float DistanceTo2D(this Vector3 origin, Vector3 target)
      {
         var originFlat = new Vector3(origin.X, origin.Y, 0);
         var targetFlat = new Vector3(target.X, target.Y, 0);
         return originFlat.DistanceTo(targetFlat);
      }`

**Comment by crosire** [comment]
I'll push a fix right away.

**Comment by RainerHilmer** [comment]
Thanks, I'm glad I could help and I can roll back those ugly changes now. :+1:

**Comment by crosire** [comment]
Published as 2.6.1.
