### ISSUE TITLE
The Quantum Break Mod Wont Work And I dont Know Why everyone else can use it

### ISSUE THREAD

**Issue by theultimateshotHd** [crosire/scripthookvdotnet#450]
[19:43:55] [ERROR] Script 'QuantumBreak' is not responding! Aborting ...
[19:43:55] [DEBUG] Aborted script 'QuantumBreak'. Why Is This Happening?

**Comment by crosire** [comment]
The error explains it. The script is stalling and ScriptHookVDotNet therefore kills it so the game can continue to run. This can happen if ```Thread.Sleep``` is called or some heavy work which takes longer than a few seconds is going on.

**Comment by theultimateshotHd** [comment]
i dont know why its doing this is there anyway i can fix it? @crosire

**Comment by crosire** [comment]
Report to the script author. This is not a problem with ScriptHookVDotNet, but the script.
