### ISSUE TITLE
Don't have ScriptHookVDotNet-date.log

### ISSUE THREAD

**Issue by Maisx** [crosire/scripthookvdotnet#452]
I don't know why but i haven't the ScriptHookVDotNet-date.log File. I installed the new ScriptHookVDotNet (but not with the source (zip)). I know, ScriptHookVDotNet is where GTAV.exe it, but it doesn't exist. This said the author Guadmaz from ''map editor'':''The log is called ScriptHookVDotNet-[date].log, it's where GTA5.exe is. If it doesn't exist, then scripthookvdotnet is not even starting, you should ask for help on their github.''.

**Comment by RainerHilmer** [comment]
Make sure you copied the file with the .asi extention to your GTA V installation folder. The file with the .dll extension is for mod developers only.
Also, have you installed Alexander Blade's ScriptHookV?

**Comment by Maisx** [comment]
Yes i installed this ScriptHookV. I have in the folder the files .asi .dll (and .xml).

**Comment by crosire** [comment]
Then you have a ```dinput8.dll```, a ```ScriptHookV.dll``` and a ```ScriptHookVDotNet.asi``` file in your GTA root directory?

**Comment by Maisx** [comment]
Yes, in the folder where GTAV.exe is. Is a dinput8.dll, a ScriptHookV.dll, a ScriptHookVDotNet.asi and and a ScriptHookVDotNet.dll.

**Comment by RainerHilmer** [comment]
Remove the ScriptHookVDotNet.dll.

**Comment by Maisx** [comment]
It don't work. When i press F7 (for the Map Editor) comes nothing.

**Comment by Maisx** [comment]
So ScriptHookVDotNet dont work...

**Comment by JohnnyCrazy** [comment]
If ScriptHookVDotNet wouldn't work, a lot more people would've reported it.

If you followed all steps, including installing .NET, it **works**. You probably missed some step

**Comment by Maisx** [comment]
I have C++ ScriptHook by Alexander Blade
.NET Framework ≥ 4.5.2
Visual C++ Redistributable for Visual Studio 2013 x64
I have
ScriptHookVDotNet.asi
I had/have ScriptHookVDotNet.dll
...

**Comment by crosire** [comment]
You do have writing permissions to your game folder, right (Steam should fix that for you already)? Run the game as administrator otherwise or ScriptHookVDotNet won't be able to create a log file.

**Comment by Maisx** [comment]
Wow finally. Thank you :+1:
