### ISSUE TITLE
Intellisense is not working

### ISSUE THREAD

**Issue by Bluethefurry** [crosire/scripthookvdotnet#454]
Hello, i'm fairly new to scripthookdotnet and i wanted to start developing a script but i cannot seem to get intellisense to work with it, the default intellisense for c# works, ive loaded the template project typed "Game.Player.Character." and then pressed ctrl+space and nothing happened.
as there is no real documentation i cannot properly work on scripting.

I'm using Visual Studio Community 2015 version 14.24720 Update 1

**Comment by crosire** [comment]
Make sure the ScriptHookVDotNet.dll was added as a reference to the project!

**Comment by RainerHilmer** [comment]
Also have the ScriptHookVDotNet.xml at the same place you reference the ScriptHookVDotNet.dll. This XML file contains the documentation.
