### ISSUE TITLE
Game.Player.Color doesn't change

### ISSUE THREAD

**Issue by jariz** [crosire/scripthookvdotnet#455]
`Game.Player.Color` appears to stay the same value (the character color of the one you started the game with).
Switching characters does not change `Game.Player.Color`'s value which I figure it should.
Using `Game.Player.Character.Model.Hash` to determine which color to display is a workaround for this, but not very clean as you'd need to determine the colors yourself based on the character model.

**Comment by crosire** [comment]
```Game.Player.Color``` uses ```GET_PLAYER_RGB_COLOUR``` in the background. Don't about the quirks of that function. But could be that it exists for different reasons than to get the player character color, like to get the multiplayer player blip color.

**Comment by Fireboyd78** [comment]
Yeah that's obviously for multiplayer colors. It should be removed unless @crosire wants to implement a "Color" for network games and one for single player.

**Comment by Fireboyd78** [comment]
Or actually rewrite it to get main character colors and not ~GET_PLAYER_RGB_COLOUR~

**Comment by crosire** [comment]
I'd rather remove it.

**Comment by crosire** [comment]
Was removed in 59c08be4827a332acb3620ae747b432c62248f32.
