### ISSUE TITLE
Add some kind of Documentation?

### ISSUE THREAD

**Issue by JohnnyCrazy** [crosire/scripthookvdotnet#46]
Since this library is growing and growing...I think we need a documentation site or something.
We could use some static-site generation, like jekyll or mkdocs, in combination with GitHub Pages.

Any thoughts @crosire ?

**Comment by crosire** [comment]
I would use [inline XML documentation](https://msdn.microsoft.com/en-us/library/ms177226.aspx). Has the advantage that you can see the docs while scripting in Visual Studio.

**Comment by JohnnyCrazy** [comment]
Yea, good point.
Although it would be cool to have a static site which provides a lot of examples (Adding them to the project isn't the best option IMO)

**Comment by IncoCode** [comment]
github wiki? :wink:

**Comment by JohnnyCrazy** [comment]
(y)

**Comment by crosire** [comment]
@Yothri Nice job with the Getting Started wiki page!

**Comment by Yothri** [comment]
Thank you, i just found some time today to do this. I will add more content when i get some extra time.
:)
