### ISSUE TITLE
'Duplicate managed types have different visibilities' when building ScriptHookVDotNet

### ISSUE THREAD

**Issue by soccermitchy** [crosire/scripthookvdotnet#462]
I'm trying to build ScriptHookVDotNet using the solution on your repo, yet I get these errors whenever I try to build the project:
```
Tasks.obj : error LNK2022: metadata operation failed (801311E4) : Duplicate managed types have different visibilities.
LINK : fatal error LNK1255: link failed because of metadata errors
```
Also, is it possible to build this in Mono? I want to see if I can set up a build server for my mod so it automatically builds when I push to git.

**Comment by kagikn** [comment]
Unfortunately, it's due to the project file. But with VS2013, compiler error doesn't occur.

**Comment by soccermitchy** [comment]
Is there anything I can do other than switching to VS13 to fix it? I don't
really have space on my C drive for it, and VS doesn't support installing
to other drives.

**Comment by JohnnyCrazy** [comment]
To answer your 2nd question: No, C++/CLI is not supported by mono ([SO Question](http://stackoverflow.com/questions/183377/does-mono-net-support-and-compile-c-cli)).

**Comment by crosire** [comment]
Managed to fix this. The project compiles fine on VS2015 too, if the Ped.hpp header is included before Tasks.hpp in Tasks.cpp. Why? Magic. I guess. And don't ask me how I figured that one out.
