### ISSUE TITLE
VehicleDoors.Trunk2 Doesnt exist

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#463]
Can I remove the Trunk2 from the Vehicle doors enum. Its defined on Native DB but Im 99.99% sure it doesnt exist and vehicles only have 6 doors max(driver, passenger, drive side rear, passenger side rear, hood and trunk)

**Comment by zorg93** [comment]
Scratch that, Im 100% sure it doesnt exist
http://puu.sh/oSMp1/9038ae3b04.png

**Comment by crosire** [comment]
Sure. (By the way, is that IDA database available somewhere?)

**Comment by zorg93** [comment]
I literally just disassembled the latest gta5.exe and documented that function to see if anything changed (i.e still 6 doors)

**Comment by zorg93** [comment]
you may be able to find documented databases from the first game versions that give quite a lot of useful stuff. however since R* started encrypting the native table, reversing natives on later patches is harder

**Comment by zorg93** [comment]
Fixed in #460
