### ISSUE TITLE
[Issue / Question] Task.EnterVehicle doesn't work.

### ISSUE THREAD

**Issue by PlayPrey** [crosire/scripthookvdotnet#464]
So I tried using ped.Task.EnterVehicle(player.CurrentVehicle, VehicleSeat.RightFront);
However, absolutely nothing happen, but other tasks work just fine! 
I tested WarpIntoVehicle, LookAt, FleeFrom, FightAgainst, and they all worked how I expected.

Since I couldn't find anyone else having the issue, I have come to the conclusion, I might be alone with this problem. Any help?

**Comment by Nacorpio** [comment]
Show us the code that you are using.

**Comment by PlayPrey** [comment]
```
using System;
using System.Windows.Input;
using System.Windows.Forms;
using GTA;
using GTA.Math;
namespace Gta5_mod.net
{
    public class Main : Script
    {
        private Vehicle girlVehicle;
        private Ped girl;
        private bool missionStarted;

        private void keyPress(object sender, KeyEventArgs e)
        {
                  if (e.KeyCode == Keys.N)
                  {
                          if(!missionStarted)
                          {
                                  missionStarted = true;
                                  girl.Task.EnterVehicle(girlVehicle, VehicleSeat.Driver);
                           }
                   }
          }
}


```


This is a stripped down version, everything I have is here: http://pastebin.com/JMfkQbr9
Mock my coding all you want, this is just some stuff I am using to try and get back into gta 5 scripting.
A lot of this is simply WRONG, but the topic is Task.EnterVehicle, so lets stick to that.

**Comment by tetchel** [comment]
Hey, just wanted to say I couldn't get this Task working either. I didn't try using the Native AI::TASK_ENTER_VEHICLE, though, so give that a shot. I ended up using SET_PED_INTO_VEHICLE.

**Comment by sollaholla** [comment]
When you call task.entervehicle, if someone else is entering the vehicle at the same time he/she will stop trying.

**Comment by PlayPrey** [comment]
Does that apply to multiple vehicles? I did try have 1 person enter my car, and at the same time someone else enter another. I did not for some reason only test one.

**Comment by sollaholla** [comment]
@PlayPrey It's only if it's the same vehicle. But if it's not working for you I'm not sure, it worked fine when I tried it. Maybe try testing a different seat?

**Comment by Fireboyd78** [comment]
Hmm, try stopping all tasks on the ped first. I remember when I was doing task-related scripting it always helped to do that.

**Comment by crosire** [comment]
Any updates on this? Either way, `EnterVehicle` just calls the relevant native script function, so it's not really related to SHVDN and I'd therefore like to close this issue.
