### ISSUE TITLE
Is there a documentation/API with descriptions for this?

### ISSUE THREAD

**Issue by sollaholla** [crosire/scripthookvdotnet#469]
I just want to know how disable phone controls, but I would love it if there were a scripting api for this! Thanks in advance! :)

**Comment by tetchel** [comment]
There is a native function MOBILE::DESTROY_MOBILE_PHONE. Maybe give that a try?

**Comment by sollaholla** [comment]
That just makes the phone invisible. :/

**Comment by tetchel** [comment]
It seems to work for me, as in I can't bring up the phone after calling that function, and if it is brought up when I call the function it disappears.

**Comment by sollaholla** [comment]
I'm sorta new to hash calls but am i doing this right?
`Function.Call<bool>(Hash.DESTROY_MOBILE_PHONE);`

**Comment by sollaholla** [comment]
@tetchel  I have a menu I made, and the UpArrow key is bound to the phone, I want to disable the phone entirely while the menu is active.

**Comment by tetchel** [comment]
Take out the <bool>

**Comment by tetchel** [comment]
When the menu is opened, call that function. When the menu closes, call `MOBILE::CREATE_MOBILE_PHONE` giving a different parameter depending on the current character (if you want). I'm getting this info from [here btw.](http://www.dev-c.com/nativedb/), scroll down to Mobile

**Comment by sollaholla** [comment]
I didn't even know that webpage existed, thanks! But the phone is still functional, although you cannot see it.

**Comment by tetchel** [comment]
You're right. I'm stuck then. You could try calling some of the unnamed functions in that section to see what they do (enter the hash manually instead of using Hash.FUNCTION_NAME), in particular the two that take bool parameters.

**Comment by sollaholla** [comment]
I'm gonna be trying those methods today. How do I update the NativeDB?

**Comment by sollaholla** [comment]
Hash _0x015C49A93E3E086E disables the phone.

**Comment by Nacorpio** [comment]
@sollaholla Just click on the pen by the native you want to modify.

**Comment by tetchel** [comment]
so what happens if you call that function and give it `true` ?

**Comment by sollaholla** [comment]
@tetchel It disables the up key for the phone. (Also for dpad)
