### ISSUE TITLE
Question: Is it possible to get the list of mods a weapon has?

### ISSUE THREAD

**Issue by tetchel** [crosire/scripthookvdotnet#470]
Hi, I've spent quite some time searching the hook API + Native DB, and I can't find any way to get the list of mods from a weapon. Am I missing something, or is this functionality not there?

Edit: I'm hoping to contribute to this project so I would be happy to add this functionality to the hook if someone helps me figure out how to do it using native calls.

**Comment by tetchel** [comment]
I noticed that in the newest release there's a note: Added "WeaponAsset" class. But I don't see it in the object explorer. Will this solve my problem? How do I use it?

**Comment by zorg93** [comment]
You need to use these natives
void GIVE_WEAPON_COMPONENT_TO_PED(Ped ped, Hash weaponHash, Hash componentHash) // D966D51AA5B28BB9 3E1E286D
void REMOVE_WEAPON_COMPONENT_FROM_PED(Ped ped, Hash weaponHash, Hash componentHash) // 1E8BE90C74FB4C09 412AA00D
BOOL HAS_PED_GOT_WEAPON_COMPONENT(Ped ped, Hash weaponHash, Hash componentHash) // C593212475FAE340 DC0FC145
BOOL IS_PED_WEAPON_COMPONENT_ACTIVE(Ped ped, Hash weaponHash, Hash componentHash) // 0D78DE0572D3969E 7565FB19
For the weapon hashes, there isnt a native that i know of to get the component hashes, so I ripped this from the gunshop script. takes a weapon hash and an int and returns the component hash
http://pastebin.com/5NpPELGV

**Comment by tetchel** [comment]
Cool, thanks for the reply. I definitely didn't make the connection that a 'component' is a mod.
