### ISSUE TITLE
How to detect if road exists at Vector3 position

### ISSUE THREAD

**Issue by sollaholla** [crosire/scripthookvdotnet#472]
Is there a function i can pass a vector3 and get a boolean back that tells me if there's a road there?

Like:
```
if (World.GetRoadAt(pos)) {
     // Do something...
}
```

**Comment by Nacorpio** [comment]
`PATHFIND::IS_POINT_ON_ROAD`

**Comment by sollaholla** [comment]
Thanks! :3

**Comment by sollaholla** [comment]
Is there a way to detect if the point is water/land? Disregarding whether it's a road or not. Just land or water?

**Comment by Nacorpio** [comment]
I don't think there's one specific method for that, but check this thread out:
http://gtaforums.com/topic/843561-pathfind-node-types/#entry1068754458

**Comment by JohnnyCrazy** [comment]
You may also want to look at `WATER::GET_WATER_HEIGHT`.

Also, please consider using our [Gitter-Channel](gitter.im/crosire/scripthookvdotnet) for scripting questions, since issues should be primarily used for bugs/features requests :wink:

**Comment by sollaholla** [comment]
@JohnnyCrazy Thanks man, also the link does not work but I would totally go over there to ask questions! Thanks for being so nice @Nacorpio @JohnnyCrazy .

**Comment by JohnnyCrazy** [comment]
Sorry, should be fixed now @sollaholla

**Comment by sollaholla** [comment]
@JohnnyCrazy Thanks a lot man! I'll just close this, and head over there.
