### ISSUE TITLE
[Bug] Delete Vehicle bug.

### ISSUE THREAD

**Issue by sollaholla** [crosire/scripthookvdotnet#479]
I was having trouble deleting the main characters vehicle so I looked at the source code and noticed:

```
void Entity::Delete()
	{
		int handle = Handle;
		Native::Function::Call(Native::Hash::SET_ENTITY_AS_MISSION_ENTITY, handle, true, false);
		Native::Function::Call(Native::Hash::DELETE_ENTITY, &handle);
	}
```

This

`Native::Function::Call(Native::Hash::SET_ENTITY_AS_MISSION_ENTITY, handle, true, false);` 

should be:

`Native::Function::Call(Native::Hash::SET_ENTITY_AS_MISSION_ENTITY, handle, false, true);`

**Comment by sollaholla** [comment]
Idk if the second bool has to be true though.

**Comment by Fireboyd78** [comment]
I wonder if that bool you set to "false" is some kind of "isVehicle" argument? I assume the "Delete" functon works fine for regular entities?

**Comment by Fireboyd78** [comment]
My bad, I meant the second one to "true".

**Comment by sollaholla** [comment]
The second one is telling the car that SET_ENTITY_AS_MISSION_ENTITY cannot be changed by any other script.

**Comment by zorg93** [comment]
*cannot be changed by any other scriptThread :)

**Comment by Nacorpio** [comment]
I can delete shopkeepers using this:
`Function.Call(Hash.SET_ENTITY_AS_MISSION_ENTITY, entity, false, true);`
