### ISSUE TITLE
how to use main menu 

### ISSUE THREAD

**Issue by abdelmoez** [crosire/scripthookvdotnet#491]
Hello guys ,

I followed a tutorial showing how to create a mod but it's very old and the code for the menu did not work 

` var menulist = new List<IMenuItem>();
        var button = new MenuButton("Example button 1");
        button.Activated += (sender, args) => { UI.Notify("This is an example"); };
        menulist.Add(button);

        button = new MenuButton("Example button 2");
        button.Activated += (sender, args) => { UI.Notify("This is an example 2"); }; // either use this or a function call
        menulist.Add(button);

        var menutoggle = new MenuToggle("This is a toggle", "Your description here");
        menutoggle.Changed += (sender, args) => { UI.Notify("You toggled me"); };
        menulist.Add(button);
        Menu Active_Menu = new Menu("Example menu", menulist.ToArray()); // if you store the menu inside a var you can edit it
        View.AddMenu(Active_Menu);`

i hope someone provide me with the new way to do it or an example

**Comment by zorg93** [comment]
Thats very old code and the menu support was removed from this project. There is an alternative here that you should probable check out
https://github.com/Guad/NativeUI
It has a wiki to help get you started as well

**Comment by abdelmoez** [comment]
thank you very much zorg93 this is what I'm looking for :) 
I really appreciate your answer
