### ISSUE TITLE
CustomPrimaryColor doest work 

### ISSUE THREAD

**Issue by abdelmoez** [crosire/scripthookvdotnet#494]
hi guys 
i'm totally new to gta v scripting 

so i wanted to spawn a vehicle with this code 

        var position = Game.Player.Character.Position + (Game.Player.Character.ForwardVector * 5);

        
        var heading = Game.Player.Character.Heading - 90;

        var vehicle = World.CreateVehicle(new Model(car), position , heading);

        vehicle.DirtLevel = 15f;
        vehicle.CustomPrimaryColor = carColor;
        vehicle.NumberPlate = "AbdelMoez";

        vehicle.PlaceOnGround();

        
        Function.Call(Hash.SET_VEHICLE_MOD_KIT, vehicle.Handle, 0);
        vehicle.SetMod(VehicleMod.Engine, 4, true);
but CustomPrimaryColor  did not work 

when i try to build the script this error pop up  and red line under CustomPrimaryColor  

**The type 'Color' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.**

**Comment by crosire** [comment]
You'll need to add the System.Drawing.dll assembly to your project references.

**Comment by abdelmoez** [comment]
I dont have System.Drawing.dll in the list 

i found System.Drawing & System.Drawing.Desgin only

**Comment by abdelmoez** [comment]
ohh wait it's working now 

thanks man :+1:
