### ISSUE TITLE
Player.Money only accesses Michael's account

### ISSUE THREAD

**Issue by dydrmr** [crosire/scripthookvdotnet#50]
When playing as Franklin or Trevor and modifying the Player.Money variable, it only accesses the value stored in Michael's account.

e.g., I was playing as Trevor, who had about $180,000 in his account, while Michael had about $940,000. When I added $100 to Player.Money, Trevor's account jumped to $940,100.

**Comment by crosire** [comment]
Yeah, it currenly always returns Michaels value and when modifying the value it applies it to all. Not how it should be.

**Comment by IncoCode** [comment]
*but we could simulate that by checking the model*
Native trainer can't add money if you are using different skin. Can assume that it checks player model.
