### ISSUE TITLE
Entity.Position not working correct?

### ISSUE THREAD

**Issue by mprahlkamps** [crosire/scripthookvdotnet#505]
The following code can move the player up, but not down. When pressing down, the player just freezes in the air. When using a Vector3(0,0,-2) for down it works.

    private void update( object sender, EventArgs e ) {

		UI.ShowSubtitle("up: " + up + " down: " + down);

		if(up) {
			playerPed.Position += new Vector3(0, 0, 1);
		}

		if(down) {
			playerPed.Position += new Vector3(0, 0, -1);
		}

	}

Using this code, it works as well:

    private void update( object sender, EventArgs e ) {

		UI.ShowSubtitle("up: " + up + " down: " + down);

		if(up) {
			playerPed.PositionNoOffset = playerPed.Position + new Vector3(0, 0, 1);
		}

		if(down) {
			playerPed.PositionNoOffset = playerPed.Position + new Vector3(0, 0, -1);
		}

	}

Any ideas?

**Comment by zorg93** [comment]
Thats just how the game engine works, when you set the position of a dynamic entity, strange behaviour can happen

**Comment by mprahlkamps** [comment]
Okay, I looked in the code and couldn't find an error, so I thought you guys see something.
