### ISSUE TITLE
Relationships to peds

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#51]
Maybe we should start adding methods to peds that allow us to alter the relationships?
I personally think this would be great, because then we can start making bodyguard scripts without having to use the natives.

http://gtaforums.com/topic/793324-relationship-groups-stopping-random-peds-from-fleeing/

**Comment by IncoCode** [comment]
Almost here :wink:

**Comment by crosire** [comment]
Added in a0af227d49da9ae5a06af20e7ff2107fead2e1d5.
