### ISSUE TITLE
What happened to the Script.Dispose method

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#511]
Hi,
I am currently testing my code against the new shvdn V2.9.1 build and I can't override the Dispose method anymore. What's going on? This is a breaking change. How are we supposed to do cleanup jobs on shvdn restart now?
EDIT: Okay I figured we need to use the Aborted event but anyway, I didn't expect a breaking change because this is just a minor build. I suggest, instead of deleting members, you just mark them with the Obsolete attribute and give some hint in the XML comment for the alternative in future cases on minor builds.

**Comment by crosire** [comment]
Whoops. We didn't expect people use the `Dispose` method. I'll push a quick fix later which adds it again and marks it obsolete. Sorry for the inconvenience.

**Comment by crosire** [comment]
Fixed in 034d55129b9b2780b298a0608c324f2cc4ed038a and released as v2.9.2.
