### ISSUE TITLE
Crash GTA5 ?

### ISSUE THREAD

**Issue by bobledeveloper** [crosire/scripthookvdotnet#516]
when i put your scripthookvdotnet files my game crash after loading end.

it's about mscorlib.dll and i'm c# dev so i know it's .net but why?

**Comment by zorg93** [comment]
What version of net framework do you have installed?

**Comment by bobledeveloper** [comment]
lastest, thanks for label ;D

**Comment by zorg93** [comment]
Try running the game with no scripts in your folder. And preferably only running the scripthookvdotnet asi file. That way we can be sure this is causing the error

**Comment by bobledeveloper** [comment]
already tested, only with scripthookvdotnet files and crash again, it crash 3/4 times the only .net mods i use it's QF Mod menu 0.4

**Comment by zorg93** [comment]
@bobledeveloper Have you resolved whats causing the crash yet?

**Comment by bobledeveloper** [comment]
Yeah, i'm C# dev so i've got all .net framework, i delete all except latest 4.6.1 and fine ^^

**Comment by zorg93** [comment]
strange, in theory 4.5.2 should be enough as this targets 4.5.2
