### ISSUE TITLE
Player.Task.RunTo(somePosition);

### ISSUE THREAD

**Issue by sollaholla** [crosire/scripthookvdotnet#524]
Is there anyway to make the player run to the way-point on the map. So far out of everything I've tried, I'm starting to think this is just not possible to do.

**Comment by sollaholla** [comment]
It only works if the player is within a certain range of the destination. So is there a way I can load paths that lead to the way-point??

**Comment by mcmonkey4eva** [comment]
I'm not sure about purely using the API here, but if you're willing to use function hash code,
`TASK_FOLLOW_NAV_MESH_TO_COORD` is available.
It'd be EG `Function.Call(Hash.TASK_FOLLOW_NAV_MESH_TO_COORD, PED.Handle, X, Y, Z, SPEED, TIMEOUT, STOPRANGE, PERSIST, 0);`

**Comment by sollaholla** [comment]
@mcmonkey4eva Thanks I'll give it a try. But I don't think this will work because I'm trying to get the player to go to a position, and not a ped.

**Comment by sollaholla** [comment]
@mcmonkey4eva Still no success :(

If there was anyway to load a navmesh that would help me so much. (There is a native for it but I have to pass in the coordinates of a square and I'm not sure how I would do that).

**Comment by crosire** [comment]
Closing for now, since this is no direct bug report or enhancement idea.
