### ISSUE TITLE
How to debug unhandled exceptions

### ISSUE THREAD

**Issue by mcmonkey4eva** [crosire/scripthookvdotnet#525]
I can log exceptions in my own code to file with a quick try/catch, however I'm still getting "uncaught .NET exception" fatal crashes in some situations.

I assume either there's an error in ScriptHookVdotNET or I'm passing it bad data that's not parsed til its out of my code... so how might I be able to track what these errors are?

The debugger popup is entirely useless. **EDIT: `An unhandled exception of type 'System.AccessViolationException' occurred in ScriptHookVDotNet.asi`... rather interesting, some data is wrong somewhere below the C# level I think is what this means, but I dunno**

What can I do to better debug this?

**Comment by zorg93** [comment]
Does the Log file yield an information about where the error occured. Trying to debug the same way you debug c# applications normally wont work for gta v mods

**Comment by mcmonkey4eva** [comment]
Log file has no reference to the error at all.

**Comment by zorg93** [comment]
Thats weird, though the error is due to writing to unallocated memory, are you by any chance directly using unsafe code in your c# file, if so can you show me

**Comment by mcmonkey4eva** [comment]
I don't use C#'s "unsafe" system at all in this project.

The worst I've got currently is a few direct hash Function call's

**Comment by zorg93** [comment]
@mcmonkey4eva did you ever figure it out?

**Comment by mcmonkey4eva** [comment]
Nope! Also haven't ran the mod in a while because this bug in particular alongside a few others has made me rather discouraged to keep at it. Also my co-developer on the project is MIA, slowing things down further. :/

Do... any functions require pointers? I thought they just all took IDs for things. (EG Ped handle's or whatever)

I don't think I use any functions that return data as pointers, as I'm not entirely sure... how to even do that from the C# end.

**Comment by zorg93** [comment]
some natives may require pointers that you called with their hash

**Comment by mcmonkey4eva** [comment]
I usually check NativeDB for anything weird like that before using a hash. Also just to get the correct arguments in the correct order too lol

**Comment by Fireboyd78** [comment]
When the exception gets thrown, is there any more information? Can you recreate it for us?

**Comment by mcmonkey4eva** [comment]
Seems to have stopped in some GTAV/ScriptHook update...
