### ISSUE TITLE
Update Game.Version

### ISSUE THREAD

**Issue by sollaholla** [crosire/scripthookvdotnet#526]
It would be nice to have an updated Game.Version, so I know when people are using cracked versions to run my mods. (the enum is what i mean)

**Comment by zorg93** [comment]
Im confused as to what you're asking. The enum has all game versions

**Comment by sollaholla** [comment]
@zorg93 Sorry, haven't checked since the last time I brought it up on gitter. It was only about a couple weeks ago. I was trying to do `Game.Version.ToString()` and wasn't getting the correct value (sometimes it would just return an empty string).

**Comment by zorg93** [comment]
Im guessing you were using a version of the game that was released after the version of scripthookvdotnet was released, resulting in the GameVersion enum not being defined for version being game version you were playing on

**Comment by sollaholla** [comment]
@zorg93 Probably. Thanks for letting me know it's up to date.
