### ISSUE TITLE
ScriptHookVdotNet.dll in scripts folder prevents scripts from loading

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#532]
I know we currently have it say a warning when it detects ScriptHookVDotNet.dll inside the scripts folder, but is there to force the scripts use the asi as a reference instead of trying to use the dll inside the scripts folder

**Comment by crosire** [comment]
The way it works is that SHVDN waits for the scripts to call the assembly resolve handler on loading, which doesn't happen if the reference was already resolved due to the DLL in the scripts folder. I don't think there is a way around that.

**Comment by zorg93** [comment]
So basically users need to read what the log says(like that happens all the time). Perhaps a better solution instead of just writing warning in the log file is display a critical error message that then closes the game telling people to remove the ScriptHookVDotNet.dll file from their scripts folder. It will make things as crystal clear as is physically possible for people wondering why no scripts are running

**Comment by crosire** [comment]
Sounds good. Problem I see is that initialization code happens late in the game loading state, so the message box may get hidden behind the fullscreen game window. And opening it in DllMain isn't an option, because of the loader lock.

**Comment by JohnnyCrazy** [comment]
Uhm, what about a console error-/warning-message? Since the console script should always load independently?

**Comment by zorg93** [comment]
Not sure why you are against including the check in DllMain, it seems to be the perfect place for it
![image](https://cloud.githubusercontent.com/assets/5469473/16950319/9059a966-4db7-11e6-9512-c0279750f203.png)

**Comment by crosire** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/dn633971(v=vs.85).aspx#general_best_practices

It may work for you now, but is likely crash for others. `MessageBoxA` blocks the calling thread. And doing that inside the loader lock is a really bad idea.

**Comment by zorg93** [comment]
Pretty sure scripthookv uses the same setup for invalid game versions and other fatal initialisation errors

**Comment by crosire** [comment]
That doesn't mean it's good programming practise and we have to do it too.

**Comment by zorg93** [comment]
The idea is you want to block the calling thread so the game wont carry on getting to boot up. Obviously a message box that's not meant to kill the process should be on a different thread

**Comment by crosire** [comment]
Like I said. Can crash or get caught in an infinite loop. It might not get to the point of actually displaying the message box. Probably not going to happen because `user32.dll` is very likely to be already in memory at the point that the ASI files are loaded. Still bad practise.
In the end, it doesn't matter much. The `Main.cpp` file is a mess already anyway.

**Comment by DorCoMaNdO** [comment]
Wouldn't deleting/moving/renaming the file be the simplest solution? Before you attempt to load any scripts, check if ScriptHookVDotNet.dll is in the scripts folder for whatever reason, if it is delete/move/rename it, that way the scripts won't load it when you attempt to load them and everything should keep functioning properly.

**Comment by crosire** [comment]
We came up with a solution that does a check on each assembly via `AssemblyName.GetAssemblyName(filename)` before starting the load process. All SHVDN assemblies are then removed. So basically what you just mentioned, yes.
