### ISSUE TITLE
Scripted Third Person Camera?

### ISSUE THREAD

**Issue by ReallyComeOn** [crosire/scripthookvdotnet#539]
I'm trying to make a new custom third person camera and I'm having some issues, the player doesn't move correctly and the camera's rotation is not moving right, it only turns where the player head is pointing.

Heres what I have in onKeydown: 

```
 camera = World.CreateCamera(new Vector3(player.Position.X, player.Position.Y, player.Position.Z + 0.7f), new Vector3(player.Rotation.X, player.Rotation.Y, player.Rotation.Z), GameplayCamera.FieldOfView);
                    World.RenderingCamera = camera;
```

Heres what I have in onTick:

```
camera.Position = new Vector3(player.Position.X, player.Position.Y, player.Position.Z + 0.7f);
                camera.Rotation = player.Rotation;
```

So what i'm asking is what steps do I take to get the camera to act like a normal third person camera, if that makes sense?

**Comment by crosire** [comment]
The code does exactly what you describe is happening. If you want the camera to look at the player and not in the same direction the player is looking, you have to construct such a rotation first with some simple vector math. For example by rotating between the camera forward vector and the vector that spans between the player and camera position.

**Comment by ReallyComeOn** [comment]
I figured out a way to get the rotations working properly, but I can't seem to fix the player's controls while the camera is active because the player will move depending where the mouse is pointing and the player will always run/walk?

**Comment by crosire** [comment]
For general programming advice please use the Gitter chat room of this project. The issues page is reserved for bug reports and enhancement ideas.
