### ISSUE TITLE
Scripthookvdotnet not working(CASE CLOSED)

### ISSUE THREAD

**Issue by earthspace1** [crosire/scripthookvdotnet#543]
Scripthookvdotnet  is not working for me, i tried everything, reinstalled gta v, redownload Scripthookvdotnet  and Scripthookv, my Scripts are not working. i have Watch Dogs Hack installed and its now showing anything

the Scripthookvdotnet log says                              Im running Gta5 1.0.791.2 and Scripthookvdotnet 2.9.2

Found 0 Scripts on all of my Scripts                 Now Working

**Comment by zorg93** [comment]
Do you have ScriptHookVDotNet.dll in your scripts folder?

**Comment by earthspace1** [comment]
No, i dont have it in scripts folder, do i need it.

**Comment by crosire** [comment]
Nope. Don't put in in there. It's the number one reason why the issue you are describing occurs for some people, which is why zorg93 brought it up. Can't think of anything else that could cause this actually.

**Comment by zorg93** [comment]
@earthspace1 Did you identify the issue causing this to not work so others can know the solution
