### ISSUE TITLE
Creating new Threads

### ISSUE THREAD

**Issue by zorg93** [crosire/scripthookvdotnet#545]
I see many mods using tricks like mutliple GTA.Script classes to enable essentially running 2 threads capable of calling natives in a mod. A much nicer solution would be to have a system in place where you can start and stop custom threads that will let users invoke natives in them, and they can start and stop as many of them as they like

**Comment by Nacorpio** [comment]
Sounds great!

**Comment by Guad** [comment]
Yes, please :+1:

**Comment by tryzombie501** [comment]
This would be a dream come true.

**Comment by RainerHilmer** [comment]
Yep even a simple thing like this
```C#
var notification = UI.Notify("blah");
Wait(2000);
notification.Hide();
```
needs a workaround through a separate notifier script with a static mediator class in-between because the code above would block the whole script for 2 seconds.

**Comment by DurtyFree** [comment]
Checked the WIP by @Tanjitsu in #659 and I am wondering why this isn't yet available in SHVDN3?

**Comment by crosire** [comment]
Closing since #886 is now merged and addresses this.
