### ISSUE TITLE
Instantiating a new copy of a script during runtime possible?

### ISSUE THREAD

**Issue by bilago** [crosire/scripthookvdotnet#549]
I hope this was the right spot to ask about this.

Lets say I have this script:

```
public class AIScript : Script
{
    private Vehicle Veh;
    public AIScript(Vehicle v)
     {
       Veh = v;
        Tick+=AIScript_Tick;
      }
    public void AIScript_Tick()
    {
      //do stuff with var Veh;
     }
}
```

Is there a way I can instantiate this (in its own thread) with a specified vehicle from within another script? like this?

```
InstaniateAI(Vehicle v)
{
   var controller = new AIScript(v);
}
```

I tried doing this, and while the function is called, its not started as its own script.

**Comment by bilago** [comment]
Your source code you have this function:

Script ^ScriptDomain::InstantiateScript(Type ^scriptType)

Any chance you can make this public so we can do something like:

```
InstaniateAI(Vehicle v)
{
   var controller = new AIScript(v);
    Script.Insantiate(controller);
}
```

**Comment by crosire** [comment]
No. That's not how scripts are supposed to be used. They are single exclusive instances. What you can do is communicate between them and lets say have a list of vehicles in your `AIScript` that it operates on and to which you add or remove vehicles from a second script.

**Comment by bilago** [comment]
Thanks for the reply.

That's currently what I've been doing, it is just turning into a coding nightmare trying to manage the AI of 30 different vehicle types all within the timing of a single instance. (Like if I want a vehicle to do x while y is true, I can't just wait since it will block the 29 other vehicles AI)

**Comment by crosire** [comment]
You can easily clean that up:
```c#
public class AIScript : Script
{
    List<AIController> _controllers = new List<AIController>();

    public AIScript() { Tick += OnTick; }

    void OnTick(object sender, EventArgs e)
    {
        foreach (AIController c in _controllers)
        {
            c.DoTick();
        }            
    }
}
private class AIController
{
    Vehicle _v;

    public AIController(Vehicle v) { _v = v; }

    public void DoTick()
    {
        // do stuff with vehicle
    }
}
```
