### ISSUE TITLE
How to get all 3d position of pixel in rendering camera?

### ISSUE THREAD

**Issue by amyburden** [crosire/scripthookvdotnet#562]
```_WORLD3D_TO_SCREEN2D``` Convert a world coordinate into its relative screen coordinate. Is there existing a function or method do the other way. In other word, convert 2D in rendering camera to 3D coordinate so that I can get depth image of camera.

**Comment by zorg93** [comment]
you'd need to do a raycast from the camera in the direction that its pointing, taking into account things like the camera field of view etc

**Comment by amyburden** [comment]
Thank you for replying and I would like to know which method can do the raycast. BTW, the raycast will finally be cast on some object and then I can get the coordinate of the ray point. Is that right?

**Comment by amyburden** [comment]
I found DRAW_SPOT_LIGHT may satisfy the function which cast a light to certain direction. After casting, how can I get the spot of object?

**Comment by crosire** [comment]
zorg93 meant `GTA.World.Raycast(...)`

**Comment by amyburden** [comment]
Thx 👍
