### ISSUE TITLE
RaycastResult

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#563]
My Sample code is:

RaycastResult location = World.GetCrosshairCoordinates();
if (location.DitHit) {}

Output is:
GTA.RaycastResult does not contain a definition for DitHit

Possible Solution:
GTA.RaycastResult Line 16

Change  
Hash.GET_SHAPE_TEST_RESULT 
To
Hash._GET_RAYCAST_RESULT

**Comment by electricman226** [comment]
The word 'did'is ended with a 'd, not a 't'.

**Comment by Tanjitsu** [comment]
I located the correct variable as "DitHitAnything".

Below page contains incorrect Ref.
https://github.com/crosire/scripthookvdotnet/search?utf8=%E2%9C%93&q=DitHit+

Working Example:

RaycastResult location = World.GetCrosshairCoordinates();

if (location.DitHitAnything)
{
      Vector3 position = location.HitCoords;
}


Or using Native:

Vector3 distant = GameplayCamera.GetOffsetInWorldCoords(new Vector3(0f, 1000f, 0f));
int handle = Function.Call<int>(Hash._CAST_RAY_POINT_TO_POINT, GameplayCamera.Position.X, GameplayCamera.Position.Y, GameplayCamera.Position.Z, distant.X, distant.Y, distant.Z, -1, 0, 7);

bool hit;
OutputArgument coords = new OutputArgument();
OutputArgument surface = new OutputArgument();
int entity;

unsafe
{
        Function.Call<int>(Hash._GET_RAYCAST_RESULT, handle, &hit, coords, surface, &entity);
}

if (hit)
{
        Vector3 position = coords.GetResult<Vector3>();
}
