### ISSUE TITLE
create GUI ?

### ISSUE THREAD

**Issue by SkelletonX** [crosire/scripthookvdotnet#565]
How can I create a GUIMENU with scripthookvdotnet ?

**Comment by electricman226** [comment]
Not sure exactly what you mean by GUI, but NativeUI is good for trainers.
Look in the UI namespace for some UI features.

**Comment by SkelletonX** [comment]
@electricman226  exemple code brow plz ?

**Comment by electricman226** [comment]
Not at my computer, but there are some examples on their forum [here](http://gtaforums.com/topic/809284-net-nativeui/).

If you want examples for UI code, look through the source of the repo, don't expect me (or others) to spoon-feed you everything line for line.

**Comment by SkelletonX** [comment]
@electricman226 thanks you brow :)
