### ISSUE TITLE
World.GetAllBlips()

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#567]
Hey, 

This maybe a question, using Dev Branch 3....

```
Blip[] blips = World.GetAllBlips();
if (blips.Length > 0)
{
   foreach (Blip blip in blips)
   {
       if (blip != null && blip.Exists())
       {
           if (blip.Entity != null && !blip.Entity.Exists() || !blip.Entity.IsAlive)
           {
               //blip.Entity.AttachedBlip.Delete();
               //blip.Delete();
           }
       }
   }
}
```

Produces

```
System.MemberAccessException: Cannot create an abstract class.
   at System.Runtime.Serialization.FormatterServices.nativeGetUninitializedObject(RuntimeType type)
   at GTA.Native.ObjectFromNative(Type type, UInt64* value)
   at GTA.Native.Function.Call[T](UInt64 hash, InputArgument[] arguments)
   at GTA.Blip.get_Entity()
```

Should i be using blip.Entity differently or is GTA.Blip.get_Entity() not working as intended ?

Regards,
Tanj

**Comment by Nacorpio** [comment]
Looks like it is not working like intended.
I recommend using the latest stable build until a developer has taken a look at it.

**Comment by Tanjitsu** [comment]
Thank you for confirming the question.
I wouldn't have stated this is relevant to the Dev Branch if i was using the latest stable build.
I was not asking for a Fix but rather questioning the Method.

**Comment by crosire** [comment]
Thanks for pointing this out. It should work now.

**Comment by Nacorpio** [comment]
NaCl.

**Comment by zorg93** [comment]
World.getAllBlips could be modified to use the blip pool directly
