### ISSUE TITLE
SteeringAngle,SteeringScale and Acceleration not working after game update.

### ISSUE THREAD

**Issue by Eddlm** [crosire/scripthookvdotnet#568]
vehicle.SteeringAngle, vehicle.SteeringScale and vehicle.Acceleration always return 0 after the Imports/Exports update.

This has [happened before](http://gtaforums.com/topic/789907-community-script-hook-v-net/?p=1069125246), and I can assume you guys will fix it, but I'm reporting the bug just in case.

**Comment by kagikn** [comment]
Now the properties work properly in v1.0.944.2, I forgot a closing commit mesage, though.
