### ISSUE TITLE
Scripthookvdontnet needs to be updated 

### ISSUE THREAD

**Issue by alexsantiago21** [crosire/scripthookvdotnet#569]
Scripthookvdotnet needs to be updated. The last update is out of date since the a new GTA Import/Export update. Take your time if you need too. I understand you have a life

**Comment by kagikn** [comment]
Some ped and vehicle field offsets are changed in Import/Export update, so we'll update SHVDN and release v2.9.4.

**Comment by kagikn** [comment]
This issue have been solved.
