### ISSUE TITLE
Add Particle Support

### ISSUE THREAD

**Issue by ricci07** [crosire/scripthookvdotnet#57]
If you are thinking about a implementing a particle fx class/enum, this may come in useful. I have been extracting a lot of string literals recently from the scripts, here is one dump. Not sure if this is all as It doesn't look a lot considering the size of GTA IV's.

scr_fbi_falling_debris
scr_fbi_dd_breach_smoke
scr_agency_atrium_glass
scr_agency3a_door_hvy_stat
scr_agency3a_door_hvy_trig
scr_fbi_exp_building
scr_fbi_ext_blaze
scr_fbi_ext_rooftop
scr_fbi_mop_drips
scr_fbi_mop_squeeze
scr_agency3b_blding_smoke
scr_agency3b_linger_smoke
scr_agency_door_haze
scr_agency3b_proj_rpg_trail
scr_agency3b_shot_chopper
scr_agency_atrium_silt
scr_agency3b_heli_expl
scr_agency3b_heli_exp_trail
scr_agency3b_wood_splinter
proj_grenade_trail
scr_env_agency3b_smoke
smoke
cinder
debris
smoke_strength
speed
scr_agency3b_elec_box
scr_crate_drop_flare
scr_sh_lighter_flame
scr_sh_lighter_sparks
scr_sh_bong_smoke
cs_water_boat_prop
cs_water_boat_Jetmax_bow
forward
ent_anim_leaf_blower
scr_ojbusass_bus_impact
scr_alien_teleport
scr_alien_impact
scr_alien_beam
scr_alien_charging
scr_alien_disintegrate
scr_clown_appears
scr_clown_death
scr_carsteal4_tyre_spiked
scr_carsteal5_car_muzzle_flash
scr_carsteal5_tyre_spiked
scr_carsteal4_wheel_burnout
ent_amb_car_wash
ent_anim_dog_poo
ent_anim_dog_peeing
scr_bio_flare
scr_pls_sub_water_drips
flow
scr_ex1_heatseeker
scr_ex2_chop_trail
scr_ex2_rpg_trail
scr_ex2_jeep_engine_fire
scr_ex2_car_impact
scr_ex2_car_slide
scr_ex3_engine_fire
scr_ex3_container_smoke
scr_ex3_water_dinghy_wash
scr_extrm2_moving_cloud
scr_rcext2_cargo_smoke
scr_rcext2_ramp_scrape
scr_extrm4_water_splash
scr_extrm4_water_blood
damage
scr_fam1_veh_smoke
scr_fam1_blood_headshot
cs_cig_smoke
cs_cig_exhale_nose
cs_cig_exhale_mouth
ent_ray_fam3_dust_settle
wheelspin
scr_fam3_wheelspin_dirt
scr_fam4_trailer_sparks
scr_fam4_truck_vent
scr_trev_puke
cs_fam6_hair_snip
scr_fbi1_litter
scr_fbi_autopsy_blood
scr_fbi4_trucks_crash
scr_bio_cutter_nozzle
scr_bio_grille_cutting
scr_bio_cutter_flame
scr_bio_grille_singed
scr_bio_grille_break
bul_carmetal
muz_assault_rifle
scr_fbi5a_flare
scr_fbi5_dry_ice
scr_tunnel_vent_bubbles
open
FlareActivate
ped_talk_water
scr_fbi5_ped_water_splash
water_splash_ped_bubbles
scr_fin_fire_petrol_trev
scr_fin_env_trev_sky
scr_fin_trev_car_impact
scr_finale2_blood_entry
scr_bigscore_peeing
scr_bigscore_ramp_sparks
scr_bigscore_tyre_spiked
scr_bigscore_rpg_trail
scr_mp_splash
scr_mp_dust_cloud
scr_mp_plane_landing_tyre_smoke
scr_mp_intro_plane_exhaust
scr_franklin0_chop_trail
ent_anim_cig_smoke_car
ent_anim_cig_smoke
ent_anim_cig_exhale_mth_car
ent_anim_cig_exhale_nse_car
ent_anim_cig_exhale_mth
ent_anim_cig_exhale_nse
scr_golf_landing_water
scr_golf_ball_trail
SCR_TREV_PUKE
ent_amb_insect_plane
scr_jew_biKe_burnout
scr_jewel_cab_smash
scr_josh3_light_explosion
scr_josh3_exp_debris
scr_josh3_fires
scr_josh3_explosion
scr_lamar1_fire_spread1
scr_lamar1_fire_spread
scr_sol1_plane_wreck
scr_sol1_plane_crash_dust
scr_sol1_plane_smoke_loop
scr_sol1_sniper_impact
scr_sol1_plane_smoke
Shot1
Shot2
Shot3
cs_mich1_spade_dirt_throw
scr_abattoir_ped_sliced
scr_abattoir_ped_minced
scr_pts_headsplash
scr_mich2_spark_impact
scr_mich2_blood_stab
scr_acid_bath_splash
scr_rcpap1_camera
scr_rcpap1_champ_slosh
scr_rcn2_debris_trail
scr_rcn2_ceiling_debris
scr_obfoundry_cauldron_steam
ent_amb_shower
ent_amb_shower_steam
scr_sh_cig_smoke
scr_sh_cig_exhale_mouth
scr_sh_cig_exhale_nose
damage_smoke
damage_fire
scr_lamgraff_paint_spray
scr_property_leaflet_drop
spawn
scr_pro_door_snow
scr_prologue_door_blast
scr_prologue_vault_haze
scr_prologue_ceiling_debris
scr_sparking_generator
scr_reconstruct_pipefall_debris
scr_reconstruct_pipe_impact
scr_burial_dirt
scr_wheel_burnout
scr_recrash_rescue_fire
scr_puke_in_car
scr_paleto_banknotes
scr_paleto_roof_impact
scr_paleto_heli_plume
scr_paleto_doorway_smoke
cs_paleto_blowtorch
cs_rbhs_int_delap_dust
scr_alarm_damage_sparks
scr_trev4_747_engine_damage
scr_trev4_747_blood_impact
scr_trev4_747_exhaust_plane_misfire
scr_trev4_747_engine_debris
scr_trev4_747_engine_heathaze
scr_trev4_trailer_fire
scr_ojtaxi_hotbox_trail
scr_ojtaxi_hotbox_door
scr_ojtaxi_hotbox_window
scr_tennis_ball_trail
scr_ojtt_train_sparks
scr_drug_grd_plane_exp
scr_drug_grd_train_exp
scr_ojdg4_water_exp
scr_ojdg4_boat_exp
scr_ojdg4_boat_wreck_fire
scr_ojdg4_train_fire
scr_drug_traffic_flare_L
scr_trev1_trailer_splash
Speed
scr_trev1_trailer_boosh
scr_trev1_crash_dust
scr_trev1_trailer_wires
scr_trev1_wheelspin_dirt
ent_ray_meth_dust_settle
scr_trev2_flare_L
scr_rotor_blade_blood
scr_trev2_heli_wreck
scr_trev3_trailer_plume

**Comment by AAYapps** [comment]
If there is a way to use particle effects, please help

I tried the GetGXTEntry

but nothing happened. I even have it in a loop

**Comment by PlayTilTheyBleed** [comment]
@AAYapps You've probably found the answer to this by now, but in case anyone  else is looking, this works for spawning particle effects. "playerPed" in the example represents what entity you want to attach the effect to. The three doubles following it are the offset from the entity's position. I'm not sure what the rest represent (if anyone can elaborate, I would appreciate it). The "scr_rcbarry2" and "scr_clown_appears" create the purple cloud and stringy FX. Just pop this into your code somewhere (don't call it in a loop!) and you should see a pretty purple cloud effect. =)

Function.Call(Hash._0xB80D8756B4668AB6, "scr_rcbarry2");
Function.Call(Hash._0x6C38AF3693A69A91, "scr_rcbarry2");
Function.Call(Hash._0x0D53A3B8DA0809D2, "scr_clown_appears", playerPed, 0.0, -2.0,  1.0, 0.0, 0.0, 0.0, 1.0, false, false, false);

**Comment by WingsOnHigh** [comment]
@AAYapps You've probably found the answer to this by now, but in case anyone else is looking, this works for spawning particle effects. "playerPed" in the example represents what entity you want to attach the effect to. The three doubles following it are the offset from the entity's position. I'm not sure what the rest represent (if anyone can elaborate, I would appreciate it). The "scr_rcbarry2" and "scr_clown_appears" create the purple cloud and stringy FX. Just pop this into your code somewhere (don't call it in a loop!) and you should see a pretty purple cloud effect. =)

Function.Call(Hash._0xB80D8756B4668AB6, "scr_rcbarry2");
Function.Call(Hash._0x6C38AF3693A69A91, "scr_rcbarry2");
Function.Call(Hash._0x0D53A3B8DA0809D2, "scr_clown_appears", playerPed, 0.0, -2.0, 1.0, 0.0, 0.0, 0.0, 1.0, false, false, false);

**Comment by crosire** [comment]
Support for particle effects was added in commit a21cc49e488a678d7a57942a28a5609bde614595. Closing this issue.
