### ISSUE TITLE
Namespace conflict when both shvdn and shvdn2 asis are installed

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#573]
Today I installed ScriptHookVDotNet2.asi and changed my VAutodrive mod to reference this assembly, which was no problem. However, there are older mods which reference ScripthookVDotNet.asi (V2.9.3) and so I keep this as well. Unfortunately at least some of those older mods cease to function. I think this is because both shvdn versions share the same namespace.

**Comment by crosire** [comment]
Download v2.9.4 again. The rename to ScriptHookVDotNet2.asi was a mistake that was fixed soon after.

**Comment by RainerHilmer** [comment]
Thanks :)

**Comment by RainerHilmer** [comment]
Oh and I hope there will be no namespace conflict once we get shvdn 3. You we have to keep both versions  or older mods which aren't updated anymore will cease to run and that would be a bummer because there are some real good ones out there. Old but great.
