### ISSUE TITLE
Correct way to deal with multiple pointers

### ISSUE THREAD

**Issue by twmht** [crosire/scripthookvdotnet#575]
Hi,

I want to deal with the api in PATHFIND

```
static Vector3* GENERATE_DIRECTIONS_TO_COORD(float x, float y, float z, BOOL p3, float* p4, float* p5, float* p6) { return invoke<Vector3*>(0xF90125F1F79ECDF8, x, y, z, p3, p4, p5, p6); } // 0xF90125F1F79ECDF8 0xED35C094
```

the api returns a pointer to Vector3 and three pointers to the floating values are required.

I can get the returned values by the following definition

World.hpp
```
static Math::Vector3^ GenerateDirectionsToCoord(Math::Vector3 target, bool unknown);

```

World.cpp
```
 Math::Vector3^ World::GenerateDirectionsToCoord(Math::Vector3 target, bool unknown) {
		Native::OutputArgument ^p4 = gcnew Native::OutputArgument();
		Native::OutputArgument ^p5 = gcnew Native::OutputArgument();
		Native::OutputArgument ^p6 = gcnew Native::OutputArgument();
        Math::Vector3 ^direction = Native::Function::Call<Math::Vector3>(Native::Hash::GENERATE_DIRECTIONS_TO_COORD, target.X, target.Y, target.Z, unknown, p4, p5, p6);
        //Native::Function::Call<float>(Native::Hash::GENERATE_DIRECTIONS_TO_COORD, target.X, target.Y, target.Z, unknown, p4, p5, p6);
        return p6->GetResult<Math::Vector3>();
    }
```

myScript.cs
```
Vector3 direction = WorldGenerateDirectionsToCoord(target, true);
```

How can I write a wrapper to get the other floating values?

**Comment by crosire** [comment]
You don't need to modify SHVDN to do that. In a C# script write the following:
```
Vector3 GenerateDirectionsToCoord(Vector3 target, bool p3, out float p4, out float p5, out float p6)
{
    OutputArgument out4 = new OutputArgument(), out5 = new OutputArgument(), out6 = new OutputArgument();
    Vector3 result = Function.Call<Vector3>(Hash.GENERATE_DIRECTIONS_TO_COORD, target.X, target.Y, target.Z, p3, out4, out5, out6);
    p4 = out4.GetResult<float>();
    p5 = out5.GetResult<float>();
    p6 = out6.GetResult<float>();
    return result;
}
```

**Comment by twmht** [comment]
@crosire  thanks!

**Comment by zorg93** [comment]
I know this has been closed, but Im kind of unsure why that function is listed as returning a vector3 Pointer. A quick disassembly shows that the return value is always set to 0(checked on version 335 and 944)
http://i.imgur.com/LzXAQld.png

**Comment by twmht** [comment]
@zorg93 

yup! The function always returns zero, but I am not sure why the returned value is defied as a pointer to Vector3.

And, p5 is always zero, too.

Btw, which tool you used to analyze the returned value?

**Comment by zorg93** [comment]
IDA, anyway I updated the native on nativeDB.
That native is weird, i dont think you even get meaningful stuff from any of the pointer parameters

**Comment by twmht** [comment]
@zorg93 

In fact, p4 is an integer which indicates the navigation, and p6 is a distance when turning right or left.

the remaining mystery is the meaning of p3 and p5.

More details can be found at http://gtaforums.com/topic/869246-gps-points-native/
