### ISSUE TITLE
[Question] How to make Ped creation callbacks?

### ISSUE THREAD

**Issue by TheFuseGamer** [crosire/scripthookvdotnet#576]
Hello. I'm trying to make some kind of a multiplayer mod and I need to stop peds/vehicles/props from spawning and remove the ones I don't need. So is there a way to detect when peds are created so I can check if they belong to a remote player or they should be deleted or are there better ways to make peds and vehicles server sided?

**Comment by electricman226** [comment]
In the current version, no.

I recommend using World#GetAllEntities to compare their handles to a List of handles that you want to keep.
ex: 
```csharp
List<int> allowedHandles = new List<int>();
foreach(Ped p in World.GetAllPeds())
  if(!allowedHandles.Contains(p.Handle)
    p.Delete();
```
Don't store the Entity Object in the List, of course; only use the Handle.

**Comment by TheFuseGamer** [comment]
Thanks for the answer. That's the idea I had in mind but I thought it could be unefficent to run it in the main loop especially that I'm going to do the same thing for vehicles and props probably

**Comment by Nacorpio** [comment]
@electricman226 There's no need to use a list for that; a `HashSet<int>` would do the job.

**Comment by electricman226** [comment]
@Nacorpio Thanks mate, fixed that in my reply.

**Comment by mcmonkey4eva** [comment]
I can confirm it's safe to do a loop through all entities in a script loop: I do it myself in my own project :P

**Comment by TheFuseGamer** [comment]
What about player events like player death or shots fired? Is it also safe to detect those manually in a loop?

**Comment by Nacorpio** [comment]
@TheFuseGamer I'm currently developing a wrapper doing exactly that for my current project.

**Comment by TheFuseGamer** [comment]
@Nacorpio Great. I hope you release it soon.

**Comment by Nacorpio** [comment]
@TheFuseGamer I'm probably not releasing it publically, but you can contact me if you are interested.

**Comment by Nacorpio** [comment]
@TheFuseGamer Are you trying to create a mod that lets you host your server for your friends to join, by the way?

**Comment by TheFuseGamer** [comment]
@Nacorpio I am, yeah. But I don't have any friends in mind to play with so I'm just doing it for fun.

**Comment by Nacorpio** [comment]
@TheFuseGamer I don't have any serious ongoing projects currently, so I could help you if you want.

**Comment by TheFuseGamer** [comment]
@Nacorpio Cool. I'm not familiar with github so how would I go about letting you help?

**Comment by Nacorpio** [comment]
@TheFuseGamer Do you have Discord or Skype?

**Comment by TheFuseGamer** [comment]
Skype. Not sure if it's alright for me to post it here though.

**Comment by Nacorpio** [comment]
I don't think it would be too much of an issue.

**Comment by zorg93** [comment]
what you are asking requires hooking so isn't possible with this(or .net languages in general) you would need to use C++ and a hooking library for that
