### ISSUE TITLE
How to deal with the long task

### ISSUE THREAD

**Issue by twmht** [crosire/scripthookvdotnet#577]
I have a long task in `onTick`

```
void onTick(object sender, EventArgs e) {
    if (!init) {
        result=longTask();
        init=true;
    }
    // use result below
}
```

whenever I refresh the script,  `longTask()` is executed again. And the game will be stuck and not responding a while.

Is there way to prevent the game not responding?

Thanks!

**Comment by zorg93** [comment]
what on earth do you have running in long task that causes the game to freeze for a while? anyway the solution is to use Script.Yield() throughout the task so that the game can do whatever it needs to do inbetween executing your task

**Comment by crosire** [comment]
Or run the task in a separate thread if it is not referencing anything of the GTA namespace.

**Comment by twmht** [comment]
In fact, the long task is required to run only once.
When loading into the story mode, the task will be executed.
But I only want the task to be executed only once, even though I tried to refresh the script.

the problem is that, I have to fetch the result of the long task, I tried to store the result as a class member, but the results always is destroyed whenever I refresh the script.

So I want a way to permanently store the result.

**Comment by crosire** [comment]
Serialize the result to a file and check if that file exists at script start. If it does, deserialize the result from the file, otherwise run the task.

**Comment by crosire** [comment]
Reloading a script destroys and recreates the entire .NET appdomain, so anything you store in memory is lost. There is no way around using some other media like the disk.

**Comment by twmht** [comment]
@crosire 

I see.

thanks!

**Comment by kagikn** [comment]
If we could get session ids, it would be more convenient, but `GET_IS_LOADING_SCREEN_ACTIVE` will help you.
