### ISSUE TITLE
Update hash lists

### ISSUE THREAD

**Issue by mcmonkey4eva** [crosire/scripthookvdotnet#578]
There's new vehicles in particular in the latest GTAV updates!

Aqua Technical and Rocket Voltic don't appear to be anywhere on the list, probably others were added as well.

EDIT: For reference, the DLC update internal name is `mpimportexport` and has quite a bit in it.

**Comment by mcmonkey4eva** [comment]
I seem to actually be having trouble spawning them at all, I got the hash for `voltic2` and spawned it in (The Rocket Voltic), but it disappears if I attempt to get in it!

**Comment by kagikn** [comment]
mpimportexport and Spawn MP Vehicles in SP can enable you to spawn MP DLC vehicles, use either of them.

**Comment by mcmonkey4eva** [comment]
Use... the DLC in and of itself, or ... not sure what the second is, but I assume that's some external mod.


I can spawn any other earlier MP DLC vehicles just fine. EG I use `kuruma2`, the armored kuruma from the MP heists DLC, all the time...

**Comment by kagikn** [comment]
Oh, the second is "Spawn MP Vehicles in SP".

**Comment by mcmonkey4eva** [comment]
Oh they're both mod titles apparently.

... This definitely needs to be native functionality of ScriptHookVDotNet, as it allows spawning literally every other vehicle type excluding the mpimportexport DLC vehicles, which I assume is purely because it hasn't been updated to work with them yet.


Also, for reference, I'm working with v3 of SHV.NET (not v2).

**Comment by mcmonkey4eva** [comment]
I made a function in C++ to fix it, added to the SHV.NET files and recompiled... trigger the function, and then you can spawn in voltic2 or any other new vehicle without it disappearing :3
here's the code, I'm sure there's a neater way to do it but this serves as a placeholder / might help find the 'clean' way of doing it:
```cpp
		void MONKEYHELPER::AttemptVehicleFix()
		{
			// Only for game versions >= 28
			Int64 i64;
			Int64* i64ptr;
			*reinterpret_cast<Int32*>(&i64) = 0x279476;
			*reinterpret_cast<Int32*>(reinterpret_cast<Int64>(&i64) + 4) = 0;
			i64ptr = reinterpret_cast<Int64*>(getGlobalPtr(i64));
			*i64ptr = 1;
		}
```

Pay no mind to the oddity of this, it's semigenerated code.

**Comment by crosire** [comment]
This was deliberatly removed from SHVDN a few updates back because it was too much effort to maintain, when there are mods already that solve the issue.

**Comment by zorg93** [comment]
that code is horrible btw. If you ever did want to do it in c++ then
`*reinterpret_cast<__int64*>(getGlobalPtr(0x279476)) = 1;`

**Comment by mcmonkey4eva** [comment]
OP Request done via https://github.com/crosire/scripthookvdotnet/pull/579 and I guess the secondary request ain't happening :(

**Comment by kagikn** [comment]
As crosire said, we don't accept the secondary request anymore.
