### ISSUE TITLE
How to test Script Hook V .Net for GTA5?

### ISSUE THREAD

**Issue by monajalal** [crosire/scripthookvdotnet#581]
Please have a look at my question here:
http://gaming.stackexchange.com/questions/296780/how-can-franklin-not-lose-the-game-because-of-lamar?noredirect=1#comment419427_296780

 I have installed Script Hook v dot net, script hook v, and Lua Plugin with Lua scripts and CSharp example scripts. However, while f4 works for indication of successful installation of script hook v, how can I make sure that script hook v .Net is also properly setup? How can I test it? I can't find a step-by-step video or tutorial for this purpose.

**Comment by Nacorpio** [comment]
By checking the log.
