### ISSUE TITLE
Need help with a migration issue from shvdn2 to shvdn3

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#583]
Hi, I am currently migrating some mods for shvdn3 and I need some help. Visual studio tells me the method World.SetRelationshipBetweenGroups doesn't exist. What do I need to code instead?
``` C#
      /// <summary>
      /// Changes the relationship between two peds.
      /// </summary>
      /// <param name="ped">The ped.</param>
      /// <param name="otherPed">The other ped.</param>
      /// <param name="relationship">The relationship.</param>
      public static void ChangeRelationshipTo(this Ped ped, Ped otherPed,
         Relationship relationship)
      {
         //Getting player relation ship group
         int i = Function.Call<int>(Hash.GET_PED_GROUP_INDEX, ped);

         //Set relationship group
         Function.Call(Hash.SET_PED_AS_GROUP_MEMBER, otherPed, i);

         //Set relationship between groups
         World.SetRelationshipBetweenGroups(relationship,
            ped.RelationshipGroup, otherPed.RelationshipGroup);
      }
```
Also the vehicle.CloseDoor method, the VehicleDoor enumeration and the PassengerSeats property don't exist anymore.

**Comment by Nacorpio** [comment]
`Vehicle.Doors`

**Comment by Tanjitsu** [comment]
ped.RelationshipGroup.SetRelationshipBetweenGroups(otherPed.RelationshipGroup, Relationship.Hate);

**Comment by RainerHilmer** [comment]
Thank you @Nacorpio and @Tanjitsu for your help. :)
Just to make it complete: Vehicle.PassengerSeats was changed to Vehicle.PassengerCapacity.
@crosire As the title is generalized we could use this ticket for other people with migration issues as well.
