### ISSUE TITLE
using third-party library in the example project

### ISSUE THREAD

**Issue by twmht** [crosire/scripthookvdotnet#584]
Hi,

I am using the provided example project and I can add my own script here.

However, whenever I download the library using nuGet or manually using pre-built dll ( add the reference manually), .NET always throws the following exception (Here I use `Newtonsoft.json` as an example)

```
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
``` 

other libraries also have this problem (For example, `LoycCore`, https://www.nuget.org/packages/LoycCore/)

I am not sure if there is something wrong about the settings of the project.

thanks!

**Comment by crosire** [comment]
You need to put the DLL from the library in the scripts folder as well.

**Comment by JohnnyCrazy** [comment]
Even better: Use [ILMerge](https://www.microsoft.com/en-us/download/details.aspx?id=17630) to merge all your DLL's into one. This way you don't have to ship out your libraries as well

**Comment by twmht** [comment]
@crosire 

thanks!
