### ISSUE TITLE
World Get - Using Model[] models

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#587]
Example...
public static Prop GetClosestProp(Vector3 position, float radius, params Model[] models)

models is converted to a ModelHash list.

Since the storage of a hash list is simpler than the storage of whole models.
Would it not make sense for these functions to expect a ModelHash list.
Then instead, expose the ModelListToHashList function for those who are working with whole models.

If in an example i was to spawn a vehicle using...
Create Model from Hash.
Create Vehicle from Model.
Store ModelHash.
Dispose of Model.

I can not use the Dispose of Model, since i will need this to later locate the vehicle in World.GetClosestVehicle().
Or i will need to generate a new model to be passed to World.GetClosestVehicle()
even though World.GetClosestVehicle() does not need a model.

Model[] models = Array.ConvertAll<VehicleHash, Model>(StoredVehicleHashes.ToArray(), hash => new Model(hash));

Please correct me if i am wrong :)

**Comment by zorg93** [comment]
The idea behind using params is to make it easier for the user

**Comment by jtgibson01** [comment]
It shouldn't be too difficult to convert the function to accept a ModelHash array as the third parameter, and then provide an overload for a Models[] parameter that calls the ModelHash version.

**Comment by Tanjitsu** [comment]
That would make sense then both options can be kept but simplified.
