### ISSUE TITLE
How can I make any of the aircraft play using the game AI?

### ISSUE THREAD

**Issue by monajalal** [crosire/scripthookvdotnet#591]
I am using this code which works for any of the cars from GTA5. However when I select an aircraft say bersa, it doesn't work well, which I mean is not smart enough and seems the game AI is very off. I wonder if you know how can I change it so that it will work for an aircraft and also soar high rather than being on land?
*If you could also link me to possibly existing code that would be great as well.

https://github.com/ai-tor/DeepGTAV

**Comment by Nacorpio** [comment]
The ScriptHookVDotNet GitHub page is probably the worst choice for asking such a question.

**Comment by JohnnyCrazy** [comment]
Yes, this has nothing to do with SHV.NET. Either create a issue inside the `DeepGTAV`-repo or create a thread in the GTA-forums.
