### ISSUE TITLE
Getting error when trying to compile SDK

### ISSUE THREAD

**Issue by bwookzy** [crosire/scripthookvdotnet#592]
I get an error when trying to compile the SDK, and I also get a warning about ScriptHookVDotNet cannot be referenced! I don't know what is going on and I am an early developer so I don't know how to fix this!

Errors: 
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The project 'ScriptHookVDotNet' cannot be referenced. An assembly must have a 'dll' or 'exe' extension in order to be referenced.	ScriptHookVDotNetExamples			
Error	CS0006	Metadata file 'C:\Users\Censored\Desktop\scripthookvdotnet-dev_v3\bin\ScriptHookVDotNet3.asi' could not be found	ScriptHookVDotNetExamples	C:\Users\Censored\Desktop\scripthookvdotnet-dev_v3\CSC	1	Active

Thank you to anyone that helps me and fixed the issue or at least tries.

**Comment by electricman226** [comment]
Did you install the ScriptHookV SDK into the 'sdk' directory? It's required for ScriptHookVDotNet to compile successfully.

**Comment by electricman226** [comment]
You're trying to build the examples solution, not the base solution. Make sure you also install ScriptHookV SDK into your 'sdk' directory once you build ScriptHookVDotNet, and then build the examples.

**Comment by crosire** [comment]
Closing, since original poster did not provide further input since creation.
