### ISSUE TITLE
World.WaypointPosition returns empty vector sometimes

### ISSUE THREAD

**Issue by MissyMelissa** [crosire/scripthookvdotnet#594]
I believe (could be wrong, just assuming here from observations) this is because it calls `GET_GROUND_Z_FOR_3D_COORD` for the blip coordinate, which returns false when the given coordinate is in an area that doesn't have its geometry loaded.

When I move far away from the point this property returns an empty vector, and when I move close to it there's a correct result.

**Comment by TheChilliPL** [comment]
"which returns false when the given coordinate is in an area that doesn't have its geometry loaded." - good to know, I spent 2 hours or more trying to make simple teleport to waypoint on key press. Is there any way to get ground z from far away?

**Comment by MissyMelissa** [comment]
You should use an external height map. Not very practical, since the world is huge, and depending on the resolution you want, this heightmap would be huge.

**Comment by crosire** [comment]
See #647 and https://github.com/crosire/scripthookvdotnet/issues/180#issuecomment-315951336.
