### ISSUE TITLE
Camera direction is unstable

### ISSUE THREAD

**Issue by twmht** [crosire/scripthookvdotnet#595]
Hi,

I want to create a camera which looks behind traffic of the car.

```
World.DestroyAllCameras();
Vector3 position = VehPos;
float fov = 60.0f;
Camera camera = World.CreateCamera(position, rotation, fov);
Function.Call(Hash.SET_CAM_INHERIT_ROLL_VEHICLE, camera.Handle, true);
camera.AttachTo(veh, new Vector3(0f, 0.5f, 0.8f));
camera.IsActive = true;
World.RenderingCamera = camera;
```

something like this in `onTick`
```
 camera.Direction = -Game.Player.Character.CurrentVehicle.ForwardVector;
```

However, it may not look at the back of the car when car is moving.

It seems that dotnet transforms the direction into the rotation, but I don't understand the math behind.

Any advise?

thanks.

**Comment by crosire** [comment]
This isn't really the place to ask for general scripting advice, there are better places for that (GTAForums, Gitter chat, ...).
