### ISSUE TITLE
Could not load ScriptHookvDotNet.dll in c# console project

### ISSUE THREAD

**Issue by twmht** [crosire/scripthookvdotnet#597]
I have created an c# console project which needs some Math API behind ScriptHookVDotNet.

However, it can not load `ScriptHookVDotNet.dll` at runtime.

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'ScriptHookVDotNet.dll' or one of its dependencies. The specified module could not be found.
```

I have added `ScriptHookVDotNet.dll` in the application path, but still not worked.

Any idea?

**Comment by crosire** [comment]
SHVDN does not work outside GTA. There are much better solutions if you need a C# math API.

**Comment by twmht** [comment]
@crosire 

I am just curios why I can't find the dll.

but, I can not see any related settings insided the project.

In fact, I want to serialize `Vector3` in scriptHookvDotNet, can you give me some advises?

thanks!

**Comment by crosire** [comment]
The important part of the message is `or one of its dependencies`. It very likely finds the DLL, but SHVDN depends on additional tools like ScriptHookV.

**Comment by twmht** [comment]
@crosire 

ok! got it! I think the way to use `Vector3` is to export only the class to dll.
