### ISSUE TITLE
Detecting game shutdown

### ISSUE THREAD

**Issue by alex8b** [crosire/scripthookvdotnet#598]
It feels like Aborted and Dispose() are only triggering when I reload the mods with Insert, but not when I exit the game via Alt-F4 menu. Is there a way to subscribe for application quit? I need it to dispose things correctly and avoid game crashing on exit.

**Comment by kagikn** [comment]
I think it needs severe work, if not possible, when the game is crashed by invaid operations such as access violation.
Also, I've never heard someone definitely needed a way to detect game shutdown.
