### ISSUE TITLE
Script Hook V Critical Error::Unknown Game Version (for GTAV / GTA5)

### ISSUE THREAD

**Issue by monajalal** [crosire/scripthookvdotnet#599]
Can someone suggest how to solve this issue?
![capture](https://cloud.githubusercontent.com/assets/1892917/23224672/e6e0063e-f8f4-11e6-8773-fa947daa2d96.PNG)

```
// GTA V SCRIPT HOOK (build Mar 16 2016, v1.0.678.1)
//     (C) Alexander Blade 2015-2016
[11:47:26] INIT: Started
[11:47:26] FATAL: Unknown game version
```

Additionally, are you aware of a modding menu/method that is not dependent on DirectX for GTAV?

**Comment by crosire** [comment]
This is not related to SHVDN. SHVDN depends on SHV which needs an update to work with the latest game version. What this space for a new update to come out which supports the latest game version: http://www.dev-c.com/gtav/scripthookv/

Great UI library for SHVDN: https://github.com/Guad/NativeUI

**Comment by monajalal** [comment]
@crosire I have downloaded the latest version of script hook v and I am not sure why I receive this error.

**Comment by crosire** [comment]
The game received an update. Blade's SHV needs to update to reflect that. This hasn't happened yet. So you need to wait until it has. SHVDN/We can't do anything about it.

**Comment by ReagentX** [comment]
I am getting this error with a completely fresh install of GTAV from Steam. How can I get past it?

**Comment by electricman226** [comment]
When you delete or verify a games content on Steam, only those files that were downloaded are considered. You must delete SHV yourself by removing the ASI loader dinput8.dll
