### ISSUE TITLE
Text offsets, and centered text

### ISSUE THREAD

**Issue by sollaholla** [crosire/scripthookvdotnet#601]
Hi! I've been struggling with the new text system, and was getting really frustrated with the offset of the text in-game.

(It's probably worth noting i copy-pasted the existing code to put it in 2.9.4 and I'm not using IntPtr).

But I did some calculations and found exactly what works.

This is what I put in the InternalDraw function, at the very top.
```
float internalOffset = ScaledHeight /
                        (Font == GTA.Font.Pricedown || Font == GTA.Font.HouseScript
                            ? 2
                            : (Font == GTA.Font.Monospace 
                                ? Screen.AspectRatio 
                                : 1.5f)); // These are aspect ratios, assuming 1.5f is a perfect aspect ratio. and 2 being 

float x = (Position.X + offset.Width) / screenWidth;
float y = (Position.Y + offset.Height - internalOffset) / screenHeight;
float w = WrapWidth / screenWidth;
```
[Centers the text to it's origin when doing `width / 2, height / 2`]

And here's some of the properties that I believe would be of great use to some:
```
// Get's raw height value 0-1
public float RawHeight
{
    get { return Function.Call<float>((Hash)0xDB88A37483346780, Scale, (int) Font); }
}

// Get's text pixel height scaled to 720p
public float ScaledHeight
{
    get { return RawHeight * Screen.Height; }
}

// Get's actual height based on game resolution
public float Height
{
    get { return RawHeight * Game.ScreenResolution.Height; }
}
```
[These *actually* work, it blows my mind. You can legit get the text's total pixel height!!]

Hope someone can implement this and do the `internalOffset` some mathematical justice if it's wrong.

**Comment by kagikn** [comment]
No need to keep this open any longer IMO as we have implemented all the features except for the raw height.
