### ISSUE TITLE
ScriptHookVDotNet v2.9.4 not realoading when insert pressed

### ISSUE THREAD

**Issue by m3rkster** [crosire/scripthookvdotnet#605]
i do have problem with ScriptHookDotNet not reloading script when i press the insert i have tryed all sorts to get the reload key to work i.e. reinstalling gta removing the mods folder and try ScriptHookVDotNet alone to see if i had conflicting problems but didn't work. is there a fix for this i have search internet but no help its so annoying when i have to restart gta takes for ever to load back up any help will be appreciated 
Thanks in Advance

**Comment by m3rkster** [comment]
im such a eejit i forgot to make the .ini file just got it from 2.9.2 lol

**Comment by amirc2013** [comment]
how did you managed to fix it ?
