### ISSUE TITLE
SHVDN not working/loading in GTA V

### ISSUE THREAD

**Issue by tzioneretz** [crosire/scripthookvdotnet#610]
Hi guys, I'm really embarrassed to be asking this because I'm sure it's something really basic.

I'm trying to run Zach's Alfredo Helper (www.lcpdfr.com/files/file/12551-alfredo-helper-police-helperloadout-loading-script/) with no luck.  This is what I've done and what I have:

- put ScriptHookVDotNet.asi in my C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V directory
- created a scripts (small "s") folder in the same directory and put AlfredoHelper.dll in there, and that is the ONLY file in it
- have the latest version of ScriptHookV, which I know is working fine because the Player Location Display (http://www.lcpdfr.com/files/file/7706-player-location-display/) functions well
- have .NET framework 4.7
- have Microsoft Visual C++ 2015 (so NOT 2013: Does it make a difference?) Redistributable (x64) 14.0.23026
- have the latest and greatest, and fully legit, version of GTA V

Alfredo Helper is activated by pressing F7 in-game.  I have no conflicts with the F7 key that I know of.  When I press it though, nothing happens, and I don't know why.

Any ideas?

Can you suggest a simple script I could try to load, just to check whether it's the SHVDN that's the problem rather than the Alfredo Helper?

**Comment by kagikn** [comment]
You need to install Microsoft Visual C++ 2013 to work ScriptHookVDotNet, not 2015. They are different things even for non-developers.

**Comment by crosire** [comment]
You need the 2013 redistributable. Yes, there is a difference.

**Comment by tzioneretz** [comment]
You're right.  I just installed the 2013 version and the thing works.  I can't believe I was so dumb.  A lot of facepalming called for.

Thank you so much, guys!  I really appreciate your time and patience.
