### ISSUE TITLE
Unable to build project, XDC0002 Cannot write to output file

### ISSUE THREAD

**Issue by Rene-Sackers** [crosire/scripthookvdotnet#615]
I'm trying to compile the C++ project. I've added the SDK to the /sdk folder, but as soon as I compile, in VS2015, and VS2017, administrator or not, I'm getting [XDC0002 Cannot write to output file](https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(XDC0002)&rd=true)

The bin folder, and `ScriptHookVDotNet3.asi` are being made, but the .NET DLL isn't being outputted.

I'm not sure where to look for resloving this. What am I doing wrong?

**Comment by crosire** [comment]
https://github.com/crosire/scripthookvdotnet/blob/dev_v3/tools/XDCMake.cs#L117

Try to delete the `obj` directory. There may be some corrupt intermediate files that prevent saving.

**Comment by Rene-Sackers** [comment]
Sorry for the late response. I've tried that already, but the same issue occurs :(

**Comment by crosire** [comment]
Then modify the `XDCMake.cs` to output the exception message, rebuild the `XDCMake.exe` from it, replace the existing prebuilt version and run through the build process for the project again to get a more meaningful error message.

**Comment by Rene-Sackers** [comment]
Ok, I found the problem, and tried solving it, but I'm not entirely sure what I'm doing.
I have spaces in the path that the solution is set in, and here's a print of this code from XDCMake.exe:

```
Console.WriteLine("Args: " + string.Join("|", args));
```

```
Args: /old|ScriptHookVDotNet|/nologo|/Fo"C:\Users\renes\Documents\visual|studio|2017\Projects\ProjectSync\scripthookvdotnet\bin\ScriptHookVDotNet3.xml"|/Fs ...
```

It seems to be taking the spaces in the /Fo argument as separate arguments. Probably because `/Fo"C:\...` doesn't have a space between the argument and the value?

Do you happen to know how to fix this? I've found the XML Document Generator settings, but not sure what to change.

**Comment by crosire** [comment]
Should work now 😄.

**Comment by Rene-Sackers** [comment]
Perfect! Thanks man :)
