### ISSUE TITLE
Vehicle mods

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#62]
For some reason, Vehicle.SetMod doesn't work for me.
When I run the method, nothing happens to the target vehicle.

Am I the only one?

**Comment by IncoCode** [comment]
Just checked and found that need to call SET_VEHICLE_MOD_KIT befor SetMod.
```c#
Function.Call( Hash.SET_VEHICLE_MOD_KIT, veh.Handle, 0 );
veh.SetMod( VehicleMod.Spoilers, 2, true );
```

**Comment by JohnnyCrazy** [comment]
This is propably resolved (Some more comments about `SET_VEHICLE_MOD_KIT` are in #111)
