### ISSUE TITLE
How to get back to original Game camera

### ISSUE THREAD

**Issue by TheChilliPL** [crosire/scripthookvdotnet#621]
I created camera by code below
`var c = World.CreateCamera(new GTA.Math.Vector3(436f, -646f, 28.7f), new GTA.Math.Vector3(0, 0, 0), 100);
World.RenderingCamera;
World.RenderingCamera = c;`
(Ignore that c is accessible only from that function)

And even if I do `c.Destroy()` after this, camera won't get switched. I tried also to find something like "default camera", but I didn't find anything.

So, how to get back to game default cam?

**Comment by Rbn3D** [comment]
I do like this:

```cs
World.RenderingCamera = null;
```

**Comment by TheChilliPL** [comment]
K, that work ;)
