### ISSUE TITLE
How to drop weapon in singleplayer?

### ISSUE THREAD

**Issue by TheChilliPL** [crosire/scripthookvdotnet#623]
I tried
`Function.Call(
                            Hash.SET_PED_DROPS_INVENTORY_WEAPON,
                            Game.Player.Character,
                            28811031,
                            p.X,
                            p.Y,
                            p.Z, 0);`

**Comment by electricman226** [comment]
If this is still an issue for you, I **highly** recommend using Alexander Blade's [Native DB](http://www.dev-c.com/nativedb/) to look through these hashes. From [this function](http://www.dev-c.com/nativedb/func/info/208a1888007fc0e6):
```
[16/06/2017 by ins1de] :
Drops the weapon object from selected peds and turns it into a pickup.
Offset defines the next position of the weapon, ammo count is the stored ammo in the pickup **(if ammoCount == 0, pickup won't be created)**
*...*
```

**Comment by TheChilliPL** [comment]
Nope. Not working

**Comment by Tanjitsu** [comment]
https://github.com/crosire/scripthookvdotnet/blob/dev_v3/source/scripting/Ped.cs
or in 
http://www.dev-c.com/nativedb/


Function.Call(Hash.SET_PED_DROPS_WEAPONS_WHEN_DEAD, Game.Player.Character.Handle, true);

**Comment by TheChilliPL** [comment]
I don't want to set if ped drops on death, I want to drop it when I call my script

**Comment by Tanjitsu** [comment]
The Game handles drops via..
Remove weapon from Ped.
Spawn weapon on floor at spot.

https://github.com/Tanjitsu/scripthookvdotnet/blob/dev_v3/source/scripting/Pickup.cs

**Comment by crosire** [comment]
This isn't really the place to ask for general scripting advice, there are better places for that (GTAForums, Gitter chat, ...).
