### ISSUE TITLE
Shvdn with OpenVHook?

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#625]
Hello, these are very sad times for all of us. Since OpenIV got a C&D from T2 and Alexander Blade is also a team member of OpenIV it's very likely that scripthookV will never get updated. I found out there is a replacement for scripthookV. It's OpenVHook ( https://github.com/JackD111/OpenVHook ). However, I guess things are not so easy. First off idk if it's fully compatible with shv and second, shvdn refers shv.
So my question is, is the shvdn team discussing a separate version of shvdn which calls into OpenVHook?

**Comment by zorg93** [comment]
#449 If we did move to using that, could be a good excuse for the eventual upgrade to 3.0

**Comment by DavidZ912** [comment]
It works fine with OpenVHook for me i made a couple small changes not sure if they are needed or not.

**Comment by crosire** [comment]
This is no longer an issue.

**Comment by kagikn** [comment]
I haven't tested OpenVHook since it got updated for 1.0.1180.1, but I believe SHVDN now works with it.
