### ISSUE TITLE
missing texture

### ISSUE THREAD

**Issue by skynovax** [crosire/scripthookvdotnet#626]
when i add lastest scripthooknet version, the mod add on car spawner is work but some texture in map have missing maybe there anyone know what scripthooknet version work for this mod and doesnt make the texture missing?

**Comment by electricman226** [comment]
I don't even believe the current version of GTA V is supported on the latest SHV, so there is your first problem.
Also, if the map is not loading textures, this is not a result of SHVDN, or even SHV most likely.

**Comment by crosire** [comment]
This doesn't sound like an issue with SHVDN, nor was there an update by the OP for over a month, so I'm closing this.
