### ISSUE TITLE
Crashing on loading screen

### ISSUE THREAD

**Issue by Daniel123212** [crosire/scripthookvdotnet#627]
So guys i have a pretty big problem...Now the scripthook V was updated and everyting needs to work fine but when i download scripthookvdotnet the game crash in the loading screen i download everyting that needs to be downloaded i try everything to fix it but nothing happends every time on the same place the game crash and i dont know what to do so i am asking for help? :) Sorry for the english.

**Comment by kagikn** [comment]
I can say one thing at least. That is that the last update of GTA changed vehicle field offsets in vehicle structs, so some mods don't work properly for now.

**Comment by Daniel123212** [comment]
Yeah but i downgrade the game version 2 days ago and everything work expect the scripthookvdotnet i downloaded every version to try but the game crash everytime and i dont find reason why just the game tell me GTAV stop working or something like this and when i check why just saying appcrash nothing else and i dont know why ....

**Comment by electricman226** [comment]
@kagikn Is someone already working on refactoring for the new offsets?

**Comment by kagikn** [comment]
@electricman226 I'm working on this, and I confirmed the new offsets except the new field offests of helicopter were moved by 16 bytes (I've found the new offsets of helicopter, though), but I forgot to search for the offsets of heli in v1.0.944.2 and v1.0.1011.1. Fortunately I have backups for these versions and Entity offsets aren't changed at all between the 2 versions.

**Comment by Daniel123212** [comment]
So guys i fix it with a lot of searching and making things but i found there is a problem with Microsoft .net framework clr.dll crash now i fix it so yea bye :D
