### ISSUE TITLE
Memory offsets changing in latest version affect Vehicle entity properties

### ISSUE THREAD

**Issue by LeeC2202** [crosire/scripthookvdotnet#633]
Vehicle.CurrentRPM and Vehicle.CurrentGear are definitely two that have stopped working.

**Comment by electricman226** [comment]
I do believe that @kagikn is already working on fixing Vehicle offsets.

**Comment by kagikn** [comment]
Try [this](https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/dev_v3/1206/artifacts). I'm sure this won't cause the issues in the latest version.

**Comment by LeeC2202** [comment]
@kagikn That's version 3, I am using 2.9.6

It's not actuallly for me, I have implemented my own memory functions to get a version of my mod compatible with GTAV 1103. I was merely bringing the problem to the attention of the developers in case nobody else had reported it. If someone (or you I should say) is already working on the fixes, that's great.

**Comment by kagikn** [comment]
@LeeC2202 [This is a suitable link](https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/dev_v2/1205/artifacts). Note that dev_v2 is a version 2 branch, not version 3.

**Comment by LeeC2202** [comment]
@kagikn Okay, thanks.

**Comment by LfxB** [comment]
@kagikn Build dev_v2/1205 seems to crash my game during the loading screen. I've also tried compiling dev_2 myself and it's the same result. I have ScriptHookVDotNet.asi in my GTA V installation directory and the latest SHV. Am I doing something wrong?

**Comment by crosire** [comment]
Fixed in v2.10.0.
