### ISSUE TITLE
Scripthookvdotnet need an update

### ISSUE THREAD

**Issue by alexsantiago21** [crosire/scripthookvdotnet#634]
Since Rockstar has released the new update for GTA V we need a new Scripthookvdotnet since the last one is outdated

**Comment by kagikn** [comment]
Yeah, but I've already updated the ScriptHookVDotNet. Use [this](https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/dev_v2/1205/artifacts) instead of the latest official version until it's officially updated.

**Comment by alexsantiago21** [comment]
its not working. if you put al the files in it crashes. if you put the Scripthookvdotnet.asi in nothing happen all the scripts that need scripthookvdotnet doesn't work when u play the game

**Comment by alexsantiago21** [comment]
I have windows 10 so I have all the stuff you need to make it work

**Comment by electricman226** [comment]
Nearly certain saying that *'I have Windows 10'* doesn't cover everything. Do you have [.NET Framework](https://www.microsoft.com/en-us/download/details.aspx?id=42643&desc=dotnet452) (version >= 4.5.2) installed?

**Comment by luk234** [comment]
I can confirm it's not working either, I meet all the requirements needed for ScripthookVdotnet to run.
I also couldn't help but notice that the updated .asi is only 32kb, while the previous version's .asi was 975kb... that could have something to do with it?

**Comment by kagikn** [comment]
I think ScripthookVDotNet2.dll must be the actual thing, not ScriptHookVDotNet.dll.

**Comment by luk234** [comment]
I've been trying to get it to run but it's not working.

List of things I did:
-rename ScripthookVDotNet2.dll to ScripthookVDotNet.dll: Nothing happens
-put both updated ScripthookVDotNet.asi and ScripthookVDotNet2.dll in the game folder: Game Crashes
-rename ScripthookVDotNet2.dll to ScripthookVDotNet.asi: Scripthook V doesn't recognize the renamed file (doing this works for older versions of ScripthookVdotnet)

Also it did not create any log files during any of my tests.

**Comment by alexsantiago21** [comment]
Yep just did the same thing it didn't work

**Comment by alexsantiago21** [comment]
Yep just did the same thing. Nothing happened

**Comment by crosire** [comment]
You need both `ScriptHookVDotNet.asi` AND `ScriptHookVDotNet2.dll` in the game directory.

**Comment by alexsantiago21** [comment]
Ok I'll try it when I'm off work

**Comment by alexsantiago21** [comment]
Ok I'll try it when I'm off work

**Comment by alexsantiago21** [comment]
Has anyone else here tried it ?

**Comment by luk234** [comment]
I just tried this but it made my game crash.

**Comment by alexsantiago21** [comment]
Damn. I guess we may just have to wait for the official update.

**Comment by kagikn** [comment]
I tried [this](https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/dev_v2/1205/artifacts) but it made my game crashed, too. Probably the dll loader need to be fixed.

**Comment by alexsantiago21** [comment]
Anyone got a fix yet ?

**Comment by alexsantiago21** [comment]
What about using scripthookvdotnet3.dll and scripthookvdotnet.asi

**Comment by crosire** [comment]
Should be fixed in e80ead805f80e86e0f6cc88ea064931d04009e6e. Build: https://ci.appveyor.com/project/crosire/scripthookvdotnet/build/dev_v2/1217/artifacts.

**Comment by luk234** [comment]
Well, it's actually working now, scripthookdotnet is creating logs and all, but...
"[20:06:05] [WARNING] A script references v2.9.4 which may not be compatible with the current v0.0.0 and was therefore ignored."
This prevents most of my scripts from being loaded.
For some reason it only happens with SOME scripts and not all, but at least scripthook dot net is working in game.

**Comment by crosire** [comment]
Yeah, that branch has no versioning, so it will reject all scripts. Needs to be merged into master for the version to appear. Alternativly define a `SHVDN_VERSION` environment variable to "2.9.8" and rebuild the project.
