### ISSUE TITLE
Dev3 Branch - Release Blockers

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#635]
~~I know there are currently backward compatible issues stopping the release of the Dev3 branch.~~
I thought it might be good to have an ongoing Topic directly for the resolution of backwards compatibility.

My Example....

If i use the latest Master build (net2) compiled as ScriptHookVDotNet.asi.
Then i add in Dev3 build [Pre ASI Loader](https://github.com/crosire/scripthookvdotnet/commit/1f140898f6752096a7e54b22e3dd5afc69e5e50f)  (net3) compiled as ScriptHookVDotNet3.asi.

I compile the Dev3 build with a change to  "ScriptsLocation" being "scriptsCustom"
This just allows the 2 different types of scripts to be located separate.
it could be "scripts\net3" ect..

So i have net2 scripts in "scripts" folder.
and net3 scripts in "scriptsCustom" folder.

Then i run GTA and both sets of scripts work as intended.
Is there something else i need to test for / is this side by side backwards compatible ?

**Comment by crosire** [comment]
You can't use the old `ScriptHookVDotNet.asi` with 3, you need the new loader for both. The `dev_v2` branch was already modified to work with the loader too.

**Comment by Tanjitsu** [comment]
My game is currently crashing if i try to use net2 from Dev2 branch with the asi loader.
If i remove the loader and rename the dll to asi it works.

**Comment by crosire** [comment]
It shouldn't be able to even boot up without the loader on the latest commit in that branch. There is no script registration taking place, so renaming it to ASI should effectivly render it useless...

**Comment by Tanjitsu** [comment]
Yeah, you are correct it doesn't load when renamed.
I still cant get Dev2 branch to run without crashing GTA.

Kagikn also [commented](https://github.com/crosire/scripthookvdotnet/issues/634)
"ScriptHookVDotNet3.dll is properly loaded but ScriptHookVDotNet2.dll makes my game crash, so there's something wrong with the latter."

**Comment by alexsantiago21** [comment]
Still no fix?
