### ISSUE TITLE
vehicle.Acceleration memory offset issue

### ISSUE THREAD

**Issue by Dilapidated** [crosire/scripthookvdotnet#636]
This may of been fixed in a pending version, if so my apologizes.

Apparently the new gunrunning update has changed the vehicle.Acceleration memory offsets.

Example:

using `Me.Player.CurrentVehicle.Acceleration.ToString())`

Pre-Gunrunning
it returns 1 when going forward
0 when stopped
-1 in reverse

After-Gunrunning
it returns higher than 0.2 when going forward
0.2 when stopped
higher than 0.2 in reverse

**Comment by electricman226** [comment]
This should be soon fixed by a later release. I do know that @kagikn was working on fixing some helicopter memory address offsets, but I'm not sure if he knows about any other ones such as this.

**Comment by Nacorpio** [comment]
I wish I had the knowledge to find the offsets myself.
