### ISSUE TITLE
[Question / Bug] Game.GenerateHash();

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#638]
Hey,

Game.GenerateHash(string input)   works for Vehicle strings but not for Ped strings.

Is this a bug or intended ?

**Comment by Tanjitsu** [comment]
To further this same issue / elaborate...

public static VehicleHash[] GetAllModels()
Uses MemoryAccess.VehicleModels
But only returns a list of Vehicles if they were defined in VehicleHash enum.
This seems limited since the Enum list already exists.

I added and re-compiled ScripthookDotNet3 with the below function for testing

public static int[] GetAllModelValues()
{
            List<int> allModels = new List<int>();
            for (int i = 0; i < 0x20; i++)
            {
                allModels.AddRange(MemoryAccess.VehicleModels[i].ToArray());
            }
            return allModels.ToArray();
}

This will return me a list of all the Vehicle values but without limiting the list.
If i use these values with call new Model() i get the vehicles.
If i pass the VehicleHash or the Vehicle name string or the Int value i get the model.

When i call new Model()  and pass in a string... Its uses Game.GenerateHash(string input);

So......
 is Game.GenerateHash getting the String from the VehicleHash defined by ScripthookDotNet 
or by GTA  ?

If its coming from VehicleHash...  then load model using string should work for Peds.

If its coming from GTA.... Could MemoryAccess::GenerateVehicleModelList() not be used to populate all available vehicles without Manual Enum updates to VehicleHash.Enum ?

**Comment by Tanjitsu** [comment]
Using Vehicle.GetAllModelValues() and Vehicle.GetModelDisplayName() i was able to extract the below values which generate the game models and are missing from VehicleHash Enum.

Caddy3 = -769147461
Insurgent3 = -1924433270
Hakuchou2 = -255678177
HalfTrack = -32236122
Tampa3 = -1210451983
Trailer = -1100548694
TrSmall2 = -1881846085
TrLarge = 1502869817
Torero = 1504306544
Ardent = 159274291
Phantom3 = 177270108
Dune3 = 1897744184
Vagner = 1939284556
Cheetah2 = 223240013
Hauler2 = 387748548
NightShark = 433954513
APC = 562680400
Chimera - 6774487
Freight = 868868440
Oppressor = 884483972
XA21 = 917809321
Youga2 = 1026149675
Technical3 = 1356124575

**Comment by zorg93** [comment]
The enum is helpful for people making scripts so they can type VehicleHash.Adder etc. However if you need all vehicles, including addon etc) the memory access stuff should be used. For your original question, the generate hash function just applies a hash function to the string. The reason you can't use those hashes to spawn stuff is you are passing strings that dont correspond to models in the game

**Comment by Tanjitsu** [comment]
Ah yes... so Ped "Michael" is model string (example "a_s_m_michael")
Where as Vehicle "Adder" is also model string "adder" ?

Well at-least i got some new vehicle model values from my venture.
Based on the above... should i submit  GetAllModelValues()  as a commit.

This would allow mods like mine to define actual vehicles via calls like...

Tuple<string, int> Vehicles = new Tuple<string, int>();
foreach (int value in Vehicle.GetAllModelValues())
{
  Model model = new Model(value);
  string name = Vehicle.GetModelDisplayName(model).ToString();
  Vehicles.Add(name, value);
}

**Comment by zorg93** [comment]
No point adding that, instead you could make an enumerator to loop through them all
