### ISSUE TITLE
Crash GTA when the game is reloaded

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#643]
The crash at startup with v2 was fixed in e80ead8, but when the game is reloaded, something crashes it even if neither `ScriptHookVDotNet2.dll` or `ScriptHookVDotNet3.dll` is loaded.

**Comment by zorg93** [comment]
I'm presuming you are talking about the asi and not the dll. Even so if they are not loaded and the game crashes how is that an issue with this

**Comment by kagikn** [comment]
Ah, here's a log.
```[21:16:48] [DEBUG] Created script domain 'ScriptDomain_AF37AEA0' with v2.9.4.
[21:16:48] [DEBUG] Loading scripts from 'D:\Steam Games\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_AF37AEA0' ...
[21:16:48] [ERROR] Failed to reload scripts because the directory is missing.
```

Note that `AssemblyVersionAttribute` is edited on purpose to test with most scripts.

**Comment by crosire** [comment]
Can't reproduce. Tried loading different game saves, but it never crashed. What's the exception message?

**Comment by kagikn** [comment]
I'm sorry, I thought the loader had the issue but actually didn't, probably another asi did. Anyway this plugin has nothing to do with the issue.
