### ISSUE TITLE
2.10.0 causes crash if file blocked by Windows

### ISSUE THREAD

**Issue by CamxxCore** [crosire/scripthookvdotnet#644]
I ran into this problem after installing v2.10.0. The game crashes with a FileLoadException during the load screen if ScriptHookVDotNet2.dll gets blocked by windows. For the average user, the game crashes with not indication of what went wrong. Might avoid some hysteria if we link users to [this](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile) page in the release notes.

**Comment by crosire** [comment]
Good point. I added that bit of info to the release page.

**Comment by kagikn** [comment]
This issue can be solved by catching FileLoadException, but still there is no way to know why SHVDN doesn't work if ScriptHookVDotNet2.dll is blocked by windows or doesn't have permission to read. Why not add logging methods in the loader?

**Comment by crosire** [comment]
Implemented a workaround that automatically unblocks the file if not done so by the user, so this should no longer be an issue.
