### ISSUE TITLE
Vehicle Hash Names

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#650]
I found a couple of missing VehicleHash's but i can not workout with the correct model name.

```
uInt: 3368285087 int: -926682209 as Class: Cycles with Name: Policebicyc
uInt: 4250797520 int: -44169776 as Class: Compacts Duplicate VehicleHash: Taxi 
uInt: 790718806 int: 790718806 as Class: Sedans Duplicate VehicleHash: Taxi

```
I'm just posting these in the hope someone can come up with the correct names so we can commit them.
I've been through the obvious such as Taxi1, Taxi2, TaxiA, TaxiC ect.

Policebicyc model looks like a scorcher.
-44169776 model looks like a Dilettante.
790718806 model looks like a Asterope.

**Comment by UnknownModder** [comment]
There aren't any hashes missing. GTA V currently has 520 vehicles. I have no idea where you got these hashes from (perhaps from add-on vehicles you have installed?).

**Comment by Tanjitsu** [comment]
@UnknownModder Correct. Seems i didn't correctly disable WoV as expected.
