### ISSUE TITLE
Script error notifications

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#654]
Though SHVDN writes error logs to a log file, it doesn't show that errors happened on the screen at all if some scripts throw an exception. We could make SHVDN do this or at least add an option for script error notifications to clearly notify users of script errors.
When I write some scripts for some native tests or analysis of GTA5.exe and one of them throws an exception, I don't necessarily notice errors happened.

**Comment by crosire** [comment]
Side note: errors are at least printed to the in-game console in v3.

**Comment by FrederikBolding** [comment]
How would you propose we do error notifications @kagikn? Just using the regular ingame "notifications" or something more custom?

**Comment by kagikn** [comment]
If we implement, ingame notifications would be more suitable for SHVDN than something more custom.

**Comment by FrederikBolding** [comment]
Just using the in-game notifications should be quite straightforward, if that's what we're going for.
![image](https://user-images.githubusercontent.com/1561200/31619843-fc18f03c-b295-11e7-94e4-a31d8beb6f26.png)

**Comment by FrederikBolding** [comment]
I'm thinking we implement #723 and then use that for script error notifications.
