### ISSUE TITLE
Showing mission success / fail

### ISSUE THREAD

**Issue by TheChilliPL** [crosire/scripthookvdotnet#663]
So, I'm trying to find functions displaying mission success/fail like on these screens from some mod.
![Mission Success Image](https://img.gta5-mods.com/q85-w800/images/delivery-missions/ffb916-GTA5%202017-02-26%2015-09-56-57.jpg)
![Mission Failure Image](https://img.gta5-mods.com/q95/images/delivery-missions/ffb916-GTA5%202017-02-26%2015-10-23-45.jpg)

**Comment by zorg93** [comment]
I cant give you much help but iirc they are scaleforms

**Comment by sollaholla** [comment]
What I do:
`
if (!Function.Call<bool>(Hash.IS_MISSION_COMPLETE_PLAYING)) return;
Effects.Start(ScreenEffect.SuccessNeutral, 5000);                ScaleFormMessages.Message.SHOW_MISSION_PASSED_MESSAGE(Game.GetGXTEntry("ENEMIES_ELIM"));
Script.Wait(4000);
`

Classes
`
public class ScaleFormMessage
{
    private Scaleform _sc;
    private int _start;
    private int _timer;

    internal void Load()
    {
        if (_sc != null) return;
        _sc = new Scaleform("MP_BIG_MESSAGE_FREEMODE");
        var timeout = 1000;
        var start = DateTime.Now;
        while (!Function.Call<bool>(Hash.HAS_SCALEFORM_MOVIE_LOADED, _sc.Handle) &&
                DateTime.Now.Subtract(start).TotalMilliseconds < timeout) Script.Yield();
    }

    internal void Dispose()
    {
        Function.Call(Hash.SET_SCALEFORM_MOVIE_AS_NO_LONGER_NEEDED, new OutputArgument(_sc.Handle));
        _sc = null;
    }

    public void SHOW_MISSION_PASSED_MESSAGE(string msg, int time = 5000)
    {
        Load();
        _start = Game.GameTime;
        _sc.CallFunction("SHOW_MISSION_PASSED_MESSAGE", msg, "", 100, true, 0, true);
        _timer = time;
    }

    public void SHOW_SHARD_CENTERED_MP_MESSAGE(string msg, string desc, HudColor textColor, HudColor bgColor,
        int time = 5000)
    {
        Load();
        _start = Game.GameTime;
        _sc.CallFunction("SHOW_SHARD_CENTERED_MP_MESSAGE", msg, desc, (int) bgColor, (int) textColor);
        _timer = time;
    }

    public void SHOW_SHARD_CREW_RANKUP_MP_MESSAGE(string title, string subtitle, int time = 5000)
    {
        Load();
        _start = Game.GameTime;
        _sc.CallFunction("SHOW_SHARD_CREW_RANKUP_MP_MESSAGE", title, subtitle);
        _timer = time;
    }

    public void SHOW_BIG_MP_MESSAGE(string msg, string subtitle, int rank, int time = 5000)
    {
        Load();
        _start = Game.GameTime;
        _sc.CallFunction("SHOW_BIG_MP_MESSAGE", msg, subtitle, rank, "", "");
        _timer = time;
    }

    public void SHOW_WEAPON_PURCHASED(string msg, string weaponName, WeaponHash weapon, int time = 5000)
    {
        Load();
        _start = Game.GameTime;
        _sc.CallFunction("SHOW_WEAPON_PURCHASED", msg, weaponName, unchecked((int) weapon), "", 100);
        _timer = time;
    }

    public void SHOW_CENTERED_MP_MESSAGE_LARGE(string msg, int time = 5000)
    {
        Load();
        _start = Game.GameTime;
        _sc.CallFunction("SHOW_CENTERED_MP_MESSAGE_LARGE", msg, "test", 100, true, 100);
        _sc.CallFunction("TRANSITION_IN");
        _timer = time;
    }

    public void CALL_FUNCTION(string funcName, params object[] paremeters)
    {
        Load();
        _sc.CallFunction(funcName, paremeters);
    }

    internal void DoTransition()
    {
        if (_sc == null) return;
        _sc.Render2D();
        if (_start != 0 && Game.GameTime - _start > _timer)
        {
            _sc.CallFunction("TRANSITION_OUT");
            _start = 0;
            Dispose();
        }
    }
}

public class ScaleFormMessages : Script
{
    public ScaleFormMessages()
    {
        Message = new ScaleFormMessage();

        Tick += (sender, args) => { Message.DoTransition(); };
    }

    public static ScaleFormMessage Message { get; set; }
}
`
`
public enum ScreenEffect
{
    SwitchHudIn,
    SwitchHudOut,
    FocusIn,
    FocusOut,
    MinigameEndNeutral,
    MinigameEndTrevor,
    MinigameEndFranklin,
    MinigameEndMichael,
    MinigameTransitionOut,
    MinigameTransitionIn,
    SwitchShortNeutralIn,
    SwitchShortFranklinIn,
    SwitchShortTrevorIn,
    SwitchShortMichaelIn,
    SwitchOpenMichaelIn,
    SwitchOpenFranklinIn,
    SwitchOpenTrevorIn,
    SwitchHudMichaelOut,
    SwitchHudFranklinOut,
    SwitchHudTrevorOut,
    SwitchShortFranklinMid,
    SwitchShortMichaelMid,
    SwitchShortTrevorMid,
    DeathFailOut,
    CamPushInNeutral,
    CamPushInFranklin,
    CamPushInMichael,
    CamPushInTrevor,
    SwitchSceneFranklin,
    SwitchSceneTrevor,
    SwitchSceneMichael,
    SwitchSceneNeutral,
    MpCelebWin,
    MpCelebWinOut,
    MpCelebLose,
    MpCelebLoseOut,
    DeathFailNeutralIn,
    DeathFailMpDark,
    DeathFailMpIn,
    MpCelebPreloadFade,
    PeyoteEndOut,
    PeyoteEndIn,
    PeyoteIn,
    PeyoteOut,
    MpRaceCrash,
    SuccessFranklin,
    SuccessTrevor,
    SuccessMichael,
    DrugsMichaelAliensFightIn,
    DrugsMichaelAliensFight,
    DrugsMichaelAliensFightOut,
    DrugsTrevorClownsFightIn,
    DrugsTrevorClownsFight,
    DrugsTrevorClownsFightOut,
    HeistCelebPass,
    HeistCelebPassBw,
    HeistCelebEnd,
    HeistCelebToast,
    MenuMgHeistIn,
    MenuMgTournamentIn,
    MenuMgSelectionIn,
    ChopVision,
    DmtFlightIntro,
    DmtFlight,
    DrugsDrivingIn,
    DrugsDrivingOut,
    SwitchOpenNeutralFib5,
    HeistLocate,
    MpJobLoad,
    RaceTurbo,
    MpIntroLogo,
    HeistTripSkipFade,
    MenuMgHeistOut,
    MpCoronaSwitch,
    MenuMgSelectionTint,
    SuccessNeutral,
    ExplosionJosh3,
    SniperOverlay,
    RampageOut,
    Rampage,
    DontTazemeBro
}

public static class Effects
{
    private static readonly string[] _effects =
    {
        "SwitchHUDIn",
        "SwitchHUDOut",
        "FocusIn",
        "FocusOut",
        "MinigameEndNeutral",
        "MinigameEndTrevor",
        "MinigameEndFranklin",
        "MinigameEndMichael",
        "MinigameTransitionOut",
        "MinigameTransitionIn",
        "SwitchShortNeutralIn",
        "SwitchShortFranklinIn",
        "SwitchShortTrevorIn",
        "SwitchShortMichaelIn",
        "SwitchOpenMichaelIn",
        "SwitchOpenFranklinIn",
        "SwitchOpenTrevorIn",
        "SwitchHUDMichaelOut",
        "SwitchHUDFranklinOut",
        "SwitchHUDTrevorOut",
        "SwitchShortFranklinMid",
        "SwitchShortMichaelMid",
        "SwitchShortTrevorMid",
        "DeathFailOut",
        "CamPushInNeutral",
        "CamPushInFranklin",
        "CamPushInMichael",
        "CamPushInTrevor",
        "SwitchSceneFranklin",
        "SwitchSceneTrevor",
        "SwitchSceneMichael",
        "SwitchSceneNeutral",
        "MP_Celeb_Win",
        "MP_Celeb_Win_Out",
        "MP_Celeb_Lose",
        "MP_Celeb_Lose_Out",
        "DeathFailNeutralIn",
        "DeathFailMPDark",
        "DeathFailMPIn",
        "MP_Celeb_Preload_Fade",
        "PeyoteEndOut",
        "PeyoteEndIn",
        "PeyoteIn",
        "PeyoteOut",
        "MP_race_crash",
        "SuccessFranklin",
        "SuccessTrevor",
        "SuccessMichael",
        "DrugsMichaelAliensFightIn",
        "DrugsMichaelAliensFight",
        "DrugsMichaelAliensFightOut",
        "DrugsTrevorClownsFightIn",
        "DrugsTrevorClownsFight",
        "DrugsTrevorClownsFightOut",
        "HeistCelebPass",
        "HeistCelebPassBW",
        "HeistCelebEnd",
        "HeistCelebToast",
        "MenuMGHeistIn",
        "MenuMGTournamentIn",
        "MenuMGSelectionIn",
        "ChopVision",
        "DMT_flight_intro",
        "DMT_flight",
        "DrugsDrivingIn",
        "DrugsDrivingOut",
        "SwitchOpenNeutralFIB5",
        "HeistLocate",
        "MP_job_load",
        "RaceTurbo",
        "MP_intro_logo",
        "HeistTripSkipFade",
        "MenuMGHeistOut",
        "MP_corona_switch",
        "MenuMGSelectionTint",
        "SuccessNeutral",
        "ExplosionJosh3",
        "SniperOverlay",
        "RampageOut",
        "Rampage",
        "Dont_tazeme_bro"
    };

    private static string EffectToString(ScreenEffect screenEffect)
    {
        if (screenEffect >= 0 && (int) screenEffect <= _effects.Length)
            return _effects[(int) screenEffect];
        return "INVALID";
    }

    public static void Start(ScreenEffect effectName, int duration = 0, bool looped = false)
    {
        Function.Call(Hash._START_SCREEN_EFFECT, EffectToString(effectName), duration, looped);
    }

    public static void Stop()
    {
        Function.Call(Hash._STOP_ALL_SCREEN_EFFECTS);
    }

    public static void Stop(ScreenEffect screenEffect)
    {
        Function.Call(Hash._STOP_SCREEN_EFFECT, EffectToString(screenEffect));
    }

    public static bool IsActive(ScreenEffect screenEffect)
    {
        return Function.Call<bool>(Hash._GET_SCREEN_EFFECT_IS_ACTIVE, EffectToString(screenEffect));
    }
}
`

**Comment by FrederikBolding** [comment]
Should we implement support for this or just let modders figure it out themselves?

**Comment by crosire** [comment]
We have https://github.com/crosire/scripthookvdotnet/blob/214733ba06a7837ea8c6dd4b04609aa7aa0629a4/source/scripting/UI/Screen.cs#L289 and https://github.com/crosire/scripthookvdotnet/blob/214733ba06a7837ea8c6dd4b04609aa7aa0629a4/source/scripting/UI/Scaleform.cs#L80, so this is pretty simple to implement without all that boilerplate code in v3.
