### ISSUE TITLE
No Assembly info available in asi

### ISSUE THREAD

**Issue by bilago** [crosire/scripthookvdotnet#667]
Moving forward with newest builds, can you include Author name and file version info in the assembly?
We are doing version checks with Realism Dispatch Enhanced (To ensure users are using the version of scripthookvdotnet that we wrote the scripts with) but we have to regex existing log files just to get the last run version number, instead of something simple like FileVersionInfo.GetVersionInfo("ScripthookVdotNet.asi")

**Comment by crosire** [comment]
Don't check the ASI (which is only a loader now), check the DLL (e.g. `ScriptHookVDotNet2.dll`). It does contain version information.

**Comment by bilago** [comment]
I've been out of the GTA modding scene for a few months while my team worked on RDE, do normal users of scripthook require a copy of the .dll in their game folder for scripthookvdotnet to function? I know previously it was just the .asi

**Comment by bilago** [comment]
Looks like the DLL is also missing the assembly information for me:

![image](https://user-images.githubusercontent.com/8310293/29280963-046d94ea-80d2-11e7-9cf2-5642abddf17e.png)

**Comment by crosire** [comment]
Yeah, sorry, I should have clarified. It only exposes .NET assembly info, but no Win32 file version.
