### ISSUE TITLE
How to reload scripts on latest release?

### ISSUE THREAD

**Issue by EnforcerZhukov** [crosire/scripthookvdotnet#670]
I updated SHVDN to ver. 2.10.1, but now the reload scripts key isn't working, neither Insert (AFAIK the default key) or F1 (the key I've been using for months, set on ScriptHookVDotNet.ini).

How to change this key on this new release?

Thanks in advance.

**Comment by kagikn** [comment]
@EnforcerZhukov Have you solved the problem since you created this issue? I'm not sure.

**Comment by kagikn** [comment]
@EnforcerZhukov You did activities since I send the reply above to you, but you've say nothing since then, so I closed this issue. But you can reopen this issue if you want to say anything about this issue.

**Comment by EnforcerZhukov** [comment]
Sorry, I had some problems with the game and I wanted to try the latest SHVDN version.

I did today, and the "problem" is still there. I can't reload scripts by pressing Insert, the key which was used on earlier versions of SHVDN (and even customizable).

**Comment by kagikn** [comment]
Umm strange. I have the reload key disabled by something sometimes, but when this happens, all ScriptHookV scripts can't receive any key input (As for RPH plugins, this can't happen, I think, so...) . Changing a way to receive key input in SHVDN might solve the problem, though.
But if you can't get the reload key working anytime, please make sure the key value you set is correct. All the key available for the reload key are listed in [this page](https://msdn.microsoft.com/en-us/library/system.windows.forms.keys(v=vs.110).aspx).

**Comment by EnforcerZhukov** [comment]
How do I set the key? I previously used an .ini file included on previous SHVDN versions, which now is not included. I had in fact the F1 key assigned to Reload Scripts, but now neither the F1 nor default Insert keys work.

**Comment by crosire** [comment]
Works the same as always. Create a `ScriptHookVDotNet2.ini` and set the reload key there.

**Comment by EnforcerZhukov** [comment]
Great, now it's working. The problem was the INI file was named `ScriptHookVDotNet.ini` instead of `ScriptHookVDotNet2.ini`.

Anyway as a suggestion I think an INI file should be provided within the releases, so it's more clear that it's possible to assign a Reload Scripts key.

**Comment by kagikn** [comment]
The INI name must be the same as the dll name, yes. I forgot this when I commented here.
