### ISSUE TITLE
IntelliSense for cs files of SHVDN

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#678]
When editing cs files of SHVDN, IntelliSense doesn't work well (at least in VS 2017 and 2015), and this annoys me. Any solutions?

**Comment by RainerHilmer** [comment]
That's because shvdn isn't fully XML documented.

**Comment by kagikn** [comment]
What I'm talking about is that IntelliSense doesn't show any properties or methods that are defined in other files in SHVDN.
![snapcrab_noname_2017-9-4_0-6-58_no-001](https://user-images.githubusercontent.com/9353978/30004168-2a8728b0-9105-11e7-9862-3ff9c84ec96a.png)

**Comment by crosire** [comment]
Since the default project is C++, Visual Studio doesn't store C# type information in the project database and IntelliSense only works per file and not project-wide.
But you can create an empty C# project and add all the cs files to get proper IntelliSense support.
