### ISSUE TITLE
Would you add SHVDN_VERSION to environment vars on AppVeyor?

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#683]
Would you add `SHVDN_VERSION` to environment vars on AppVeyor? Currently `SHVDN_VERSION` isn't defined, and this annoys me when I post a build that includes hotfixes to 5Mods and some people have different problems due to internal version of SHVDN. 
EDIT: I thought the var is also used for v3, but it doesn't, so adding `SHVDN_VERSION` can't cause any problems.

**Comment by crosire** [comment]
`SHVDN_VERSION` is only defined when building a tag through AppVeyor, since that's the only time I can extract version information automatically. All other builds don't know which version they are build for, as such the environment variable is not defined.

**Comment by kagikn** [comment]
Then could you automatically define `SHVDN_VERSION` as the latest released version of all tags when compiling the code? I wish this can be done.

**Comment by crosire** [comment]
Technically it shouldn't be an issue if the variable is not defined. In that case the version defaults to "0.0.0", which the v2 branch accepts as valid when comparing to the version scripts were compiled against.
I could default the value to something higher, but that would likely break future automated builds in the v3 branch.

**Comment by kagikn** [comment]
Now I'm a collaborator, and crosire explicitly gave me permission to release new versions that just bumps up the third number in the version. In other word, I can merge changes that only fix some functions, properties, or memory offsets. So I'll close this issue for now.
![screenshot_2017-09-09-10-16-03](https://user-images.githubusercontent.com/9353978/30235823-a0a88b28-9548-11e7-9c8b-dddd37b9da41.png)
