### ISSUE TITLE
Speed in the function

### ISSUE THREAD

**Issue by varunkumar2310** [crosire/scripthookvdotnet#687]
https://github.com/crosire/scripthookvdotnet/blob/069629e02b4ce289b3c1d0615ede478569305cf3/source/scripting/Tasks.cs#L167

Instead of the speed being 1f by default, can we have a function parameter "float speed",
so that we can use that argument in
Function.Call(Hash.TASK_FOLLOW_POINT_ROUTE, _ped.Handle, speed, 0);

**Comment by crosire** [comment]
Done.
