### ISSUE TITLE
Guard page stack issue

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#69]
Sometimes, my game just crashes mentioning something about an error in a guard page or a stack. I don't really know what this means. Any ideas?

**Comment by crosire** [comment]
See my comment on #10.

**Comment by Nacorpio** [comment]
It seems like I can't even load my game before it gives me that error now.
I don't know if has anything to do with my code, but it worked perfectly fine two minutes ago.

**Comment by crosire** [comment]
You should try and reinstall the .NET framework.

**Comment by Nacorpio** [comment]
How can I do that as quickly as possible?

**Comment by Nacorpio** [comment]
I tried reinstalling it, but it still gives me the same error.

**Comment by Nacorpio** [comment]
Update:
Apparently, it has something to do with my mod, but it just suddenly started doing this.
I didn't add anything that could have caused this. No crash occurs without my mod.

**Comment by crosire** [comment]
Do you use the "Script.Wait" function?

**Comment by Nacorpio** [comment]
No, I do not.

**Comment by Nacorpio** [comment]
All I added was an array of Action<object[]>.
Could that be the cause?

**Comment by crosire** [comment]
How big is that array?

**Comment by Nacorpio** [comment]
It's limited to two actions.

**Comment by crosire** [comment]
I can't help much without source code ...

**Comment by Nacorpio** [comment]
https://github.com/Nacorpio/GTA-Purge-Mod

**Comment by Nacorpio** [comment]
*private int Accuracy {
            get {
                return (IsActive ? Ped.Accuracy : Accuracy);
            }
            set {
                if (IsActive) {
                    Ped.Accuracy = value;
                } else {
                    Accuracy = value;
                }
            }
        }

        public int Armor {
            get {
                return (IsActive ? Ped.Health : Armor);
            }
            set {
                if (IsActive) {
                    Ped.Armor = value;
                } else {
                    Armor = value;
                }
            }
        }

        public int Money {
            get {
                return (IsActive ? Ped.Money : Money);
            }
            set {
                if (IsActive) {
                    Ped.Money = value;
                } else {
                    Money = value;
                }
            }
        }

        public float Heading {
            get {
                return (IsActive ? Ped.Heading : Heading);
            }
            set {
                if (IsActive) {
                    Ped.Heading = value;
                } else {
                    Heading = value;
                }
            }
        }

        public int Health {
            get {
                return (IsActive ? Ped.Health : Health);
            }
            set {
                if (IsActive) {
                    Ped.Health = value;
                } else {
                    Health = value;
                }
            }
        }*

Apparently, when those were removed, the error vanishes.
What is wrong here?

**Comment by Nacorpio** [comment]
I know what was wrong - my property was recursive. That way, I caused an overflow in a stack. Thank you anyways.

**Comment by crosire** [comment]
Ah, well, that makes sense. =)
