### ISSUE TITLE
Port entire C++/CLI code except loader to C#

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#690]
I've started thinking we can port entire C++/CLI code to C# (except for the loader, of course).
I'm not going to say that I don't like C++/CLI or that I don't want to write C++/CLI code, but it's true that C++/CLI quite poorly supported .NET features.
In fact, I tried to define `ModelInfoClassType` as an internal enum in C++/CLI, but I couldn't and it made me very very sad. 
The major problem to port would be function pointers in the NativeAccess class (raw pointers don't matter, and [I use some of them in C#](https://github.com/kagikn/GlowingPickups/blob/master/GlowingPickups/MemoryAccess.cs#L161)), but we can use funtion pointers via `GetDelegateForFunctionPointer` in C# (and some SHVDN or RPH mods use it).
Besides, I seriously want complete IntelliSense, not incomplete one, and Resharper doesn't support C++/CLI, I'm not using due to lack of money to buy, though. (and I heard MulleDK19 is redoing RPH 2 in C#).

# Porting Status (see [this branch](https://github.com/kagikn/scripthookvdotnet/tree/port-code-to-C%23) for details)
## core
- [X] Console.cs
- [X] Main.cs
- [X] Native.cs (Note: SHV functions haven't been replaced with the methods in wrapper)
- [x] NativeMemory.cs
- [X] Script.cs
- [X] ScriptDomain.cs
- [X] Settings.cs
- [X] P/Invoke methods for SHV functions ~~Wrapper class for SHV functions~~
## scripting
- [X] Matrix.cs
- [X] Quaternion.cs
- [X] Vector2.cs
- [X] Vector3.cs

## ScriptHookVDotNet.csproj
- [x] Fixing some stuff to pass compiler checks
- [x] Testing the stuff in core files directly accessing memory

**Comment by kagikn** [comment]
@crosire And one more thing, would you mind updating the project to VS2017 and changing the target framework version to 4.7? I'd like to use Auto-Implemented Properties.

**Comment by kagikn** [comment]
I ported some core code to C# in [this branch](https://github.com/kagikn/scripthookvdotnet/tree/port-code-to-C%23/source/core). I'm serious. I have to make a wrapper class for SHV API in C++/CLI, though.

**Comment by crosire** [comment]
I like the idea. Keeping some code C++/Cli can be more powerful though. And as you noticed, it's a bit complex to write the `NativeMemory.cpp` implementation in pure C#. So I'm not 100% sold on it, but am not against it either.
As for .NET 4.7: Seems like it was rolled out via Windows Update now, so sounds like a good idea.

**Comment by kagikn** [comment]
We could add overloads that pass by reference to Math class (e.g. the Multiply method that have `out` matrix paramater), just like SlimDX and SharpDX. May I do this?

**Comment by crosire** [comment]
I'm not sure what you're getting at?

**Comment by kagikn** [comment]
I created ScriptHookVDotNet.csproj and I'm configuring the project, in a local branch.
I need to test some stuff in new SHVDN (made of pure C#) and the wrapper, but almost there!

**Comment by kagikn** [comment]
@crosire Would you mind upgrading thr projects to VS2017 or 2015? I used expression-bodied members in some class (e.g. Matrix.cs), though (which are available in C# 6.0 or later).
But C# 6.0 and 7.0 brought a lot of useful features (e.g. `ValueTuple` with aliases) in fact.

**Comment by crosire** [comment]
It's already a VS2015 solution? So with the .NET 4.7 tools for VS2015 installed things should work.
