### ISSUE TITLE
Hash._WORLD3D_TO_SCREEN2D not synchronized properly

### ISSUE THREAD

**Issue by muaz-git** [crosire/scripthookvdotnet#693]
I am trying fetch 2d screen coordinates of the entities. But it seems like results are lagging a bit. Specially when I move car a bit faster which causes camera to move faster. In this [sample](https://drive.google.com/open?id=0B7dFO5oiamETWXUyVHZhMTBxdkU), you can see that green box (projected 2d box calculated using `_WORLD3D_TO_SCREEN2D`) is not well synchronized and partially wrong as compared to the 3d box (blue one). 
Can anyone please help me in fixing it. Or maybe help me in understanding what exactly happens when the function `Hash._WORLD3D_TO_SCREEN2D` is called. Your help will be really appreciated. Thanks.

**Comment by E66666666** [comment]
You should use `SET_DRAW_ORIGIN` and `CLEAR_DRAW_ORIGIN` with your normal other draws in between that. Not sure why WORLD3D_TO_SCREEN2D lags behind, but changing the draw origin to a 3D point works perfectly for me.

**Comment by muaz-git** [comment]
@E66666666 well, 3d box is more or less accurate. I am having problems with `_WORLD3D_TO_SCREEN2D`, if I could some how get to know the internal implementation or some clues how to fix it. Would be great.

**Comment by muaz-git** [comment]
I found solution [here ](http://gtaforums.com/topic/842182-world-to-screen-lag/?p=1069860948)more helpful. There are still bit lags but much much better than simply using `_WORLD3D_TO_SCREEN2D`. Sometimes using matrices from either previous or next frame gives more accuracy but still finding the general pattern for more accurate boxes. If anyone find better solution please let me know.

**Comment by DurtyFree** [comment]
That solution seems to be more efficient, maybe it should be implemented here?

**Comment by crosire** [comment]
Closing this for now, since it's not an issue with SHVDN itself.
