### ISSUE TITLE
New BlipSprite Enum

### ISSUE THREAD

**Issue by qiangqiang101** [crosire/scripthookvdotnet#695]
StuntRace = 435,
        HotProperty,
        KillListCompetitive,
        King = 439,
        DeadDrop,
        PennedIn,
        Beast,
        CrossTheLinePointer,
        CrossTheLine,
        LamarD,
        Bennys,
        LamarDNumber1,
        LamarDNumber2,
        LamarDNumber3,
        LamarDNumber4,
        LamarDNumber5,
        LamarDNumber6,
        LamarDNumber7,
        LamarDNumber8,
        Yacht,
        FindersKeepers,
        Briefcase2,
        ExecutiveSearch,
        Wifi,
        TurretedLimo,
        AssetRecovery,
        YachtLocation,
        Beasted,
        Loading,
        SlowTime = 466,
        Flip,
        ThermalVision,
        Doped,
        Railgun,
        Seashark,
        Blind,
        Warehouse,
        WarehouseForSale,
        Office,
        OfficeForSale,
        Truck,
        SpecialCargo,
        Trailer,
        VIP,
        Cargobob,
        AreaCutline,
        Jammed,
        Ghost,
        Detonator,
        Bomb,
        Shield,
        Stunt,
        Heart,
        StuntPremium,
        Adversary,
        BikerClubhouse,
        CagedIn,
        TurfWar,
        Joust,
        Weed,
        Cocaine,
        IdentityCard,
        Meth,
        DollarBill,
        Package2,
        Capture1,
        Capture2,
        Capture3,
        Capture4,
        Capture5,
        Capture6,
        Capture7,
        Capture8,
        Capture9,
        Capture10,
        Quadbike,
        Bus,
        DrugPackage,
        Hop,
        Adversary4,
        Adversary8,
        Adversary10,
        Adversary12,
        Adversary16,
        Laptop,
        Motorcycle,
        SportsCar,
        VehicleWarehouse,
        Document,
        PoliceStationInverted,
        Junkyard,
        PhantomWedge,
        ArmoredBoxville,
        Ruiner2000,
        RampBuggy,
        Wastelander,
        RocketVoltic,
        TechnicalAqua,
        TargetA,
        TargetB,
        TargetC,
        TargetD,
        TargetE,
        TargetF,
        TargetG,
        TargetH,
        Juggernaut,
        SteeringWheel = 545,
        Cup,
        RocketBoost,
        Rocket,
        MachineGun,
        Parachute2,
        FiveSeconds,
        TenSeconds,
        FifteenSeconds,
        TwentySeconds,
        ThirtySeconds,
        WeaponSupplies,
        Bunker,
        APC,
        Oppressor,
        HalfTrack,
        DuneFAV,
        WeaponizedTampa,
        WeaponizedTrailer,
        MobileOperationsCenter,
        AdversaryBunker,
        BunkerVehicleWorkshop,
        WeaponWorkshop,
        Cargo,
        GTAOHangar,
        TransformCheckpoint,
        TransformRace,
        AlphaZ1,
        Bombushka,
        Havok,
        HowardNX25,
        Hunter,
        Ultralight,
        Mogul,
        V65Molotok,
        P45Nokota,
        Pyro,
        Rogue,
        Starling,
        Seabreeze,
        Tula

**Comment by kagikn** [comment]
@qiangqiang101 Sorry for late reply, I was porting v3 code to C# when you made this issue, and I was busy with the PR.
I just tested all the blips you listed, will add them soon.
