### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#696]
I just checked NuGet and there's a [ScriptHookV.NET package](https://www.nuget.org/packages/ScriptHookV.NET) with the 1.1.0 version, and looks like the package is [not uploaded by Crosire](https://www.nuget.org/profiles/Raxdiam).

If there's the option, can you upload the current version to NuGet? That will make the work easier for devs.

![image](https://user-images.githubusercontent.com/11861253/30993911-88e5e3fc-a487-11e7-9667-577bd30d3abb.png)

**Comment by crosire** [comment]
An official NuGet package for the v2 version is now available.
See https://www.nuget.org/packages/ScriptHookVDotNet2/.
