### ISSUE TITLE
Use Waffle.io?

### ISSUE THREAD

**Issue by JohnnyCrazy** [crosire/scripthookvdotnet#7]
Hey,

Since still a lot of things need to be implemented, I would suggest using https://waffle.io to keep track of what's in progress and what needs to be done. It prevents double work and keeps everything organized

Project in waffle.io (No tasks/issues yet): https://waffle.io/crosire/scripthookvdotnet

Any thoughts?

**Comment by crosire** [comment]
First time I heard of them (only worked with Github issues manually so far), indeed looks very useful. I'll add some feature issues tomorrow (everybody else is of course free to add stuff too, I encourage you to do so!).
