### ISSUE TITLE
Typo in the VehicleHash enum.

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#705]
It  should be RE7B instead of LE7B.

**Comment by kagikn** [comment]
RE7B's `modelName`, `txdName`, `handlingId`, and `gameName` are internally named LE7B and not a few vehicles have different names for them. But the 4 names RE7B has are so confusing that many people would think RE7B is missing.

**Comment by zorg93** [comment]
This kind of depends if we wants names that are meaningful or correct. RE7B is much better for devs to work with, but LE7B is the correct name

**Comment by crosire** [comment]
I would pefer meaningful names over "correct" names, similar to the discussion we had on "Firetruk" vs "Firetruck". Although I noticed this is still "Firetruk". Probably going to change that later. Unless there is major objection.

**Comment by kagikn** [comment]
After this discussion, I realized meaningful names are better than "correct" names for most people.

**Comment by Tanjitsu** [comment]
Is this is a pretty list of names for people too look at, or a scripting tool for developers to produce modifications to the game ?
