### ISSUE TITLE
Scripthookvdot net crashes game when I try to load a plugin with Ragehook

### ISSUE THREAD

**Issue by calinative5** [crosire/scripthookvdotnet#707]
Whenever I have ragehook plugin , scripthook & scripthook v dot net installed together the game crashes after I do anyting with the Ragehook console command. However, when i uninstall scripthook v dot net everything works perfectly fine with just ragehook and scripthook. Any ideas or suggestions?

**Comment by FrederikBolding** [comment]
Can you supply us with logs from the different plugins regarding the crash?

**Comment by calinative5** [comment]
Forgive me, man, I'm kind of new at this. When the game crashes it doesn't say it has anything to do with Ragehook It just says the game has crashed. 
![img_0856](https://user-images.githubusercontent.com/32650527/31622705-01e4200c-b252-11e7-86f8-d0cb256ec5ec.jpg)

**Comment by calinative5** [comment]
HERES THE FILES I HAVE IN MY GTA DIRECTORY. I PUT THE SCRIPTHOOKVDOTNET.DLL IN SCRIPTS TO SEE IF THAT MADE A DIFFERENCE, NO LUCK THO. EVERYTHING WORKS PERFECT WITHOUT SCRIPTHOOKVDOT NET. ALSO WHEN I REMOVE RAGEHOOK AND JUST HAVE SCRIPTHOOKVDOT NET IN ALL THE SCRIPTS WORK. THE TWO FILES JUST Won't WORK TOGETHER FOR SOME REASON. 
![img_0857](https://user-images.githubusercontent.com/32650527/31622845-662224ec-b252-11e7-90f2-888e67bdaca9.jpg)
![img_0858](https://user-images.githubusercontent.com/32650527/31622847-667811e0-b252-11e7-85b0-a0ef4eb5aa2d.jpg)
![img_0859](https://user-images.githubusercontent.com/32650527/31622848-66a82e52-b252-11e7-86c2-418928bfcd38.jpg)

**Comment by FrederikBolding** [comment]
Okay, could you post the contents of the log files?

**Comment by calinative5** [comment]
Exactly where would I find the log files? is that the crash report there under common.rpf?

**Comment by FrederikBolding** [comment]
In your GTA directory, there is a bunch of log files from different Scripthooks, Loaders etc.

**Comment by calinative5** [comment]
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/1388281/ScriptHookV.log)
[RagePluginHook.log](https://github.com/crosire/scripthookvdotnet/files/1388282/RagePluginHook.log)
[OpenIV.log](https://github.com/crosire/scripthookvdotnet/files/1388284/OpenIV.log)
[asiloader.log](https://github.com/crosire/scripthookvdotnet/files/1388285/asiloader.log)
[AdvancedHook.log](https://github.com/crosire/scripthookvdotnet/files/1388287/AdvancedHook.log)

**Comment by calinative5** [comment]
[ScriptHookVDotNet2.log](https://github.com/crosire/scripthookvdotnet/files/1388309/ScriptHookVDotNet2.log)

**Comment by FrederikBolding** [comment]
There doesn't seem to be any obvious reason in the logs as to why you're crashing. Can it have something to do with the plugin you're loading?

**Comment by calinative5** [comment]
To be honest I have no idea. What I will do is take all my plugins out and see if ragehook and scripthookvdot net work that way. If they do I will then add my plugins one by one and see which one is making the game crash. If it doesn't work at all I'ma have to assume they dont work together which is weird.

**Comment by calinative5** [comment]
I will post screenshots of all my plugins.

**Comment by calinative5** [comment]
![img_0860](https://user-images.githubusercontent.com/32650527/31639150-2029d1ee-b28c-11e7-82af-06af5ea88aeb.jpg)
![img_0861](https://user-images.githubusercontent.com/32650527/31639151-205a46c6-b28c-11e7-8618-772f2996371a.jpg)
![img_0862](https://user-images.githubusercontent.com/32650527/31639152-20747ea6-b28c-11e7-851e-10328bc287e8.jpg)
![img_0863](https://user-images.githubusercontent.com/32650527/31639153-20a5cdc6-b28c-11e7-9cc8-8e266170c1bb.jpg)

**Comment by calinative5** [comment]
![img_0860](https://user-images.githubusercontent.com/32650527/31639227-7d2bc154-b28c-11e7-8528-36d94a50dffe.jpg)
![img_0861](https://user-images.githubusercontent.com/32650527/31639228-7d455600-b28c-11e7-8590-9e7530253ba9.jpg)
![img_0862](https://user-images.githubusercontent.com/32650527/31639229-7d6015b2-b28c-11e7-9358-7cdf57d6aafb.jpg)
![img_0863](https://user-images.githubusercontent.com/32650527/31639230-7d7e4bf4-b28c-11e7-9f45-9a80a8355cea.jpg)

**Comment by calinative5** [comment]
Seems as if they won't work together. I even tried to just spawn a vehicle using the spawn command and the game crashed after typing Spawn and hitting space. For now i'ma just take scripthookvdotnet out and play that way. Hopefully, a fix comes out soon.

**Comment by Ruthles101893** [comment]
yeah im currently having this issue as long as i remove scripthookdotnet and do reloadallplugins with rage it dosnt crash, but if i do it with shdn it crashes rph if i do "reloadallplugins" or load a plugin, i've tried renaming scripts to _scripts, still crashes. It works perfectly fine without rage and with rage (without loading anything) here are e the logs of rph, shv, and shdn, and other logs just incase

[ScriptHookV.log](https://github.
[AdvancedHookV.log](https://github.com/crosire/scripthookvdotnet/files/7779129/AdvancedHookV.log)
[asiloader.log](https://github.com/crosire/scripthookvdotnet/files/7779128/asiloader.log)
[OpenIV.log](https://github.com/crosire/scripthookvdotnet/files/7779127/OpenIV.log)
com/crosire/scripthookvdotnet/files/7779126/ScriptHookV.log)
[RagePluginHook.log](https://github.com/crosire/scripthookvdotnet/files/7779121/RagePluginHook.log)
[ScriptHookVDotNet.log](https://github.com/crosire/scripthookvdotnet/files/7779123/ScriptHookVDotNet.log)
