### ISSUE TITLE
Getting SocialClub Name returns weird encoding symbols

### ISSUE THREAD

**Issue by DurtyFree** [crosire/scripthookvdotnet#708]
I just tried out the current SHVDN3 version and getting the social club name by using Game.Player.Name, seems to return some weird encoding symbols.

For example this: "ܨ\u0019V�\u0001"

**Comment by DurtyFree** [comment]
Did some testing today and it seems like the player class is  beeing broke because of the PLAYER_ID always beeing 0.

Tested with:
`using GTA;
using GTA.Native;

public class PlayerNativeTest : Script
{
	public PlayerNativeTest()
	{
		KeyDown += PlayerNativeTest_KeyDown;
	}

	private void PlayerNativeTest_KeyDown(object sender, System.Windows.Forms.KeyEventArgs e)
	{
		if (e.KeyCode == System.Windows.Forms.Keys.L)
		{
		    Console.Info("Your Social Club Name: " + Game.Player.Name);
		    var playerHandle = Function.Call<int>(Hash.PLAYER_ID);
		    Console.Info("Player Handle: " + playerHandle);			
		    Console.Info("Your Social Club Name by handle: " + Function.Call<string>(Hash.GET_PLAYER_NAME, playerHandle));
			Console.Info("Wanted Level: " + Game.Player.WantedLevel);
			Console.Info("Max Wanted Level: " + Game.MaxWantedLevel);			
        }
	}
}`

Results:
https://imgur.com/a/Sohip

**Comment by kagikn** [comment]
After conversation about with him (in PM), I realized [this is responsible](https://github.com/crosire/scripthookvdotnet/blob/dev_v3/source/core/Native.cs#L421) for this issue.
