### ISSUE TITLE
Console text cutoff

### ISSUE THREAD

**Issue by FrederikBolding** [crosire/scripthookvdotnet#717]
It seems that the console can't write more than 82 characters (in my case) without cutting off the rest of the string. I think the issue might be native and something we have to work around in the console code. It seems that there might have been attempts at doing that, but I was unsure when reading the code. Any ideas, thoughts or comments?

Example:
![image](https://user-images.githubusercontent.com/1561200/31618325-f0869e08-b291-11e7-8fac-981d06081e35.png)

**Comment by kagikn** [comment]
I've encountered the same issue. I know SHVDN has issue with multibyte strings longer than 99 byte in UTF-8 (I have [a solution](https://forums.gta5-mods.com/topic/13602/tips-how-to-draw-long-multibyte-strings), though), but I didn't know this problem until this issue page was created. We should solve this issue.

**Comment by FrederikBolding** [comment]
So it's an issue with how the strings are handled? We should handle strings via your attached function if that works better. Have you tested it?

**Comment by kagikn** [comment]
No, I've never tested in SHVDN. So I need to add the function to SHVDN try using it first.

**Comment by JohnnyCrazy** [comment]
I thought we handled this case by creating a new string...

**Comment by FrederikBolding** [comment]
@JohnnyCrazy You're talking about https://github.com/crosire/scripthookvdotnet/blob/fa48cd13fbf286f2ba1d6fe91bddd0328b083984/source/core/Console.cs#L737 right? - I stumbled upon that as well, but it doesn't seem to be working.

**Comment by FrederikBolding** [comment]
The following code using @kagikn's string slicing function seems to work better.
```
Native.Function.Call(Native.Hash.BEGIN_TEXT_COMMAND_DISPLAY_TEXT, "CELL_EMAIL_BCON");

foreach (string s in ToSlicedStrings(text))
{
    Native.Function.Call(Native.Hash.ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME, s);
}
```

![image](https://user-images.githubusercontent.com/1561200/31667725-888340da-b350-11e7-8a17-c0d114341310.png)

**Comment by FrederikBolding** [comment]
Actually just changing:
`Native.Function.Call(Native.Hash.BEGIN_TEXT_COMMAND_DISPLAY_TEXT, "CELL_EMAIL_BCON");`
Seems to do the trick.
![image](https://user-images.githubusercontent.com/1561200/31668181-c155528a-b351-11e7-9ded-ce4a00feeab9.png)

**Comment by FrederikBolding** [comment]
PR #719 changes from STRING to CELL_EMAIL_BCON, which allows for larger strings. It seems that we are also using it in other parts of the hook already.
