### ISSUE TITLE
Game::GetUserInput() not working?

### ISSUE THREAD

**Issue by Yothri** [crosire/scripthookvdotnet#72]
Hi,

just wanted to try working with User Interfaces and couldnt get GetUserInput not working.
![ss 2015-05-14 at 04 27 19](https://cloud.githubusercontent.com/assets/5815215/7633701/288b38d2-fa56-11e4-9f67-d848a8804d6a.png)

Guess i am using it wrong ?

Game crashes as soon as pressing numpad0

**Comment by Nacorpio** [comment]
Maybe you should assist us with the log?
Thank you.

**Comment by Yothri** [comment]
Well, i would but it doesnt say anything about the crash. Last thing after the crash is just that the Script has successfully instantiated and started.

**Comment by Nacorpio** [comment]
I have never used that function, so I'm afraid I won't be able to help you unless you somehow find out what causes the error.
Thank you.

**Comment by Yothri** [comment]
Well i am also contributing to the project, if i find out i will try to fix it :)

**Comment by Nacorpio** [comment]
Alright, nice.

**Comment by CrossCRS** [comment]
Does it only happen if you use only Game.GetUserInput(25); instead?

**Comment by JohnnyCrazy** [comment]
Hey,

The function works differently:
The first parameter should merge into the textbox, so if the textbox is open, you will see "Please enter..." already, the cursor will be located after the string.
The second parameter defines the max-length, 25 is not enough since your first string already got this length.

But I think I just discovered that using the string parameter doesnt work at all, the textbox is always empty, I will look into it.

**Comment by Yothri** [comment]
I tried now without a string in front... So just like this:
Game::GetUserInput(25);

but still crashing and log doesnt say anything since whole game crashes...

**Comment by JohnnyCrazy** [comment]
That should not happen. I'm using it multiple times in my projects and it works without flaws.

Are you on the latest GTA V version?

**Comment by Yothri** [comment]
I am using GTA V version: 1.0.350.2

**Comment by JohnnyCrazy** [comment]
This is a dumb idea, but could you try changing `string` to `String`? GetInput returns null if the user canceled the input.

**Comment by Yothri** [comment]
Got it like this now:
![ss 2015-05-14 at 04 27 19](https://cloud.githubusercontent.com/assets/5815215/7634053/9fb9f8c4-fa58-11e4-880f-388a60f3d826.png)

Still crashing. Log doesnt say anything.
Probably the natives.h is wrong? But everything else works fine... :P

**Comment by Yothri** [comment]
I just found out that this part:
`
while (Function.Call<int>(Hash.UPDATE_ONSCREEN_KEYBOARD) == 0)
                    Script.Wait(0);
`
(Do not wonder, converted to C#)
Causes the "crash".. Well it´s not really a crash, it´s just blocking the main thread caused by the Script.Wait(0) because this native UPDATE_ONSCREEN_KEYBOARD is allways 0...

**Comment by crosire** [comment]
Yeah. I was expecting Script.Wait to no longer work due to the crash fix from earlier (was just hoping for the best) ... Need to fix that again.

**Comment by Yothri** [comment]
So as soon as this gets fixed it should work again right?
Script.Wait just seemed to freeze the whole game thread, not only the script thread.
