### ISSUE TITLE
question, Could not cast transparent proxy to type - AppDomain

### ISSUE THREAD

**Issue by AppiChudilko** [crosire/scripthookvdotnet#720]
I have been this exception. Whats problem? Last version SHVDN. 

SVHDN Log

> [12:41:57] [DEBUG] Path0 scripts
> [12:41:57] [DEBUG] Path01 C:\test\bin\scripts
> [12:41:57] [DEBUG] Path1 C:\test\bin\scripts
> [12:41:57] [DEBUG] Path C:\test\bin\scripts
> [12:41:57] [DEBUG] Location C:\test\bin\ScriptHookVDotNet.dll
> [12:41:57] [DEBUG] FullName GTA.ScriptDomain
> [12:41:57] [INFO] Created new script domain with v3.0.0.
> [12:41:57] [DEBUG] appdomain GTA.ScriptDomain
> [12:41:57] [DEBUG] appdomainType System.MarshalByRefObject
> [12:41:57] [INFO] Created new script domain with v3.0.0.
> [12:41:57] [ERROR] Failed to create script domain': System.InvalidCastException: Could not cast transparent proxy to type "GTA.ScriptDomain" in GTA.ScriptDomain.Load (String path)

ScriptHookV.log

> // GTA V SCRIPT HOOK (build Sep  3 2017, v1.0.1180.2)
> //     (C) Alexander Blade 2015-2017
> [08:14:31] INIT: Started
> [08:14:31] INIT: Success, game version is VER_1_0_1180_2_STEAM
> [08:14:31] INIT: Registering script 'ScriptHookVDotNet.asi' (0x00007FFC126B1360)
> [08:14:35] INIT: Pool 1 extended
> [08:14:35] INIT: Pool 2 extended
> [08:14:35] INIT: Pool 3 extended
> [08:14:35] INIT: Pool 4 extended
> [08:14:41] INIT: GtaThread collection size 189
> [08:14:41] INIT: wnd proc 0x00000000FFFF08F9
> [08:14:41] INIT: IDXGISwapChain 0x00007FFC148A0AA0 (0x00007FFC14843610)
> [08:14:41] INIT: IDXGISwapChain set
> [08:14:41] INIT: DX init started
> [08:14:41] INIT: DX feature level B000
> [08:14:41] INIT: DX init succeeded
> [08:15:34] CORE: Requesting thread creation
> [08:15:34] CORE: Creating threads
> [08:15:38] CORE: Started control thread, id 39 active 1
> [08:15:38] CORE: Started thread 'ScriptHookVDotNet.asi' (0x00007FFC126B1360), id 40 active 1
> [08:15:38] CORE: Launching main() for 'ScriptHookVDotNet.asi' (0x00007FFC126B1360), id 40
> [08:16:02] UNINIT: Unregistering script 'ScriptHookVDotNet.asi'

```
public static ScriptDomain Load(string path)
{
    Log("[DEBUG]", "Path0 ", path);
    if (!Path.IsPathRooted(path))
    {
        path = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), path);
        Log("[DEBUG]", "Path01 ", path);
    }
    Log("[DEBUG]", "Path1 ", path);

    path = Path.GetFullPath(path);

    // Create AppDomain
    var setup = new AppDomainSetup();
	setup.ApplicationBase = path;
	setup.ShadowCopyFiles = "false";
	setup.ShadowCopyDirectories = path;

	var appdomain = AppDomain.CreateDomain("ScriptDomain_" + (path.GetHashCode() * Environment.TickCount).ToString("X"), null, setup, new System.Security.PermissionSet(System.Security.Permissions.PermissionState.Unrestricted));
	appdomain.InitializeLifetimeService();

    Log("[DEBUG]", "Path ", path);
    Log("[DEBUG]", "Location ", typeof(ScriptDomain).Assembly.Location);
    Log("[DEBUG]", "FullName ", typeof(ScriptDomain).FullName);
            
    ScriptDomain scriptdomain = null;

    try
    {
        MarshalByRefObject test = (MarshalByRefObject) appdomain.CreateInstanceFromAndUnwrap(typeof(ScriptDomain).Assembly.Location, typeof(ScriptDomain).FullName);
        Log("[DEBUG]", "appdomain ", test.ToString());
        Log("[DEBUG]", "appdomainType ", test.GetType().ToString());
                
        scriptdomain = (ScriptDomain) appdomain.CreateInstanceFromAndUnwrap(typeof(ScriptDomain).Assembly.Location, typeof(ScriptDomain).FullName);
    }
	catch (Exception ex)
	{
		Log("[ERROR]", "Failed to create script domain':", Environment.NewLine, ex.ToString());

		AppDomain.Unload(appdomain);

		return null;
	}

	Log("[INFO]", "Loading scripts from '", path, "' ...");

	if (Directory.Exists(path))
	{
		var filenameScripts = new List<string>();
		var filenameAssemblies = new List<string>();

		try
		{
			filenameScripts.AddRange(Directory.GetFiles(path, "*.vb", SearchOption.AllDirectories));
			filenameScripts.AddRange(Directory.GetFiles(path, "*.cs", SearchOption.AllDirectories));
			filenameAssemblies.AddRange(Directory.GetFiles(path, "*.dll", SearchOption.AllDirectories));
		}
		catch (Exception ex)
		{
			Log("[ERROR]", "Failed to reload scripts:", Environment.NewLine, ex.ToString());

			AppDomain.Unload(appdomain);

			return null;
		}

		for (int i = 0; i < filenameAssemblies.Count; i++)
		{
			var filename = filenameAssemblies[i];
			var assemblyName = AssemblyName.GetAssemblyName(filename);

			try
			{
				if (assemblyName.Name.StartsWith("ScriptHookVDotNet", StringComparison.OrdinalIgnoreCase))
				{
					Log("[WARNING]", "Removing assembly file '", Path.GetFileName(filename), "'.");

					filenameAssemblies.RemoveAt(i--);

					try
					{
						File.Delete(filename);
					}
					catch (Exception ex)
					{
						Log("[ERROR]", "Failed to delete assembly file:", Environment.NewLine, ex.ToString());
					}
				}
			}
			catch (Exception ex)
			{
				Log("[ERROR]", "Failed to load assembly file '", Path.GetFileName(filename), "':", Environment.NewLine, ex.ToString());
			}
		}

		foreach (string filename in filenameScripts)
		{
			scriptdomain.LoadScript(filename);
		}
		foreach (string filename in filenameAssemblies)
		{
			scriptdomain.LoadAssembly(filename);
		}
	}
	else
	{
		Log("[ERROR]", "Failed to reload scripts because the directory is missing.");
	}

	return scriptdomain;
}
```

**Comment by kagikn** [comment]
Thanks to this guy, I realized the dll won't be loaded if the filename is ScriptHookVDotNet.dll.
We should fix this issue or at least notice for this. Any ideas, @crosire ?

**Comment by AppiChudilko** [comment]
@kagikn whats i can do? Because i wanna fix this problem.

**Comment by kagikn** [comment]
@AppiChudilko If your dll name is ScriptHookVDotNet.dll, rename it to ScriptHookVDotNet3.dll (the default name), and the problem will be solved.

**Comment by AppiChudilko** [comment]
@kagikn 

> [07:10:20] [DEBUG] Path C:\test\bin\scripts
> [07:10:20] [DEBUG] Location C:\test\bin\ScriptHookVDotNet3.dll
> [07:10:20] [DEBUG] FullName GTA.ScriptDomain
> [07:10:20] [INFO] Created new script domain with v3.0.0.
> [07:10:21] [ERROR] Failed to create script domain': System.InvalidCastException: Could not cast transparent proxy to type "GTA.ScriptDomain" in GTA.ScriptDomain.Load (String path)

**Comment by kagikn** [comment]
Very weird, but I have no idea how to fix this problem. We'll need more test in different environment or search the core code to find out what causes the problem.

**Comment by AppiChudilko** [comment]
@kagikn svh2 have not this problem

**Comment by FrederikBolding** [comment]
Could there be something wrong with the version you are compiling @AppiChudilko? Have you changed anything?

**Comment by AppiChudilko** [comment]
@FrederikBolding no

**Comment by crosire** [comment]
This should be fixed in master.
