### ISSUE TITLE
Advanced notification support

### ISSUE THREAD

**Issue by FrederikBolding** [crosire/scripthookvdotnet#723]
For now we only support "simple" notifications. I think we should support more "advanced" notifications, that includes usage of header, icons etc.

I've been trying to implement it, but I am having a difficult time with the natives: https://github.com/FrederikBolding/scripthookvdotnet/blob/38ae2ed3660e7bf0a89c9441bff366376e8e2431/source/scripting/UI/Notification.cs

Any ideas? Thoughts on advanced notifications?

**Comment by FrederikBolding** [comment]
I'm looking at this again, should have a pull request ready soon! 😄

**Comment by crosire** [comment]
Closing since #817 was merged which implements this.
