### ISSUE TITLE
Quaternation issues?

### ISSUE THREAD

**Issue by CalicoApricot** [crosire/scripthookvdotnet#726]
Following a thread posted on [forums.gta5-mods.com](https://forums.gta5-mods.com/topic/15515/quaternation-sh-t), it seems ScriptHookVDotNet have some problems calculating quaternions in some particular scenarios.

More exactly —and to repost an example in wrote there—, I firstly converted a Menyoo-based map to .ymap ([Los Santos Electric Railway [Replace]洛圣都电气化铁路](https://www.gta5-mods.com/maps/los-santos-electric-railway-replace) to be exact) but two specific replaced items aren't rotated in-game (rail catenaries replacing _prop_cs_20m_rope.ydr_ and _prop_cs_30m_rope.ydr_ in \Grand Theft Auto V\mods\x64c.rpf\levels\gta5\props\lev_des\lev_des.rpf\), standing always in a horizontal position when loaded as addon map.

However they are correctly rotated/shifted when loaded in both Menyoo or Map Editor in-game or when displayed in the Codewalker app.
Another user also reported the same problem while exporting their map as addon.

Does this quaternation issue is related to a bug within ScriptHookVDotNet?

**Comment by varunkumar2310** [comment]
@CalicoApricot 
I have fixed issues on quaternions in PR #773 #774 #775 .
Can you verify one again, if the issues are still persisting ?
