### ISSUE TITLE
Setting for not loading any scripts or loading specified ones on startup

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#733]
I used to not mind loading all scripts on startup at all, but one script modder's remark made me realize not loading all scripts on startup can brought benefit especially when you have many scripts to load.
Why not add a setting for this?

**Comment by DurtyFree** [comment]
I have some questions regarding this

Define "many scripts", how many?
We are loading up round about 30 scripts on game startup and there are no issues so far.

What benefit would not loading up all at ones bring?
What do you mean by not loading them all on startup, what decides which one to load first and when  get the other ones loaded?

**Comment by kagikn** [comment]
I have about 50 scripts for v2 and my game keep me waiting quite long, there's no issue to use SHVDN though.
Iknow that I should seek what benefit not loading up all at ones brings more, but I don't have much time to play GTA now.

**Comment by kagikn** [comment]
I'll close this issue for now, but if I find not loading any scripts and loading only specific ones really useful, I'll reopen.
