### ISSUE TITLE
Matrix.TransformPoint and Matrix.InverseTransformPoint seem to be broken

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#737]
When I ported SHVDN to C# I didn't completely get what `Matrix.TransformPoint` and `Matrix.InverseTransformPoint`. Can anyone check if they're properly implemented in C# and port the C++/CLI code properly if they're broken?
[Old implementation](https://github.com/crosire/scripthookvdotnet/blob/095fe75b039b4a7bf96822a3f24e0f6efad6d47b/source/scripting/Matrix.cpp#L285)

**Comment by crosire** [comment]
That looks broken: https://github.com/crosire/scripthookvdotnet/blob/888d1eca1bb3ec30bbe9158514aded4d4626380e/source/scripting/Math/Matrix.cs#L388
`InverseTransformPoint` should not permanently invert the current matrix, it should only do that for the duration of the method (AFAIK access to `this` fields is working on a reference, not a copy of the object). The correct way to do so would be:
```c#
return Invert(this).TransformPoint(vector);
```

**Comment by kagikn** [comment]
That makes sanse. Will test the code after Script Hook V is updated or revert back to a old patch.

**Comment by Tanjitsu** [comment]
Using Raycast (Camera.GetOffsetPosition()) seems to show the Matrix.TransformPoint not transforming the vector.

**Comment by varunkumar2310** [comment]
Any update w.r.t this issue ?

**Comment by kagikn** [comment]
@varunkumar2310 I've just fix using `Func` in `GetEntitySkeletonData` (`Marshal.GetDelegateForFunctionPointer` doesn't allow `Func`) and inverting matrix themselves in `InverseTransformPoint`, but I'm not sure if the methods that use `Matrix.InverseTransformPoint` now return correct values.

**Comment by jamesdsmith** [comment]
I discovered an issue in Matrix.TransformPoint, fixed in PR #772

**Comment by crosire** [comment]
Closing since this has been fixed in #772.
