### ISSUE TITLE
Question | Inquiry

### ISSUE THREAD

**Issue by InspectorGadget** [crosire/scripthookvdotnet#738]
Hello, I'd like to clarify if this ScriptHook is currently supporting the latest 1.42 GTA V or not? I've been having issues injecting using Gradient (Xenos). I've also attached with 2 screenshots
![screenshot 121](https://user-images.githubusercontent.com/20971020/33885400-2e3bf4b4-df7e-11e7-9869-35b641ae0afb.png)
![screenshot 122](https://user-images.githubusercontent.com/20971020/33885402-2e74b876-df7e-11e7-8533-10d3677582a5.png)

 for further understanding.

Thanks

**Comment by DurtyFree** [comment]
No, SHVDN requires ScriptHookV, which doesn't support the Doomsday Heist Update yet.
