### ISSUE TITLE
Crash after a few minutes

### ISSUE THREAD

**Issue by crosire** [crosire/scripthookvdotnet#74]
Apparently 4f10ef082a29f92a851aedcd7b3a4eca425fadde introduced a new bug where the game does crash after being ingame for a few minutes.

**Comment by Tusticles** [comment]
Same here but after a few seconds, not minutes.

**Comment by MarcusBlackX** [comment]
Yes but for me it's around 10 seconds after story mode loads and crashes.

**Comment by Yothri** [comment]
Same here, crashing after 3-5 seconds

**Comment by Monsterxsync** [comment]
Same here after story loads pretty much instantly. Just using old version
for now.

**Comment by Nacorpio** [comment]
I won't update my mod to the new version unless this gets fixed.

**Comment by Ethenal** [comment]
You can check out the commit before the bugged one if you want to have a functioning version.

**Comment by Yothri** [comment]
I hope this will get fixed soon.

**Comment by crosire** [comment]
Rewrote the whole script management routine. Each script now gets its own thread to run in. They are still executed sequentially (some tests showed that things started to go crazy quickly if not), but it comes with some benefits:
* Scripts can be aborted completly (and cleanly).
* Script Hook now checks if scripts are responsive. If one blocks the game and times out it will be aborted automatically to prevent the game from crashing.
* Calling "Script::Wait" no longer blocks everything, it only waits in the script it was requested in, all others continue to run.

**Comment by IncoCode** [comment]
Good job :+1:

**Comment by RainerHilmer** [comment]
Excellent! :+1:

**Comment by Tusticles** [comment]
Great job :+1:

**Comment by Nacorpio** [comment]
I get an error in the Main constructor when I try to launch the script.
*[15:18:33] [ERROR] Failed to instantiate script 'GTAV_purge_mod.Main' because constructor threw an exception:*

**Comment by crosire** [comment]
Natives cannot be called in the constructor currently.

**Comment by Nacorpio** [comment]
I remove the natives, and now I get the following error:
``*[15:39:01] [ERROR] Failed to instantiate script 'GTAV_purge_mod.Main' because constructor threw an exception:
System.MissingFieldException: Fältet hittades inte: GTA.Script.View.
   vid GTAV_purge_mod.Main..ctor()*``

**Comment by Yothri** [comment]
Getting NullReferenceExceptions as fuck.

**Comment by Nacorpio** [comment]
Somehow, it works for me now.
I don't know what I did to make it work, but it does.

**Comment by crosire** [comment]
You can now (starting with 7900b0c1d50d128a31d750e5abfb618cc52f07e0) call natives in the constructor again.
