### ISSUE TITLE
camera vibrated with the vehicle

### ISSUE THREAD

**Issue by tyzaizl** [crosire/scripthookvdotnet#748]
[camera_vibration.mp4.zip](https://github.com/crosire/scripthookvdotnet/files/1574833/camera_vibration.mp4.zip)
When I set the camera with "First Person Vehicle Hood", the camera will be vibrated with the vehicle terribly, and sometimes the camera points to the sky in 1st frame and then points to the ground in next frame.
How to solve this problems?
Does anyone has an idea?
just rename the attachment *.mp4 to watch the video of this problem

**Comment by kagikn** [comment]
I believe, SHVDN has nothing to do with this. If you use other mods except ScriptHookV and SHVDN, remove them and test your game.

**Comment by tyzaizl** [comment]
@kagikn thanks for reply
yes, I use a script based on ScriptHookV and SHVDN.
And is it possible to set the camera static when it in "First Person Vehicle Hood" state, as the camera in air?

**Comment by kagikn** [comment]
What scripts are you using?
Some mods such as "GTA V FoV" needs/needed updates to support the latest game patch, trust me.

**Comment by tyzaizl** [comment]
https://github.com/umautobots/GTAVisionExport
this project to extract buffers (RGB, depth, stencil) as tiff images from the game.

**Comment by tyzaizl** [comment]
By the way, I didn't met this problem in the forma version of GTAV 1.0.877.1 and SHVDN 2.10.1.

**Comment by kagikn** [comment]
Sorry, but I'll close this issue. If we confirm SHVDN still has some serious bugs related to what you mentioned, we'll reopen.

**Comment by tyzaizl** [comment]
@kagikn Thanks a lot. I have solved this problem. And it's not the problem of SHVDN. I missed one command in my project. Thanks anyway.
