### ISSUE TITLE
ScriptDomain.StartAllScripts() stops execution if non-script dependencies are present

### ISSUE THREAD

**Issue by DorCoMaNdO** [crosire/scripthookvdotnet#749]
Line 560 returns if the loaded assembly had no scripts, this breaks the console function ReloadAllScripts() when a non-script dependency is present in the scripts folder, I doubt that's intended since the initial loading of scripts works just fine when such a dependency is present.

**Comment by kagikn** [comment]
Thanks for reporting a bug. Btw, next time please link to specific line numbers, like this. https://github.com/crosire/scripthookvdotnet/blob/691e2650259a4f5109710fc8a83a55b18a8e6e6a/source/core/ScriptDomain.cs#L560

**Comment by DorCoMaNdO** [comment]
Never linked to a line, didn't know if it would display the long link or embed the line's content so I just gave the line number.
