### ISSUE TITLE
False circular script dependency detection

### ISSUE THREAD

**Issue by DorCoMaNdO** [crosire/scripthookvdotnet#750]
Didn't happen with older versions of script hook (talking really old, I haven't updated in a while since I lost the source of most of my scripts), but I couldn't update for the last few months regardless of the compatibility issues some of the scripts have, the code falsely detects a circular dependency when there isn't one, line 469 in ScriptDomain.cs for some reason does not remove the dependency after it has loaded.

https://github.com/crosire/scripthookvdotnet/blob/691e2650259a4f5109710fc8a83a55b18a8e6e6a/source/core/ScriptDomain.cs#L469

Replacing line 469 with the following solved the issue:
```item.Value.RemoveAll(t => t.ToString() == scriptType.Item2.ToString());```

**Comment by crosire** [comment]
This should no longer be an issue with the changes from #815.
