### ISSUE TITLE
Community Script Hook V .NET doesn't load (Win10 Creators Update)

### ISSUE THREAD

**Issue by HeyHeyDaniel** [crosire/scripthookvdotnet#751]
Hi!

I just installed everything I need for the "Single Player Apartment Mod" and during the GTA 5 loading screen I get the following error-message and GTA 5 stops loading. When I click "OK" it continue to load and I can play the game but without the features of the mod, of course.  Does anyone know how to fix that?

---------------------------
Community Script Hook V .NET
---------------------------
FATAL: Unable to load 'C:\Program Files (x86)\Grand Theft Auto V\ScriptHookVDotNet2.dll' due to the following exception:
 
System.IO.FileLoadException: Die Datei oder Assembly "file:///C:\Program Files (x86)\Grand Theft Auto V\ScriptHookVDotNet2.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)
 
Dateiname: "file:///C:\Program Files (x86)\Grand Theft Auto V\ScriptHookVDotNet2.dll" ---> System.NotSupportedException: Es wurde versucht, eine Assembly von einer Netzwerkadresse zu laden, was in früheren Versionen von .NET Framework zum Ausführen der Assembly als Sandkastenassembly geführt hätte. In dieser Version von .NET Framework wird die CAS-Richtlinie standardmäßig nicht aktiviert, dieser Ladevorgang kann daher gefährlich sein. Wenn Sie nicht beabsichtigen, durch diesen Ladevorgang eine Sandkastenassembly zu erstellen, aktivieren Sie den loadFromRemoteSources-Schalter. Weitere Informationen finden Sie unter "http://go.microsoft....LinkId=155569".
 
   bei System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
 
   bei System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
 
   bei System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
 
   bei System.Reflection.Assembly.LoadFrom(String assemblyFile)
 
   bei ManagedInit()
 
 
 
 
---------------------------
OK   
---------------------------
 
Thanks :-)

**Comment by crosire** [comment]
https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/

**Comment by HeyHeyDaniel** [comment]
I did that and now there is no error message anymore. But the mod/script doesn't seem to load...
