### ISSUE TITLE
Making game engine to wait.

### ISSUE THREAD

**Issue by muaz-git** [crosire/scripthookvdotnet#756]
Hello,

So I am trying to modify code from this [repository](https://github.com/umautobots/GTAVisionExport). Which is actually capturing images and later plan to use the data for object recognition or some other research problems. 

I am trying to capture the data for different lightning conditions, i.e. changing weathers and day time. I am using following code:

```
Game.Pause(true);
Script.Wait(500);
int d = 0; // delay variable
for (int hour = 0; hour < 24; hour++){
    colors = new List<byte[]>();
    World.CurrentDayTime = new TimeSpan(hour, 0, 0);
    Script.Wait(d);
    foreach (var wea in wantedWeather) { // wantedWeather: list of desired weathers
            World.TransitionToWeather(wea, 0.0f);
            Script.Wait(d);
            colors.Add(VisionNative.GetColorBuffer()); // captures the screen
    }
// here goes code to save colors as an image on disk.
}
Game.Pause(false);
```
 

If I don't use loops and change the weather or time once, in the beginning bright objects get a bit exposed, but after some time it brings back all the details.

 

And when I try to use `d=0`, it does proper transitions to weather and time, but some times specially for day time bright objects (like sky) get over exposed such that there are no details to near by objects i.e. clouds.

 

In my opinion, game engine needs some time to adapt the environment to get back to normal. 

 

I tried to increase the delay i.e. `d=100` or `d=1000`, in that case script just waits and there are no transitions to weather or time, and only one image of "environment" (maybe `Scripthook` is waiting) gets saved.

 

So I was just wondering if I could somehow make my code wait such that game engine brings rendering to normal or lights not get over exposed. Does there any functionality exist?

**Comment by Tanjitsu** [comment]
TransitionToWeather would suggest the game is told to move from one to the other... this would not be instant. Instead use World.Weather = Weather.Sunny,

**Comment by Tanjitsu** [comment]
From looking at your initial code some more... you might be best to first set the weather, then cycle the hours. I seem to remember the time change is alot more responsive.

For the delay.. ("some functionality I could use to make Scripthook wait").
Script.Wait(x) should be pausing your script alone.
You could try to use Script.Yield().

**Comment by muaz-git** [comment]
@Tanjitsu thank you for comment. Can you please explain the difference between `Script.Wait()` and `Script.Yeild()`. Also, if there are any other functions that can be used in similar manner?

**Comment by muaz-git** [comment]
So currently, what I have tried is as follows:
```
DateTime endtime;
Game.Pause(true);
Script.Wait(500);
foreach (var wea in wantedWeather) { // wantedWeather: list of desired weathers
   colors = new List<byte[]>();
   World.Weather = wantedWeather[w];
   for (hour = 0; hour < 24; hour += 2) {
      World.CurrentDayTime = new TimeSpan(hour, 0, 0);
      endtime = DateTime.UtcNow + new TimeSpan(0, 0, 0, 0, 1000);
      while (endtime > DateTime.UtcNow){
         Script.Yield();
      }
      colors.Add(VisionNative.GetColorBuffer());
   }
}
// here goes code to save colors as an image on disk.
Game.Pause(false);
```
Using this approach, results are much better. I was just wondering if `"yielding"` for like 1 second is a good idea or if there is some better alternative to it?

**Comment by Tanjitsu** [comment]
Prob something like...
Script.Yield(); stops executing your script and allows other scripts to run until the next cycle.
Script.Wait(); stops executing your script until a certain amount of time has passed.
Wait could last multiple cycles of the main thread.

**Comment by crosire** [comment]
`Script.Yield()` is a shortcut for `Script.Wait(0)`.

**Comment by muaz-git** [comment]
So, when I pause the game using the script and iterate over different weathers, it doesn't render complete effects of particular weather.
For example, I pause and change the weather to `Snowing` or `Blizzard`, game doesn't render snow until or unless I resume the game.
The idea, why I am trying to do this way is, I want to capture data in a way that I should have same annotations i.e. for pedestrians or cars, over different lightning conditions (weathers and times) so that we can develop an algorithm to detect objects which would be robust to these conditions.
Do you guys think if it is possible somehow using scripthook? I would really appreciate your comments over it. Thank you.

**Comment by varunkumar2310** [comment]
@muaz-git 
Use 
1. Game.TimeScale = 0.0f; ( slows down the game time significantly, but not to static conditions )
2. for loop (loop ur cameras)
3. ----   Game.Pause(true);
4. ----   get camera screenshot/ get annotations
5. ----   render next camera
6. ----   Script.Wait(0)
7. ----   Game.Pause(false);
8. Game.TimeScale = 1.0f;

**Comment by varunkumar2310** [comment]
@muaz-git
pseudo algo/ steps u need to follow :

Game.TimeScale = 0.0f; ( slows down the game time significantly, but not to static conditions )
for loop (loop ur cameras/ environments)
---- Game.Pause(true);
---- get camera screenshot/ get annotations
---- render next camera/ change game environment settings
---- Script.Wait(0)
---- Game.Pause(false);
Game.TimeScale = 1.0f;
rewrite the above code using on-ticks and relevant calls.
