### ISSUE TITLE
Task.StartScenario() doesn't appear to expose the heading parameter.

### ISSUE THREAD

**Issue by LeeC2202** [crosire/scripthookvdotnet#757]
TASK_START_SCENARIO_AT_POSITION has a heading as a parameter, Task.StartScenario() seems to ignore this and sets a default value of 0f for the heading.

Like the World.GetGroundHeight() function (which forces the offset to 1000f), forcing default parameters does nothing but limit the functionality of that function. It is much better when those parameters are made available to the people needing to use those functions, outside the limited predefined values.

If people want 0f, or in the case of the World.GetGroundHeight() 1000f, then they can set it to that. But at least they will have the option to also set it to something more useful.

**Comment by RainerHilmer** [comment]
The problem with GroundHeight is that it always returns 0f when farther away than ~30 meters from the player. I found out that if I add 1000 meters it's like the code somehow scans for the ground height from above until it hits the ground. The highest elevation on the map is the roof top of the cable car station on Mt Chiliad,  which is around 800 meters iirc. I just rounded to 1000 meters in case R* adds something even higher in the future. Yes, that trick was my idea. :)

**Comment by LeeC2202** [comment]
Hi RaineHilmer,
The problems is when you stand under something, it detects the height of whatever you're stood under, instead of the ground you're stood on, which is where I kept running into problems with it. It's something that I noticed when I was doing my cinematic onfoot camera. I do detection to make sure the camera is always above ground, by using an offset of +5f and then scanning downwards. But when you are under a garage, because it is scanning from 1000f, it detects the garage roof. And like in my helicopter effects, I needed to detect ground and water height but under bridges, the top of the bridge gets detected as the ground.

So the offset isn't so much a case of the highest point on the map, just a case of how high above your current detection point you are checking from... and that's why it is so important to be able to set values of sometimes as little as 1f, especially if you are checking for slight variations in ground topology. In my latest mod, I have an adjustment mode where I can adjust spawn locations that need to maintain a 1f distance from the ground and that needs to change when it goes up slopes or steps. So I check for the position + (0,0,1f) and always adjust to get a distance of 1f from the position to the ground. But if those steps are under something, SHVDN GroundHeight won't work.

I hope my explanation has added a bit more information as to why I see things like this as being so important. I know my comments are often negative but the things I have created have exposed problems that I envision others might have, so I make them in the hope they help to make things better for others.

**Comment by LeeC2202** [comment]
These might give a better visual example of how the ground height problem affected what I was doing.

This is with a native based check: https://youtu.be/cMDErXDy2kc and you can see how I can move the cursor. This is with SHVDN https://youtu.be/i6YMZnGpKj8

**Comment by RainerHilmer** [comment]
This sounds very good indeed. I din't know about the collision request. Maybe you can fork the repo and offer an improved code? I think everyone would greatly appreciate it.

**Comment by LeeC2202** [comment]
I am afraid I don't know anything about how GitHub works with forking repos and pull requests. As a lone soldier, I am pretty much self-contained. I also don't use the latest Visual Studio, I only use the latest version of the game for compatibility testing (I actually have 6 versions for testing via the launcher bypass mod) and I still use SHVDN 2.9.6, so my whole setup isn't really compatible with anything, purely because it doesn't need to be. And then of course, is my questionable code quality... which I guess is a shame, because I actually find API wrapping quite interesting, from wrapping the Nintendo API on the Gameboy Color.

But my ground height code is nothing more than this:

```public static float GetWorldGroundHeight(Vector3 position, float zoffset)
{
	OutputArgument groundZ = new OutputArgument();
	Function.Call(Hash.GET_GROUND_Z_FOR_3D_COORD, position.X, position.Y, position.Z + zoffset, groundZ, 0);
	return groundZ.GetResult<float>();
}```

As for the collision request, that's probably left to the user to call as required, otherwise they could end up force-loading lots of collision data that will eat up resources. Unless of course you made an overload that took a `bool requestcollision` as well.

But I think the crux of all this, is just that if there are parameters that can be used, it would be good if there was some way of accessing them, without resorting to what can often be confusing native calls. There's another with the Task.ParkVehicle where the mode property is defaulted to 1 out of these options.

Modes:
0 - ignore heading
1 - park forward
2 - park backwards

So if you need a vehicle to reverse into a location, or you don't know what direction you will eventually park in, you have to move your whole task sequence processing into natives, just to get access to that one vital property.

Anyway, these are just my rambling suggestions, maybe they provide a bit of useful insight as well.

**Comment by LeeC2202** [comment]
As you can see, I don't know how to use the code markup on here either... don't know what happened to the code formatting in that post. :( Sorry about that.

**Comment by Tanjitsu** [comment]
public static float GetGroundHeight(Vector2 position, float offset = 1000f)
		{
			return GetGroundHeight(new Vector3(position.X, position.Y, offset));
		}

**Comment by LeeC2202** [comment]
But that's just causing people to take a 3D point in space represented by a Vector3, converting that to a Vector2, just so you can pass the 3rd part of the Vector3 as another parameter... to a native that wants an X, Y, Z _and_ an offset.

Isn't (Vector3 position, float offset) the more logical way to do that?

Offsets are _relative_ to a point in space, like the `Ped.GetOffsetInWorldCoords()`, if your offset is relative to an arbitrary point in 3D space (in this case 0, 0, 0), then it's merely a component of the position... it's not an offset.

**Comment by LeeC2202** [comment]
Sorry... I promise this is my last comment... let me just leave you with this thought.

Trevor's trailer is at around Vector3(1900f, 3800f, 33f) and the height check would be from Vector3(1900f, 3800f, 1033f) because it would be 1000f + the Z component.

The Chiliad Cable Car is at Vector3(450f, 5500f, 781f) and the height check would be from Vector3(450f, 5500f, 1781f) because it is from 1000f + the Z component.

The 1000f isn't the check height, it's the offset _**on top of**_ the position.Z value.

**Comment by Tanjitsu** [comment]
Using the offset exposed you could just call GetGroundHeight(position, 0f);
and that would have the effect of just using the vector with a 0f offset.
