### ISSUE TITLE
ScriptHookVDotNet crashes game when loading RPH

### ISSUE THREAD

**Issue by chickenboi12** [crosire/scripthookvdotnet#759]
I've spent 4 hours straight trying to figure out why my game crashes whenever I have SHVDN installed but as soon as I take it out my game runs smoothly. I don't really know what to look for in the log files. Anyone have any ideas what is causing this?

[AdvancedHook.log](https://github.com/crosire/scripthookvdotnet/files/1645234/AdvancedHook.log)
[AdvancedHookV.log](https://github.com/crosire/scripthookvdotnet/files/1645235/AdvancedHookV.log)
[asiloader.log](https://github.com/crosire/scripthookvdotnet/files/1645236/asiloader.log)
[ELS.log](https://github.com/crosire/scripthookvdotnet/files/1645237/ELS.log)
[openCameraV.log](https://github.com/crosire/scripthookvdotnet/files/1645238/openCameraV.log)
[OpenIV.log](https://github.com/crosire/scripthookvdotnet/files/1645239/OpenIV.log)
[RagePluginHook.log](https://github.com/crosire/scripthookvdotnet/files/1645240/RagePluginHook.log)
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/1645241/ScriptHookV.log)
[ScriptHookVDotNet2.log](https://github.com/crosire/scripthookvdotnet/files/1645242/ScriptHookVDotNet2.log)

**Comment by RainerHilmer** [comment]
Well the first suspicious thing I can see without even opening any of the logs. You are using scripthookV AND AdvancedHook. You should decide for one of both because of conflicts. Since shvdn references scripthookV you should get rid of advancedhook.

**Comment by chickenboi12** [comment]
Thank you for that, I got rid of AH but it still crashes when I load up Rage.

**Comment by RainerHilmer** [comment]
Your issue is related to RPH but not shvdn. I suggest you either ask for help in the RPH forum or in the forum at gta5-mods.com.

**Comment by RainerHilmer** [comment]
What mod is policeVehicleRadar? Maybe this is the culprit. Have you tried without it?

**Comment by chickenboi12** [comment]
It's the only script in my scripts folder and it doesn't matter if I have it or not. It doesn't work

**Comment by RainerHilmer** [comment]
This is really strange because shvdn does **nothing** if there is no .net script mod. Have you tried a modified gameconfig.xml like this one -> https://www.gta5-mods.com/misc/gameconfig-xml-dilapidated

**Comment by chickenboi12** [comment]
I have not. I'll give it a try though

**Comment by Ruthles101893** [comment]
so i can use ScriptHookVDotNet v2.10.7 without rage instantly crashing like the latest version of shdn even when i do reloadallplugins

**Comment by CriminalJustice** [comment]
I'm still having the same issue with SHVDN that I had before with the most previous version When I take out the  ScriptHookVDotNet.asi file my game runs great, but the second I put that file back in, the game starts crashing. I've tested this many times. This is with the latest version of SHVDN that was just updated yesterday. The other SHVDN files work. Then one that doesn't is the ScriptHookVDotNet.asi file. This new version of GTAV 2802 has really done a number on allot of peoples games.

**Comment by kagikn** [comment]
Closing this issue since #1167 should fix.
