### ISSUE TITLE
Task.Goto does not work

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#76]
I tried the following code but the player character just stands there. Game.Player.Character.Task.GoTo(CommonFunctions.GetWaypoint().Position, ignorePaths: false);
//note: CommonFunctions.GetWaypoint() returns a valid Waypoint marker Blip.

**Comment by Yothri** [comment]
Just try this instead:
```cs
Game.Player.Character.Task.GoTo(CommonFunctions.GetWaypoint().Position, false);
```

If it´s then not working it must be the GetWaypoint() function. Or maybe the fact that, the marker is too far from the player away? No idea, test it out when setting the marker 10meters away or so.

**Comment by RainerHilmer** [comment]
Thanks for your reply.
ignorePaths: is just syntactic sugar. So it doesn't change anything if I omit it. I use this also with the DriveTo method and that works flawlessly.
GetWaypoint works because I have used it a hundred times already for letting the character drive autonomously to a waypoint.
I have tested it with a short distance, maybe 30 meters though because it's not even possible to set a waypoint just 10 meters away. It gets removed as soon as you leave the map view.

**Comment by Yothri** [comment]
Well then i got no idea why this isn´t working. Probably another bug after some last revision commits?!
Gonna check this out and look into it when i get home.

**Comment by RainerHilmer** [comment]
Thanks for your help. It's much appreciated. I remember the Goto method hasn't worked in GTA IV/EFLC either (I mean with the scripthookdotnet).

**Comment by Yothri** [comment]
Okey so i tried it now and when doing this:
```cs
if(e.KeyCode == Keys.NumPad1)
{
    Game.Player.Character.Task.GoTo(Game.Player.Character.Position + Game.Player.Character.ForwardVector * 20.0f, false);
}
```

My character just runs 20.0f units in front of him.
I am now going to try using this Waypointing.

**Comment by RainerHilmer** [comment]
Hmm okay I'm going to try that and take a look under the hood because it looks the same from above. Thanks so far. :)

**Comment by RainerHilmer** [comment]
This is totally weird!
/* This works: */
         Game.Player.Character.Task.GoTo(Game.Player.Character.Position + Game.Player.Character.ForwardVector * 70.0f, false);
         /* but this don't: */
         //Game.Player.Character.Task.GoTo(waypoint.Position, false);

Yes, waypoint.Position has valid values. I created a debug output for it (not shown here). I tried both with the same distances, same positions, with and without obstacles in the line. I don't get it!

**Comment by Yothri** [comment]
Upload your whole project to uploaded.net or such another freehoster and share it with me. I'll have a look at it.

**Comment by RainerHilmer** [comment]
I found the culprit and I created a new issue ticket because the culprit is in the GetGroundZ method.
https://github.com/crosire/scripthookvdotnet/issues/180
