### ISSUE TITLE
Manipulating other script instances from inside of script.

### ISSUE THREAD

**Issue by racinmat** [crosire/scripthookvdotnet#760]
Hi, 
I have a main script, which does many things, some heavy lifting, and has interval 100ms. 
And I have helper script, with interval=0, which just manages camera and stuff. 
And I need to get instance of that helper script in the main script, so I couls set som attributes there. Is it possible?

**Comment by RainerHilmer** [comment]
What you need is a mediator.
1. Create a static class, for example
internal static Mediator
2. Place internal properties for everything you need to communicate between your scripts. Example
internal bool ConfigIsLoaded {get; set;}
3. Now let's say you need to wait in Script2 until Script1 is done with loading the configuration before it can proceed. Example for Script1
´´´C#
private void LoadConfig()
{
//Code that loads config...
Mediator.ConfigIsLoaded = true;
}
´´´
Example for Script2
´´´C#
while (!Mediator.ConfigIsLoaded) {return;}
// Do stuff which needs to wait until the config is loaded.
´´´

**Comment by RainerHilmer** [comment]
Why did I even bother to write all this?

**Comment by racinmat** [comment]
Thanks much for explaining. I thought something like static class would do.
This will do perfectly for my purpose. I just thought scripthook allows me accessing list of loaded scripts, seems like it does not. 
I think race conditions don't bother me because from one class I will use it only for writing, and from other class, only for reading.

**Comment by RainerHilmer** [comment]
@racinmat Have you considered if your writing script possibly executes before the values are valid? Also consider the possible extension of your mod in the future. A "Dirty" state is just a little property but can be a great help. [https://martinfowler.com/eaaCatalog/unitOfWork.html](https://martinfowler.com/eaaCatalog/unitOfWork.html)

**Comment by racinmat** [comment]
1. Yeah, I considered it, but thanks for reminder, it will definitely make the script more reusable in the future. 
2. Well, when I am programmer, I don't see any reason why I shouldn't have access to other scripts, because I am already messing with the game, and all possible abuse would be my responsibility as of someone who downloads some mod and runs it on my own PC.

**Comment by RainerHilmer** [comment]
What I mean is that someone could write a malicious mod which causes other mods to crash. You know trolls. I have already to deal with users who install all kind of crap and then come complaining because allegedly one of my mods doesn't work. However, I was always able to resolve their issue and it showed it was something else causing trouble (forgot a helper dll, conflicting key binding, installation error, etc.).
