### ISSUE TITLE
Euphoria functions do not work

### ISSUE THREAD

**Issue by RyaAnPhly** [crosire/scripthookvdotnet#762]
SHVDotNet's Euphoria functions being outdated and causing crashes can you please update them

**Comment by DezelON** [comment]
How soon will this bug be fixed? And how so far can you manage a regdol?

**Comment by kagikn** [comment]
Finally, Euphoria functions are fixed. Processes of native functions are splitter like shit in newer exes, so I had to gather memory offsets from different places. Please tell us if some euphoria stuff does not work in the latest version (1.0.2372.x).
