### ISSUE TITLE
Another missing parameter: SET_GAMEPLAY_CAM_RELATIVE_PITCH

### ISSUE THREAD

**Issue by LeeC2202** [crosire/scripthookvdotnet#763]
The SHVDN scripting source says this: **Native::Function::Call(Native::Hash::SET_GAMEPLAY_CAM_RELATIVE_PITCH, relativePitch);**

This is incorrect. SET_GAMEPLAY_CAM_RELATIVE_PITCH is a two parameter native, as stated on the 
NativeDB.

"void SET_GAMEPLAY_CAM_RELATIVE_PITCH(float x, **float Value2**)"
Parameters:
x = pitches the camera on the x axis.
Value2 = always seems to be hex 0x3F800000 (1.000000 float).

This is what the scripts show.
![relative_pitch](https://user-images.githubusercontent.com/13275001/35689643-e87369ba-076b-11e8-9a06-fdd0533a5f65.png)

Without the second parameter being set to 1f, the pitch value is set incorrectly.

**Comment by LeeC2202** [comment]
I can't believe I forgot to mention, this is in relation to doing `GameplayCamera.RelativePitch = value`

**Comment by Tanjitsu** [comment]
Just fork the project, make the change and then create pull request :)

World.Camera
public static float RelativePitch
{
	get
	{
		return Function.Call<float>(Hash.GET_GAMEPLAY_CAM_RELATIVE_PITCH);
	}
	set
	{
		Function.Call(Hash.SET_GAMEPLAY_CAM_RELATIVE_PITCH, value, 1f);
	}
}
