### ISSUE TITLE
Vehicle.Wheelspeed. How it works?

### ISSUE THREAD

**Issue by GARMSK** [crosire/scripthookvdotnet#764]
Its always returns 0, why?

**Comment by E66666666** [comment]
It's incorrectly labeled. It's the speed that shows on the dashboard.

**Comment by GARMSK** [comment]
Oh, fine. But actually I need to know when my car is drifting...

**Comment by E66666666** [comment]
You can figure out if the car is drifting (and by how much) by comparing the total velocity with the forward velocity.

I used this once:
`float angle = acos(velocity.y / sqrt(velocity.x^2+velocity.y^2)) * 180.0f / M_PI;`

**Comment by GARMSK** [comment]
It returns NaN when I stopped and heading by 2 parts of 180° when Im moving... Maybe its cause Im using vb.net but its hard to belive..
In vb it looks like:
Acos(CurrVeh.Velcity.Y/Sqrt(CurrVeh.Velocity.X^2 + CurrVeh.Velocity.Y^2)) * 180.0F / PI
