### ISSUE TITLE
Game Crashes when loading sp

### ISSUE THREAD

**Issue by MrLolzAlot** [crosire/scripthookvdotnet#766]
My came keeps crashing when i have shvdn in the game files. Without shvdn the game runs. Mods i have (menyoo, scripthookv, quantum break.)

**Comment by RainerHilmer** [comment]
Remove the mods and try again. Then add them back one after the other and try to run the game each time. Scripthookvdotnet does **nothing** without mods. So it must be one of them causing your troubles.
