### ISSUE TITLE
Game crashes when Im in the city or town

### ISSUE THREAD

**Issue by GARMSK** [crosire/scripthookvdotnet#767]
Sorry for bad english. So. I know why it happens but donno why. Its happening cause in my script Im taking maxspeed and highgear fron .ini file. All my script workin only with lastvehicle(currentvehicle)

**Comment by JohnnyCrazy** [comment]
Since this is probably not related to ScriptHookVDotNet itself and more of a scripting problem, please try asking in our gitter channel.
