### ISSUE TITLE
Crashing when loading into singleplayer With/without Rageplugin

### ISSUE THREAD

**Issue by Uhohjr** [crosire/scripthookvdotnet#770]
So, I just downloaded this to try a Tornado mod from the modding site, and apparently whenever I try to load the game . It crashes on me no matter what I do with it, especially with LSPDFR installed , Rageplugin, ScripthookV, and a couple other things for the LSPDFR mod. I dunno if it has to do with my updated Mods folder or the plugins.  Has anyone else had this issue lately?

**Comment by RainerHilmer** [comment]
This issue tracking system is for ScriptHookVDotNet but not for the Tornado mod. Issues with any mods need to be directed to the mod creator - and don't forget to provide the logs. Your information is utterly insufficient.
