### ISSUE TITLE
Mod Menu for input serialization

### ISSUE THREAD

**Issue by Neutrinobeam** [crosire/scripthookvdotnet#78]
I've written Mod Menu, https://www.gta5-mods.com/scripts/mod-menu-no-more-hotkeys, to try to sidestep the issue of mods catching keyboard input in parallel, creating key conflicts and requiring configuration files to adjust keybinds. It may be a solved issue for coders better than I, but near as I can tell, scripthookvdotnet is subject to the same issue. Mod Menu also implements input through the game's natives, and includes a header modMenu.h that wraps and documents some natives I've found useful for the in game inputs. Please use that information however you see fit.

I would love to support scripts loaded by ScriptHookVDotNet within Mod Menu and have extended my (rudimentary) implementation for such, but fear I am not a learned enough coder to be able to contribute here.

Currently, MM requires the target dll to have implemented two exports

extern "C"{_declspec(dllexport) void __stdcall loadUI(LPCSTR empty){
// Call your menu or toggle active / inactive for example
}}

extern "C"{_declspec(dllexport) LPCSTR __stdcall getModName(LPCSTR empty){
	return "Mod Name";
}}

For the purposes of ScriptHookVDotNet the "empty" parameters would contain the filename of the targeted script with .cs or .vb extension.

It may be inappropriate or fundamentally in conflict with the design of managed ticks and keyboard events, but I'd love to see them work together.

**Comment by crosire** [comment]
How would one do this? To Script Hook the :NET plugin is just one single script, one DLL. So you can only have one "loadUI" and one "getModName" export, but Script Hook V .NET can load an unlimited amount of .NET scripts, not just only one.

**Comment by Neutrinobeam** [comment]
The LPCSTR "empty" parameter would contain the file name of the targeted
.cs or .vb script for scripthookdotnet. So it'd have to check against the
loaded scripts. It's a fake name.
On May 17, 2015 7:14 AM, "crosire" <notifications@github.com> wrote:
>
> How would one do this? To Script Hook the :NET plugin is just one single
script, one DLL. So you can only have one "loadUI" and one "getModName"
export, but Script Hook V .NET can load an unlimited amount of .NET
scripts, not just only one.

**Comment by crosire** [comment]
Oh, right, over-read that. Sorry.

**Comment by RainerHilmer** [comment]
I don't know if I understand this right but what I faced in GTA IV was that most mods from other developers didn't filter the keys in a correct manner. Let's say the key combination in the ini was Ctrl+X but you got the same effect by just pressing X or any other key combination with X. Aside from that I have no issues.

**Comment by Sergeeeek** [comment]
It's possible to make some sort of menu manager class and let scripts register new menus there.

**Comment by RainerHilmer** [comment]
@Sergeeeek: I was about to implement that in my VCommonFunctions framework but I can spend my time with other things now. :+1:

**Comment by JohnnyCrazy** [comment]
We came to the conclusion we won't support this for various reasons. But we **may** feature something similar in the future.
