### ISSUE TITLE
ScriptHook isnt updated yet

### ISSUE THREAD

**Issue by pleaseupdatescripthook** [crosire/scripthookvdotnet#780]
Dear: Who ever is seeing this 
Can someone please tell me if there is still an update because my scripthook stopped working since yesterday. its needs an update but if there is one someone please tell me it. i appreciate it

                                                                                                                                             sincerely: Your Boi

**Comment by RainerHilmer** [comment]
Just wait for the new scripthookV to get updated like everyone else! ScripthookVDotNet is not the issue! So you've even posted in the wrong place.

**Comment by pleaseupdatescripthook** [comment]
ok buddy! lmao
