### ISSUE TITLE
Setting camera rotation switches X and Y angles

### ISSUE THREAD

**Issue by racinmat** [crosire/scripthookvdotnet#781]
Camera rotation should be set in euler angles, according to void SET_CAM_ROT(Cam cam, float rotX, float rotY, float rotZ, int rotationOrder), first parameter is rotation around X axis, second around Y axis, third around Z axis. 
But when creating new camera and setting its rotation, it does not work correctly. X and Y are switched.
I want to create new camera, in fixed position, loking downwards. That means rotation around Y axis for 270 degrees, doing a "pitch" in (roll, pitch, yaw) terminology. That code should do it. 
```
var newCamera = World.CreateCamera(new Vector3(), new Vector3(), 50);
newCamera.NearClip = 0.15f;
newCamera.IsActive = true;
newCamera.Position = new Vector3(-1078f, -216f, 37f);
newCamera.Rotation = new Vector3(0f, 270f, 0f); 
```
but this instead it performs roll, rotation around X axis, for 270 degrees, can be seen on this screenshot
![screenshot 25](https://user-images.githubusercontent.com/5525771/38422558-7dace710-39ab-11e8-8df5-149e58ffeee4.png)

The correct position, performing pitch, is done by 
```
var newCamera = World.CreateCamera(new Vector3(), new Vector3(), 50);
newCamera.NearClip = 0.15f;
newCamera.IsActive = true;
newCamera.Position = new Vector3(-1078f, -216f, 37f);
newCamera.Rotation = new Vector3(270f, 0f, 0f);
```
and it looks like that, which is desired result:
![screenshot 26](https://user-images.githubusercontent.com/5525771/38422566-845b95e8-39ab-11e8-877f-6c078c620dca.png)

Note I tried to perform the rotation myself by calling the SET_CAM_ROT function, tried various values of the rotationOrder variable, but nothing changed. 

Is this a bug, or did I mess up understanding of GTA coordinate system?
Because all other rotations, rotation of entites (cars, peds) seem to be in Euler angles.
E.g. when calculating bounding box of car from its position, rotation and model dimensions, math for classical euler angles applies, without any switching of X and Y angle.

**Comment by varunkumar2310** [comment]
@racinmat 
As said for function "SET_CAM_ROT" in 
http://www.dev-c.com/nativedb/
rotationOrder seems to be the constant. Which is why SHVDN doesnt take any argument for that.

+ The function is working properly.
You quote : "did I mess up understanding of GTA coordinate system?" :  Yes

Check the coordinate system of GTA 5 from my previous comment, and as usual "right hand thumb" rule applies for rotation around axes.

**Comment by racinmat** [comment]
Thanks, I has wrong assumption about the order of angles, I though they were Euler angles. 
![image](https://user-images.githubusercontent.com/5525771/38740607-45ab469e-3f38-11e8-9b4f-cb45773c87f8.png)

That confused me, thanks for clarification. For some reason, With this definition of rotation around axes, it makes sense.
