### ISSUE TITLE
ScriptHookVDotNet Crashes Game

### ISSUE THREAD

**Issue by LieutenantKhaos** [crosire/scripthookvdotnet#783]
I'm not sure why, but ScriptHookVDotNet keeps crashing my game, and I have no idea what the issue is. If anyone can tell me what log to post here, I would appreciate it. The lighting and rendering in my game has also messed up too sometimes when using ScriptHookVDotNet.

**Comment by varunkumar2310** [comment]
In the game folder, there are "ScriptHookV.log" and "ScriptHookVDotNet***.log",
if your are using any other scripts\ mods\ plugins, they also have similar log files in the game directory.
First check the log outputs and try to debug\ understand the issue using them.

**Comment by RainerHilmer** [comment]
1. OfficerAudioVariety.cs crashed because of a bug.
2. NoMoreShortcuts crashed because it couldn't find iFruitAddon2.
ScriptHookVDotNet does **NOT** crash!

**Comment by LieutenantKhaos** [comment]
Well, it keeps crashing even after installing iFruitAddon2.

**Comment by LieutenantKhaos** [comment]
Maybe this can help.

[crash.txt](https://github.com/crosire/scripthookvdotnet/files/1976932/crash.txt)
