### ISSUE TITLE
VehicleWheelCollection Count offset is wrong

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#786]
Looks like the int [offset](https://github.com/crosire/scripthookvdotnet/blob/dev_v3/source/scripting/World/Entities/Vehicles/VehicleWheelCollection.cs) in VehicleWheelCollection is now wrong in the Dev3 branch.
Apparently my vehicle has 1109676483 wheels 😁

**Comment by E66666666** [comment]
Yeah, wheel count might be nicer to get with patterns:
```cpp
addr = mem::FindPattern("\x3B\xB7\x48\x0B\x00\x00\x7D\x0D", "xx????xx");
numWheelsOffset = addr == 0 ? 0 : *(int*)(addr + 2);
```

**Comment by kagikn** [comment]
0b13c7a fixed this issue. I used a different memory pattern, though.
