### ISSUE TITLE
How to use both scripthookdotnet2.dll and scripthookdotnet.dll together

### ISSUE THREAD

**Issue by superretro2010** [crosire/scripthookvdotnet#788]
Im trying to get my mods to work together for gta 5 but one mod requires an older version of scripthookdotnet 2.9.6 while the other requires a newer the latest version 2.10.6. I managed to install the latest scripthookdotnet.asi and scripthookdotnet2.dll in the gta 5 root folder with the older scripthookdotnet.dll from 2.9.6 and it works but crashes when i exit the game so how should this be installed? and should i also add the older scripthookdotnet.asi from 2.9.6 in the scripts folder while having the newer asi 2.10.6 in the gta 5 root folder or can i leave that out seeing im using the older dll from 2.9.6 with the newer dll 2.10.6 with 2.10.6 asi in gta 5 root folder which seems to work currently but crashes when i exit the game?

**Comment by crosire** [comment]
You only need the latest version. They are backwards compatible.

**Comment by superretro2010** [comment]
Crosire i tried using just the latest version but when i load the game most of the blips dont load and heistproject doesnt work with the latest scripthookdotnet only the old one for some reason

**Comment by superretro2010** [comment]
Nevermind it works except with bank heist project wierd
