### ISSUE TITLE
Are Task hashes still valid ?

### ISSUE THREAD

**Issue by varunkumar2310** [crosire/scripthookvdotnet#791]
@crosire @CamxxCore 
can someone confirm if this list of hashes
```
https://pastebin.com/2gFqJ3Px
https://pastebin.com/R9iK6M9W
```
are still valid ?
or whom should I ask ?

For example : i create task
`ped.Task.UseMobilePhone()`
and check using `TASK_USE_MOBILE_PHONE` or `TASK_USE_MOBILE_PHONE_TIMED`
`Function.Call<int>(Hash.GET_SCRIPT_TASK_STATUS, ped, (uint)task);`
this returns 7 => task status = none.

or check using `CTaskMobilePhone`
`Function.Call<bool>(Hash.GET_IS_TASK_ACTIVE, ped, (uint)task);`
this returns false => task status = none.

However my ped is still using the phone, but these natives return results which say otherwise.
I think these task hashes have changed over time due to updates.

**Comment by Tanjitsu** [comment]
Others that might report better depending on the task.

GET_SEQUENCE_PROGRESS 
or IS_PED_ACTIVE_IN_SCENARIO
or IS_SCRIPTED_SCENARIO_PED_USING_CONDITIONAL_ANIM

**Comment by CamxxCore** [comment]
The Task IDs from that dump are still valid. Can't say whether any new tasks have been added since then, though.

**Comment by varunkumar2310** [comment]
@CamxxCore 
But as mentioned in the issue w.r.t player carrying a mobile phone,
the task hashes don't return the expected result.
There were other task also experiencing similar results at the time.
I will make a list, if that can help.

**Comment by Tanjitsu** [comment]
The "task" is just a label for grouping, its reverse engineered.
Rockstar does not follow standards for all its grouped assets, or obfuscates them purposefully.
Take the vehicles as an example.

Most follow the pattern - model name = display name
But then "some" don't - FireTruk = FireTruck

Which is why other natives exist such as "IS_PED_RUNNING_MOBILE_PHONE_TASK"

Are you trying to find out of the Ped has a phone or has the phone Animation active....
IS_PLAYING_PHONE_GESTURE_ANIM

**Comment by varunkumar2310** [comment]
@Tanjitsu 
Basically, in my script, in some situations I wanted the ped to stop using the phone, like lets say he wants to interact with another ped, or hes expected to collide with stuff, like traffic/ accidents, etc.

And hence, I was using GET_SCRIPT_TASK_STATUS or GET_IS_TASK_ACTIVE and the corresponding task hash to determine the same.

Thanks for pointing out the mentioned natives.

Till now I have not ventured into animation dictionary, so I had overlooked natives anywhere related to animations.

+ are there any resources related with animations ?
This is one I found,
`https://www.youtube.com/user/dparnas9/playlists`

**Comment by Tanjitsu** [comment]
Specifically for
>  "in my script, in some situations I wanted the ped to stop using the phone"

You should be able to just run something like ped.Tasks.ClearAll();
But then you might only need to use ped.Tasks.ClearSecondary();

Or you could use BlockPermanentEvents / AlwaysKeepTask to change from using default behaviours.

For animations you could look at 
https://www.gta5-mods.com/scripts/animation-viewer
https://alexguirre.github.io/animations-list/

OpenIV will also let you browse animations now i think.
