### ISSUE TITLE
Why change Entity Handle when MarkAsNoLongerNeeded() is called ?

### ISSUE THREAD

**Issue by varunkumar2310** [crosire/scripthookvdotnet#793]
https://github.com/crosire/scripthookvdotnet/blob/421a83571afa7934f9d8f8ec3592c9b327f99ea6/source/scripting/World/Entities/Entity.cs#L1320

I create a Ped, when I no longer use it , I do : 
`Ped.MarkAsNoLongerNeeded();`
However, this changes Ped.Handle to 0, due to mentioned above line in the code.

So, lets say
```
Ped PreviousPed = (Ped)Entity.FromHandle(Ped.Handle);
or
Ped PreviousPed = new Ped(Ped.Handle);
then when I call : 
PreviousPed.Exists() : this returns true
```
Meaning that the ped handle is still valid, even after I call MarkAsNoLongerNeeded()
So, I dont see the reason why we need to set the Ped.Handle to 0.

**Comment by varunkumar2310** [comment]
Is it just because, `SET_ENTITY_AS_NO_LONGER_NEEDED` takes a pointer as an input ?

**Comment by crosire** [comment]
Once it is marked as no longer needed, you should not use it anymore, as such the game clears the handle. SHVDN just replicates that behavior.
