### ISSUE TITLE
Updating the NuGet Package + adding SHVDN 3 as prerelease

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#796]
Currently the NuGet package for SHVDN 2 is one version behind [GitHub Releases](https://github.com/crosire/scripthookvdotnet/releases) (NuGet is `2.10.5` and GitHub is `2.10.6`). I think that it should be updated.

Also, now that SHVDN 3 is the main branch of the project I think that it would be a good idea to upload prerelease packages as `ScriptHookVDotNet3`.

What do you guys think?

**Comment by crosire** [comment]
Updated the v2 NuGet package a few times in the meantime. The v3 version is more or less abandoned, so there is little incentive to make a NuGet package out of it.
