### ISSUE TITLE
The Game will crash if a file being loaded via symbolic links does not exist

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#797]
To reproduce this:

* Drop a symbolic link to an SHVDN DLL in /scripts (in my case, `mklink "E:\Grand Theft Auto V\scripts\NativeUI.dll" "D:\Proyectos\NativeUI\bin\x64\Debug\NativeUI.dll"`)
* Delete the original file (in this example, is `"D:\Proyectos\NativeUI\bin\x64\Debug\NativeUI.dll"`)
* Launch the game

After that, the game will crash without output about it in `ScriptHookVDotNet2.log`.

You can find the `mklink` syntax here: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink

**Comment by crosire** [comment]
Seems to be fixed in master now.
