### ISSUE TITLE
ScriptHookVDotNet crashes game

### ISSUE THREAD

**Issue by LieutenantKhaos** [crosire/scripthookvdotnet#798]
This problem has been going on too long now, I can't use scripts because scripthookvdotnet keeps making my game crash, and I've literally tried everything, and still no luck, AT ALL. This is really frustrating me that I cannot play GTA because it crashes every single time in-game. If anyone knows what to do, PLEASE help me out, this is ridiculous. My game is fine without scripthookvdotnet.

[RAGEPluginHook.log](https://github.com/crosire/scripthookvdotnet/files/2172809/RAGEPluginHook.log)
[ScriptHookVDotNet2.log](https://github.com/crosire/scripthookvdotnet/files/2172810/ScriptHookVDotNet2.log)
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/2172811/ScriptHookV.log)

**Comment by RainerHilmer** [comment]
ScriptHookVDotNet doesn't crash. It's some crap mod which causes it and some installation flaw from your side. TriggerHappy crashes and you forgot to install NativeUI (or you installed it in the wrong place)! RPH crashed also but that's got nothing to do with shvdn.
