### ISSUE TITLE
World.GetAllPeds and World.GetNearbyPeds crashes game

### ISSUE THREAD

**Issue by xcxooxl** [crosire/scripthookvdotnet#802]
Both of those functions crashes the game for me, Not sure if there is a different way to get nearby peds.

**Comment by Tanjitsu** [comment]
Probably  #758

**Comment by Cr1TiKa7** [comment]
Made a little research and found that the issue is in line 570/571 in the NativeMemory.cs. Propably a wrong pattern? maybe @kagikn can fix this

**Comment by crosire** [comment]
Closing as duplicate of #758.
