### ISSUE TITLE
Unable to draw the same image twice with UI.DrawTexture

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#803]
As the title says. Take the following code as an example:

```csharp
string Image = AppDomain.CurrentDomain.BaseDirectory + "\\image.png";
UI.DrawTexture(Image, 0, 0, 200, new Point(200, 200), new Size(75, 75));
UI.DrawTexture(Image, 0, 0, 200, new Point(400, 200), new Size(75, 75));
```

As you can see in the following picture, only the latest one is shown on the screen:

![10072840431151874048_20180806224454_1](https://user-images.githubusercontent.com/11861253/43751319-680259c0-99ca-11e8-9469-dc82f480331b.png)

SHV Version: 1.0.1493.0
SHVDN Version: 2.10.6
GTA Version: 1.0.1493.0
Additional Information: Game is running on DX11

**Comment by LeeC2202** [comment]
The Index parameters are the same for both of those lines, they need to be different.
So UI.DrawTexture(Image, 0, 0... and then UI.DrawTexture(Image, 1, 0...
