### ISSUE TITLE
An exception occurred while executing ScriptHookVDotNet.asi

### ISSUE THREAD

**Issue by GerogePaul** [crosire/scripthookvdotnet#808]
An exception occurred while executing 'ScriptHookVDotNet.asi' (0x00007FFCCB5B1490), id 38

Any Help Would Be Apreciated

[ScriptHookVDotNet2.log](https://github.com/crosire/scripthookvdotnet/files/2304675/ScriptHookVDotNet2.log)
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/2304676/ScriptHookV.log)

**Comment by justalemon** [comment]
Without any logs, there is nothing that we can do.

Head down to your Grand Theft Auto V directory and upload the files called `ScriptHookV.log` and `ScriptHookVDotNet2.log`.

**Comment by Art-3-mis** [comment]
How can you update them?

**Comment by justalemon** [comment]
1. You don't have NativeUI updated, reinstall it
1. Menyoo is known for crashing other mods, try to remove it
