### ISSUE TITLE
Random in Vector3/Vector2

### ISSUE THREAD

**Issue by IncoCode** [crosire/scripthookvdotnet#82]
Can we use GAMEPLAY::GET_RANDOM_FLOAT_IN_RANGE(0,1)? In this case we don't need Random instance.
https://github.com/crosire/scripthookvdotnet/blob/master/source/Vector3.cpp#L80

**Comment by Nacorpio** [comment]
Have you been trying to use the native?

**Comment by JohnnyCrazy** [comment]
Any reason we should? Any benefits?
Native-Calls execution should take a lot longer than just a plain .NET one.

**Comment by Nacorpio** [comment]
Yes, I agree with @JohnnyCrazy.

**Comment by IncoCode** [comment]
@JohnnyCrazy , this will help get rid of the two Random instances. But I agree that it should take longer.
@Nacorpio , works fine.

**Comment by crosire** [comment]
@IncoCode What's the problem with having those two instances? It's not like they take much memory or something...
