### ISSUE TITLE
CORE : an exception occured while executing 'scripthookvdotnet.asi'

### ISSUE THREAD

**Issue by Zenspaced** [crosire/scripthookvdotnet#821]
![2018-11-08_07-59-38](https://user-images.githubusercontent.com/14360516/48207098-3633b200-e370-11e8-9ad8-58ecb1842224.png)

See image. Not sure what is causing it. Logs attached too.
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/2562263/ScriptHookV.log)

**Comment by sprucecopse** [comment]
Same happened to me, I reinstalled 2.10.7 and that solved the problem for me. Seems that 2.10.8 is unstable, hope it gets fixed soon.

**Comment by crosire** [comment]
Closing since this outdated. Please reopen if it becomes a problem in current versions again.
