### ISSUE TITLE
How to use Game.PlayMusic

### ISSUE THREAD

**Issue by nabeghe** [crosire/scripthookvdotnet#827]
Hi, I passed a mp3 file path to ttt method but it's not working!

**Comment by qiangqiang101** [comment]
Plays music from the game's music files.
https://github.com/crosire/scripthookvdotnet/blob/421a83571afa7934f9d8f8ec3592c9b327f99ea6/source/scripting/Game/Audio.cs#L106

if you want to play external music file
https://gtaforums.com/topic/853070-play-external-wav-file-with-volume-control-without-naudiodll-or-bass/
