### ISSUE TITLE
Tick system

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#83]
For those of you who find it very frustrating to work with ticks, I have come up with a solution.
I don't know how many of you who would find this useful, but I do at least.

You just implement this abstract class, and you'll be ready to go.

An example on how you could use IsActive, is when wrapping around peds.
This can also be found in my mod, which you can see on my Github page.
You could make it tick only when the ped is alive, and so on. 
``IsActive = Ped != null && Ped.IsAlive;``

Basically, it organizes the ticks, and makes the whole thing a lot easier.
You can also give any instance a lifespan.

public abstract class Updater {

        private bool _active = false;

        private int _activeTick;
        private int _inactiveTick;

        private readonly int _startTick;
        private int _tick;

        private Dictionary<int, Action> _actionQueue = new Dictionary<int, Action>(); 

        protected Updater(int startTick = 0) {
            _tick = startTick;
            _startTick = startTick;
        }

        public void Tick() {

            OnUpdate(_tick);

            if (_actionQueue.ContainsKey(_tick)) {
                _actionQueue[_tick].Invoke();
            }

            if (_tick == 0 || _tick == _startTick) {
                
                OnFirstUpdate();

            }

            if (_active) {

                _inactiveTick = 0;

                OnActiveUpdate(_activeTick, _tick);

                if (_activeTick == 0) {
                    OnFirstActiveUpdate(_tick);
                }

                _activeTick++;

            } else {

                _activeTick = 0;

                OnInactiveUpdate(_inactiveTick, _tick);

                if (_inactiveTick == 0) {
                    OnFirstInactiveUpdate(_tick);
                }

                _inactiveTick++;

            }

            _tick++;

        }

        /// <summary>
        /// Fired everytime a tick has been made.
        /// </summary>
        /// <param name="tick">The total amount of ticks.</param>
        protected abstract void OnUpdate(int tick);

        /// <summary>
        /// Fired on the absolute first update.
        /// </summary>
        protected abstract void OnFirstUpdate();

        /// <summary>
        /// Fired everytime a tick has been made while active.
        /// </summary>
        /// <param name="activeTick">The current tick on this activity state.</param>
        /// <param name="tick">The total amount of ticks.</param>
        protected abstract void OnActiveUpdate(int activeTick, int tick);

        /// <summary>
        /// Fired everytime a tick has been made while inactive.
        /// </summary>
        /// <param name="inactiveTick">The current tick on this activity state.</param>
        /// <param name="tick">The total amount of ticks.</param>
        protected abstract void OnInactiveUpdate(int inactiveTick, int tick);

        /// <summary>
        /// Fired the first time an active update has been made.
        /// </summary>
        /// <param name="tick">The total amount of ticks.</param>
        protected abstract void OnFirstActiveUpdate(int tick);

        /// <summary>
        /// Fired the first time an inactive update has been made.
        /// </summary>
        /// <param name="tick">The total amount of ticks.</param>
        protected abstract void OnFirstInactiveUpdate(int tick);

        public Dictionary<int, Action> ActionQueue { get { return _actionQueue; } set { _actionQueue = value; }} 

        /// <summary>
        /// Returns the tick of which the ticking started.
        /// This isn't always 0, as the StartTick can be set.
        /// </summary>
        public int StartTick { get { return _startTick; }}

        /// <summary>
        /// Returns how many times this Updating instance has ticked.
        /// </summary>
        public int Tick { get { return _tick; } }

        /// <summary>
        /// If active, returns how many times it has been ticked during its session.
        /// </summary>
        public int ActiveTicks { get { return _activeTick; }}

        /// <summary>
        /// If inactive, returns how many times it has been ticked during its session.
        /// </summary>
        public int InactiveTicks { get { return _inactiveTick; }}

        /// <summary>
        /// Returns whether this Updating instance is active.
        /// </summary>
        public bool IsActive {
            get { return _active; }
            protected set { _active = value; }
        }

    }

**Comment by RainerHilmer** [comment]
Looks like a kind of event broker. Could become interesting.

**Comment by Nacorpio** [comment]
Yeah, pretty much.

**Comment by JohnnyCrazy** [comment]
I think this would be perfect for a new wiki page :+1: 
Would you mind if we move this to the wiki? @Nacorpio

**Comment by RainerHilmer** [comment]
You know what I find as good as the code itself? You added XML comments. That's what most developers are too lazy to do. I always say the best framework is worth nothing without a decent documentation. So chapeau.

**Comment by Nacorpio** [comment]
I don't mind, @JohnnyCrazy. =D

**Comment by JohnnyCrazy** [comment]
[Done](https://github.com/crosire/scripthookvdotnet/wiki/Tick-System-by-Nacorpio) :)  
Also added a list to the [Get Started page](https://github.com/crosire/scripthookvdotnet/wiki/Getting-Started#code-snippets)

**Comment by Nacorpio** [comment]
Good job.
