### ISSUE TITLE
What is IsInCdImage?

### ISSUE THREAD

**Issue by MrFoxPro** [crosire/scripthookvdotnet#841]
Whats difference with IsValid?

**Comment by LeeC2202** [comment]
Isn't IsInCdImage a check to see if it's part of the shipped gamefiles (i.e. vanilla content) and IsValid a check to see if it is a valid model instance?

That's the way I understand it but that may of course be wrong.

**Comment by crosire** [comment]
This isn't really the place to ask scripting questions.
