### ISSUE TITLE
Not working with game version 1.0.1604.1

### ISSUE THREAD

**Issue by jbreitung** [crosire/scripthookvdotnet#843]
This mod is no longer working with the new game version 1.0.1604.1.

**Comment by kagikn** [comment]
Just wait for Script Hook V's update if you don't have any previous GTA5.exe. This time the exe updated not so much, and we won't need to update memory offsets in this plugin.
I'll release a new version if I successfully improve performance of this plugin so much or a new major GTA V comes and memory offsets gets updated, though.
