### ISSUE TITLE
Create Issue template to avoid the classic "SHV does not works" after a GTA Update

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#844]
I usually take a time to read the repo issues to see the progress of ScriptHookVDotNet, but then I find the stupid people that thinks `SHV == SHVDN` after a GTA Update.

Examples: #843 #820 #806 #801 #780 #778 

If you guys didn't know, is possible to [create Issue Templates](https://help.github.com/articles/about-issue-and-pull-request-templates/) directly as files on the repo. They might come useful as long as the user on the other side of the screen ~~has eyes~~ takes the time to read it. 

I might send a PR later.

**Comment by sirjake1990** [comment]
Calling people stupid but taking the time to collect previous examples of the instances of people who don't know the intricacies of this particular platform but know certain mods depend on it but just want to help is a pretty jerk move IMO.

There is no clear and obvious documentation (could be ONE SENTENCE) on how this entire modding platform is still dependent on one guy updating the original ScriptHookV but would save a bunch of headaches for the people who know this platform.

Could be prevented for newbies but let's just keep calling people stupid.

**Comment by justalemon** [comment]
Well, that is my opinion for those that are unable to do some research first (or don't want to enable the [beta of related issues](https://github.blog/changelog/2018-11-05-related-issues/)).

**Comment by sirjake1990** [comment]
You are entitled to your opinion and so are the keepers of this repo, just seems if this is a recurring issue then a simple solution seems to be a quick note on the main page that its dependent on an updated scripthook version and is essentially dead in the water until it gets that. Could just not put that note and get repeat issues getting opened and get repeat opened issues though, whatever floats their boat.
