### ISSUE TITLE
Can you port deband.fx for videoplayers?

### ISSUE THREAD

**Issue by DanillaTech** [crosire/scripthookvdotnet#851]
Hello and sorry for offtopic :)

Can you port your deband shader for videoplayers or suggest how can user do that?

I know that madVR exists, but it gives worse quality of debanding and worse perfomance - it works bad with smooth video project, which interpolates video frames to 60FPS, it's is true at least on Intel HD4000 card.

![image](https://user-images.githubusercontent.com/8999560/53102162-31b89100-353c-11e9-8d89-32a5892a192b.png)

Yeah, I can use reshade on videoplayer, but I think it has better perfomance - at least without SVP on fullHD video on mpv with integrated deband glsl shader it loads GPU on ~40%, on reshade ~50%. Also it's not very comfortable to watch with reshade - at least in PotPlayer jumping to next file does not work - screen frezes until you press stop and then play.

Shaders have same syntax like https://github.com/zachsaw/RenderScripts/blob/2ceb62ab6d75ac613eab2674dfade0a42bbafa26/RenderScripts/ImageProcessingShaders/SweetFX/AdvancedCRT.hlsl vs https://github.com/crosire/reshade-shaders/blob/master/Shaders/CRT.fx

I hope it's not very difficult for you to port them

Thanks anyway)

**Comment by crosire** [comment]
This is the SHVDN repository...

**Comment by DanillaTech** [comment]
Reshade's/reshade-shaders do not have issue section :(

**Comment by DanillaTech** [comment]
Reshade's/reshade-shaders do not have issue section :(
