### ISSUE TITLE
UI.DrawTexture corrupts when markers are being drawn with varying alpha/colour levels.

### ISSUE THREAD

**Issue by LeeC2202** [crosire/scripthookvdotnet#853]
This is probably the most bizarre bug I have seen and I honestly don't know if the bug is in UI.DrawTexture, or some connection between markers and sprites in the game itself.

As you can see in this video, I have a track overlay being drawn with UI.DrawTexture. The brake disc effect on the car is created with markers. While the brake discs are in the glowing state, the overlay is corrupted. When the markers have cooled and stopped being drawn, the overlay is fine.

https://youtu.be/FFmNEpUp-eY

Is there some connection between how the markers and UI.DrawTexture are being rendered as far as SHVDN is concerned, Or could this be a level up in SHV, or even a game issue? I didn't post this as a [BUG] because I honestly can't confirm where the bug comes from. It's such a bizarre connection, I am truly baffled.

**Comment by LeeC2202** [comment]
Just to update on this, the bug is not present in game version 1493 with SHVDN 2.10.6 but is present in 1604.1, with either 2.10.6 or 2.10.9.

So this appears to be something that has manifested in the latest game version.

**Comment by LeeC2202** [comment]
Looks like I might have put 2 and 2 together and got 5 with this, sorry. There is a connection but maybe it's being caused by some code reading values from memory, with regards to wheel parameters.

**Comment by LeeC2202** [comment]
Okay, after more testing today, this does seem to be an issue with UI.DrawTexture. What made that a more likely situation, was when another mod running cured the bug in the mod I was having problems with. This video shows what I mean. https://youtu.be/7EtMkVwk4Qw

When the World Guide GUI is hidden, the overlay image corrupts when markers are drawn. When the World Guide GUI is shown, the overlay displays normally. They're both using UI.DrawTexture and they're both drawing to level 0 with index 0.

Someone I have been modding with has just sent me another fix and that's a mod that simply draws a '.' with UIText at size 0.01f... that also stops the problem. I obviously don't know what happens behind the scenes with the UI elements but it looks like something in the latest game version is affecting them.

Does anyone have any idea what might be happening here?

**Comment by crosire** [comment]
`UI.DrawTexture` is just a wrapper for ScriptHookV's `drawTexture`, so there is not much SHVDN can do if that does not work well.
