### ISSUE TITLE
Error: FATAL: Unable to load \.....\ScriptHookVDotNet2.dll due to the following exception:

### ISSUE THREAD

**Issue by Phxlp** [crosire/scripthookvdotnet#854]
Hello, 
after launching GTA 5, I´ve got this error showing up.  ScriptHook and GTA 5 work normally, just ScriptHookVDotNet isnt loading. Can someone help me?

Thanks

 
![image](https://user-images.githubusercontent.com/49121260/55289429-faed5a80-53c6-11e9-9441-282802fc3ba6.png)

**Comment by electricman226** [comment]
In the GTA V folder, you placed the dll `ScriptHookVDotNet2.dll` in there. Right click that file, and go to `Properties`.

On the bottom right, there should be a button that says `Unblock`. Click that and make sure to click `OK`. That should fix your issue.

**Comment by Phxlp** [comment]
Thank you, ill try that later.

**Comment by Phxlp** [comment]
I´ve only got the options `read-only´ and `hidden´ .  Can you maybe post a picture or omething, i dont really get what you mean by Unblock....

**Comment by Cr1TiKa7** [comment]
Is the problem still there for you?

**Comment by Phxlp** [comment]
Yes, i couldnt solve it. After clicking Properties, it wont keep unlocked.

**Comment by Cr1TiKa7** [comment]
Have you installed all the requirments that are needed?
Since it tells you that a dependency is missing I guess you forgot one of the dependencies:
- C++ ScriptHook by Alexander Blade
- .NET Framework ≥ 4.7.2
- Visual C++ Redistributable for Visual Studio 2017 x64

**Comment by Phxlp** [comment]
Yes, scripthook by AB works, i have the latest. NET FRAMEWORK and C++

**Comment by Cr1TiKa7** [comment]
When does the error actually come up? As soon as you start GTA V or somewhere around that point the game enters the Singleplayer mode? 

If it's the last one it would be good to know if the game starts when you remove every file from the scripts folder.

**Comment by Phxlp** [comment]
After double-clicking, it works until the loading screen (where the pictures show up). Then i get the issue. The game itself starts, my other mods (menyoo) work fine.

**Comment by Cr1TiKa7** [comment]
Hmm ok.. but your scripts folder is empty right? So we can atleast say that it has nothing todo with that?

**Comment by Phxlp** [comment]
I have to try that later, i cant actually remember.

**Comment by Cr1TiKa7** [comment]
Ok, would be good to know if it's maybe just a script which is not working correctly or not.

**Comment by Phxlp** [comment]
I get the same error without any scripts too.
I also removed the other mods and downloaded the latest versions again. (and re-installed them)

**Comment by Tanjitsu** [comment]
If your dll wont stay "unblocked" then this is an issue with your windows access rights, i would suggest looking into admin mode for windows.

If the "unblocked" issue has been passed then you will have .log files in your GTA Dir. They will provide more insight into how far through the loading process you are before crashing. A simple approach is to just start by reverting to clean GTA dir, delete all the folders not created by Rockstar. Then simply add 1 element at a time too see which one causes the crash.
