### ISSUE TITLE
Script timing

### ISSUE THREAD

**Issue by MrXJKz** [crosire/scripthookvdotnet#855]
There's a way to achieve a "sleep" for a part of the script?

`        for (int i = 0; i <= position.Length; i++)
        {
            UI.Notify($"~g~Teleported to~s~: {position[i].ToString()}");
            Game.Player.Character.Position = position[i];
            Wait(100);
        }`

Want to do something like this.

**Comment by Tanjitsu** [comment]
Script.Wait(100);
