### ISSUE TITLE
.ini File?

### ISSUE THREAD

**Issue by MagixDevelopers** [crosire/scripthookvdotnet#856]
Hello I would like to know how to create a .ini file for my script. If anyone knows please respond! Thank you!

**Comment by yoni1857** [comment]
`C#
var config = ScriptSettings.load("scripts\\*name of ini file*");
var myValue = config.GetValue<*value type*>("*Value Category ([Options], [Settings], etc)*", "*Value's Name*", *value default*);
`

.ini file:
`ini
[Category]

Value = the value
`
