### ISSUE TITLE
Failed to load assembly

### ISSUE THREAD

**Issue by JanBch** [crosire/scripthookvdotnet#857]
Hey guys,

I just recently re-installed GTA 5 after a couple of months without playing it.
So I hopped on, installed some of my favourite mods but just could not get them to work. I´ve been looking for about 9 hours now to find a solution for this problem. During that time, I opened the "Scripthookvdotnet2"log and looked for the problem, here is what I got:

20:56:48] [DEBUG] Created script domain 'ScriptDomain_75F9358A' with v2.10.8.
[20:56:48] [DEBUG] Loading scripts from 'E:\# Spiele\GTA V\scripts' into script domain 'ScriptDomain_75F9358A' ...
[20:56:48] [INFO] Loading assembly 'AccountInBank.dll' ...
[20:56:48] [ERROR] Failed to load assembly 'AccountInBank.dll'

Does anyone know how to actually solve this?
I have the latest Version of ScripthookV installed.

**Comment by justalemon** [comment]
Under "Failed to load assembly", you should be able to see what has gone wrong with the script.

Send that text to the mod developer, because it appears that is a Mod issue and not a problem with SHVDN.
