### ISSUE TITLE
Vehicle.Acceleration is broken in 1604.

### ISSUE THREAD

**Issue by enzo522** [crosire/scripthookvdotnet#861]
After 1604, Vehicle.Acceleration returns 0 almost every time.
This issue was solved in simplefuel mod by ikt.
ikt's source code can be found in [here](https://github.com/E66666666/gta5-simplefuel/blob/master/LeFixSimpleFuel/Memory/VehicleExtensions.cpp).
The updated memory offset is assigned to the variable "throttleOffset".
I hope this issue would be solved as soon as possible.
Thank you.

**Comment by Cr1TiKa7** [comment]
As soon as one of the maintainer accepts my pull request it should be fixed in v3 of scripthookvdotnet

**Comment by kagikn** [comment]
I confirmed Vehicle.Acceleration and Vehicle.Clutch are broken in 1604, 1734, and 1737, with this code. https://github.com/E66666666/GTAVManualTransmission/blob/4bf8fd9f17384c9cf91f882d0e941ee7f453733c/Gears/Memory/VehicleExtensions.cpp#L92
Will fix these by using memory patterns. Good memory patterns have future-proof more than direct offsets.

**Comment by enzo522** [comment]
Fixed in 2.10.10. Thank you for your work.
