### ISSUE TITLE
Menu Items not accessible

### ISSUE THREAD

**Issue by Frede1012** [crosire/scripthookvdotnet#87]
The menu items (ie. MenuLabel, MenuButton etc) of a menu is not accessible, is this on purpose? How am i supposed to change menu content dynamically? Am i missing something, or is it just not implemented yet?

**Comment by Monsterxsync** [comment]
@Frede1012  do you mean like this? 
MenuLabel playerMenuLabel = new MenuLabel("Categories", true);
        playerMenuLabel.UnderlineColor = Color.LimeGreen;

My problem is "MenuToggle" don't remember there current state and always default to OFF am i missing something here?

**Comment by Monsterxsync** [comment]
P.S if MenuButton and MenuToggle could take functions with parameters would neaten up code alot.

**Comment by StijnBrouwer** [comment]
I added ListMenu for dynamically generated menus

I will add properties for accessing the value of elements and more ways of passing actions. Thanks for the suggestion.

But I want to know what you guys think, is direct access to Menu's elements needed? Or should ListMenu do the job?

**Comment by Nacorpio** [comment]
You could just use lambda expressions, store it in an Action and there you go.
Credits to @StijnBrouwer.

**Comment by Frede1012** [comment]
@StijnBrouwer Gimme a sec, i have been working a bit on it. Let me test, commit and then i'll comment here again :)

**Comment by StijnBrouwer** [comment]
@Frede1012 Okay, nice.

**Comment by StijnBrouwer** [comment]
Does the tweening when removing a specific menu work too? Because my tweening code is so shitty and broken.

Oh, and change those variable names! The `m` prefix is only for private members. And make SelectedIndex a property, so that you can update the menu without breaking shit.

**Comment by Frede1012** [comment]
@StijnBrouwer Check my fork (newest commit). https://github.com/Frede1012/scripthookvdotnet/commits/master

I cleaned up the public menu properties :)

**Comment by StijnBrouwer** [comment]
Looks good, have you tested it yet?

**Comment by Frede1012** [comment]
Yes, it seems to work absolutely fine. However, i seem to have some graphical problems with the menus on my pc. I guess they aren't supposed to be flashing and purple? :P

**Comment by StijnBrouwer** [comment]
Did they flash before you made the changes?

**Comment by Frede1012** [comment]
@StijnBrouwer Yep, they have been acting weird all along.

**Comment by StijnBrouwer** [comment]
Okay, then it's fine.

RIP your graphics card though

**Comment by Frede1012** [comment]
@StijnBrouwer What do you mean?

**Comment by StijnBrouwer** [comment]
@Frede1012 Flickering textures and those kind of things are often a sign that your graphics card is dying. But I don't know if that's the case. Really weird...

**Comment by Frede1012** [comment]
@StijnBrouwer This graphics card is fairly new, and nothing else is flashing :P I hope its not that.. 

Anyway, i will submit a pull request and add it in a few, ok?

**Comment by StijnBrouwer** [comment]
@Frede1012 Go ahead

**Comment by Frede1012** [comment]
Issue is fixed in #89 (waiting for approval)

**Comment by StijnBrouwer** [comment]
I have made some changes in https://github.com/StijnBrouwer/scripthookvdotnet/tree/properties that add value accessors to MenuItems and an update function to Menu. (because just an accessor for the Menu's item list, like it is currently, obviously doesn't work)

**Comment by StijnBrouwer** [comment]
I'm going to test it first before pull requesting though, so it might take some time.

**Comment by Frede1012** [comment]
@StijnBrouwer Can't we remove the UpdateText function completely and update the text on Draw()?

**Comment by StijnBrouwer** [comment]
My idea was to keep UpdateText, but make it private and automatically called when data gets changed.

**Comment by Frede1012** [comment]
@StijnBrouwer Thats a good idea as well :P
