### ISSUE TITLE
Crashing on loading screen 

### ISSUE THREAD

**Issue by Zraine** [crosire/scripthookvdotnet#871]
When is loading screen it crashed.
crash:
FATAL: Unable to load 'C:\programs Files\Rockstar Game\Grand Theft Auto V\
ScriptHookVDoNet2.dll"

**Comment by Zraine** [comment]
![IMG_20190809_190806](https://user-images.githubusercontent.com/53949050/62796299-30265980-bad9-11e9-87ec-cfa55a04a45d.jpg)

**Comment by crosire** [comment]
Unblock the ScriptHookVDotNet2.dll (right click > Properties > Unblock).
