### ISSUE TITLE
player out of control after create a new camera

### ISSUE THREAD

**Issue by YaoChen5566** [crosire/scripthookvdotnet#874]
Hi guys. 

I press key 'V' to first-person-view.
And then create a new camera, attach it to character's head.
I want to use key WASD to control my character but it failed.
Character walk straight, never stop and turn unless I destroy the camera.
If I create a new camera, does the key become to control camera not character?
Or there are some method to control the character after creating a new camera?
The following are my code about what I mention above.
Thx guys 

`if (k.KeyCode == Keys.NumPad7) {`
`Ped playerPed = Game.Player.Character;`
`Camera newCam = World.CreateCamera(new Vector3(0f, 0f, 0f), new Vector3(0f, 0f, 0f), 82f);`
`newCam.AttachTo(playerPed, 12844, new Vector3(0f, 2f, 0.4f));`
`newCam.Rotation = Game.Player.Character.Rotation;`
`World.RenderingCamera.IsActive = true;`
`World.RenderingCamera = newCam;`
`}`

**Comment by Tanjitsu** [comment]
What happens if you don't use    newCam.AttachTo(playerPed
Then update the cams position each tick manually.

**Comment by YaoChen5566** [comment]
Hi Tanjitsu.
Thx for your suggestion.
I've tried it but the player still out of control.
And each tick seems refresh the position per sec.
I want the camera to be continuously. 

If I press 'V' to set origin camera to third-person-view then create the new camera.
I can control the character walk normally with 'WASD'.
But if I press 'V' to change origin camera to first-person-view then create the new camera.
'WASD' all let player run straight and never stop until I destroy the camera, aim or switch the weapon
I cannot let player turn around

Briefly, this situation only occurs for first-person-view control method

Thx

**Comment by crosire** [comment]
This sounds like an issue with the GTA scripting API and not SHVDN, so closing.
