### ISSUE TITLE
INS key conflicting with my config

### ISSUE THREAD

**Issue by niente0** [crosire/scripthookvdotnet#880]
Hello, I usually use the INS key to jump. Unfortunately it is the same key that ScriptHookVdotnet uses to reload scripts. How can I change that key? Thanks

**Comment by crosire** [comment]
In SHVDN2 create a `ScriptHookVDotNet.ini` file with these contents:
```
ReloadKey=Insert
```
Replace `Insert` with any key name from https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys.
