### ISSUE TITLE
Force Radio Song

### ISSUE THREAD

**Issue by voxeltrance** [crosire/scripthookvdotnet#883]
How can you force the radio to change to a certain station and start playing a song? You can see this towards the end of 'The Third Way', when the radio changes to "Wouldn't Wanna Be Like You" during Trevor & Devon's chat.

I've been playing around with the `SET_RADIO_TRACK` native with no luck. Has anyone else done this?

**Comment by crosire** [comment]
Scripting questions are better off asked elsewhere, like https://gtaforums.com/forum/372-coding/.
