### ISSUE TITLE
Script Hook V .NET 2.10.10 - FATAL: Unknown game version, check http://dev-c.com for updates?

### ISSUE THREAD

**Issue by WellBeSerious** [crosire/scripthookvdotnet#884]
- Script Hook V .NET 2.10.10
- GTA 5 from Rockstar Games Launcher
- Updated game, as always forced to, and this appeared:

FATAL: Unknown game version, check http://dev-c.com for updates
WOULD YOU LIKE TO CHECK DOWNLOAD PAGE NOW ?
http://dev-c/gtav/scripthookv/
Supported versions:
https://drive.google.com/open?id=1n6WRNeY8S5JyS8Nv5noAD4FLhP-Ws1vS

"Yes" or "No" are the only choices. Neither do anything.

UPDATE 1:
Rockstar Games Launcher updated and installed the newer version on drive C, while the old version is G (game drive). I couldn't uninstall from the new folder because I'd have to uninstall 80+ GB. I just deleted from both folders [Program Files and Program Files (x86) on both drives], then reinstalled Launcher. Am updating now and will update.

**Comment by justalemon** [comment]
This is a problem with ScriptHookV, not ScriptHookVDotNet.

Wait for an update on ScriptHookV or downgrade your game.
