### ISSUE TITLE
Can't grab peds with new 2.10.10 (edit 17/10)

### ISSUE THREAD

**Issue by urudred** [crosire/scripthookvdotnet#892]
**Version**
2.10.10 (was working on 2.10.9)

**Description**
I can't grab peds with mods, when I grab one, the ped continues walking.

**Comment by Tanjitsu** [comment]
As this sounds like an issue with a Mod can you provide more details to specify for testing.
Which mod / which function you think is not functioning ?

**Comment by urudred** [comment]
Hello, thank you for answering.
I'm talking about this mod: https://gtaxscripting.blogspot.com/2019/07/gta-v-thanos-endgame.html
Now I tried with new version (v3.0.2) and it works but this is "laggy" (not the game, the animation).
I made a little video showing it: https://youtu.be/U3sYEwc4huM

**Comment by Tanjitsu** [comment]
Hey your video is set to private and this "mod" relies on a lot of DLL's.
Trying to track down the specific issue with out being the creator would be painful.

You should contact the creator of the mod and ask him to update it.
He can post a "bug" if he finds its an issue with ScriptHook.Net.

**Comment by justalemon** [comment]
Problems when using scripts created by JulioNib are most of the time related to the mod itself.

The mods are obfuscated and terribly optimized, so I would say contact him prior to making reports here.
