### ISSUE TITLE
DLC Vehicles Native Memory Pattern

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#896]
Is it worth adding the patterns from E66666666's script provided by Unknown Modder to the Hooks Natives to allow all DLC vehicles to be used with out the need for individual scripts to enable this ?

https://github.com/E66666666/GTAVAddonLoader/blob/391c55a4b03238ccf1be005dc93e3652527965df/GTAVAddonLoader/NativeMemory.cpp#L219

**Comment by DurtyFree** [comment]
Yes this would be great actually.

**Comment by Tanjitsu** [comment]
Yeah i gave it a shot but its beyond me.
I don't know enough about C++ or memory modding to successfully convert this over to C#.

**Comment by kagikn** [comment]
I think you can enter any DLC vehicles and normally use them now. If the countermeasure doesn't work properly in your game, please let me know.
