### ISSUE TITLE
World.GetAllBlips() doesn't exist when compiling?

### ISSUE THREAD

**Issue by leemetme** [crosire/scripthookvdotnet#898]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
Which version of SHVDN was the problem encountered with?
- **3.0.2**

**Description**

Console when running my code:
```
[INFO] --- Community Script Hook V .NET 3.0.2 ---
[INFO] --- Type "Help()" to print an overview of available commands ---
[ERROR] Failed to compile untitled.cs with 1 error(s):
[ERROR] at line 59: 'GTA.World' does not contain a definition for 'GetAllBlips'
[WARNING] Resolving API version 0.0.0.
```

But it does though, right?! When I run this in the console.
```
$> return World.GetAllBlips()
[INFO] [Return Value]: GTA.Blip[]
```
It returns an array perfectly fine.

When I copy the code from **master** branch `scripthookvdotnet/source/scripting_v3/GTA/World.cs` to my personal `untitled.cs`, then I get the following error(s).

```
[ERROR] Failed to compile untitled.cs with 4 error(s):
[ERROR] at line 61: The best overloaded method match for 'GTA.Native.Function.Call(GTA.Native.Hash, params GTA.Native.InputArgument[])' has some invalid arguments
[ERROR] at line 61: Argument 2: cannot convert from 'GTA.BlipSprite' to 'GTA.Native.InputArgument[]'
[ERROR] at line 67: The best overloaded method match for 'GTA.Native.Function.Call(GTA.Native.Hash, params GTA.Native.InputArgument[])' has some invalid arguments
[ERROR] at line 67: Argument 2: cannot convert from 'GTA.BlipSprite' to 'GTA.Native.InputArgument[]'
```

The code I copied to my `untitled.cs`:
```
	public static Blip[] GetAllBlips(params BlipSprite[] blipTypes)
		{
			var res = new List<Blip>();
			if (blipTypes.Length == 0)
			{
				blipTypes = Enum.GetValues(typeof(BlipSprite)).Cast<BlipSprite>().ToArray();
			}
			foreach (BlipSprite sprite in blipTypes)
			{
				int handle = Function.Call<int>(Hash.GET_FIRST_BLIP_INFO_ID, sprite);

				while (Function.Call<bool>(Hash.DOES_BLIP_EXIST, handle))
				{
					res.Add(new Blip(handle));

					handle = Function.Call<int>(Hash.GET_NEXT_BLIP_INFO_ID, sprite);
				}
			}
			return res.ToArray();
		}
```

Thank you for your time.

**Comment by crosire** [comment]
`GetAllBlips` does only exist in v3. Plain C# scripts are compiled using v2 for backwards compatibility and v2 does not have that method, hence the error. You'll need to compile your script to an assembly (and reference v3) for it to work.
