### ISSUE TITLE
Is it possible to reference both ScripthookVDotNet 2 AND 3 toghether?

### ISSUE THREAD

**Issue by Madatek** [crosire/scripthookvdotnet#899]
It appears they conflict but maybe it's just me doing things wrong

**Comment by crosire** [comment]
No, why would you need that?

**Comment by Tanjitsu** [comment]
They both do the same things, just V3 is an updated "nicer" version.
If your mod is written for V2 then just keep using that or re-write it for V3.
If you are starting a new mod then use V3.

**Comment by Madatek** [comment]
Many thanks

> No, why would you need that?

I wasn't sure, I saw V2 and V3 and got confused
