### ISSUE TITLE
Not being able to create a new instance of classes in v3

### ISSUE THREAD

**Issue by AmyrAhmady** [crosire/scripthookvdotnet#900]
Hey, is there a reason for making constructors of classes like Entity, Ped, Vehicle, and such `internal` instead of being `public` in v3 like how it used to be in v2 or older versions?
Or maybe there's a new and efficient way to achieve that.

I'd be glad if someone tell me what's actually going on.

**Comment by crosire** [comment]
Yes. You should use `Entity.FromHandle` if you really need to create an instance from a handle. But generally that is not necessary, since you can just pass in entities into `Native.Function.Call` directly (both as input and return type) and SHVDN will take care of the conversion behind the scenes.
