### ISSUE TITLE
Unable to build the project...

### ISSUE THREAD

**Issue by LavamasterYT** [crosire/scripthookvdotnet#902]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
Which version of SHVDN was the problem encountered with?
3.0.2

**Description**
Add a clear and concise description of what the bug is and how to reproduce it.

I am unable to build the project, it gives me the error:

ScriptHookV SDK files not found. Please copy the SDK files into the 'sdk' folder and try again.	ScriptHookVDotNet	D:\Projects\GitHub\scripthookvdotnet-master\ScriptHookVDotNet.vcxproj	167

**Comment by crosire** [comment]
I suggest you read the readme again, especially the "Contributing" part, which explains exactly what you are missing.
