### ISSUE TITLE
Vehicle.EnginePowerMultiplier always = 0

### ISSUE THREAD

**Issue by PietroKaro** [crosire/scripthookvdotnet#905]
Version: ScriptHookVDotNet v3.0.2

I changed the propriety "EnginePowerMultiplier" of my vehicle and it works correctly but when i try to get the value writed in notification, i always find 0.
How it's possible?

**Comment by Tanjitsu** [comment]
Because its using a [Memory offset ](https://github.com/crosire/scripthookvdotnet/blob/bb099632fc3120817b06154b866bf5d24b6d1e6a/source/scripting_v3/GTA/Entities/Vehicles/Vehicle.cs#L474) which is most likey out of date.

**Comment by PietroKaro** [comment]
Thanks for the answer! I write in C# but i only know fairly basic programming concepts :/ What is memory offset? It seems to me that it has to do with the allocation of the variables in memory.

**Comment by Tanjitsu** [comment]
The offset is the position of the value in memory.

**Comment by PietroKaro** [comment]
Ah ok, thanks.
