### ISSUE TITLE
Missing Method Exception

### ISSUE THREAD

**Issue by LeeC2202** [crosire/scripthookvdotnet#909]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
3.0.2 (SHVDN 2)

**Description**
A mod that has worked for ages has just crashed with a System.MissingMethodException: Method not found: GTA.Math.Vector3 GTA.Math.Quaternion.op_Multiply(GTA.Math.Quaternion, GTA.Math.Vector3) when trying to use the latest versions.

This is a method I have used in several mods, so it means I have others that are going to crash with the same error. Is there a reason this method was removed?

**Comment by Tanjitsu** [comment]
I cant see a Multiply option taking in a Vector3 from the old branch
[dev_v2/source/](https://github.com/crosire/scripthookvdotnet/tree/dev_v2/source/scripting)

**Comment by crosire** [comment]
The operator was missing, but this has already been fixed in b0abb023ec6c06fd92303656325a53135666ec5a a month ago, but no release was made with that.

**Comment by crosire** [comment]
Has been adressed with a v3.0.3 release now.
