### ISSUE TITLE
Visual Studio alternative?

### ISSUE THREAD

**Issue by nitanmarcel** [crosire/scripthookvdotnet#913]
Hi! Is there any alternative IDE to Visual Studio? I just starting modding the game and so far it's a pain in the a**. Not because of my C# knowledge but of this stupid IDE Microsoft is so proud of. It eats 0% CPU and 604 mb of memory but every 5 seconds when I type something it stops working. And it's not affecting only the IDE but my whole keyboard. I can click though windows but for 3 seconds I can't type nothing at all.

 

 

This happens a lot when the IDE tries to load the autocomplete.

 

Is there anything I could use? Maybe VS Code or Rider or CLion. Anything but not VS.

 

Thanks!

**Comment by crosire** [comment]
This is not the place to ask this question.
