### ISSUE TITLE
How to correctly use wait for animations?

### ISSUE THREAD

**Issue by nitanmarcel** [crosire/scripthookvdotnet#914]
I have a made animation with an object fading in and out by fading out with - 10 with 200ms wait before next fade. How would that work on different FPSes? Is there a way to use wait after every frame passed?

Here is my code

```

            while (takeOffSound.IsPlaying())
            {
                foreach (int i in Enumerable.Range(1, 20))
                {
                    tardis.Opacity -= 10;
                    Wait(50);
                }
                foreach (int i in Enumerable.Range(1, 20))
                {
                    tardis.Opacity += 10;
                    Wait(50);
                }
            }
```

**Comment by crosire** [comment]
The issues page is for bug reports or feature requests. Scripting questions should go to other forums (see README).

The value you pass in `Wait` is in milliseconds and it will pause the script for that amount of time, unaffected by FPS.
