### ISSUE TITLE
SHVDN v3 doxygen documentation.

### ISSUE THREAD

**Issue by nitanmarcel** [crosire/scripthookvdotnet#918]
Hi! I've noticed that this library doesn't have an web documentation beside the wiki so I took my time and created one with doxygen: [You can find it here](https://nitanmarcel.github.io/shvdn-docs.github.io/)

I hope this is helpful but if for some reasons this looks wrong you can ask me to delete it.

Also feel free to do as you wish with the html generated which you can find on my github repo [here](https://github.com/nitanmarcel/shvdn-docs.github.io)

**Comment by ChemsoDev** [comment]
hey man i've added ur documentation to the wiki !
https://github.com/crosire/scripthookvdotnet/wiki#useful-links
![image](https://user-images.githubusercontent.com/41765106/78459598-08ac7e80-76b2-11ea-994a-d1302f80f4d3.png)
