### ISSUE TITLE
Bug when trying to kill the player using Kill()

### ISSUE THREAD

**Issue by ChemsoDev** [crosire/scripthookvdotnet#919]
```cs
using GTA;
using System;
using System.Windows.Forms;

public class Climbing : Script
{
    public Climbing()
    {
        Tick += OnTick;
        KeyUp += OnKeyUp;
        KeyDown += OnKeyDown;
    }

    private void OnTick(object sender, EventArgs e)
    {
        if (Game.Player.IsClimbing)
        {
            Game.Player.Character.Kill();
        }
    }

    private void OnKeyDown(object sender, KeyEventArgs e)
    {

    }

    private void OnKeyUp(object sender, KeyEventArgs e)
    {

    }
}
```
I wrote that code and it won't work
spawning object ie cars work under OnKeyX() methods wind for me but i tried to make this little script to test automation i mean script that runs automatically so i placed the code under the OnTick() method but nothing happens in the game

**Comment by crosire** [comment]
The issues page is for bug reports or feature requests. Scripting questions should go to other forums (see README).

**Comment by ChemsoDev** [comment]
oh hi sorry for that
it used to be a question
cz when i type Game.Player.Character.Kill(); it wont work for the player
when i tried Game.Player.Character.Health = 0; that worked for me so i think there is a bug u try to kill the current player with kill() method
and sorry again for the inconvenience
