### ISSUE TITLE
Rockstar have a "scripts" file, which blocks the creation of a "scripts" folder.

### ISSUE THREAD

**Issue by LeeC2202** [crosire/scripthookvdotnet#922]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
This isn't really version specific as it effectively concerns all versions.

**Description**
The Launcher and Social club updated today and caused my older game versions to stop running. I tried to move my mods into the latest version but there is a file called "scripts" with no extension. As most windows users probably know, a file and folder can't exist in the same location, with the same name, meaning you can't create a folder called scripts. I presume this was a deliberate move by Rockstar to block at least some part of modding from working.

I have a version of 1868 from just before the new launcher was released and this scripts file doesn't exist, so it must be something new. I typically mod in version 1493, so hadn't encountered this problem until today.

I don't see any other posts about this on here, so I presume that other people have a workaround... I'm just not sure what it is. Any suggestions anyone?

**Comment by ChemsoDev** [comment]
u said R* take a clever move. then why don't ya just do the same and remove the file>create the folder>launch the game! that simple!
and dont worry abt the game if this file is missing the launcher gonna redownload it again

**Comment by LeeC2202** [comment]
> u said R* take a clever move. then why don't ya just do the same and remove the file>create the folder>launch the game! that simple!
> and dont worry abt the game if this file is missing the launcher gonna redownload it again

I must confess, that seemed too obvious to work but it does... for now anyway. Given the way Rockstar works, I fully expected it to crash with an error about the file being missing and it not being able to download it because the folder was there, which is why I didn't try to remove it... but it did neither.

Maybe I gave them too much credit, or maybe they know this would happen and they will just delete the folder at some point, saying it was "an unauthorised file, so we're allowed to remove it". Can't help feeling this is just a little too easy but I'll take it as I need to finish a mod.

I guess thanks are in order... so thank you.

**Comment by ChemsoDev** [comment]
Np just delete it and make a backup in case then

**Comment by ChemsoDev** [comment]
@LeeC2202 hi,
solved?
