### ISSUE TITLE
Directory.SetCurrentDirectory() causes script reloading to fail.

### ISSUE THREAD

**Issue by LeeC2202** [crosire/scripthookvdotnet#923]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
SHVDN 2.10.10 version from 3.0.3

**Description**
I am creating a file browser class for use in a mod I am working on. I changed the directory in the mod with the Directory.SetCurrentDirectory() command. When I hit insert to reload the scripts, it fails because it is now looking for the scripts folder inside the directory I changed to.

I wouldn't have thought that this command would have affected SHVDN, as I presumed it got its base directory from a path relative to the game folder but it seems it does.

**Comment by crosire** [comment]
The default scripts location is `.\scripts`, which is relative to the current directory. If you want to change that to an absolute path, create a ScriptHookVDotNet.ini in the game folder with this content:
```
ScriptsLocation=C:\path\to\scripts
```

**Comment by LeeC2202** [comment]
I presume ScriptHookV has the same problem, because it created its log file in the wrong folder as well. Would it not  be better to make it relative to the game folder, rather than the current directory?

**Comment by crosire** [comment]
One could argue that using `Directory.SetCurrentDirectory` is ill adviced as well. Or that that the paths being relative to the current directory is useful in cases where you launch the game manually and want to set up different environments. Either way it's primarily a question of different design choices and I wouldn't really consider this a bug, but expected behavior.
It could be changed or course, but would take a while to get deployed, so I wouldn't rely on that in your mod.

**Comment by Tanjitsu** [comment]
I would have to agree that using ```Directory.SetCurrentDirectory``` in a mod seems like the wrong choice. I would assume setting the directory is an environment level change and not something which would be used in a framework such as this.

Why would you need to force the system to use a different location as the "current" location ?
It would seem more logical to just have the path to the chosen location and work with it leaving the actual current location intact.

**Comment by LeeC2202** [comment]
"One could argue that using Directory.SetCurrentDirectory is ill adviced as well".

Nobody argued that anything was ill-advised (note the spelling), it was suggested that it might be better to do something in an alternate way... put your ego away!

And it's very nice (and unsurprising) of you all to jump on the ill-advised bandwagon, while neglecting the fact that assuming a relative directory stays intact is just as ill-advised, if not more so.  If you *need* something to be in a certain place, then it's your job to ensure it is... That's why professional applications let you set absolute paths to essential directories, instead of just assuming relative ones. It's why the game has a registry key that doesn't say ..\Rockstar Games\Grand Theft Auto V it gives the full, **absolute path**.

You don't need to question why I do anything I do, nor are any of you qualified to do so... you need to question why something in your system stops working when something happens. I called a function, SHVDN stopped working, that's the only relevant factor. Whether it was wrong or right of me to call that function has no relevance whatsoever, because my system is full of hundreds of applications that might do it as well.

And I suggest some of you remember the saying about throwing stones and glass houses before pointing fingers. Trust me, there's enough "ill-advised" going on in the world of API and mod development with SHVDN already. Take the blinkers off every now and again, SHVDN and GTA5 aren't the only things on everyone's PC.

Closed because I'm not being the subject of further hypocritical finger-pointing.
