### ISSUE TITLE
Fatal Unhandled Exception System.Text.UTF8Encoding.GetByteCount(String chars)

### ISSUE THREAD

**Issue by LeeC2202** [crosire/scripthookvdotnet#924]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
SHVDN v2.10.12 as part of release 3.0.3,
Project is built against 2.10.10

**Description**
This has happened a few times now and under no consistent conditions. I have two buttons on a GUI and when I select one of them, this error is thrown.

System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Text.UTF8Encoding.GetByteCount(String chars)
   at SHVDN.NativeFunc.PushLongString(String str, Action`1 action)
   at GTA.UIText.Draw(Size offset)
   at GTA.UIText.Draw()
   at CustomHSLSetter.HSLPicker.Draw()
   at CustomHSLSetter.cCustomHSLSetter.onTick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()

There are no errors in the ScriptHookVDotNet2.log, only the ScriptHookVDotNet.log

**Comment by LeeC2202** [comment]
Edit, I have found out when this happens but I am not sure why. A UIText.Caption seems to be getting set to "" when I change a control... which I have now prevented.

But is this error caused because an empty string is being passed to a SHVDN function that always expects there to be text in the caption?

**Comment by crosire** [comment]
`""` or `string.Empty` are supported, `null` is not. Judging by the exception it was set to `null`?.
