### ISSUE TITLE
Consistent crashing in GTA V w/SHVDN

### ISSUE THREAD

**Issue by Xula09** [crosire/scripthookvdotnet#925]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
Which version of SHVDN was the problem encountered with? 
  -3.0.2 & 3.0.3

**Description**
Getting a consistent error in the Lacey Jones mission area GTA V
Exception code: 0xc00000fd
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Only when SHVDN is installed.  I removed the SHVDN files and game will play through the mission fine. 

I had no issues with a previous game setup but had to reinstall Win 10 due to corrupted boot sector thus Freshly installed Win and Fresh re-install of GTA V.  SHVDN was fine with all the mods I had in the previous build but now can repeatably crash in the above area.  

Please advise

**Comment by Tanjitsu** [comment]
Have you removed your mods instead of ScriptHookDotNet ?
Then add them one by one...   

ScriptHookDotNet does not do much unless a mod does something.  
So the issue is 99% likely to be a mod causing the problem.  
If that is the case you should have a ScriptHookDotNet.log file in the root GTA Directory.

**Comment by Xula09** [comment]
Thanks for the response. 
I've reached out to the mod creator of the offending mod and I'll see if we can come up with why it's my specs or game in particular that's having the issue.  He hasn't been able to re-create my crashes but perhaps there is something I'm not doing on my end... more to come if it can help the community
