### ISSUE TITLE
The difference between v2 and v3 projects?

### ISSUE THREAD

**Issue by mtsouris81** [crosire/scripthookvdotnet#927]
Hello, 

I'd like to implement more of the native functions and contribute to the project. Just wondering what's the plan with V2 and v3? Should I add my implementations to the V3 project? 

I'm planning to go through the native DB reference and add (and test / confirm) functions that aren't already there. That includes adding method calls and new entries to the enums for function hashes. 

So, once again, with that plan in mind, should I be adding to V2 or V3? I'll obviously create a pull request and all that good stuff. 

The project is great so far.

**Comment by Tanjitsu** [comment]
Alot of mods still use V2 but i would suggest to any new mods to use V3.
It would make sense to focus on V3.

**Comment by crosire** [comment]
I agree. v2 is there for legacy reasons. v3 should be used going forward.
