### ISSUE TITLE
HOW to show korean language?

### ISSUE THREAD

**Issue by socialpercon** [crosire/scripthookvdotnet#929]
popup.Items.Add(new UIText("한국어", new Point(UI.WIDTH / 2, 0), 0.7f, Color.White, Font.ChaletLondon, true));

UIText cannot show korean text...how to show korean language?

**Comment by justalemon** [comment]
The Simplified Chinese, Traditional Chinese, Japanese, Korean and Russian languages have separate fonts that are only loaded when the language is set to the specific language.

Another thing that you can do is to import the Korean character set into the EFIGS font, sadly I forgot how to do that.

**Comment by socialpercon** [comment]
> The Simplified Chinese, Traditional Chinese, Japanese, Korean and Russian languages have separate fonts that are only loaded when the language is set to the specific language.
> 
> Another thing that you can do is to import the Korean character set into the EFIGS font, sadly I forgot how to do that.

thank you for anwser. i solved that issue by version up. but my code have to change all of them.
