### ISSUE TITLE
Please make an overload of GetNearbyPeds and GetNearbyVehicles which takes a Vector3.

### ISSUE THREAD

**Issue by RainerHilmer** [crosire/scripthookvdotnet#93]
Example:
World.GetNearbyPeds(Vector3 position, float radius)

**Comment by Frede1012** [comment]
We currently don't have a native hash for a function that does this. But i suppose we could fake a ped and pass it to the native function, not sure if thats too "hackish" or if its going to work :P

**Comment by RainerHilmer** [comment]
Yep I thought so after I found out in the natives db. Thanks.
