### ISSUE TITLE
Get dimensions of an entity

### ISSUE THREAD

**Issue by sharma-n** [crosire/scripthookvdotnet#933]
Hi,
I'm trying to get the dimensions (length, width, height) of an entity from the C++ code. Is there a way to do that?

I'm able to get the coordinates of the center of the object using:

```python
objCenter = ENTITY::GET_ENTITY_COORDS(hitEntityHandle, TRUE);
```

Is there a method that allows me to find the length, width and height of an entity in a similar way?

**Comment by crosire** [comment]
This is the issues page for SHVDN, not the C++ SHV. Please check the links in the Readme for better places to get scripting help.
