### ISSUE TITLE
Vehicle Windows

### ISSUE THREAD

**Issue by toxicscams** [crosire/scripthookvdotnet#934]
Which version of SHVDN was the problem encountered with? v3.0.3

Add a clear and concise description of what the bug is and how to reproduce it.
When I use Vehicle.LockStatus = VehicleLockStatus.Unlocked; The Player Breaks The Window To Enter The Car, Even Tho It Is Unlocked, I dont know how to reproduce it.

**Comment by Tanjitsu** [comment]
Have you looked at [VehicleFlags](https://github.com/crosire/scripthookvdotnet/blob/main/source/scripting_v3/GTA/Entities/Peds/EnterVehicleFlags.cs), i would not consider this a bug.  
GTA usually needs more than 1 flag changed to override a sitution.

**Comment by crosire** [comment]
Checked by locking a vehicle with `V.LockStatus = VehicleLockStatus.Locked` and then unlocking again via `V.LockStatus =VehicleLocksStatus.Unlocked` and it performed as expected.
The property is only calling the `SET_VEHICLE_DOORS_LOCKED` native under the hood, so if that native is not doing what you want, there will be a different reason, but I'd not consider it a SHVDN bug either.
