### ISSUE TITLE
World.CurrentDate causes FATAL errors

### ISSUE THREAD

**Issue by jglassmaker** [crosire/scripthookvdotnet#935]
I have a small % of users reporting an error when my mod tries to get World.CurrentDate. Can reproduce by using SHVDN console by first setting date to and then returning via SHVDN. Mod: https://www.gta5-mods.com/scripts/better-chases

System.ArgumentOutOfRangeException: Month must be between one and twelve.

GTA.Native.Function.Call(GTA.Native.Hash.SET_CLOCK_DATE, 15, 0, 2009);
return GTA.World.CurrentDate

Having these users use the same native to set their date to 6/16/2009 resolves the issue. Not sure why GTAV allows a 0 month but the GET shouldn't cause a FATAL.

-----

**Version**
3.0.3

**Comment by Tanjitsu** [comment]
It also sounds like a bug that your code should handle rather than a user.
If you pass any incorrect parameter to handler function it will cause an error.

As a mod developer its your job to define the parameters of the contents being passed to the middle man.

But it is also true that due the collaborative input nature of the SHVDN some functions have more checks than others.

**Comment by jglassmaker** [comment]
> It also sounds like a bug that your code should handle rather than a user.
> If you pass any incorrect parameter to most handler functions it will cause an error.
> 
> As a mod developer its your job to define the parameters of the contents being passed to the middle man.
> 
> But it is also true that due the collaborative input nature of the SHVDN some functions have more checks than others.

That makes no sense at all. So I should have to wrap every single SHVDN getter in a try catch because calling the get is supposed to throw fatal errors?

But I guess you actually don't really know what you are talking about because you think you pass parameters to a variable getter.

**Comment by E66666666** [comment]
A fun thing I spotted:

https://github.com/crosire/scripthookvdotnet/blob/f98d8b87d363371910b9ff6228e7e4f0f917155f/source/scripting_v3/GTA/Entities/Vehicles/Vehicle.cs#L1109

`Vehicle.SteeringAngle` returns degrees, but sets radians.

**Comment by janrog** [comment]
But this happens with only the SHVDN installed, without any mods. When the in-game month is set to January or December the get_CurrentDate() function will just crash. Also we're talking about a getter function, there are no parameters being passed to it. To me it seems like the game is using month format starting from 0 and SHVDN interprets them as starting from 1. I might be wrong on that though.

**Comment by crosire** [comment]
Should be fixed now. `GET_CLOCK_MONTH` indeed returns the month in range [0-11], whereas `DateTime` expects it in range [1-12].

**Comment by Tanjitsu** [comment]
> > It also sounds like a bug that your code should handle rather than a user.
> > If you pass any incorrect parameter to most handler functions it will cause an error.
> > As a mod developer its your job to define the parameters of the contents being passed to the middle man.
> > But it is also true that due the collaborative input nature of the SHVDN some functions have more checks than others.
> 
> That makes no sense at all. So I should have to wrap every single SHVDN getter in a try catch because calling the get is supposed to throw fatal errors?
> 
> But I guess you actually don't really know what you are talking about because you think you pass parameters to a variable getter.

I made no mention of passing to a getter.
I read your set statement as being an issue with the setter and i only replied to get the discussion started.
If "you" know what you are talking about then put in a pull request rather than asking other people to investigate an issue you have already found a solution too.

**Comment by jglassmaker** [comment]
> I made no mention of passing to a getter.
> I read your set statement as being an issue with the setter and i only replied to get the discussion started.
> If "you" know what you are talking about then put in a pull request rather than asking other people to investigate an issue you have already found a solution too.

You took 10 seconds to read over my bug report, made a bunch of assumptions, and then had to put in your 2 cents. Your comment was vague, unsubstantiated, unrelated, and about as pointless and baseless as this last comment you made. 

The issue is closed and fixed now - I'm not wasting anymore time with you.
