### ISSUE TITLE
Calling Native Functions outside of ScriptDomain causes crash

### ISSUE THREAD

**Issue by Frede1012** [crosire/scripthookvdotnet#94]
There seems to be a problem calling native functions outside of a scriptdomain, in this case Main.ccp ManagedTick. I have been working on a console for the scripthook (https://github.com/Frede1012/scripthookvdotnet/commit/9bd51e1445be135a83ec66ca576c3e9c78179573), which demonstrates the issue.

The crash happens with all Native Function calls i have tried.

**Comment by crosire** [comment]
Native functions can only be called from inside an active ScriptDomain. This was a design choice.
