### ISSUE TITLE
How to reload all or a single script

### ISSUE THREAD

**Issue by clarkxl** [crosire/scripthookvdotnet#943]
mod im using keeps getting aborted as soon as a error comes, is there a way to restart it thru console or other means? as i have to continually restart the whole game just to reload 1 script when a certain npc isnt in range

**Comment by Tanjitsu** [comment]
You can reload all scripts from the menu with the command Reload()

**Comment by clarkxl** [comment]
> You can reload all scripts from the console using the command [Reload()](https://github.com/crosire/scripthookvdotnet/blob/b850d2bfbf62456188ea5fbff5e94196d2ac4340/source/core/DllMain.cpp#L54)

thank you!
