### ISSUE TITLE
Please add SET_TV_CHANNEL_PLAYLIST

### ISSUE THREAD

**Issue by meimeiriver** [crosire/scripthookvdotnet#944]
Please add _0xF7B38B8305F1FE8B to SHVDN as **SET_TV_CHANNEL_PLAYLIST** mnemonic. I use it quite often.

**Comment by crosire** [comment]
It already exists in v3: https://github.com/crosire/scripthookvdotnet/blob/1a1b57543626994854ceeedd3ce54a41ef7a9198/source/scripting_v3/GTA.Native/NativeHashes.cs#L1020
