### ISSUE TITLE
Memory Offsets

### ISSUE THREAD

**Issue by Tanjitsu** [crosire/scripthookvdotnet#948]
v3.0.4_v3

With version 2060 the SeatIndex offset is not correct.https://github.com/crosire/scripthookvdotnet/blob/10eb70ebcae20b3bbc2471fc76ec899e73920b93/source/scripting_v3/GTA/Entities/Peds/Ped.cs#L605

Does anyone still know how to lookup the correct offsets so we can update these ?

**Comment by yorgi1408** [comment]
I'd also like to add that Vehicle.ThrottlePower offset is wrong in 2060

``offset = Game.Version >= GameVersion.v1_0_1604_0_Steam ? 0x99C : offset;``

**Comment by kagikn** [comment]
I'm fixing memory offsets, and I realized offsets for `Ped.SeatIndex` doesn't refer pure seat index variable when I made the player cycle through passenger seats with Insurgent Pick-Up Custom and Bus. I need to shift the offsets of the property by -2.

**Comment by kagikn** [comment]
I forgot to tag, but I fixed the issues in 65abac7e7465712e8864e4727adb0c0992b31d80 now.
