### ISSUE TITLE
How to push commits to main branch without using pull requests?

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#949]
I tried pushing my squashed commits after I pushed commits I want to join to the main branch, but the error message `Required status check "continuous-integration/appveyor/pr" is expected.` appeared and I failed.
I also tried pushing my commits that are reviewed by AppVeyor (of course those have the same commit id), but the same message appeared.

What do I need to do to push commits to the main branch without using pull requests?

**Comment by crosire** [comment]
Try directly commiting changes to `main`, without any merging strategy (just take your changes you may have done in a side branch and re-commit them in `main` manually). My last few commits were all direct and I had no problems pushing them.

**Comment by kagikn** [comment]
Are you sure the status check allows collaborators to push commit directly? I mean, you configured the setting properly? 
You can directly push commits without passing the status check because you don't have `Include administrators` in `Branch protection rule` enabled, but collaborators can't.

**Comment by crosire** [comment]
Yikes. Try again now. Still requires linear history, but status checks are off.

**Comment by kagikn** [comment]
Yeah, I can push my commits directly now.
