### ISSUE TITLE
World.CreateVehicle() gives me null

### ISSUE THREAD

**Issue by Nacorpio** [crosire/scripthookvdotnet#95]
public LootVehicle(VehicleHash model, Vector3 position) {
            _vehicle = World.CreateVehicle(new Model(model), position);
            Main.DebugText.Caption = (_vehicle == null ? "Yes" : "No");
}

Why does this give me "Yes"?

**Comment by JohnnyCrazy** [comment]
Is this still a problem @Nacorpio ? Maybe it's caused by another `Main.DebugText.Caption` call?

**Comment by Nacorpio** [comment]
I'm going to try it out in a bit, and we'll see.

**Comment by JohnnyCrazy** [comment]
@Nacorpio Any news? :smiley:

**Comment by Nacorpio** [comment]
Just a moment. I maybe just did.

**Comment by Nacorpio** [comment]
How do you print something in the log again?

**Comment by JohnnyCrazy** [comment]
Just use this one-liner for this test:
````c#
public void Log(object msg)
{
    File.AppendAllText("log.txt", msg + Environment.NewLine);
}
````

**Comment by Frede1012** [comment]
@JohnnyCrazy Not atm :P

**Comment by JohnnyCrazy** [comment]
Can I close this @Nacorpio ? :D

**Comment by crosire** [comment]
Since there was no more feedback I'll close this for now.
