### ISSUE TITLE
[Question] C# Source files and SHVDNv3

### ISSUE THREAD

**Issue by E66666666** [crosire/scripthookvdotnet#952]
The v3 API is nicer to use, even more so when quickly prototyping stuff. However, .cs files compile using the v2 API:
https://github.com/crosire/scripthookvdotnet/blob/main/source/core/ScriptDomain.cs#L189

Would it be possible to have support for compiling v3 sources, in some way?

My suggestion would be either differentiating it on file name (`.3.cs/vb`) or a first-line comment indicating compatibility version (`//SHVDNv3`).

**Comment by PlavnikHacks** [comment]
no. not possible.

**Comment by E66666666** [comment]
Why wouldn't it be possible? It should be pretty trivial to use a different assembly to compile with, depending on the input file. If that isn't wanted, surely parsing one line in the file to be compiled, should be enough of a hint?

Adding a requirement for v3 scripts can't really break v2 scripts.

**Comment by crosire** [comment]
Sure is possible and is implemented now!

**Comment by E66666666** [comment]
That was quick, thank you!
