### ISSUE TITLE
Custom App For Phone?

### ISSUE THREAD

**Issue by PlavnikHacks** [crosire/scripthookvdotnet#953]
So i see the phone has a lot of apps on it, is there a way to make one with options like a settings app?

-Also, is it possible to create a custom contact? If so please respond if not then just answer the first question. 

Thank you!

**Comment by Tanjitsu** [comment]
Hey, this is not a forum for questions about modding but rather a place to work on SHVDN.

You question would be better suited to somewhere like [gtaforums.com](https://gtaforums.com/forum/372-coding/).
