### ISSUE TITLE
ScriptHookVDotNet is outdated

### ISSUE THREAD

**Issue by marcel8bit** [crosire/scripthookvdotnet#954]
hi, i have the latest version of the game, and scripthook V dotnet (also the latest version) makes my game crash. in the pevious version of gta V, it did not crash the game.
the version:
[ScriptHookVDotNet.zip](https://github.com/crosire/scripthookvdotnet/files/5207483/ScriptHookVDotNet.zip)

**Comment by duszan777** [comment]
i have also this problem.

**Comment by PietroKaro** [comment]
This is not a ScriptHookVDotNet problem but is related to ScriptHookV. The SHV author have to update the library for the new version of game exe. ScriptHookDotNet remains the same, new SHV should be published in a week.

**Comment by kagikn** [comment]
Actually, ScriptHookVDotNet v3.0.4 is also outdated due to outdated memory offsets since 1.0.2060.0. I'm not closing this issue until we release the next version of SHVDN.

**Comment by PietroKaro** [comment]
@kagikn So, should SHVDN be updated every game update due to this problem?

**Comment by Kiddabob** [comment]
> This is not a ScriptHookVDotNet problem but is related to ScriptHookV. The SHV author have to update the library for the new version of game exe. ScriptHookDotNet remains the same, new SHV should be published in a week.

It is actually already up to date: http://www.dev-c.com/gtav/scripthookv/

**Comment by Tanjitsu** [comment]
> @kagikn So, should SHVDN be updated every game update due to this problem?

No you do not need to update SHVDN each time.
You only need to update if you want the newer additions or if Rockstar breaks existing functionality.

**Comment by SHIBEM1** [comment]
When will be new update?

**Comment by tweakerpussy** [comment]
its unfortunate that there's so many many mods that rely on scripthookvdotnet. In my opinion if you make script/mod that where so many mods rely on that script/mod than you should update it regularly or just give permission to someone that will actually do it.

**Comment by NatalProductions** [comment]
Is there any progress being made? Is scripthookv.net even being updated anymore? Please tell us it's being worked on by someone even if it's not Crosire.

**Comment by Tanjitsu** [comment]
> Actually, ScriptHookVDotNet v3.0.4 is also outdated due to outdated memory offsets since 1.0.2060.0. I'm not closing this issue until we release the next version of SHVDN.

@NatalProductions As per this thread... Yes it is.

**Comment by nitish332** [comment]
may be

**Comment by kagikn** [comment]
Now v3.1.0 is released. I'm closing this issue.
