### ISSUE TITLE
When i launch gta 5 with scripthookvdotnet it crashes

### ISSUE THREAD

**Issue by Programmer213133** [crosire/scripthookvdotnet#964]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
3

**Description**
When i launch my gta 5 with scripthookvdotnet it crashes i have no scripts in my folder just installed it.

my log just says reading scripts in D:/SteamLibary/Common/Grand theft auto 5/scripts

**Comment by kagikn** [comment]
I saw through the source code, but I don't think ScriptHookVDotNet v3.1.0 itself crashes the game in v1.0.2189.0. Maybe some of the other plugins you have are not compatible with the new version of `GTA5.exe`.
