### ISSUE TITLE
RelativePosition makes game crash

### ISSUE THREAD

**Issue by bttf92** [crosire/scripthookvdotnet#967]
**Version**
3.0.4 of SHVDN after last Cayo Perico update of the game.

**Description**
Game crashes without errors when trying to get the RelativePosition of an entity bone. Issue doesn't occur with world position.

**Comment by bttf92** [comment]
Created a pull request with working fix.

**Comment by kagikn** [comment]
This is what alloc8or said in 5Mods Discord:
>This is because V's RAGE was updated. One of the changes is in rage::fwExtensibleBase (GetBaseClassId was added) which means virtual functions in every class that derives from fwExtensibleBase shifted one place down (+8 bytes), which includes entity classes.

Thank you so much for telling us that, alloc8or!
