### ISSUE TITLE
DELETE_ENTITY needs to be replaced by DELETE_VEHICLE for Vehicle type entities

### ISSUE THREAD

**Issue by 3-bit** [crosire/scripthookvdotnet#969]
**Version**
SHVDN 3

**Description**
I am not sure what triggers it because it's a GTA V engine issue, possibly persistence but vehicles will sometimes not be deleted even when looped.

Eg:
```
vehicle.IsPersistent = false; //Whether this is here or not, same story
while(vehicle.Exists())
{
    vehicle.Delete();
}
```
Will not delete the vehicle nor will it lock up. Internally the handle gets discarded after the first ```.Delete()``` and then ```.Exists()``` fails and the vehicle will not be deleted because the engine just marks it as no longer needed. It will despawn when far away but will not instantly delete.

What I have found out is that calling ```DELETE_VEHICLE``` directly will delete the vehicle without a problem. The only thing is that the vehicle must be made a mission entity right before deleting it.

```
Vehicle veh = whatever;
veh.IsPersistent = true;
GTA.Native.OutputArgument arg = new GTA.Native.OutputArgument(veh);
GTA.Native.Function.Call(GTA.Native.Hash.DELETE_VEHICLE, arg);
```

I have found DELETE_VEHICLE to be reliable, but not DELETE_ENTITY. Anyone else care to comment?

**Comment by PietroKaro** [comment]
It has always worked for me but i'll try to call that function. How long have you had this problem with "Delete()"?

**Comment by 3-bit** [comment]
It seems I found the trigger. If you set the vehicle .IsPersistent = false right before deleting it, it won't delete it. Same thing happens with peds. The trick is to not disable persistence before deleting the object. Same thing as DELETE_VEHICLE. Not sure what Rockstar's logic was designing this.

**Comment by PietroKaro** [comment]
You're right 👍

https://github.com/crosire/scripthookvdotnet/blob/4b6b99aff19e6d2344b1b6056398cdbf1c4440c6/source/scripting_v3/GTA/Entities/Entity.cs#L1332

**Comment by 3-bit** [comment]
Maybe it's because if I do ```.IsPersistent = false``` right before it marks the vehicle as no longer needed then ```Exists()``` fails because the engine internally fails ```DOES_ENTITY_EXIST``` on a handle that has been marked as no longer needed.

I need to test it soon to see what's going on.

**Comment by PietroKaro** [comment]
Anyway it's a strange situation because when you use "Delete()", SHVDN call automatically "SET_ENTITY_AS_MISSION_ENTITY" before deleting entity. Your game shouldn't crash.

**Comment by RelaperCrystal** [comment]
> Maybe it's because if I do `.IsPersistent = false` right before it marks the vehicle as no longer needed then `Exists()` fails because the engine internally fails `DOES_ENTITY_EXIST` on a handle that has been marked as no longer needed.
> 
> I need to test it soon to see what's going on.

Marking anything as no longer needed requires SHVDN to pass the handle as _pointer_ (in the language of managed world, it is passed by _references_ from `ref` keyword), and game probably _sets_ the handle to an invalid value, therefore failing `Exists()`.
