### ISSUE TITLE
v3.1.0 is not available on NuGet

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#970]
v3.1.0 released two days ago is not available on NuGet for download (I feel that this is more of an oversight than a bug).

**Comment by kagikn** [comment]
Sorry, I didn’t realize I had forgotten to update the assembly versions until I saw b38d444.

**Comment by crosire** [comment]
@kagikn Happens ¯\_(ツ)_/¯. Used to be easier when this was automated. Thank you so much for doing the release btw.!
