### ISSUE TITLE
Calling functions that use Wait sometimes will raise an "Illegal call to 'Script.Wait()' outside main loop!"

### ISSUE THREAD

**Issue by justalemon** [crosire/scripthookvdotnet#982]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
3.1.0

**Description**
Calling functions that use Wait sometimes will raise an "Illegal call to 'Script.Wait()' outside main loop!"

The following snippet can be used to reproduce this problem:

```cs
List<Ped> pednt = new List<Ped>();
for (int i = 0; i < 5; i++)
{
    World.CreatePed(PedHash.Agent14, Game.Player.Character.Position);
}
foreach (Ped ped in pednt)
{
    ped.Delete();
}
```

Which results in a traceback like:

```
Failed to instantiate script FoodShops.FoodShops because constructor threw an exception: System.InvalidOperationException: Illegal call to 'Script.Wait()' outside main loop!
   at GTA.Script.Wait(Int32 ms)
   at GTA.Model.Request(Int32 timeout)
   at GTA.World.CreatePed(Model model, Vector3 position, Single heading)
   at FoodShops.FoodShops..ctor()
```

**Comment by PietroKaro** [comment]
It seems you can't call Wait function inside constructor. I had the same problem calling "directly" Script.Wait(). The strange thing is that  it doesn't always raise the exception.

**Comment by crosire** [comment]
This is expected behavior, see also documentation: https://github.com/crosire/scripthookvdotnet/blob/5cb3dafbe00a8ed67147e62e3ce672aee1dc47a3/source/scripting_v3/GTA/Script.cs#L264
Constructors are handled differently compared to events (they don't run through the normal thread loop), so there is no semaphore the `Wait` function can trigger and wait on.
