### ISSUE TITLE
A new guard page for the stack cannot be created. GTAV

### ISSUE THREAD

**Issue by CitizenDroid** [crosire/scripthookvdotnet#989]
Game crashing!.
Not sure what is causing this but thought the error starting with .NET would make this page a good place to finish as no other sites have any solutions. I only have basic mods installed, Redux, scripthookv, dotnet, enhance trainer and heap, pack and weapon adjusters these were installed on clean copy twice now and I have changed gameconfig several times and have only notice a time difference some configs seems to last a bit longer but still crashe after a while then I'm hit with this report.
-------------------------------------------------------------------------------
.NET-BroadcastEventWindow.4.0.0.0.141b42a.0:GTA5.exe - System E....
A new guard page for the stack cannot be created.
--------------------------------------------------------------------------------
I have also used the gameconfig from github which lasts longer than the current one on offer on gta5mods.com.
Just wondered if this could be connected to dotnet!. maybe some kind of memory issue or leak!  but that's just a guess from what I have read. If anyone has an idea as to what this issue is actually connected with I would really appreciate any guidance or advise here. 
I'm unning Ryzen 5, 32gig ram and Geforce RTX 2070 super game housed on a dedicated 2tb wd black slave drive with 1tb free space just it say space is not an issue .
I have played same mods on a much lesser system with no issues!! so can't figure this out and I've hit a wall. I have repaired and updated Net framework but since I'm using Windows 10 that is preinstalled and can not be uninstalled only repaired! trust Gates to make things hard! he should team up with Rockstar that would be a marriage made in hell! :/.
so I thought I would try here before giving up completely although I may have one more try without Redux but doubt that is the culprit!.
Regards and thanks for all the mods :)

**Comment by Tanjitsu** [comment]
Remove all the mods and run it with just scripthook + SHVDN.
If it works... add your mods 1 by 1 until you find which mod is causing the crash.

**Comment by CitizenDroid** [comment]
I think it was the latest gameconfig on gta5mods as I have found another one on same site and it seems to work just fine. I'm running a few mods now and thankfully have had no issues even after hours of play.
many thanks for your input :)
