### ISSUE TITLE
Game crashes on pressing f4

### ISSUE THREAD

**Issue by vivasvan1** [crosire/scripthookvdotnet#990]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
Which version of SHVDN was the problem encountered with?
//   GTA V SCRIPT HOOK (build Mar 20 2021, v1.0.2245.0)
//     (C) Alexander Blade 2015-2021
My .NET version is:
C:\Users\Vivasvan>dotnet --list-sdks
5.0.101 [C:\Program Files\dotnet\sdk]

**Description**
I am able to run scriptHookV with NativeTrainer.asi but when i copy paste the 
ScriptHookVDotNet.asi, ScriptHookVDotNet.ini, ScriptHookVDotNet2.dll, ScriptHookVDotNet2.xml, ScriptHookVDotNet3.dll, ScriptHookVDotNet3.xml 
and run the game on f4 it crashes. I have Visual Studio 2019 installed, 
Please let me know if there is anything else i need to provide

[ScriptHookVDotNet.log](https://github.com/crosire/scripthookvdotnet/files/6319212/ScriptHookVDotNet.log)
[ScriptHookV.log](https://github.com/crosire/scripthookvdotnet/files/6319213/ScriptHookV.log)

**Comment by Tanjitsu** [comment]
From your log files...

// GTA V SCRIPT HOOK (build Mar 20 2021, v1.0.2245.0)
//     (C) Alexander Blade 2015-2021
[17:26:36] INIT: Started
[17:26:36] INIT: Success, game version is VER_1_0_350_1_STEAM

Seems like you are running an old version (i would assume this a cracked copy of gta).

**Comment by MixGamingAdda** [comment]
> From your log files...
> 
> // GTA V SCRIPT HOOK (build Mar 20 2021, v1.0.2245.0)
> // (C) Alexander Blade 2015-2021
> [17:26:36] INIT: Started
> [17:26:36] INIT: Success, game version is VER_1_0_350_1_STEAM
> 
> Seems like you are running an old version (i would assume this a cracked copy of gta).

ya bro i also have same issue but my mods work fine but SCRIPTS folder dosen't. Game version :- 1.0.350.1  also cracked.
