### ISSUE TITLE
The Assembly or a dependency thereof was not found - Error

### ISSUE THREAD

**Issue by RealOesi** [crosire/scripthookvdotnet#991]
**Version**
SHVDN 3.1.0.0

**Description**
I tried to make my own external mod menu with SHVDN and Memory.dll.
Question 1:
Can I a external mod menu with SHVDN at all?
Question 2 (Only if the answer to Question 1 is YES):
How can i fix this error:
- $ exception {"The file or assembly \" ScriptHookVDotNet, Version = 3.1.0.0, Culture = neutral, PublicKeyToken = 8564999cffc18483 \ "or a dependency thereof was not found. The system cannot find the specified file.": "ScriptHookVDotNet, Version = 3.1.0.0, Culture = neutral, PublicKeyToken = 8564999cffc18483 "} System.IO.FileNotFoundException
(it's a german text, translated by google translate :D)

**Comment by RelaperCrystal** [comment]
Did you installed the exact same version of SHVDN you referencing in the menu? And post your original exception log text here.
