### ISSUE TITLE
my shit isnt working

### ISSUE THREAD

**Issue by penisbruhmoment** [crosire/scripthookvdotnet#998]
Please note: **ScriptHookVDotNet is NOT ScriptHookV**!
If you get a `FATAL` error (e.g. `FATAL: Unknown game version` after a game update), than this project is not responsible and you instead need to wait for [**ScriptHookV**](http://www.dev-c.com/gtav/scripthookv/) to update.

-----

**Version**
Which version of SHVDN was the problem encountered with?
the current one
**Description**
Add a clear and concise description of what the bug is and how to reproduce it.
ok so i i tried to install mods that go along with it, it didnt work i removed the mods it did work but as soon as i put YOUR scripthook into my game it says "you signed out of rockstar games social club quit game" and i have to quit the game

**Comment by RelaperCrystal** [comment]
This isn't SHVDN's issue. Rockstar Games Launcher sometimes forgot your login. Just simply start Rockstar Games Launcher, log back in, and launch the game via Rockstar Games Launcher.

**Comment by penisbruhmoment** [comment]
i just took out shvdn and it worked fine i put it back in it didnt work, so it is SHVDNS issue

**Comment by RelaperCrystal** [comment]
Did you try start the game via Rockstar Games Launcher? Or you played via Steam? Are you sure putting SHVDN back causing RGSC to automatically sign out? What about using SHV alone?

**Comment by penisbruhmoment** [comment]
i never tried shv alone but i'm sure putting SHVDN in makes me sign out and i launched gta via steam

**Comment by RelaperCrystal** [comment]
Login process is done by another program. Right now, I assume you mean that, 1. you can play vanilla game without RGSC signing you out, and 2. you haven't tested whether it is SHV causing the game to sign you out, and 3. you installed SHV with SHVDN in one step without testing SHV is working or not. There is nothing can be "sure" in modding and problems like this must be solved with a "process of elimination".

**Comment by penisbruhmoment** [comment]
i just took it out and the script hook works and doesnt log me out but the script hook dot net does i literally just tried to launch it via the launcher but it used steam as a launcher anyway

**Comment by RelaperCrystal** [comment]
Have you been asked for login when starting launcher? Did you check the "remember me" (or similar) box?

**Comment by penisbruhmoment** [comment]
yes i have and i check remember me, and sh doesnt work for the mod im downloading

**Comment by RelaperCrystal** [comment]
Well, it's RGL logging you out. At this time I don't have any solution, but you may change the title (summary) of the issue so people knows what you are dealing with instead of "my sh*t isn't working" to get further attention from others?

**Comment by Tanjitsu** [comment]
If you have used a Mod Manager before i would imagine it has left some stuff behind such as start in offline mode or disable SC ect.

Clean GTA and check things like commandline.txt which might hold old commands.
Only start with ScriptHookV + ScriptHookVDotNet
Dont add any mods.
If it does not work then post your logs.
